### ISSUE TITLE
Wandb in jenkins pipeline

### ISSUE THREAD

**Issue by Italosayan** [wandb/client#1006]
wandb, version 0.8.32
Python 3.7.3
Darwin

### Description
Use weights and biases init statement during Jenkins pipeline.

### What I Did
I tried adding Jenkins to the sudoers file but that didn't fix it.
https://www.edureka.co/community/8365/permission-denied-error-while-running-simple-job-in-jenkins

```
Paste the command(s) you ran and the output:
Executed through simple jenkins pipeline:
wandb.init(project="superdan_training")

I'm getting a permission error:

+ python -m training.training
wandb: ERROR Failed to create run directory: [Errno 13] Permission denied: '/.config'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/wandb/__init__.py", line 1049, in init
    run = wandb_run.Run.from_environment_or_defaults()
  File "/usr/local/lib/python3.7/site-packages/wandb/wandb_run.py", line 232, in from_environment_or_defaults
    api = InternalApi(environ=environment)
  File "/usr/local/lib/python3.7/site-packages/wandb/apis/internal.py", line 70, in __init__
    self._settings = Settings(load_settings=load_settings)
  File "/usr/local/lib/python3.7/site-packages/wandb/settings.py", line 22, in __init__
    self._global_settings.read([Settings._global_path()])
  File "/usr/local/lib/python3.7/site-packages/wandb/settings.py", line 100, in _global_path
    util.mkdir_exists_ok(config_dir)
  File "/usr/local/lib/python3.7/site-packages/wandb/util.py", line 499, in mkdir_exists_ok
    os.makedirs(path)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/italosayan/.jenkins/workspace/super-dan-experiment/training/training.py", line 13, in <module>
    wandb.init(project="superdan_training")
  File "/usr/local/lib/python3.7/site-packages/wandb/__init__.py", line 1053, in init
    raise LaunchError("Could not write to filesystem.")
wandb.run_manager.LaunchError: Could not write to filesystem.
```

**Comment by vanpelt** [comment]
This is trying to write a file to the users home directory which in your case is "/" and you don't have permission to write there.  Either start your process with a user that has a home directory, or set the environment variable to `WANDB_CONFIG_DIR=/tmp` or some other directory you have write access to.

**Comment by Italosayan** [comment]
Worked like a charm. I added WANDB_CONFIG_DIR and WANDB_API_KEY to the environment variables inside Global properties in Jenkins.
