### ISSUE TITLE
AttributeError: 'PyDevTerminalInteractiveShell' object has no attribute 'kernel'

### ISSUE THREAD

**Issue by mbmccoy** [wandb/client#1008]
wandb, version 0.8.34
Python 3.7.4
Linux

### Description

Using `wandb` with PyCharm in the interactive terminal. It seems that `wandb` is detecting the interactive terminal as a `jupyter` environment. PyCharm uses the pydev console, which is kinda like Jupyter, but not 100% compatible.

Happened upon upgrade from `0.8.33` -> `0.8.34`.

```
Error in callback <function _init_jupyter.<locals>.cleanup at 0x7f612c1905f0> (for post_run_cell):
Traceback (most recent call last):
  File "/home/mccoy/.local/share/virtualenvs/training-gym-ZeodOefO/lib/python3.7/site-packages/IPython/core/events.py", line 88, in trigger
    func(*args, **kwargs)
  File "/home/mccoy/.local/share/virtualenvs/training-gym-ZeodOefO/lib/python3.7/site-packages/backcall/backcall.py", line 104, in adapted
    return callback(*args, **kwargs)
  File "/home/mccoy/.local/share/virtualenvs/training-gym-ZeodOefO/lib/python3.7/site-packages/wandb/__init__.py", line 502, in cleanup
    run._stop_jupyter_agent()
  File "/home/mccoy/.local/share/virtualenvs/training-gym-ZeodOefO/lib/python3.7/site-packages/wandb/wandb_run.py", line 185, in _stop_jupyter_agent
    self._jupyter_agent.stop()
  File "/home/mccoy/.local/share/virtualenvs/training-gym-ZeodOefO/lib/python3.7/site-packages/wandb/jupyter.py", line 139, in stop
    self.save_history()
  File "/home/mccoy/.local/share/virtualenvs/training-gym-ZeodOefO/lib/python3.7/site-packages/wandb/jupyter.py", line 185, in save_history
    'language_info': self.shell.kernel.language_info
AttributeError: 'PyDevTerminalInteractiveShell' object has no attribute 'kernel'
```

**Comment by vanpelt** [comment]
Ahh, thanks for letting us know.  We'll work on a new release that handles the PyCharm shell.

**Comment by vanpelt** [comment]
I just made a branch that fixes this, you can install with `pip install --no-cache-dir --upgrade https://github.com/wandb/client/archive/bug/ipython.zip`.  We should be releasing 0.8.35 in the next couple days.

**Comment by mbmccoy** [comment]
Works great. Note that I did get one warning:

```
ERROR:wandb.jupyter:Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable
```

Otherwise, it seems to work just fine.

**Comment by sooheon** [comment]
I'm getting the same warning, and wandb attempts to print an ipython HTML object to the console.

**Comment by sooheon** [comment]
Also seeing `SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>`
