### ISSUE TITLE
Can wandb work with ray (or other multiprocessing)?

### ISSUE THREAD

**Issue by alsuhr-c** [wandb/client#1018]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.8.35
* Python version: Python 3.7.6
* Operating System: Linux

### Description

I'm trying to run wandb with ray (https://github.com/ray-project/ray), where I am training two models at once, one as a `ray.remote` process. I want to have two wandb experiments for each model, rather than using the same experiment. However, I can't seem to get it to work using ray. MWE below with a description.

### What I Did

The following MWE script outlines how I can reproduce the error. Basically, it calls the first function as a `ray.remote function`, then immediately calls `second_fn`. Because ray's scheduler isn't immediate, `second_fn` is called first and creates the first wandb experiment (`'test_second_fn'`). Then once `first_fn` is actually called, it also tries to create a wandb experiment (`'test_first_fn'`) but some things break (output after the MWE), and shut down all the logging for both experiments (as far as I can tell -- no values are logged, but the console log for `test_first_fn` is still updating, where as the console log for `test_second_function` is not). 

```
import ray
import wandb

from time import sleep

@ray.remote(num_gpus=0, num_cpus=1)
def first_fn():
    print('Calling first function and creating test_first_fn')
    wandb.init(project='test_project', name='test_first_fn')

def second_fn():
    print('Calling second function and creating test_second_fn')
    wandb.init(project='test_project', name='test_second_fn')
    sleep(1000)

def train():
    ray.init(num_cpus=1, num_gpus=0, memory=100 * (1024 ** 2))
    first_fn.remote()
    second_fn()

if __name__ == '__main__':
    train()
```

Relevant output of this. Messages with (pid=25954) are coming from the call to `first_fn`.

```
Calling second function and creating test_second_fn
wandb: Tracking run with wandb version 0.8.35
(pid=25954) Calling first function and creating test_first_fn
(pid=25954) wandb: Tracking run with wandb version 0.8.35
wandb: Run data is saved locally in wandb/run-20200506_183331-3oa6cwhf
wandb: Syncing run test_second_fn
wandb: ⭐️ View project at https://app.wandb.ai/lil/test_project
wandb: 🚀 View run at https://app.wandb.ai/lil/test_project/runs/3oa6cwhf
wandb: Run `wandb off` to turn off syncing.

(pid=25954) wandb: Run data is saved locally in wandb/run-20200506_183332-pj53w5zg
(pid=25954) wandb: Syncing run test_first_fn
(pid=25954) wandb: ⭐️ View project at https://app.wandb.ai/lil/test_project
(pid=25954) wandb: 🚀 View run at https://app.wandb.ai/lil/test_project/runs/pj53w5zg
(pid=25954) wandb: Run `wandb off` to turn off syncing.
(pid=25954) 
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/site-packages/wandb/apis/file_stream.py", line 213, in _thread_body
    self._send(ready_chunks)
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/site-packages/wandb/apis/file_stream.py", line 249, in _send
    self._client.post, self._endpoint, json={'files': files}))
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/site-packages/wandb/apis/file_stream.py", line 227, in _handle_response
    raise response
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/site-packages/wandb/util.py", line 590, in request_with_retry
    response.raise_for_status()
  File "/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/files/lil/test_project/3oa6cwhf/file_stream
```

That link (ID `3oa6cwhf`) is associated with the `test_second_fn` experiment.

Is there any way to get this to work with ray?

Edit: worth mentioning that this results in the same error as #940 but there don't seem to be any unicode errors. If you comment out either of the two function calls, wandb should initialize properly.

Also, I'm not trying to do a ray tune, which it seems like wandb supports. 

Thanks!

**Comment by alsuhr-c** [comment]
Hi, 

Just wondering if there is any update on this issue. It's blocking my research right now; I've had to resort to text-based logging in order to get the results for intermediate training.

I tried using the suggestions here: https://docs.wandb.com/library/init#how-do-i-launch-multiple-runs-from-one-script but it seems this still doesn't support multiple runs at the same time (besides, the MWE above is breaking before I even try to log anything), just multiple runs in the same script. 

If I add `wandb.join` statements after initializing the `test_second_function` experiment, I don't see the error message, and I can call `wandb.log` in `second_function` after calling `wandb.join` and it *seems* like the logs are going through to wandb, but in fact the wandb process associated with `test_second_function` has terminated, so the calls to `log` are no-op and nothing shows up on its wandb experiment dashboard.

**Comment by alsuhr-c** [comment]
For now, I found a workaround: calling both functions as `ray.remote` functions rather than having one exist in the main process and another in the process initiated by `ray`. Ideally, though, having the ability to log to multiple runs would be very useful (kind of how python's `logging` allows you to log to multiple loggers in one process).

Thanks!
