### ISSUE TITLE
wandb.watch incompatible with non-contiguous tensors

### ISSUE THREAD

**Issue by jotterbach** [wandb/client#1019]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.8.31
* Python version: Python 3.7.3
* Operating System: Linux

### Description

I'm running a  complex distributed model, where controlling the contiguity of all tensors at all times is difficult. This seems to be incompatible with the `wandb.watch` which uses `view`s to change the tensor layouts.

### What I Did

Here is the stacktrace:

```python
[0] Traceback (most recent call last):
[0]   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[0]     "__main__", mod_spec)
[0]   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
[0]     exec(code, run_globals)
[0]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/__main__.py", line 7, in <module>
[0]     main()
[0]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/run.py", line 196, in main
[0]     run_command_line(args)
[0]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/run.py", line 42, in run_command_line
[0]     run_module(sys.argv[0], run_name='__main__', alter_sys=True)
[0]   File "/opt/conda/lib/python3.7/runpy.py", line 205, in run_module
[0]     return _run_module_code(code, init_globals, run_name, mod_spec)
[0]   File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
[0]     mod_name, mod_spec, pkg_name, script_name)
[0]   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
[0]     exec(code, run_globals)
[0]   File "/root/code/rcall/rcall/commands/entrypoint.py", line 34, in <module>
[0]     main()
[0]   File "/root/code/rcall/rcall/commands/entrypoint.py", line 30, in main
[0]     run_fn(**kwargs)
[0]   File "/root/code/rcall/rcall/runtime.py", line 207, in run_fn
[0]     raise e
[0]   File "/root/code/rcall/rcall/runtime.py", line 184, in run_fn
[0]     result = func(*args, **kwargs)
[0]   File "/root/code/johannes-sandbox/cd-training/cdk/train_ddp.py", line 496, in train
[0]     loss.backward()
[0]   File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
[0]     torch.autograd.backward(self, gradient, retain_graph, create_graph)
[0]   File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
[0]     allow_unreachable=True)  # allow_unreachable flag
[0]   File "/opt/conda/lib/python3.7/site-packages/wandb/wandb_torch.py", line 256, in <lambda>
[0]     handle = var.register_hook(lambda grad: _callback(grad, log_track))
[0]   File "/opt/conda/lib/python3.7/site-packages/wandb/wandb_torch.py", line 254, in _cal[0] lback
[0]     self.log_tensor_stats(grad.data, name)
[0]   File "/opt/conda/lib/python3.7/site-packages/wandb/wandb_torch.py", line 165, in log_tensor_stats
[0]     flat = tensor.view(-1)
[0] RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by vanpelt** [comment]
We just fixed this in master and should be releasing a new version tomorrow.  For now, you can install off master with:

```
pip install --upgrade https://github.com/wandb/client/archive/master.zip
```

**Comment by ariG23498** [comment]
Hey @jotterbach 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
