### ISSUE TITLE
MPI_INIT failed when calling wandb.init()

### ISSUE THREAD

**Issue by Liangtaiwan** [wandb/client#1024]
* Weights and Biases version: 0.8.34
* Python version: 3.8.1
* Operating System: Arch Linux (kernel 5.5.7.arch-1)

### Description

When using slurm to init wandb, it seems that it fail to init mpi.
Maybe the error is due to wandb try to init mpi again when calling wandb.init().

Here is the related issue
https://github.com/open-mpi/ompi/issues/7025#issuecomment-536826728

### What I Did

```
srun: job 52496 queued and waiting for resources
srun: job 52496 has been allocated resources
Python 3.8.1 (default, Jan 22 2020, 06:38:00)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init()
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/username/wandb/ wasn't writable, using system temp directory
wandb: W&B is a tool that helps track and visualize machine learning experiments
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: No credentials found.  Run "wandb login" to visualize your metrics
wandb: Tracking run with wandb version 0.8.35
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[s15.speech:244894] Local abort before MPI_INIT completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: Job step aborted: Waiting up to 182 seconds for job step to finish.
```

**Comment by cvphelps** [comment]
Hi there, thanks for your issue report. @raubitsj is working on a rewrite of our CLI that will hopefully solve this and other issues

**Comment by vanpelt** [comment]
This specific issue is being caused by the file system not being writable at "/home/username/wandb".  You can override the directory wandb uses to write temporary files by setting the WANDB_DIR env variable to something like /tmp

**Comment by Liangtaiwan** [comment]
@cvphelps  Thanks for your reply.
@vanpelt  It seems that the problem this not cause by the WANDB_DIR

I got the same issue after given the WANDB_DIR env variable.

```
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['WANDB_DIR']
'/tmp'
>>> import wandb
>>> wandb.init()
wandb: W&B is a tool that helps track and visualize machine learning experiments
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: No credentials found.  Run "wandb login" to visualize your metrics
wandb: Tracking run with wandb version 0.8.35
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[s15.speech:316184] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: Job step aborted: Waiting up to 182 seconds for job step to finish.
```

**Comment by Liangtaiwan** [comment]
@cvphelps, @vanpelt 
I found a error message in my journal, maybe it's helpful for you.
```
May 14 19:36:26 s12.speech systemd-coredump[159861]: Process 159698 (slurmstepd) of user 0 dumped>
                                                     
                                                     Stack trace of thread 159702:
                                                     #0  0x0000154446d9e0f1 pmix_ptl_base_lost_co>
                                                     #1  0x0000154446d9f36b pmix_ptl_base_recv_ha>
                                                     #2  0x0000154446cb5e2a n/a (libevent-2.1.so.>
                                                     #3  0x0000154446cb64cf event_base_loop (libe>
                                                     #4  0x0000154446d60dff n/a (libpmix.so + 0x7>
                                                     #5  0x000015444776246f start_thread (libpthr>
                                                     #6  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159706:
                                                     #0  0x0000154447685abf __poll (libc.so.6 + 0>
                                                     #1  0x0000154446e0b610 n/a (task_cgroup.so +>
                                                     #2  0x000015444776246f start_thread (libpthr>
                                                     #3  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159700:
                                                     #0  0x000015444776901a pthread_cond_timedwai>
                                                     #1  0x00001544478cf478 n/a (libslurmfull.so >
                                                     #2  0x000015444776246f start_thread (libpthr>
                                                     #3  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159703:
                                                     #0  0x0000154447687f0b __select (libc.so.6 +>
                                                     #1  0x0000154446da020f n/a (libpmix.so + 0xb>
                                                     #2  0x000015444776246f start_thread (libpthr>
                                                     #3  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159699:
                                                     #0  0x0000154447768cf5 pthread_cond_wait@@GL>
                                                     #1  0x00001544478d5f88 n/a (libslurmfull.so >
                                                     #2  0x000015444776246f start_thread (libpthr>
                                                     #3  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159698:
                                                     #0  0x000015444765d9af wait4 (libc.so.6 + 0x>
                                                     #1  0x0000563ba53d2aa2 n/a (slurmstepd + 0x1>
                                                     #2  0x0000563ba53d4bc7 job_manager (slurmste>
                                                     #3  0x0000563ba53d05b5 main (slurmstepd + 0x>
                                                     #4  0x00001544475b8023 __libc_start_main (li>
                                                     #5  0x0000563ba53cd94e _start (slurmstepd + >
                                                     
                                                     Stack trace of thread 159701:
                                                     #0  0x0000154447685abf __poll (libc.so.6 + 0>
                                                     #1  0x000015444796e7ad eio_handle_mainloop (>
                                                     #2  0x0000563ba53e7b77 n/a (slurmstepd + 0x2>
                                                     #3  0x000015444776246f start_thread (libpthr>
                                                     #4  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159704:
                                                     #0  0x0000154447685abf __poll (libc.so.6 + 0>
                                                     #1  0x000015444796e7ad eio_handle_mainloop (>
                                                     #2  0x0000154446dd4ea6 n/a (mpi_pmix_v3.so +>
                                                     #3  0x000015444776246f start_thread (libpthr>
                                                     #4  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159705:
                                                     #0  0x0000154447685abf __poll (libc.so.6 + 0>
                                                     #1  0x0000154446dd4d4a n/a (mpi_pmix_v3.so +>
                                                     #2  0x000015444776246f start_thread (libpthr>
                                                     #3  0x00001544476903d3 __clone (libc.so.6 + >
                                                     
                                                     Stack trace of thread 159707:
                                                     #0  0x0000154447685abf __poll (libc.so.6 + 0>
                                                     #1  0x0000563ba53d90f6 n/a (slurmstepd + 0x1>
                                                     #2  0x000015444776246f start_thread (libpthr>
                                                     #3  0x00001544476903d3 __clone (libc.so.6 + >
-- Subject: Process 159698 (slurmstepd) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 159698 (slurmstepd) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
```

**Comment by vanpelt** [comment]
@Liangtaiwan The error isn't telling us what's causing the crash.  I did notice from your output that the environment your calling wandb.init in doesn't have credentials.  Can you ensure the environment variable WANDB_API_KEY is set to your API key in the slurm environment?  Also, if you're able to access the file system the experiment was run on there's a `wandb/debug.log` that would be helpful to debug.

**Comment by Liangtaiwan** [comment]
@vanpelt There is no different if I pass the api_key in the slurm enviroment. (I tried it.)
and I cannot found any debug.log under the wandb directory.

**Comment by Liangtaiwan** [comment]
@vanpelt I'm not sure this issue is related to tensorflow or not.
When import tensorflow, it will call MPI_INIT() and do some MPI related operation.

I found that in wandb/client, you import tensorflow in the module for some reason.

**Comment by pohanchi** [comment]
I meet the same issue on wandb in slurm environment. I think import tensorflow in the wandb.init() might be a big reason to cause this error.

**Comment by pohanchi** [comment]
hope this issue can be solved as soon as possible @vanpelt

**Comment by vanpelt** [comment]
Hey @pohanchi @Liangtaiwan we're spinning up our own Slurm environment to reproduce this.  In the mean time, can one or both of you try our new CLI which should work better in these environments?  You can find it here:  https://github.com/wandb/client-ng

```python
pip install wandb-ng
```

**Comment by Liangtaiwan** [comment]
@vanpelt I encounter the same error as before.

**Comment by pohanchi** [comment]
the debug.log is below 
![image](https://user-images.githubusercontent.com/34079344/82312646-f1271c00-99f9-11ea-8f4e-3468beeee218.png)

**Comment by vanpelt** [comment]
Ok, thanks for trying.  I'm trying to reproduce and will hopefully have an answer in the next few days.

**Comment by vanpelt** [comment]
Ok sorry guys, I failed to realize we already have a special wrapper for this case.  You can use the following example code to run a sweep with MPI:

https://github.com/wandb/examples/blob/master/sweeps-mpi-wrappers/README.md

This should work with the mainline "wandb" library or the "wandb-ng" library, I suggest "wandb" for now.  Please let us know if the instructions don't make sense, or you're still seeing any issues.

**Comment by pohanchi** [comment]
```
[pohan@s08 ~]$ python wrap_mpi_outer.py 
[s08.speech:693945] [[38613,0],0] ORTE_ERROR_LOG: Data unpack had inadequate space in file util/show_help.c at line 513
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value No permission (-17) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "No permission" (-17) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[s08.speech:693958] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
Problem at: train.py 5 <module>
Traceback (most recent call last):
  File "/home/pohan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 534, in init
    run = wi.init()
  File "/home/pohan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 450, in init
    run._set_run_obj(ret.run)
AttributeError: 'NoneType' object has no attribute 'run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pohan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 539, in init
    wi._atexit_cleanup()
  File "/home/pohan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 317, in _atexit_cleanup
    ret = self.backend.interface.send_exit_sync(exit_code, timeout=60)
AttributeError: 'NoneType' object has no attribute 'interface'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 5, in <module>
    wandb.init()
  File "/home/pohan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 552, in init
    raise_from(Exception("problem"), e)
  File "<string>", line 3, in raise_from
Exception: problem
```

The error message is above.  My train.py is just a program 
```
import wandb 
wandb.init()
```

I just run the command ``` python wrap_mpi_outer.py```
@vanpelt

**Comment by vanpelt** [comment]
@pohanchi can you try with the mainline wandb library?  Run the following:

```
pip uninstall wandb-ng
pip install wandb --upgrade
```

**Comment by pohanchi** [comment]
![image](https://user-images.githubusercontent.com/34079344/82747148-69783f00-9d64-11ea-917f-287512d76b0d.png)

I get the error above. My storage is still sufficient, so it is not the problem about insufficient storage.

**Comment by vanpelt** [comment]
@pohanchi This error is due file permissions.  We're attempting to write to "/tmp/wandb" but the user running the process does not write permission to that directory.  Can you change the "WANDB_DIR" environment variable to a directory that is writable?

**Comment by Twsschx** [comment]
> Hey @pohanchi @Liangtaiwan we're spinning up our own Slurm environment to reproduce this. In the mean time, can one or both of you try our new CLI which should work better in these environments? You can find it here: https://github.com/wandb/client-ng
> 
> ```python
> pip install wandb-ng
> ```

I am running the wand-ng and it appears 'Enter api key'. How to get the api key ?

**Comment by cvphelps** [comment]
This works with the new cli, `pip install wandb` version 0.10+. To get your API key go to wandb.ai/authorize.
