### ISSUE TITLE
Friendlier error message when project name length is less than three chars

### ISSUE THREAD

**Issue by lukas** [wandb/client#103]
* Weights and Biases version: 0.4.45
* Python version: 3.6.3
* Operating System: mac

### Description
I named a project tf and I got this error

```
Enter a name for your new project: tf
error: Traceback (most recent call last):
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/wandb/api.py", line 70, in wrapper
error:     return func(*args, **kwargs)
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/wandb/api.py", line 453, in upsert_project
error:     'description': description, 'repo': self.git.remote_url, 'id': id})
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/gql/client.py", line 52, in execute
error:     raise Exception(str(result.errors[0]))
error: Exception: {'message': 'name must be atleast 3 characters, got: "tf"', 'code': 400, 'locations': [{'column': 3, 'line': 2}]}
error: 
error: During handling of the above exception, another exception occurred:
error: 
error: Traceback (most recent call last):
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/wandb/cli.py", line 58, in wrapper
error:     return func(*args, **kwargs)
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/wandb/cli.py", line 490, in init
error:     project = prompt_for_project(ctx, entity)
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/wandb/cli.py", line 110, in prompt_for_project
error:     api.upsert_project(project, entity=entity, description=description)
error:   File "/Users/l2k/.pyenv/versions/3.6.1/envs/wandb-3.6.1/lib/python3.6/site-packages/wandb/api.py", line 96, in wrapper
error:     raise CommError(message)
error: wandb.api.CommError: name must be atleast 3 characters, got: "tf"
Error: An Exception was raised, see <unknown> for full traceback.
wandb.api.CommError: name must be atleast 3 characters, got: "tf"
```

**Comment by adrianbg** [comment]
Oops, should've referenced #107 in that commit
