### ISSUE TITLE
Cannot get api key after run local WANDB

### ISSUE THREAD

**Issue by stalkermustang** [wandb/client#1054]
Weights and Biases version: version 0.8.36
Python version: 3.7.5
Operating System: Linux

### Description
I'm running wandb localy:
```wandb local --upgrade --port 8892```

Then i get in console: 
`wandb: You can find your API key in your browser here: http://localhost:8892/authorize
wandb: Paste an API key from your profile and hit enter:`

And when i go to page, i see 
![image](https://user-images.githubusercontent.com/26546178/82574387-b0610b80-9b8f-11ea-8591-34ffffecb3e2.png)
this endless (and reloading) message. Sometimes browser redirect me to /signup page, but there's error:
![image](https://user-images.githubusercontent.com/26546178/82574458-d8506f00-9b8f-11ea-87cb-e03b68d6521d.png)
restarts and rebuilds didn't help. 

In debug.log i only see:
`2020-05-21 17:03:16,408 DEBUG   MainThread:22316 [auth.py:find_config_file():47] Trying paths: ['/home/seeall/.docker/config.json', '/home/seeall/.dockercfg']
2020-05-21 17:03:16,408 DEBUG   MainThread:22316 [auth.py:find_config_file():54] No config file found
2020-05-21 17:03:16,598 DEBUG   MainThread:22316 [auth.py:resolve_authconfig():295] Looking for auth entry for 'docker.io'
2020-05-21 17:03:16,599 DEBUG   MainThread:22316 [auth.py:resolve_authconfig():306] No entry found
2020-05-21 17:03:19,564 DEBUG   MainThread:22316 [auth.py:resolve_authconfig():295] Looking for auth entry for 'docker.io'
2020-05-21 17:03:19,564 DEBUG   MainThread:22316 [auth.py:resolve_authconfig():306] No entry found`

BUT dockerlogs spam:

```docker logs wandb-local  | head -5
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/enable-services.sh...
*** Running /etc/my_init.d/load-settings.sh...
*** Enabling production mode
*** Booting runit daemon...
*** Runit started as PID 38
panic: Dirty database version 8. Fix and force version.
*** Starting wandb servers...

*** Migrating database...
goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/migrate/main.go:82 +0x7dd
*** All services started
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'
*** Access W&B at http://localhost:8080

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla/main.go:268 +0x534e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e```

**Comment by hokmund** [comment]
Got the same problem today after upgrading wandb-local with `wandb local --upgrade`

**Comment by vanpelt** [comment]
This looks like the migration failed on restart.  Can you run the following and attach the input.

```
docker exec -it wandb-local bash
sudo mysql
use wandb_local
SELECT * FROM schema_migrations
```

You can also attempt manual restarting, and share the logs from first boot:

```
docker stop wandb-local
wandb local
docker logs wandb-local
```

**Comment by vanpelt** [comment]
@stalkermustang your migration failed at version 8 which is suspect.  CAn you also run:

```
SHOW create table runs;
```

From within the mysql shell?  There should be an "agent_id" column.  Assuming there is, you can run the following from the mysql shell:

```
UPDATE schema_migrations SET dirty = 0;
```

Then restart the instance to have new migrations applied.

**Comment by stalkermustang** [comment]
Thanks, it's working! But...then don't, and i `docker rmi` image, then rebuild from zero and start new local wand, but there's old admin (with simimllar nickname, lol).
Can you tell me pls, how to delete all users or restore to default? Where's stored mysql-db, which contains info? How i can clear it? Simly drop table?

**Comment by stalkermustang** [comment]
also i cannot delete users from
`http://localhost:8080/admin/users`
tab :/

**Comment by stalkermustang** [comment]
so i'm remove image, stop and remove container, then rm volume wandb from docker. Also i clear wandb file on my local server (with log and settings). 
Then i typo "wandb local", docker pull image, build and start. But at this point CLI don't tell me /authorize link and dont want from me api-key (why?)

`SELECT * FROM schema_migrations ` show dirty=1 and version 6 (different from 8 previos, lol)
but
`SHOW create table runs;` dont show agent_id now! (after first try 2 mesasges above i got it).

what magic is it? @vanpelt

**Comment by stalkermustang** [comment]
Now log be like:
```*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/enable-services.sh...
*** Running /etc/my_init.d/load-settings.sh...
*** Enabling production mode
*** Booting runit daemon...
*** Runit started as PID 38
*** Starting wandb servers...
panic: Dirty database version 6. Fix and force version.
*** Migrating database...

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/migrate/main.go:82 +0x7dd
*** All services started
*** Access W&B at http://localhost:8080
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla/main.go:268 +0x534e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e```

**Comment by stalkermustang** [comment]
Another detailed try:

1) stop container
2) remove container
3) rm image
4) rm volume
5) rm folder (and remake it) on local server
--
6) wandb local
wait for pull image

```
c18f29776971: Pull complete
Digest: sha256:fc4be379cbaf9863605a97bacccd38518dfe116c50fd6e68ca936c5a8e30efa5
Status: Downloaded newer image for wandb/local:latest
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running docker stop wandb-local
```

^- at this point i don't see /authorize link like first time

7) docker logs wandb-local
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/enable-services.sh...
*** Enabling production mode
*** Running /etc/my_init.d/load-settings.sh...
*** Rotating minio credentials...
*** Booting runit daemon...
*** Runit started as PID 41
*** Setting up mysql database...
*** Configuring minio...
*** Starting wandb servers...
Bucket created successfully local/local-files.
Successfully added arn:minio:sqs:wandb-local:_:redis
*** Migrating database...
*** All services started
*** Access W&B at http://localhost:8080
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla/main.go:268 +0x534e
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
```
- wandb running, but with problems as i can see

8) go into container:
```
docker exec -it wandb-local bash
sudo mysql
use wandb_local
SELECT * FROM schema_migrations;
```
and output is:
```
SELECT * FROM schema_migrations
    -> ;
+---------+-------+
| version | dirty |
+---------+-------+
|      24 |     1 |
+---------+-------+
1 row in set (12.53 sec)
```
(version 24 what???)

9) `SHOW create table runs;`

i got:
```
runs  | CREATE TABLE `runs` (
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `name` varchar(128) NOT NULL,
  `job_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `sweep_name` varchar(64) DEFAULT NULL,
  `config` json DEFAULT NULL,
  `summary_metrics` json DEFAULT NULL,
  `system_metrics` json DEFAULT NULL,
  `state` varchar(64) DEFAULT NULL,
  `commit` varchar(64) DEFAULT NULL,
  `host` varchar(64) DEFAULT NULL,
  `exitcode` bigint(20) DEFAULT NULL,
  `description` text,
  `heartbeat_at` datetime DEFAULT NULL,
  `group_name` varchar(128) DEFAULT NULL,
  `subgroup_name` varchar(128) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `history_count` bigint(20) DEFAULT '0',
  `event_count` bigint(20) DEFAULT '0',
  `log_count` bigint(20) DEFAULT '0',
  `stopped` tinyint(1) DEFAULT '0',
  `keys_info` json DEFAULT NULL,
  `agent_id` varchar(128) DEFAULT NULL,
  `original_entity_name` varchar(64) DEFAULT NULL,
  `original_project_name` varchar(128) DEFAULT NULL,
  `original_run_name` varchar(128) DEFAULT NULL,
  `tags_json` json DEFAULT NULL,
  `display_name` varchar(128) DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`project_id`,`name`),
  KEY `ix_runs_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
/*!50100 PARTITION BY HASH (project_id)
PARTITIONS 101 */ |
```
agent_id here, huh

10) ok, type `UPDATE schema_migrations SET dirty = 0;`

11) docker stop wandb-local
wandb local

12) docker logs wandb-local | head -8
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/enable-services.sh...
*** Running /etc/my_init.d/load-settings.sh...
*** Booting runit daemon...
*** Runit started as PID 1145
*** Enabling production mode
*** Starting wandb servers...
*** Migrating database...
panic: Dirty database version 38. Fix and force version.

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/migrate/main.go:82 +0x7dd
*** All services started
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'
*** Access W&B at http://localhost:8080

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla/main.go:268 +0x534e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
!!! Unable to start backend, see logs at http://localhost:8080/system-admin/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla-filemeta/main.go:102 +0x118e
*** Starting wandb servers...
panic: github.com/wandb/core/services/gorilla/mysql.(*metadataStore).prepareInsertUser-fm: Error 1054: Unknown column 'user_info_text' in 'field list'

goroutine 1 [running]:
main.main()
	/home/runner/work/core/src/github.com/wandb/core/services/gorilla/cmd/gorilla/main.go:268 +0x534e
```

**Comment by stalkermustang** [comment]
have no idea what is going...

**Comment by vanpelt** [comment]
@stalkermustang when the container boots it will run migrations.  If you kill or stop the container during the running of these migrations you'll end up with the database in an invalid state.  We need to get to the bottom of why your migration is failing.  Can you run the following?

```
docker stop wandb-local
docker volume rm wandb
wandb local
```

Once this is up and running you can see the migration progress in the vm by querying the database:

```
docker exec -it bash wandb-local
sudo mysql
use wandb_local;
SELECT * FROM schema_migrations;
```

You'd will need to run the SELECT statement multiple times and ultimately it should return finish at version 67 with the dirty column equal to 0.

**Comment by vanpelt** [comment]
@stalkermustang the data exists in a docker managed volume named "wandb" which I removed above by running `docker volume rm wandb`

**Comment by noklam** [comment]
I am getting simliar problem, may I know how can I fix it?

**Comment by stalkermustang** [comment]
I waited an hour until my migration ended (I expected the process to be much faster).

> You'd will need to run the SELECT statement multiple times and ultimately it should return finish at version 67 with the dirty column equal to 0.

at this point i go to /authorize page and ... done!

**Comment by vanpelt** [comment]
This is likely due to the docker file system driver.  @noklam @stalkermustang what OS are you running docker from?  Switching to the "overlay" filesystem would likely make this run much faster.

**Comment by noklam** [comment]
I am running from Window.

**Comment by vanpelt** [comment]
Can you run `docker info` and paste the output here.

**Comment by noklam** [comment]
> Can you run `docker info` and paste the output here.

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.922GiB
 Name: docker-desktop
 ID: DGPW:JMBA:A2IC:HHYZ:LO3F:3KNP:BDLD:N7RO:6B5R:P4BE:IFSL:7A5V
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 47
  Goroutines: 58
  System Time: 2020-05-26T01:26:42.021750745Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```
