### ISSUE TITLE
SWEEP error

### ISSUE THREAD

**Issue by Merlin55** [wandb/client#1067]
**Hi, I am new to wandb. I am trying sweep to do hyperparameter searching. After I typed the command "wandb agent ID", there is only one set of hyperparameter run. When it comes to the second set, it raised the following error:**

- 2020-05-28 02:12:37,337 INFO    MainThread:7173 [wandb_agent.py:run():194] Running runs: []
2020-05-28 02:12:37,555 INFO    MainThread:7173 [wandb_agent.py:_process_command():256] Agent received command: run
2020-05-28 02:12:37,555 INFO    MainThread:7173 [wandb_agent.py:_command_run():286] Agent starting run with config:
	batch_size: 136
	epochs: 3
	log_interval: 17
	lr: 0.01617047217268529
	momentum: 0.8414045852070394
	seed: 4
	test_batch_size: 1982
2020-05-28 02:12:37,559 DEBUG   MainThread:7173 [wandb_config.py:_load_defaults():128] wandb dir not provided, skipping defaults
2020-05-28 02:12:37,682 INFO    MainThread:7173 [wandb_agent.py:_command_run():325] About to run command: /usr/bin/env python main.py --batch_size=136 --epochs=3 --log_interval=17 --lr=0.01617047217268529 --momentum=0.8414045852070394 --seed=4 --test_batch_size=1982
2020-05-28 02:12:42,695 INFO    MainThread:7173 [wandb_agent.py:run():194] Running runs: ['dm3it6yv']
2020-05-28 02:13:13,411 INFO    MainThread:7173 [wandb_agent.py:run():209] Cleaning up finished run: dm3it6yv
2020-05-28 02:13:13,585 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:13:13,585 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-05-28 02:13:14,794 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:13:14,794 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-05-28 02:13:17,399 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:13:17,399 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-05-28 02:13:17,400 ERROR   MainThread:7173 [retry.py:__call__():108] Retry attempt failed:
Traceback (most recent call last):
  File "/home/pwang/anaconda3/envs/py37/lib/python3.7/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pwang/anaconda3/envs/py37/lib/python3.7/site-packages/wandb/apis/internal.py", line 116, in execute
    six.reraise(*sys.exc_info())
  File "/home/pwang/anaconda3/envs/py37/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/pwang/anaconda3/envs/py37/lib/python3.7/site-packages/wandb/apis/internal.py", line 110, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/pwang/.local/lib/python3.7/site-packages/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pwang/.local/lib/python3.7/site-packages/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pwang/.local/lib/python3.7/site-packages/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/pwang/anaconda3/envs/py37/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2020-05-28 02:13:21,933 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:13:21,934 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-05-28 02:13:31,257 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:13:31,257 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-05-28 02:13:50,818 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:13:50,818 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-05-28 02:14:26,396 ERROR   MainThread:7173 [internal.py:execute():113] 500 response executing GraphQL.
2020-05-28 02:14:26,396 ERROR   MainThread:7173 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: must be real number, not dict\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}

**I tried several times. But it still can only work for the first set, and failed on the second set. Could anyone help me? Many thanks!**

**Comment by vanpelt** [comment]
Can you share your sweep config / sweep.yaml file?

**Comment by Merlin55** [comment]
The experiment is "pytorch-cnn-mnist" in the example folder. Here is the sweep config:

method: bayes
metric:
  goal: minimize
  name: graph_0
parameters:
  lr:
    distribution: uniform
    max: 0.037289897112918954
    min: 0.002536465250558708
program: main.py


Thank you!


> Can you share your sweep config / sweep.yaml file?

**Comment by ariG23498** [comment]
Hey @Merlin55 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:
