### ISSUE TITLE
W&B process failed to launch, see: wandb\debug.log

### ISSUE THREAD

**Issue by zkx741481546** [wandb/client#1089]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.0
* Python version:3.7
* Operating System:win10

### Description

I run my program in pycharm 2020 and init wandb with this code:`wandb.init(project="future_trade_test", sync_tensorboard=True)`,
and it show this error:
```wandb: Tracking run with wandb version 0.9.0
Traceback (most recent call last):
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 106, in <module>
    main()
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 98, in main
    headless(args)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 54, in headless
    util.sentry_reraise(e)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\util.py", line 94, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 52, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\run_manager.py", line 1140, in wrap_existing_process
    stderr_read_file = os.fdopen(stderr_read_fd, 'rb')
  File "C:\Users\zkx74\Anaconda3\lib\os.py", line 1027, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [WinError 6] 句柄无效。
wandb: ERROR W&B process (PID 20148) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "E:/PycharmProjects/test_parallel3/run_paraellel3.py", line 14, in <module>
    wandb.init(project="future_trade_test", sync_tensorboard=True)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\__init__.py", line 1123, in init
    _init_headless(run)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\__init__.py", line 312, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
```

The wired thing is if I run it with debug mode, wandb init normally. And I can also run another project with wandb normally.
The project which have this problem is copied from my friend who is also using Wandb, I guess this may have some connections with the bug?

Here is my debug.log:
```2020-06-08 17:00:40,866 DEBUG   MainThread:20148 [wandb_config.py:_load_defaults():133] no defaults not found in config-defaults.yaml
2020-06-08 17:00:42,080 DEBUG   MainThread:20148 [git_repo.py:repo():30] git repository is invalid
2020-06-08 17:00:42,163 DEBUG   MainThread:20148 [run_manager.py:__init__():547] Initialized sync for future_trade_test/uip8waey
```
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by vanpelt** [comment]
We have an experimental version of our library that should work much better in Windows and address this issue.

You can install it with `pip install wandb-ng`, more information can be found here: https://github.com/wandb/client-ng

**Comment by zkx741481546** [comment]
> We have an experimental version of our library that should work much better in Windows and address this issue.
> 
> You can install it with `pip install wandb-ng`, more information can be found here: https://github.com/wandb/client-ng

Thanks for your reply. I installed wandb-ng, but when I trying to use command `wandb login`, this error occured
`(base) C:\Users\zkx74>wandb login
Traceback (most recent call last):
  File "c:\users\zkx74\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zkx74\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zkx74\Anaconda3\Scripts\wandb.exe\__main__.py", line 7, in <module>
  File "c:\users\zkx74\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\zkx74\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\zkx74\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\zkx74\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\zkx74\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\zkx74\anaconda3\lib\site-packages\wandb\cli\cli.py", line 48, in wrapper
    return func(*args, **kwargs)
  File "c:\users\zkx74\anaconda3\lib\site-packages\wandb\cli\cli.py", line 83, in login
    wandb.login(relogin=relogin)
  File "c:\users\zkx74\anaconda3\lib\site-packages\wandb\sdk\wandb_login.py", line 36, in login
    active_entity = wl._get_entity()
  File "c:\users\zkx74\anaconda3\lib\site-packages\wandb\sdk\wandb_setup.py", line 144, in _get_entity
    entity = self._server._viewer.get("entity")
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by zkx741481546** [comment]
> We have an experimental version of our library that should work much better in Windows and address this issue.
> 
> You can install it with `pip install wandb-ng`, more information can be found here: https://github.com/wandb/client-ng

And I noticed that the wandb-ng version has "No tensorboard_sync option, no from wandb import magic", how should I do to see my tensorboard in wandb-ng

**Comment by vanpelt** [comment]
We're actively working on bringing the new version to feature parity to the current.  tensorboard_sync should be coming in the next week or 2.

**Comment by vukovicnikola** [comment]
Have there been any updates on this issue in the main client? Or should people experiencing this error continue using wandb-ng?

**Comment by farizrahman4u** [comment]
Should be working on wandb/client now.
