### ISSUE TITLE
requirements: Should indicate `tensorboardX>=1.5`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [wandb/client#1097]
* Weights and Biases version: 0.9.1
* Python version: 3.6.9
* Operating System: Linux

### Description

If I try to to use `wandb.init(..., sync_tensorboard=True)` with `tensorboardX==1.4`, it doesn't work.

If I use `tensorboardX==1.5`, it does.

### What I Did

```sh
(
set -eux
cd $(mktemp -d)
python3 -m virtualenv -p python3 .
source bin/activate
pip install wandb==0.9.1

cat > ./test.py <<EOF
import wandb
import wandb.tensorboard
wandb.init(project="test", sync_tensorboard=True)
EOF

export WANDB_MODE=dryrun

# Expect failure
pip install tensorboardX==1.4
! python ./test.py

# Upgrade and succeed
pip install tensorboardX==1.5
python ./test.py
)
```

Output: from `tensorboardX==1.4`:
```
+ pip install tensorboardX==1.4
...
+ python ./test.py
Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    import wandb.tensorboard
  File "/tmp/tmp.0esiVV8BjZ/lib/python3.6/site-packages/wandb/tensorboard/__init__.py", line 46, in <module>
    from tensorboardX.proto.summary_pb2 import Summary
ModuleNotFoundError: No module named 'tensorboardX.proto'
...
+ python ./test.py
...
wandb: Program ended successfully.
```

**Comment by EricCousineau-TRI** [comment]
Relates #709 - in that I ran across it while debugging this :(

**Comment by vanpelt** [comment]
Thanks for debugging, just merged.
