### ISSUE TITLE
[BUG][SCRIPT]Artifact download not working in script mode : ERROR 'graphql: got null for non-null'

### ISSUE THREAD

**Issue by jqueguiner** [wandb/client#1120]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.9.1
* Python version: Python 3.6.9 :: Anaconda, Inc.
* Operating System: Linux

### Description

Unable to download artifacts using Python3 script while it’s working on jupyter notebook

### What I Did
This code works in jupyter notebook
```python
import wandb
run = wandb.init()

artifact = run.use_artifact('jilijeanlouis/ovh-automl-image-classification-train-resnet50-homey-brown-dhole/export-models:v1', type='model')
artifact_dir = artifact.download()
```

But in python script I get:

```
>>> artifact = run.use_artifact('jilijeanlouis/ovh-automl-image-classification-train-resnet50-homey-brown-dhole/export-models:v1', type='model')
Traceback (most recent call last):
>>>   File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/wandb/wandb_run.py", line 430, in use_artifact
    self.api.use_artifact(artifact.id)
  File "/opt/conda/lib/python3.6/site-packages/wandb/apis/internal.py", line 1038, in use_artifact
    'artifactID': artifact_id,
  File "/opt/conda/lib/python3.6/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/wandb/apis/internal.py", line 108, in execute
    return self.client.execute(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/gql/client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'graphql: got null for non-null'}
```

**Comment by jqueguiner** [comment]
In the meantime for anyone trying to find a workaround the API itself works great : [https://docs.wandb.com/library/reference/wandb_api#artifact](https://docs.wandb.com/library/reference/wandb_api#artifact)

Doing the same thing will be
```python
>>>wandb_api = wandb.Api()
>>>artifact = wandb_api.artifact(name='jilijeanlouis/ovh-automl-image-classification-train-resnet50-homey-brown-dhole/export-models:v1', type='model')
>>>artifact_dir = artifact.download()
>>>print(artifact_dir)
'/root/.cache/wandb/artifacts/final/model/5fb842b1ce0c65684462f18c946a020b/artifact'>>> os.system('ls '+b)
best-resnet50-default.pt  best-resnet50-details.pt  best-resnet50-export.pkl  best-resnet50-save.pth  best-resnet50-state_dict.pt  best-resnet50.onnx
```

**Comment by vanpelt** [comment]
Nice @jqueguiner we've fixed this issue in master.  We're targeting a new release first thing next week!

**Comment by jqueguiner** [comment]
associated PR : https://github.com/wandb/client/pull/1125

**Comment by jqueguiner** [comment]
Works like a charm ! thanks
