### ISSUE TITLE
wandb in pytest causes OSError: [Errno 29] Illegal seek

### ISSUE THREAD

**Issue by awaelchli** [wandb/client#1138]
* Weights and Biases version: 0.9.2
* Python version: 3.7.6
* Operating System: Linux

### Description

Tried to use wanb in pytest here in this PR 
https://github.com/PyTorchLightning/pytorch-lightning/pull/2502
The error occurs locally and in the CI on Linux.
On Mac, the CI is simply timing out.

### What I Did

```
py.test -v pytorch_lightning/tests/loggers/test_wandb.py


_______________ ERROR at setup of test_auroc[pred1-target1-0.0] ________________

self = <contextlib._GeneratorContextManager object at 0x7fe46c19d190>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 29] Illegal seek

/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/contextlib.py:119: OSError
```

**Comment by vanpelt** [comment]
This looks like an error with the generator that's being passed into your trainer.  Is there anything special about the data loader you're using?

**Comment by awaelchli** [comment]
I don't think so, it should be a regular torch DataLoader. Does wandb inspect the dataloaders? How would it find them? The only thing I can think of is that we use a profiler iterable that wraps the dataloader iterable when looping over it. 
https://github.com/PyTorchLightning/pytorch-lightning/blob/9924c76faa7789294811a27c392ba6b33e07f3f1/pytorch_lightning/trainer/training_loop.py#L439

**Comment by vanpelt** [comment]
If you run your code without the wandb logger do you get any errors?  This specific piece of code in the stack trace doesn't seem directly related to any code I'm aware of wandb hooking into.

**Comment by awaelchli** [comment]
it only happens in pytest when we involve wandb. 
if we skip the tests that involve wandb, everything works.
outside of pytest, wandb works very well with pytorch lightning.

so it is really just pytest. I already looked through your pytests here in this repo but could not find any special setting that needs to be triggered. maybe a special env var needs to be set?

**Comment by awaelchli** [comment]
@vanpelt 
I'm now able to provide a minimal example
```python
import wandb

def test_wandb_logger_dirs_creation():
    wandb.init(name='name', project='project')
```
running it with pytest test_wandb.py will throw the OSError

**Comment by vanpelt** [comment]
You can try setting `WANDB_DISABLED=true` to make calling `wandb.init` a noop, but future calls to `wandb.log` will likely fail.  I'll try to reproduce today and see if we can do anything else to make this work.

**Comment by awaelchli** [comment]
`WANDB_DISABLED=true` is not an option for us because we want to test that our wand-wrapper creates the correct file structure

**Comment by vanpelt** [comment]
Ok, for testing we can mock out our run object which should make the tests pass:

```
import wandb
from unittest.mock import MagicMock

def test_wandb_logger_dirs_creation():
    wandb.run = MagicMock()
    wandb.init(name='name', project='project')
```

**Comment by awaelchli** [comment]
Thanks @vanpelt, that works!

**Comment by avi-jit** [comment]
I'm sorry, is there a fix/workaround for this? @vanpelt 's unittest.mock didn't work for me :/

**Comment by vanpelt** [comment]
@avi-jit what error are you seeing when you attempt to use MagicMock?

**Comment by avi-jit** [comment]
The same: [Errno 29] Illegal seek

Here's the traceback:
```
======================================== test session starts ========================================
platform linux -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /nas/home/thawani/MCS/num2vec/pycharm, inifile: pytest.ini
collected 1 item                                                                                    

test_.py FE                                                                                   [100%]

============================================== ERRORS ===============================================
_______________________________ ERROR at teardown of test_proto_read ________________________________

self = <contextlib._GeneratorContextManager object at 0x7f01dfe885e0>, type = None, value = None
traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 29] Illegal seek

../../../anaconda3/envs/num_hf3/lib/python3.8/contextlib.py:120: OSError
============================================= FAILURES ==============================================
__________________________________________ test_proto_read __________________________________________

self = <contextlib._GeneratorContextManager object at 0x7f0254cd2ca0>, type = None, value = None
traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 29] Illegal seek

../../../anaconda3/envs/num_hf3/lib/python3.8/contextlib.py:120: OSError
====================================== short test summary info ======================================
FAILED test_.py::test_proto_read - OSError: [Errno 29] Illegal seek
ERROR test_.py::test_proto_read - OSError: [Errno 29] Illegal seek
==================================== 1 failed, 1 error in 58.94s ====================================

Traceback (most recent call last):
  File "/nas/home/thawani/anaconda3/envs/num_hf3/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/main.py", line 235, in wrap_session
    config._ensure_unconfigure()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 829, in _ensure_unconfigure
    fin()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/capture.py", line 129, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/capture.py", line 474, in pop_outerr_to_orig
    out, err = self.readouterr()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/capture.py", line 515, in readouterr
    out = self.out.snap()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/capture.py", line 626, in snap
    res = super().snap()
  File "/nas/home/thawani/anaconda3/envs/num_hf3/lib/python3.8/site-packages/_pytest/capture.py", line 585, in snap
    self.tmpfile.seek(0)
OSError: [Errno 29] Illegal seek

wandb: Waiting for W&B process to finish, PID 140579

```

Note that this fails when I call trainer.fit() but doesn't fail if I merely instantiate a wandb_logger, or even a Trainer with the wandb_logger.

**Comment by vanpelt** [comment]
Can you share where / how you're setting `wandb.run` to MagicMock and what version of wandb you're using?

**Comment by avi-jit** [comment]
> Can you share where / how you're setting `wandb.run` to MagicMock and what version of wandb you're using?

Wandb version is 0.9.4. Here's the minimal code to get the error:
```
from unittest.mock import MagicMock
import wandb
def test_minimal():
    wandb.run = MagicMock()
    wandb_logger = pl.loggers.WandbLogger(project='num2vec')
    trainer = pl.Trainer(max_epochs=1, gpus=[1], logger=wandb_logger)
    dataset = preprocess.WikiNumDataset(task='read', sample=100, multi=False, max_len=30, num_tok='binning')
    net = read.Reader(transformers.BertModel.from_pretrained('bert-base-uncased'), enc='value', units=dataset.units,
                      num_vocab_size=dataset.num_bins)
    train_loader = torch.utils.data.DataLoader(dataset, batch_size=4)
    trainer.fit(net, train_loader, val_dataloaders=[train_loader])
```
The same works when I do this outside of pytest.

**Comment by vanpelt** [comment]
It's so odd this isn't working.  One thing to try would be to set `wandb_logger._experiment = MagicMock()` in your test_minimal.  The other option is to install our next generation client with `pip install wandb -U --pre` and set `os.environ["WANDB_MODE"] = "noop"` in your test.

**Comment by avi-jit** [comment]
> set `wandb_logger._experiment = MagicMock()` in your test_minimal

This worked, thanks!
