### ISSUE TITLE
sweep+pytorch lightning hangs

### ISSUE THREAD

**Issue by erap129** [wandb/client#1139]
`wandb --version 0.9.2 python --version 3.8`

* Weights and Biases version: 0.9.2
* Python version: 3.8
* Operating System: Windows

### Description

Hello, when I try to run a sweep with a model built with Pytorch lightning it always hangs. It never runs even the first configuration.  

### What I Did

a minimal working example is in this notebook: [https://github.com/AyushExel/COVID19WB/blob/master/main.ipynb](https://github.com/AyushExel/COVID19WB/blob/master/main.ipynb
)  
For the author it seems to work but I log on with my wandb account it just hangs:  
![image](https://user-images.githubusercontent.com/30405025/86604639-5042ef00-bfae-11ea-93f0-eb5340f8f270.png)  
Any help would be appreciated.  
Thanks

**Comment by vanpelt** [comment]
Hey @erap129 using sweeps with jupyter notebooks can interact poorly with CUDA / accessing the GPU and hang if any previous code in the notebook attempts to connect to the GPU before calling wandb.agent: https://docs.wandb.com/sweeps/python-api#wandb-agent

We're working on improvements for the case and expect to have a version that addresses this issue by the end of the month.  Until then you can have the agent run a python script and call it from your notebook with `!wandb agent` or ensure no cells connect to the GPU until the agent is called by placing logic in functions that the agent function calls.

**Comment by MohsenSharifi1991** [comment]
I have a similar issue with wandb and sweep. I even tried to run this code my https://github.com/AyushExel/COVID19WB/blob/master/main.ipynb on my windows CPU. Keep getting below error. Appreciate it if you can give feedback on how to resolve this issue.

2020-07-06 14:48:06,322 - wandb.wandb_agent - ERROR - Exception while processing command: {'args': {'learning_rate': {'value': 0.1}, 'model': {'value': 'VGG16'}, 'optimizer': {'value': 'sgd'}}, 'program': '', 'run_id': 'c2qet22d', 'run_storage_id': 'UnVuOnYxOmMycWV0MjJkOnVuY2F0ZWdvcml6ZWQ6bW9oc2Vuc2g5MQ==', 'type': 'run'}
Traceback (most recent call last):
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\site-packages\wandb\wandb_agent.py", line 265, in _process_command
    result = self._command_run(command)
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\site-packages\wandb\wandb_agent.py", line 311, in _command_run
    run_id=command.get('run_id'), in_jupyter=self._in_jupyter)
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\site-packages\wandb\wandb_agent.py", line 52, in __init__
    self._proc.start()
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Mohsen\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Process finished with exit code -1

**Comment by cvphelps** [comment]
@borisdayma could you take a look

**Comment by kevinkwshin** [comment]
Any progress here? I have the same problem with erap129.

**Comment by borisdayma** [comment]
Hi,

Here are some examples for running sweeps:
- with a script: [lightning-kitti](https://github.com/borisdayma/lightning-kitti)
- with a colab or jupyter notebook: see at the end of [this colab](https://colab.research.google.com/drive/16d1uctGaw2y9KhGBlINNTsWpmlXdJwRW?usp=sharing)

**Comment by ariG23498** [comment]
Hey @kevinkwshin 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:

**Comment by serg06** [comment]
I use regular Pytorch + wandb (not Lightning), but I was able to fix this issue recently in my code, so I'll post the solution here: I just encapsulated all the top-level stuff (besides imports, functions, and class definitions) in `if __name__ == '__main__':`. I even had to stick the `wandb.init` and `wandb.config` stuff under there.
