### ISSUE TITLE
artifact.download() creates directory with invalid name for Windows [NotADirectoryError]

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1143]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.2
* Python version: 3.6.10
* Operating System: Win 10

### Description

The default directory name for downloading an artifact contains colon (e.g. '.\\artifacts\\PointNetpp-on-sampled_1hp1mlx9_checkpoint:v1'), and thus cannot be created on Win, see [Win Naming Conventions](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) for a reference.

This issue has an easy **workaround**. It's enough to just supply custom root dir to download artifact:
`artifact.download('./wandb/last_checkpoint/')`
But it would still be nice to have artifact download working with the default parameters

### What I Did
Code snippet: 
```
artifact = run.use_artifact('PointNetpp-on-sampled_1hp1mlx9_checkpoint:latest', type='checkpoint')
artifact.download()   # creates directory with ":"
```
Fail: 
```
Traceback (most recent call last):
  File "d:\MyProject\nn\train.py", line 36, in <module>
    trainer.fit(model)
  File "d:\MyProject\nn\trainer.py", line 75, in fit
    start_epoch = self._start_experiment(model)
  File "d:\MyProject\nn\trainer.py", line 94, in _start_experiment
    start_epoch = self._restore_run(model)
  File "d:\MyProject\nn\trainer.py", line 199, in _restore_run
    checkpoint = self.experiment.load_checkpoint_file(last_epoch)
  File "d:\MyProject\nn\experiment.py", line 145, in load_checkpoint_file
    artifact.download()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\apis\public.py", line 2085, in download
    pool.map(download_file, manifest.entries)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\apis\public.py", line 2081, in download_file
    util.mkdir_exists_ok(os.path.dirname(target_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\util.py", line 517, in mkdir_exists_ok
    os.makedirs(path)
  File "C:\ProgramData\Anaconda3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: '.\\artifacts\\PointNetpp-on-sampled_1hp1mlx9_checkpoint:v1'
```

**Comment by tyomhak** [comment]
Hey Maria, thank you very much for reporting. Filing an internal ticket for this.

**Comment by vanpelt** [comment]
This was fixed in version 0.9.3, let us know if you still see this.

**Comment by MarioProjects** [comment]
It is happening to me at Ubuntu. Info:

Python 3.8.13 & 3.9.15
wandb, version 0.13.9
Ubuntu 20 LTS

If I try to create a folder with colon `:` it prompts an error.

**Comment by MarioProjects** [comment]
Okay so, tested it on an NTFS disk instead of ext4, and works! Maybe is not the best solution to use colons in the naming :)

**Comment by Woodyet** [comment]
It's not a choice W&B does this automatically to indicate versioning eg.

Dataset_name:v1

You can pick dataset name... :v1 is auto appened
