### ISSUE TITLE
Failed to query for notebook name

### ISSUE THREAD

**Issue by tshmak** [wandb/client#1153]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.2
* Python version: 3.6.10 :: Anaconda, Inc.
* Operating System: Linux

### Description
According to https://docs.wandb.com/library/integrations/jupyter#notebook-name, you can get rid of the error message 

> Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable

by setting 
```
os.environ['WANDB_NOTEBOOK_NAME'] = 'some text here'
```
However, this did not work when I ran `wandb.init()` after `import torch`. 

### What I Did

```
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import wandb

In [2]: import os

In [3]: os.environ['WANDB_NOTEBOOK_NAME'] = 'some text here'

In [4]: wandb.init()
<IPython.core.display.HTML object>
Out[4]: W&B Run: https://app.wandb.ai/tshmak/uncategorized/runs/1s4m5go1

In [5]: import torch

In [6]: wandb.init()
<IPython.core.display.HTML object>
Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable
SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
Out[6]: W&B Run: https://app.wandb.ai/tshmak/uncategorized/runs/2dsu7jlm
```

**Comment by vanpelt** [comment]
Hey @tshmak if you set WANDB_NOTEBOOK_NAME you should set it to the same as your jupyter notebook.  Since you're not running in a jupyter notebook context and instead directly in ipython you'll always receive the error.  We should be able to detect this case and not dump logs to your console so we'll keep this open.  You can safely ignore the error, everything should *just work without it.  We do this to try to capture the raw source code used to run a jupyter session.

**Comment by wiseyoungbuck** [comment]
I also still have this issue using JupyterLab. Seeting the OS environment variable does not fix it either.

**Comment by tcapelle** [comment]
Me 2

**Comment by omerferhatt** [comment]
Bug still exists. It gives warning message in python console.

**Comment by ariG23498** [comment]
Hey @omerferhatt 
The feature of `os.environ['WANDB_NOTEBOOK_NAME'] = 'name_of_the_notebook'` only exists for jupyter notebooks for the time being.
One should not find a problem with the `python console` too. With the `ipython console` setting the environment variable is not possible because we do not have a name for the interactive-python shell.
@wiseyoungbuck I did not find any problem with jupytelab too after I set the environment variable. Would you want to elaborate on the issue that you see?

**Comment by Skerre** [comment]
I once tried to run wandb in my jupyter notebook file and since then this error pops up in every other context. Inside of spyder, it will give me the same error, somehow assuming that wandb is connected with jupyter notebook, but it isnt. 
I deleted wandb multiple times, i tried to find and delete every logfile there is, every folder I could see. I also reinstalled urllib3 and requests multiple times, restarted the computer. 

Wandb works perfectly fine on my other machine and also did on the current one before I did this horrible mistake to run it in jupyter notebook...

I also restarted the machine many times. Any ideas ? 

ERROR:wandb.jupyter:Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.

HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')))

DEBUG:wandb.sdk.lib.git:git repository is invalid
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.wandb.ai:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.wandb.ai:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.wandb.ai:443
ERROR:wandb.sdk.lib.retry:Retry attempt failed:
Traceback (most recent call last):
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/lab1/anaconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/lab1/anaconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/lab1/anaconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/lab1/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')))

**Comment by vanpelt** [comment]
@Skerre this error is actually not related to querying for the notebook name.  Python is unable to verify the security of the connection to api.wandb.ai.  This usually indicates you're running behind a proxy that is intercepting the traffic and invalidating the SSL certificate.  Do you know if there is a proxy running in your environment?

**Comment by Skerre** [comment]
@vanpelt I don't know of any proxies, the machine is currently not located within my reach but what confused me was the fact that it worked 3 days ago, the first time I tried, but the day after not anymore.

**Comment by Skerre** [comment]
Works. Thanks

**Comment by fredguth** [comment]
Is this printed as a warning?  I use `warnings.filterwarnings('ignore')` and still get the warning.

**Comment by DbCrWk** [comment]
I'm writing Jupyter notebooks in VS Code and I get this error when running wandb.
