### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by drozzy** [wandb/client#1161]
`wandb, version 0.9.2
Python 3.7.6
Linux`

### Description
Running my usual taining now produces a Connection reset by peer` error. Started happening a week ago or so. I tried version wanbd `0.9.3` and still the same error.

```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
wandb: Network error (ConnectionError), entering retry loop. See /..../wandb/debug.log for full traceback.
wandb: Tracking run with wandb version 0.9.2
```

looking into debug.log I get more stack trace:
```
Traceback (most recent call last):
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/home/drozzy/.conda/envs/myproject/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
                                                                                      
```

This happens when I run my script from a slurm machine, however, it seems to work on my home machine.
What could be the cause? Any tips welcome - as I'm really puzzled.

**Comment by vanpelt** [comment]
This is either a network or SSL issue on the slurm machine.  Can you try running `curl -v https://api.wandb.ai/healthz` you should see something like:

```
*   Trying 35.186.228.49...
* TCP_NODELAY set
* Connected to api.wandb.ai (35.186.228.49) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api.wandb.ai
*  start date: Jul 14 21:31:28 2020 GMT
*  expire date: Oct 12 21:31:28 2020 GMT
*  subjectAltName: host "api.wandb.ai" matched cert's "api.wandb.ai"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa2cf80d600)
> GET /healthz HTTP/2
> Host: api.wandb.ai
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< vary: Origin
< date: Sun, 19 Jul 2020 17:40:02 GMT
< content-length: 0
< via: 1.1 google
< alt-svc: clear
< 
* Connection #0 to host api.wandb.ai left intact
* Closing connection 0
```

**Comment by drozzy** [comment]
```
* About to connect() to api.wandb.ai port 443 (#0)
*   Trying 35.186.228.49...
* Connected to api.wandb.ai (35.186.228.49) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer
```

**Comment by vanpelt** [comment]
This looks like an SSL error where the machine doesn't support TLSv1.2.  More information here: https://unix.stackexchange.com/questions/280548/curl-doesnt-connect-to-https-while-wget-does-nss-error-12286/310696#310696 You can likely fix with `apt-get install nss` or `yum update nss`
