### ISSUE TITLE
Network error (ReadTimeout), entering retry loop during sweep

### ISSUE THREAD

**Issue by FordUniver** [wandb/client#1185]
* Weights and Biases version: 0.9.1
* Python version: 3.7.7
* Operating System: MacOS X / Debian

### Description

I started a wandb sweep grid search and I am getting a lot of `Network error (ReadTimeout), entering retry loop.` from various kinds of machines within different kind of networks (i.e. this happens both at home on my laptop and on larger remote computers). Sometimes runs get through and sync but then at seemingly random times the network error shows up. Sometimes it resolves itself within a minute or two sometimes it just stays down for half an hour or longer. I've posted the log below.

### What I Did

```
2020-08-04 16:35:53,246 ERROR   MainThread:13897 [retry.py:__call__():108] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/wandb/apis/internal.py", line 108, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/forduniver/anaconda3/envs/test_repo/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10
```

**Comment by tyomhak** [comment]
Hi there, thanks for reporting! We're looking into this. In the meantime could  you please try updating to the latest wandb version, and checking if the issue persists?

**Comment by tyomhak** [comment]
Hey @FordUniver , are you still experiencing this issue?

**Comment by FordUniver** [comment]
@tyomhak Hey, yes I am still experiencing it even with the updated version of wandb. It is very unpredictable though though, so for some sweeps it occurs a lot and for others barely.

**Comment by cvphelps** [comment]
Hi @FordUniver, I'm taking a look at this issue. We just released a new client on Friday — 0.10.0, which should improve retry problems. Could you try it and see if it reduces the network error noise?

**Comment by ariG23498** [comment]
Hey @FordUniver 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:

**Comment by qshzh** [comment]
I encountered the same error on wandb 0.10.27 in different devices.

**Comment by XikunZhang** [comment]
I encountered the same error on wandb 0.10.28.

**Comment by raubitsj** [comment]
@XikunZhang , im sorry about the error you experienced today.
We had a database outage for ~40 minutes which is likely when you saw this error.

During this time, any sweeps that were running likely were reporting errors, but the sweep should continue to run and it would recover at the end of the outage.

Any actively running training jobs started by the sweep should continue running during the outage but they will be reporting messages about failures, but they will recover at the end of the outage.

When the backend is not responding, by default we do not let new training jobs start because we want to make sure the data is saved.  If you want to run offline and sync the data later, you can chose that with `wandb offline` or WANDB_MODE="offline", or wandb.init(mode="offline")

**Comment by XikunZhang** [comment]
@raubitsj Yeah it works again now. Thanks!

**Comment by TrinhDinhPhuc** [comment]
I faced this problem too. My model was trained 3 days ago

**Comment by vanpelt** [comment]
Thanks for reporting @TrinhDinhPhuc, do you still have access to the run directory or the log output for the run that failed?  It's all hands on deck here at W&B to further harden our retry logic to ensure we are always able to handle network faults or server issues.

**Comment by TrinhDinhPhuc** [comment]
Yes, I still have the run directory and events.out file inside it

**Comment by vanpelt** [comment]
Great, if you can send a tarball or zip of it to vanpelt@wandb.com that would be helpful.  We also just released wandb 0.10.29 which has much more robust retry logic.

**Comment by yllgl** [comment]
> Great, if you can send a tarball or zip of it to [vanpelt@wandb.com](mailto:vanpelt@wandb.com) that would be helpful. We also just released wandb 0.10.29 which has much more robust retry logic.


@vanpelt I encounter the same problem.
I just use wandb 0.10.33, and latest wandb/local. I use singularity to run wandb/local. I can visit wandb login page and everything seems ok. here is my running wandb/local.
```
INFO:    Converting SIF file to temporary sandbox...
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /THL5/software/singularity/3.7.3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in contain
er
WARNING: Skipping mount /THL5/software/singularity/3.7.3/var/singularity/mnt/session/etc/passwd [files]: /etc/passwd doesn't exist in container
WARNING: Skipping mount /THL5/software/singularity/3.7.3/var/singularity/mnt/session/etc/group [files]: /etc/group doesn't exist in container
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
chgrp: changing group of '/vol/env': Invalid argument
*** Loading settings...
2021/07/05 22:09:51 Created default user
2021/07/05 22:09:51 Generating new certificate and key for auth...
*** Booting runit daemon...
*** Runit started as PID 14879
*** Setting up mysql database...
*** Configuring minio...
*** Starting wandb servers...
Bucket created successfully `local/local-files`.
Successfully added arn:minio:sqs:wandb-local:_:redis
chgrp: changing group of '/THL5/home/hugpu1/.mc': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/session': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/share': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/share/downloads.json': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/share/uploads.json': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/config.json.old': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/config.json': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/certs': Invalid argument
chgrp: changing group of '/THL5/home/hugpu1/.mc/certs/CAs': Invalid argument
chgrp: changing group of '/vol/env/minio-config.json': Invalid argument
*** Migrating database...
Loading custom chart definitions...
*** All services started
*** Access W&B at http://localhost:8080
```

however, when I use wandblogger in pytorch_lightning, there are some mistakes. My code is simple:
```python
import wandb
from pytorch_lightning.loggers import WandbLogger

# Pytorch modules
import torch
from torch.nn import functional as F
from torch import nn
from torch.optim import Adam
from torch.utils.data import DataLoader, random_split

# Pytorch-Lightning
from pytorch_lightning import LightningDataModule, LightningModule, Trainer
import pytorch_lightning as pl

# Dataset
from torchvision.datasets import MNIST
from torchvision import transforms

class LitMNIST(LightningModule):

    def __init__(self, n_classes=10, n_layer_1=128, n_layer_2=256, lr=1e-3):
        '''method used to define our model parameters'''
        super().__init__()
        self.layer_1 = torch.nn.Linear(28 * 28, n_layer_1)
        self.layer_2 = torch.nn.Linear(n_layer_1, n_layer_2)
        self.layer_3 = torch.nn.Linear(n_layer_2, n_classes)
        self.lr = lr
        self.accuracy = pl.metrics.Accuracy()
        self.save_hyperparameters()
    def forward(self, x):
        '''method used for inference input -> output'''
        batch_size, channels, width, height = x.size()
        # (b, 1, 28, 28) -> (b, 1*28*28)
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = F.relu(x)
        x = self.layer_2(x)
        x = F.relu(x)
        x = self.layer_3(x)
        x = F.log_softmax(x, dim=1)
        return x
    def training_step(self, batch, batch_idx):
        '''needs to return a loss from a single batch'''
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        '''used for logging metrics'''
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        self.log('valid_loss', loss)
    def test_step(self, batch, batch_idx):
        '''used for logging metrics'''
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        self.log('test_loss', loss)
    def configure_optimizers(self):
        '''defines model optimizer'''
        return Adam(self.parameters(), lr=self.lr)
class MNISTDataModule(LightningDataModule):

    def __init__(self, data_dir='./', batch_size=256):
        super().__init__()
        self.data_dir = data_dir
        self.batch_size = batch_size
        self.transform = transforms.ToTensor()
    def prepare_data(self):
        '''called only once and on 1 GPU'''
        # download data
        MNIST(self.data_dir, train=True, download=True)
        MNIST(self.data_dir, train=False, download=True)
    def setup(self, stage=None):
        '''called on each GPU separately - stage defines if we are at fit or test step'''
        # we set up only relevant datasets when stage is specified (automatically set by Pytorch-Lightning)
        if stage == 'fit' or stage is None:
            mnist_train = MNIST(self.data_dir, train=True, transform=self.transform)
            self.mnist_train, self.mnist_val = random_split(mnist_train, [55000, 5000])
        if stage == 'test' or stage is None:
            self.mnist_test = MNIST(self.data_dir, train=False, transform=self.transform)
    def train_dataloader(self):
        '''returns training dataloader'''
        mnist_train = DataLoader(self.mnist_train, batch_size=self.batch_size)
        return mnist_train
    def val_dataloader(self):
        '''returns validation dataloader'''
        mnist_val = DataLoader(self.mnist_val, batch_size=self.batch_size)
        return mnist_val
    def test_dataloader(self):
        '''returns test dataloader'''
        mnist_test = DataLoader(self.mnist_test, batch_size=self.batch_size)
        return mnist_test
if __name__ =='__main__':
    wandb.login(host='http://121.16.25.13:8080')
    wandb_logger = WandbLogger()
    mnist = MNISTDataModule()
    model = LitMNIST(n_layer_1=128, n_layer_2=256, lr=1e-3)
    trainer = Trainer(
        logger=wandb_logger,    # W&B integration
        gpus=1,                # use all GPU's
        max_epochs=3,
        accelerator='ddp',            # number of epochs
        )
    trainer.fit(model, mnist)
    trainer.test(model, datamodule=mnist)
    wandb.finish()
```
And error is like this:
```python
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
Thread SenderThread:
Traceback (most recent call last):
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/THL5/software/python/3.8_anaconda_2020.07/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/THL5/software/python/3.8_anaconda_2020.07/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://121.16.25.13:8080/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 685, in run_resume_status
    response = self.gql(
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/util.py", line 727, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 55, in run
    self._run()
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 105, in _run
    self._process(record)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 292, in _process
    self._sm.send(record)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 181, in send
    send_handler(record)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 574, in send_run
    error = self._maybe_setup_resume(run)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 416, in _maybe_setup_resume
    resume_status = self._api.run_resume_status(
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/THL5/software/python/3.8_anaconda_2020.07/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 685, in run_resume_status
    response = self.gql(
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/util.py", line 727, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
wandb: ERROR Internal wandb error: file data was not synced
Problem at: /THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py 155 experiment
Traceback (most recent call last):
  File "untitled.py", line 108, in <module>
    trainer.fit(model, mnist)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 496, in fit
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))': /api/5288891/store/
    self.pre_dispatch()
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 530, in pre_dispatch
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))': /api/5288891/store/
    self.logger.log_hyperparams(self.lightning_module.hparams_initial)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 48, in wrapped_fn
    return fn(*args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 184, in log_hyperparams
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))': /api/5288891/store/
    self.experiment.config.update(params, allow_val_change=True)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 41, in experiment
    return get_experiment() or DummyExperiment()
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 48, in wrapped_fn
    return fn(*args, **kwargs)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 39, in get_experiment
    return fn(self)
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 155, in experiment
    self._experiment = wandb.init(
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 761, in init
    run = wi.init()
  File "/THL5/home/hugpu1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 522, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
```
Could anybody help me?

**Comment by vanpelt** [comment]
The `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://121.16.25.13:8080/graphql` indicates either the api key / user you're logged in as doesn't have access to this project or you have a proxy infront of the wandb server that is requiring additional authentication.  When you access the website via a browser are you prompted to login with your own authentication system?

**Comment by Bing1002** [comment]
I am experiencing this issue again. Any idea of the reason or potential bug?

**Comment by jstmn** [comment]
I'm also getting this issue. I'm using wandb `0.13.7` on linux

**Comment by Nicolas1203** [comment]
I also have this issue on wandb `0.15.0`, python 3.8 with similarly weird behavior. Namely, it occurs only when I set the env variable `CUDA_VISIBLE_DEVICES=1` on my machine with two GPUs. It worked just fine the update.

**Comment by Kojuru** [comment]
I just found out that you can also get this error if the number of sweeps is too high. I accidentally defined 3^11 sweeps in my config and my job did not run at all. I just got this network error message.
