### ISSUE TITLE
Segmentation Fault with the newest opencv-python (4.4.0.42)

### ISSUE THREAD

**Issue by jd730** [wandb/client#1210]
`wandb --version && python --version && uname`

* wandb, version 0.9.5
* Python 3.7.0
* Linux

### Description

Segmentation Fault with the newest opencv-python (4.4.0.42)

### What I Did

![image](https://user-images.githubusercontent.com/9247850/90733379-6bbc4c00-e307-11ea-82d4-dc414949d2bb.png)

When I downgrade `opencv-python` to `4.3.0.36`, it worked well.

**Comment by tyomhak** [comment]
Hey @jd730 , I can't reproduce this. Can you please share a simple script to reproduce this error?

**Comment by jd730** [comment]
Hi @tyomhak, I even got an error from just below command.
```
import cv2
import wandb
wandb.init()
```

**Comment by tyomhak** [comment]
I tested this code in Ubuntu, Mac Catalina and Win10, and it worked everywhere. Can you please try reinstalling both opencv and wandb, and see if that fixes the issue?

**Comment by tyomhak** [comment]
@vanpelt do you know what could have caused this error?

**Comment by jd730** [comment]
I tested on my mac with new conda env and it worked but when I tested on my Linux server (AWS) with a new conda env, the error still occurred.
 
Specifically, there are below package is installed a new env on Linux

```
Package         Version
--------------- -------------------
blessings       1.7
certifi         2020.6.20
chardet         3.0.4
click           7.1.2
configparser    5.0.0
docker-pycreds  0.4.0
gitdb           4.0.5
GitPython       3.1.7
gpustat         0.6.0
gql             0.2.0
graphql-core    1.1
idna            2.10
numpy           1.19.1
nvidia-ml-py3   7.352.0
opencv-python   4.4.0.42
pathtools       0.1.2
pip             20.2.2
promise         2.3
psutil          5.7.2
python-dateutil 2.8.1
PyYAML          5.3.1
requests        2.24.0
sentry-sdk      0.16.5
setuptools      49.6.0.post20200814
shortuuid       1.0.1
six             1.15.0
smmap           3.0.4
subprocess32    3.5.4
urllib3         1.25.10
wandb           0.9.5
watchdog        0.10.3
wheel           0.34.2
```
and the `opencv_python` is from `opencv_python-4.4.0.42-cp37-cp37m-manylinux2014_x86_64.whl`

The environment install is used by below script:

```
conda create -n wandb python=3.7
pip install wandb==0.9.5 opencv_python==4.4.0.42
```

**Comment by alessandroscoppio** [comment]
I am also getting a segmentation fault error, but without openCV. I am using many different libraries for my project and I can't really figure out which one is in conflict, I just realized that removing wandb related code (init, watch, save) solved the segmentation fault error and allows me to train again.

Interestingly, on a gcp compute instance with the same packages installed the error does not occur, similar to @jd730 situation.

**Comment by vanpelt** [comment]
@alessandroscoppio can you provide a stack trace of what you're seeing when it seg faults?  Can you also try our prerelease library by running `pip install -U -pre wandb`?

**Comment by alessandroscoppio** [comment]
The only output line is:
`[1]    11764 segmentation fault (core dumped)  python3 train.py configs/config.yaml
`
After installing prerelease library ( wandb-0.10.0rc6 ) I have the same trace, looks like what changes is just the PID.

`[1]    12236 segmentation fault (core dumped)  python3 train.py configs/config.yaml
`
The libraries used in my project are the ones you can expect from a Deep Learning project, torch, numpy, time, etc etc I did have openCV installed but not using it anymore I uninstalled it and nothing changed.

**Comment by jd730** [comment]
Hi @tyomhak,
I could gather the verbose log before `segmentation fault` when I run some jobs. 
Although I am already logged in, it printed login option and then killed itself.

It also resolved when I downgraded `opencv-python` version to `4.3.0.36`

```
etry attempt failed:
Traceback (most recent call last):
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/urllib3/response.py", line 399, in _decode
    data = self._decoder.decompress(data)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/urllib3/response.py", line 86, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -2 while decompressing data: inconsistent stream state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/urllib3/response.py", line 768, in read_chunked
    chunk, decode_content=decode_content, flush_decoder=False
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/urllib3/response.py", line 405, in _decode
    e,
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 115, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/jahwang/.conda/envs/detr/lib/python3.7/site-packages/requests/models.py", line 756, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state'))
wandb: Network error (ContentDecodingError), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: run.sh: line 7: 66911 Segmentation fault
```

**Comment by langan7** [comment]
I have the same problem. I downgraded OpenCV and I'm still getting segfault...

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by maximilianmordig** [comment]
Still appearing with the most recent wandb version `0.16.6`

**Comment by barzanisar** [comment]
I am also getting this error with opencv-python=4.10.0.84 and wandb=0.15.12
