### ISSUE TITLE
Viewing wandb offline

### ISSUE THREAD

**Issue by aclifton314** [wandb/client#1222]
## System Info
wandb: 0.9.6
python: 3.7.6
OS: Pop!_OS 20.04 LTS

## Question
I trained a model offline and set `WANDB_MODE="dryrun"`. Is it possible to view the results of what `wandb` records after training without needing an internet connection?

**Comment by vanpelt** [comment]
You can run a wandb server locally: https://docs.wandb.com/self-hosted/local  This would allow you to sync dryrun jobs to this local instance instead of over the internet.

**Comment by aclifton314** [comment]
@vanpelt I get the following error:
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?filters=%7B%22name%22%3A%7B%22wandb-local%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Traceback (most recent call last):
  File "/path/to/anaconda3/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/cli.py", line 156, in wrapper
    return func(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/cli.py", line 880, in local
    running = subprocess.check_output(["docker", "ps", "--filter", "name=wandb-local", "--format", "{{.ID}}"])
  File "/path/to/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/path/to/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'ps', '--filter', 'name=wandb-local', '--format', '{{.ID}}']' returned non-zero exit status 1.
```

**Comment by aclifton314** [comment]
I went to the wandb directory that was created when I trained the model and ran `wandb local`. Just to give some more context.

**Comment by vanpelt** [comment]
You need to either run this as root, or configure your machine to allow non-root users to launch docker instances: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by aclifton314** [comment]
Looks like I'm getting weird docker proxy issues. I'll work on getting those sorted out and come back to this issue.

**Comment by aclifton314** [comment]
I think ultimately my issue is stemming from docker since `wandb local` gives: 
```
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/be/be1f454c9f7a96fcc4c249651a41611e842beea511391a085624a6084193e043/data?verify=1598924006-n2bzB0VtbK1TSNOxP%2BiKS%2FldfwI%3D: x509: certificate signed by unknown authority.
See 'docker run --help'.
```

but also ` docker run hello-world` gives:
```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pulling fs layer 
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/bf/bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b/data?verify=1598924111-2L9zhRm7FL6%2BUnoSmVyvNXnfoeM%3D: x509: certificate signed by unknown authority.
See 'docker run --help'.
```
I know this is more of a docker issue and not a wandb issue, but if anyone has any recommendations I could try I would appreciate it very much. Otherwise, I'll close out this issue while I resolve the docker errors.

**Comment by vanpelt** [comment]
Hey @aclifton314 this is the same error regarding the SSL verification through the proxy.  Can you share some more information about the proxy you're using?  We should be able to configure the system to have the proxies certificate in it's authentication chain.

**Comment by aclifton314** [comment]
@vanpelt I might be able to. It's the proxy that my company uses. I'm not sure what information I would be able to provide, but we can always try!

**Comment by vanpelt** [comment]
In that case, I would ask someone in your company about how to add the certificate being served from your proxy to your local certificate authority.

**Comment by aclifton314** [comment]
I got `wandb local` (and `docker run hello-world`) working through the company proxy. Thanks for walking me through that. In the directory that I ran my training there is a `wandb` directory. I ran `wandb local` and signed in successfully, but the metrics aren't showing up. I get taken to a page to get started with Weights and Biases:
```
user@pop-os:~$ cd project/dir/
user@pop-os:~/project/dir/$ ls
run_training.py       wandb
user@pop-os:~/project/dir/$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
```
I then went into the `~/project/dir/wandb` directory and repeated the same thing:
```
user@pop-os:~$ cd project/dir/wandb
user@pop-os:~/project/dir/wandb$ ls
debug.log  dryrun-20200828_220136-10kab6tp  settings
user@pop-os:~/project/dir/wandb$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
```
and get sent to the same page. Finally, I did:
```
user@pop-os:~$ cd project/dir/wandb/dryrun-20200828_220136-10kab6tp
user@pop-os:~/project/dir/wandb/dryrun-20200828_220136-10kab6tp$ ls
config.yaml  output.log  wandb-events.jsonl  wandb-history.jsonl  wandb-metadata.json  wandb-summary.json
user@pop-os:~/project/dir/wandb/dryrun-20200828_220136-10kab6tp$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
```
and get sent to the same page. Am I messing something up here?

**Comment by vanpelt** [comment]
@aclifton314 by default our library will connect to our hosted service running at https://api.wandb.ai.  You can run your own server by running `wandb local`.  This server will only be accessible on the machine your running the container on at http://localhost:8080.  Once the server is running you can run jobs in "online" mode instead of the "dryrun", or "offline" mode that you are running with.  You can sync these run to a wandb server (either the one you're running locally, or our cloud service) by running `wandb sync wandb/dryrun-20200828_220136-10kab6tp`.  Does that make sense?

**Comment by aclifton314** [comment]
@vanpelt Yes it does make sense. However, I'm not sure what's going on now. I ran `wandb local` then:
```
wandb sync wandb/dryrun-20200828_220136-10kab6tp
Skipping directory: {} wandb/dryrun-20200828_220136-10kab6tp/
```
going to `http://localhost:8080` asks me to login. I login but the credentials aren't accepted. I clicked Reset Password but no email was sent.

**Comment by vanpelt** [comment]
@aclifton314 looks like you're trying to sync a directory that was logged with 0.9.X with version 0.10.0 of the library.  Try installing wandb with `pip install wandb==0.9.7` and running sync.

For the credentials, you can reset your password manually by running the following command:

`docker run -it wandb-local /usr/local/bin/local password YOUREMAIL@ADDRESS.COM`

**Comment by aclifton314** [comment]
@vanpelt roger that. I uninstalled `wandb` and ran `pip install wandb==0.9.7`. I ran the following and got an error:
```
user@ac-ubuntu-vm:~/wandb$ wandb sync dryrun-20200828_220136-10kab6tp/
wandb: Network error (ConnectionError), entering retry loop. See /path/to/wandb/wandb/debug.log for full traceback.
```

Here is the log:
```
020-09-14 18:09:05,026 DEBUG   MainThread:2799 [wandb_config.py:_load_defaults():150] wandb dir not provided, skipping defaults
2020-09-14 18:09:08,549 ERROR   Thread-1  :2799 [retry.py:__call__():108] Retry attempt failed:
Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f84e2736c90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e2736c90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/apis/internal.py", line 108, in execute
    return self.client.execute(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e2736c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2020-09-14 18:09:13,456 ERROR   MainThread:2799 [retry.py:__call__():108] Retry attempt failed:
Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/path/to/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f84e1e5f450>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/path/to/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e1e5f450>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/apis/internal.py", line 108, in execute
    return self.client.execute(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e1e5f450>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by vanpelt** [comment]
That means we can't connect to wandb/local.   Are you running `wandb sync` from the same machine as you're running wandb/local?  Can you access the wandb interface at http://localhost:8080?

**Comment by aclifton314** [comment]
@vanpelt, thanks for your patience while working through this.

Here are the commands that I am running:
```
user@ac-ubuntu-vm:~$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
user@ac-ubuntu-vm:~$ cd wandb/
user@ac-ubuntu-vm:~/wandb$ ls
dryrun-20200828_220136-10kab6tp  dryrun-20200831_101028-16spyjsr  settings
user@ac-ubuntu-vm:~/wandb$ wandb sync dryrun-20200828_220136-10kab6tp/
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
Error: Invalid or missing api_key.  Run wandb login
user@ac-ubuntu-vm:~/wandb$ wandb login
wandb: You can find your API key in your browser here: http://localhost:8080/authorize
wandb: Paste an API key from your profile and hit enter: MY_API_KEY
wandb: Appending key for localhost to your netrc file: /home/user/.netrc
Successfully logged in to Weights & Biases!
user@ac-ubuntu-vm:~/wandb$ wandb sync dryrun-20200828_220136-10kab6tp/
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
Error: Invalid or missing api_key.  Run wandb login
```

Going to `http://localhost:8080/` I am sent to a webpage that says "Developer tools for deep learning." I click the login button and enter my credentials. I am prompted that the credentials are incorrect. However, going to wwww.wandb.com and logging in with the same credentials works.

Is that the correct order of commands to run?

**Comment by vanpelt** [comment]
When you first started `wandb local` you should have been prompted to create an account inside on the instance.  If you can't login to http://localhost:8080, run the following to change your password manually:

`docker run -it wandb-local /usr/local/bin/local password YOUR_EMAIL@DOMAIN.com`

Then you can run wandb login with the api key shown at http://localhost:8080/authorize

**Comment by aclifton314** [comment]
Here is what I ran:
```
user@ac-ubuntu-vm:~/wandb$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
user@ac-ubuntu-vm:~/wandb$ docker run -it wandb-local /usr/local/bin/local password user314@email.com
Unable to find image 'wandb-local:latest' locally
docker: Error response from daemon: pull access denied for wandb-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

After running `wandb local` the only prompt I got was what is listed above.

**Comment by vanpelt** [comment]
Apologies, it's `docker exec` not `docker run`.

**Comment by aclifton314** [comment]
No worries. That seemed to change the password but I'm still getting an "incorrect credentials" error when I try to `wandb login`.
```
user@ac-ubuntu-vm:~/wandb$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
user@ac-ubuntu-vm:~/wandb$ docker exec -it wandb-local /usr/local/bin/local password user314@email.com
Enter password for user314@email.com: MY_PASSWORD
User updated
user@ac-ubuntu-vm:~/wandb$ ls
dryrun-20200828_220136-10kab6tp  dryrun-20200831_101028-16spyjsr  settings  wandb
user@ac-ubuntu-vm:~/wandb$ wandb sync dryrun-20200828_220136-10kab6tp/
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
Error: Invalid or missing api_key.  Run wandb login
user@ac-ubuntu-vm:~/wandb$ wandb login
wandb: You can find your API key in your browser here: http://localhost:8080/authorize
wandb: Paste an API key from your profile and hit enter: 
```
My browser gets launched after `wandb login` and takes me to a login page `http://localhost:8080/login`. That page does not approve my credentials. going to `http://localhost:8080/authorize` redirects me to `http://localhost:8080/login`.

**Comment by vanpelt** [comment]
You need to be able to login to `http://localhost:8080/login`.  Are you sure you're putting the same email / password as you're setting with the manual command?  Did you try clicking "Forgot password" to have the instance send you an email?  If none of these techniques work you can start with a fresh local installation and you'll be prompted to create a user on first boot.  NOTE: this will delete any data previously saved to this instance.

```
docker stop wandb-local
docker volume rm wandb
wandb local
```

**Comment by aclifton314** [comment]
@vanpelt that worked! I started with a fresh instance and was able to sync the dry runs. Thank you for all your help and patience!

**Comment by loctruong96** [comment]
I got this far and got the error 
wandb: ERROR Host must be a url in the form https://some.address.com, received localhost:8085
wandb: Network error (InvalidSchema), entering retry loop.
any ideas:
