### ISSUE TITLE
OSError: out of pty devices

### ISSUE THREAD

**Issue by crystina-z** [wandb/client#1224]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.6
* Python version: Python 3.6.3 
* Operating System: Linux

### Description
A simple `wandb_init` call would yield the following error on slurm while it's fine locally
```
    run = wandb.init(
        project=project_name,
        name=run_name,
        group=group_name,
        config=config,
        sync_tensorboard=True,
        reinit=True,
  )
```
Traceback (most recent call last):
  File "etx/run.py", line 113, in <module>
    main()
  File "etx/run.py", line 94, in main
    wandb, run = init_wandb(args, fold_string, fold=fold)
  File "etx/run.py", line 47, in init_wandb
    reinit=True,
  File "/home/czhang/anaconda3/envs/new_cap/lib/python3.6/site-packages/wandb/__init__.py", line 1280, in init
    _init_headless(run)
  File "/home/czhang/anaconda3/envs/new_cap/lib/python3.6/site-packages/wandb/__init__.py", line 279, in _init_headless
    stdout_master_fd, stdout_slave_fd = io_wrap.wandb_pty(resize=False)
  File "/home/czhang/anaconda3/envs/new_cap/lib/python3.6/site-packages/wandb/io_wrap.py", line 161, in wandb_pty
    master_fd, slave_fd = pty.openpty()
  File "/home/czhang/anaconda3/envs/new_cap/lib/python3.6/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/home/czhang/anaconda3/envs/new_cap/lib/python3.6/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
```

**Comment by vanpelt** [comment]
This should fixed in the new version of our library.  We're planning to officially release it at the end of this week.  You can try it now with `pip install wandb -U --pre`.  Let us know if you're still seeing this issue with this library.

**Comment by crystina-z** [comment]
yes i think this one works, thx!
