### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by Shubhamai** [wandb/client#1227]
* Weights and Biases version: 0.9.6
* Python version: Python 3.8.3
* Operating System: Windows 10

### Description

I am trying to run sweeps in `Tensorflow 2.3.0` and `Keras 2.4.0`, here  is my complete code 

# Code
```
from tensorflow import keras
import tensorflow as tf
from tensorflow.keras.mixed_precision import experimental as mixed_precision
import os
import datetime

import wandb
from wandb.keras import WandbCallback

# Configure the sweep – specify the parameters to search through, the search strategy, the optimization metric et all.
sweep_config = {
    'method': 'random', #grid, random
    'metric': {
      'name': 'accuracy',
      'goal': 'maximize'   
    },
    'parameters': {
       
        'dropout': {
            'values': [0.3, 0.4, 0.5]
        },
        'weight_decay': {
            'values': [0.0005, 0.005, 0.05]
        },
        'learning_rate': {
            'values': [1e-2, 1e-3, 1e-4, 3e-4, 3e-5, 1e-5]
        },
        'optimizer': {
            'values': ['adam', 'nadam', 'sgd', 'rmsprop']
        },
        'activation': {
            'values': ['relu', 'elu', 'selu', 'softmax']
        }
    }
}

sweep_id = wandb.sweep(sweep_config, project="snake-classification")

def train():
    config_defaults = {
        'weight_decay': 0.0005,
        'learning_rate': 1e-3,
        'activation': 'relu',
        'optimizer': 'nadam',
        'dropout': 0.5,
        'momentum': 0.9,
        'seed': 42
    }
    
    # Initialize a new wandb run
    wandb.init(project="snake-classification", 
               name="first-run", 
               notes="sweep first run", 
               sync_tensorboard=True,
               config=config_defaults)
    
    config = wandb.config
    
    efficientbetb7 = tf.keras.applications.EfficientNetB3( weights='imagenet',  input_shape=(256, 256, 3),include_top=False, classes=1)
    efficientbetb7.trainable = False


    efficientbetb7.summary()

    model_input = keras.Input(shape=(256, 256,3))
    x = efficientbetb7(model_input, training=False)
    x = keras.layers.GlobalAveragePooling2D()(x)
    dense1 = keras.layers.Dense(64, activation='relu')(x)
    dense2 = keras.layers.Dense(32, activation='relu')(dense1)
    dropout1 = keras.layers.Dropout(config.dropout)(dense2)
    outputs = keras.layers.Dense(1, activation=config.activation)(dropout1)


    model = keras.Model(model_input, outputs)


    log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1, update_freq='batch')


    if config.optimizer=='sgd':
      optimizer = keras.optimizers.SGD(lr=config.learning_rate, decay=1e-5, momentum=config.momentum, nesterov=True)
    elif config.optimizer=='rmsprop':
      optimizer = keras.optimizers.RMSprop(lr=config.learning_rate, decay=1e-5)
    elif config.optimizer=='adam':
      optimizer = keras.optimizers.Adam(lr=config.learning_rate, beta_1=0.9, beta_2=0.999, clipnorm=1.0)
    elif config.optimizer=='nadam':
      optimizer = keras.optimizers.Nadam(lr=config.learning_rate, beta_1=0.9, beta_2=0.999, clipnorm=1.0)


    model.compile(optimizer=optimizer,
                  loss=keras.losses.BinaryCrossentropy(),
                  metrics=["accuracy", keras.metrics.BinaryAccuracy()],
                  run_eagerly=True)
    
    model.fit(train, epochs=1, callbacks=[tensorboard_callback, WandbCallback(data_type="image", generator=train)])

datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    horizontal_flip=True,
    vertical_flip=True,
    rescale=1./255,
)

train = datagen.flow_from_directory(
    "train/content/data/train",
    color_mode="rgb",
    target_size=(256, 256), 
    class_mode='binary', 
    batch_size=8,
    shuffle=True,)

wandb.agent(sweep_id, train)
```

### What I Did

But when running `wandb.agent(sweep_id, train)` i am getting this error 

```
wandb: Agent Starting Run: sfmuooiu with config:
	activation: selu
	dropout: 0.3
	learning_rate: 0.0003
	optimizer: rmsprop
	weight_decay: 0.005
2020-09-03 10:54:21,112 - wandb.wandb_agent - ERROR - Exception while processing command: {'args': {'activation': {'value': 'selu'}, 'dropout': {'value': 0.3}, 'learning_rate': {'value': 0.0003}, 'optimizer': {'value': 'rmsprop'}, 'weight_decay': {'value': 0.005}}, 'program': '', 'run_id': 'sfmuooiu', 'run_storage_id': 'UnVuOnYxOnNmbXVvb2l1OnNuYWtlLWNsYXNzaWZpY2F0aW9uOnNodWJoYW1haQ==', 'type': 'run'}
Traceback (most recent call last):
  File "C:\Users\Saurabh\anaconda3\lib\site-packages\wandb\wandb_agent.py", line 265, in _process_command
    result = self._command_run(command)
  File "C:\Users\Saurabh\anaconda3\lib\site-packages\wandb\wandb_agent.py", line 310, in _command_run
    proc = AgentProcess(function=self._function, env=env,
  File "C:\Users\Saurabh\anaconda3\lib\site-packages\wandb\wandb_agent.py", line 52, in __init__
    self._proc.start()
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by cvphelps** [comment]
Hi there, thanks for reporting this sweeps issue. Could you please try this same thing with our new version of the client library by installing:
```pip install wandb --upgrade --pre```

**Comment by Shubhamai** [comment]
Hi @cvphelps , thanks for reply 🙂. Just tried that, now my wandb version is showing `0.10.0rc5` but i still got the same error

**Comment by Shubhamai** [comment]
Also @cvphelps , that i was running the whole code in a local jupyter notebook, and in the terminal, i got this error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Saurabh\anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by ryanstout** [comment]
I'm still seeing this issue, has this been fixed? Thanks!

**Comment by vanpelt** [comment]
@ryanstout can you share the stack trace that you're seeing and the version of wandb you're using?

**Comment by vib2810wiai** [comment]
Getting a similar issue with using joblib with wandb. The code works fine if used without wandb init and logging

With backend 'multiprocessing'
```
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Number of Training Batches: 6, Number of Examples: 168
Number of Validation Batches: 1, Number of Examples: 9
Training from Epoch 1 to 250
Epoch 1/250
----------
Traceback (most recent call last):
  File "deep_ensembles.py", line 151, in <module>
    model = model_pipeline(config)
  File "deep_ensembles.py", line 148, in model_pipeline
    trainer.train_model_par(model_ensemble, image_datasets, train_loader_dict, criterion, optimizer_list, config, args)
  File "/home/eshwar/face_anthro/ensembles/utils/train_model.py", line 291, in train_model_par
    values=Parallel(n_jobs=M, backend='multiprocessing', verbose=0)\
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/pool.py", line 156, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
AttributeError: Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module.<locals>.<lambda>'

wandb: Waiting for W&B process to finish, PID 3277
wandb: Program failed with code 1. 
wandb: Find user logs for this run at: /home/eshwar/face_anthro/ensembles/wandb/offline-run-20210630_070416-27v5uqi1/logs/debug.log
wandb: Find internal logs for this run at: /home/eshwar/face_anthro/ensembles/wandb/offline-run-20210630_070416-27v5uqi1/logs/debug-internal.log
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/eshwar/face_anthro/ensembles/wandb/offline-run-20210630_070416-27v5uqi1
```
With backend 'loky'
```
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Number of Training Batches: 6, Number of Examples: 168
Number of Validation Batches: 1, Number of Examples: 9
Training from Epoch 1 to 250
Epoch 1/250
----------
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/externals/loky/backend/queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'weakref' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "deep_ensembles.py", line 151, in <module>
    model = model_pipeline(config)
  File "deep_ensembles.py", line 148, in model_pipeline
    trainer.train_model_par(model_ensemble, image_datasets, train_loader_dict, criterion, optimizer_list, config, args)
  File "/home/eshwar/face_anthro/ensembles/utils/train_model.py", line 291, in train_model_par
    values=Parallel(n_jobs=M, backend='loky', verbose=0)\
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/eshwar/anaconda3/envs/dl/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.

wandb: Waiting for W&B process to finish, PID 3442
wandb: Program failed with code 1. 
wandb: Find user logs for this run at: /home/eshwar/face_anthro/ensembles/wandb/offline-run-20210630_071142-9e9aumse/logs/debug.log
wandb: Find internal logs for this run at: /home/eshwar/face_anthro/ensembles/wandb/offline-run-20210630_071142-9e9aumse/logs/debug-internal.log
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/eshwar/face_anthro/ensembles/wandb/offline-run-20210630_071142-9e9aumse
```

**Comment by antoine-lebaud** [comment]
Hi,
I am having the same issue, any workaround?
@vib2810wiai how did change the backend type?
thx
