### ISSUE TITLE
ERROR: Abnormal program exit

### ISSUE THREAD

**Issue by JunhaoWang** [wandb/client#1236]
`wandb --0.10.0 && python --3.6.12`

* Weights and Biases version: 0.10.0
* Python version: 3.6
* Operating System: Linux Ubuntu 18.06

### Description

Cannot run wandb.init()

### What I Did

```
(kg) junhao@compute006:~$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init()
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 2
wandb: You chose 'Use an existing W&B account'
wandb: You can find your API key in your browser here: https://app.wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:
wandb: Appending key for api.wandb.ai to your netrc file: /home/junhao/.netrc
Problem at: <stdin> 1 <module>
Traceback (most recent call last):
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 479, in init
    run = wi.init()
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 358, in init
    _backend=backend, _disable_warning=True, _settings=self.settings
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 95, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/interface/interface.py", line 438, in communicate_login
    "Couldn't communicate with backend after %s seconds" % timeout
wandb.errors.error.Error: Couldn't communicate with backend after 5 seconds
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 479, in init
    run = wi.init()
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 358, in init
    _backend=backend, _disable_warning=True, _settings=self.settings
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 95, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/interface/interface.py", line 438, in communicate_login
    "Couldn't communicate with backend after %s seconds" % timeout
wandb.errors.error.Error: Couldn't communicate with backend after 5 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/junhao/anaconda3/envs/kg/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 513, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
>>> B

```

**Comment by vanpelt** [comment]
There should be an `internal-debug.log` in your wandb directory.  Can you share that with us?

**Comment by hossein20s** [comment]
I have the same issue. Tried the tutorial example with 2 separate accounts and got the same problem
`(ml) developer@db97178ac511:/opt/host/tutorial$ python tutorial.py
2020-09-15 14:53:05.491180: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
wandb: Currently logged in as: hosseinakhlaghpour (use `wandb login --relogin` to force relogin)
Problem at: tutorial.py 21 <module>
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 479, in init
    run = wi.init()
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 357, in init
    wandb_login._login(
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 95, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/interface/interface.py", line 437, in communicate_login
    raise wandb.Error(
wandb.errors.error.Error: Couldn't communicate with backend after 5 seconds
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 479, in init
    run = wi.init()
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 357, in init
    wandb_login._login(
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 95, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/interface/interface.py", line 437, in communicate_login
    raise wandb.Error(
wandb.errors.error.Error: Couldn't communicate with backend after 5 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tutorial.py", line 21, in <module>
    wandb.init(
  File "/home/developer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 513, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/ml/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/envs/ml/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/conda/envs/ml/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
`

**Comment by cpoptic** [comment]
+ 1 Same here

> wandb.errors.error.Error: Couldn't communicate with backend after 5 seconds

Python 3.7.9
wandb 0.10.0
OS: Windows 10

Running wandb locally via `wandb local`
Can confirm the local server is running at `http://localhost:8080/home`

**Comment by michelkok** [comment]
To me downgrading wandb to 0.9.7 solved the problem. It seems to be a problem with the newest version only.

**Comment by mohamedr002** [comment]
> To me downgrading wandb to 0.9.7 mitigated the problem. It seems to be a problem with the newest version only.

This also worked for me. Thank you

**Comment by JayThibs** [comment]
I'm having this issue in Colab. I was able to pass the login with wandb.login(key=key) (otherwise Colab crashes), but wandb.init() gives me an error.

I'll be downgrading to 0.9.7 from 0.12.1.

**Comment by vanpelt** [comment]
@JayThibs we're looking into this.  I've noticed that if the authentication is invalid we'll crash.  Would you be able to share a colab with me that causes this issue for you?  My email is vanpelt@wandb.com

**Comment by JayThibs** [comment]
@vanpelt Ok, thanks for the response. Just saw this. Will email with a notebook soon.

**Comment by aced125** [comment]
Getting this issue now

**Comment by arman-sakif** [comment]
> I'm having this issue in Colab. I was able to pass the login with wandb.login(key=key) (otherwise Colab crashes), but wandb.init() gives me an error.
> 
> I'll be downgrading to 0.9.7 from 0.12.1.

how to downgrade?

**Comment by conceptofmind** [comment]
@vanpelt I am currently experiencing this issue now as well.

**Comment by jzenn** [comment]
Hey @michelkok, `wandb==0.9.7` seems like an old version to downgrade to; Do you have any experience with a somewhat newer version that might resolve the issue mentioned in this thread?

**Comment by phil-fradkin** [comment]
I'm getting a similar error with the following stack trace:

```
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 266, in _setup_manage$
    _use_grpc=use_grpc, settings=self._settings
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 112, in start
    self._launch_server()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 108, in _launch_s$rver
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 266, in _setup_manage$
    _use_grpc=use_grpc, settings=self._settings
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 112, in start
    self._launch_server()
  File "/h/phil/anaconda3/envs/rna_contrast/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 108, in _launch_s$
rver
    assert ports_found
AssertionError
```
with wandb v0.13.5

Any advice as to how to get around this? It seems to be failing sporadically as some jobs keep on running and others crash with this error periodically

**Comment by LucHayward** [comment]
I am still experiencing similar issues, see out put below.

```
Traceback (most recent call last):
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 112, in start
    self._launch_server()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 108, in _launch_server
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 112, in start
    self._launch_server()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 108, in _launch_server
    assert ports_found
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_masters.py", line 897, in <module>
    wandb.init(project="Masters", config=args, resume=False, group="final",
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1116, in init
    raise Exception("problem") from error_seen
Exception: problem
Traceback (most recent call last):
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/cli/cli.py", line 282, in service
    server.serve()
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/server.py", line 130, in serve
    self._inform_used_ports(grpc_port=grpc_port, sock_port=sock_port)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/server.py", line 65, in _inform_used_ports
    pf.write(self._port_fname)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/site-packages/wandb/sdk/service/port_file.py", line 25, in write
    f = tempfile.NamedTemporaryFile(prefix=bname, dir=dname, mode="w", delete=False)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/scratch/hywluc001/conda-envs/pointnet/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpsnxv_nef/port-18551.txtacbmdqof'
```

**Comment by vict0rsch** [comment]
Yep, definitely back. But it's happened to me for the first time ever today without any package up/down-grade.

```
Traceback (most recent call last):
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 111, in __init__
    self._service.start()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 119, in start
    self._launch_server()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 115, in _launch_server
    assert ports_found
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 192, in <module>
    runner.run()
  File "main.py", line 96, in run
    self.trainer: BaseTrainer = cls(**self.trainer_config)
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-1/ocpmodels/trainers/base_trainer.py", line 144, in __init__
    self.load()
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-1/ocpmodels/trainers/base_trainer.py", line 153, in load
    self.load_logger()
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-1/ocpmodels/trainers/base_trainer.py", line 184, in load_logger
    self.logger = registry.get_logger_class(logger_name)(self.config)
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-1/ocpmodels/common/logger.py", line 112, in __init__
    self.run = wandb.init(
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1115, in init
    raise Exception("problem") from error_seen
Exception: problem


Self-canceling SLURM job 2666801
slurmstepd: error: *** JOB 2666801 ON rtx7 CANCELLED AT 2023-01-10T20:43:59 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 2666801.0 ON rtx7 CANCELLED AT 2023-01-10T20:43:59 ***
Traceback (most recent call last):
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/cli/cli.py", line 282, in service
    server.serve()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/server.py", line 130, in serve
    self._inform_used_ports(grpc_port=grpc_port, sock_port=sock_port)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/server.py", line 65, in _inform_used_ports
    pf.write(self._port_fname)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/port_file.py", line 27, in write
    f = tempfile.NamedTemporaryFile(prefix=bname, dir=dname, mode="w", delete=False)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxm30s71a/port-6513.txtksswlbb9'
```

**Comment by MaugrimEP** [comment]
Same for me, I performed no changes on my env, and the script does not want to run anymore. Tried updating wandb without success.

**Comment by develop-productivity** [comment]
> I'm getting a similar error with the following stack trace:

hi. have you solved this problem, i meet seem problem with you today!

**Comment by Subash33** [comment]
I am having same issue sporadically. Any new updates on it?

**Comment by Anri-Lombard** [comment]
Just got this error as well after downgrading to avoid another error.
