### ISSUE TITLE
STDOUT/STDERR streams should be serialized before sending to the backend

### ISSUE THREAD

**Issue by adrianbg** [wandb/client#125]
Right now, STDOUT and STDERR have separate TextStreamPushers, which means the two streams can cause each other's data to be erased on the back end. This results in the following race condition which prevents stack traces from being logged (eg. when you press ctrl-c):

```/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python /Users/adrian/.pyenv/versions/wandb-3.6/bin/wandb run ./mnist-cnn.py

Using TensorFlow backend.
/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Train on 60000 samples, validate on 10000 samples
2018-02-13 17:35:54.799610: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Epoch 1/3
37152/60000 [=================>............] - ETA: 11s - loss: 0.4748 - acc: 0.8465
```

https://app.wandb.ai/adrianbg/garbage/runs/d8iycxh5

You can see that the run didn't actually finish, but there is no apparent error.

**Comment by adrianbg** [comment]
In this run, downloading `output.log` gives different different results than the terminal on the run page, and both of them look different than the local terminal output:

```(wandb-3.6) adrian@Adrians-MBP:~/src/wandb-examples/keras$ wandb run ./mnist-cnn.py
wandb: Syncing https://app.wandb.ai/adrianbg/garbage/runs/4pj90kcr
wandb: Run directory: wandb/run-20180214_194906-4pj90kcr

Using TensorFlow backend.
/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Train on 60000 samples, validate on 10000 samples
2018-02-14 11:49:16.104273: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
{'batch_size': 32, 'epochs': 3, 'steps': None, 'samples': 60000, 'verbose': 1, 'do_validation': True, 'metrics': ['loss', 'acc', 'val_loss', 'val_acc']}
Epoch 1/3
48544/60000 [=======================>......] - ETA: 4s - loss: 0.3329 - acc: 0.8962^Cwandb: Ctrl-c pressed; waiting for program to end.
Traceback (most recent call last):
  File "./mnist-cnn.py", line 54, in <module>
    TensorBoard(write_images=True, write_grads=True, histogram_freq=1)])
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/keras/models.py", line 960, in fit
    validation_steps=validation_steps)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1657, in fit
    validation_steps=validation_steps)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1213, in _fit_loop
    outs = f(ins_batch)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
KeyboardInterrupt

wandb: Program failed with code 255. Press ctrl-c to abort syncing.
wandb: Waiting for final file modifications.
wandb: Syncing files in wandb/run-20180214_194906-4pj90kcr:
wandb:   wandb-metadata.json
wandb:   diff.patch
wandb:   wandb-events.jsonl
wandb:
wandb: Verifying uploaded files... verified!
wandb: Synced https://app.wandb.ai/adrianbg/garbage/runs/4pj90kcr
(wandb-3.6) adrian@Adrians-MBP:~/src/wandb-examples/keras$
```

**Comment by adrianbg** [comment]
This doesn't seem to be happening any more.
