### ISSUE TITLE
Invalid cross-device link error preventing logging of images

### ISSUE THREAD

**Issue by timothybrooks** [wandb/client#1252]
wandb, version 0.10.2
Python 3.7.8
Linux

### Description

When trying to log images with W&B, I am getting an error that prevents the temp image file from being copied, which prevents logging and causes the job to crash.

### What I Did
Calling ``wandb.log(...)` on an `wandb.Image(...)` object, I get the following error:

```
Traceback (most recent call last):                                               
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/shutil.py", line 566, in move                                                 
    os.rename(src, real_dst)                                                                                                                  
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp5u21hyu4wandb-media/34f2xax2.png' -> '/home/timbrooks/code/prototypes/wandb/run-202009
22_021201-3qfz7a58/files/media/images/val/0/input_4000_0.png'      
```

**Comment by tyomhak** [comment]
Hey @timothybrooks, thanks for reporting. @vanpelt can you please help here?

**Comment by vanpelt** [comment]
Hey @timothybrooks `wandb.Image` writes the data to your system temp directory and links them to your folder if symlinks are supported.  Your system is unable to link between the underlying storage on /tmp vs your home directory.  The simplest solution is to put your `wandb` directory into your system temp directory.  You can do this by setting the `dir` argument of `wandb.init` to `/tmp`.

**Comment by timothybrooks** [comment]
Hmm I see. I had been using it fine in prior versions of wandb with my system, and other applications seem to be copying from /tmp successfully, although its possible that something changed on the side of our cluster. Oddly, it occasionally works for the first few images before throwing this error. Do you know why that might occur?

I would prefer to not store my logs on /tmp since those eventually get automatically removed and it would be a hassle for me to need to sync them. Any other options? Perhaps there is instead a way to specify a different temp directory (on the same filesystem) to use for these images to ensure they can be moved to my run directory?

**Comment by timothybrooks** [comment]
Here is a full stack trace in case this helps. Perhaps there was an issue writing the image into /tmp in the first place?

```
Traceback (most recent call last):                                                                                                                                                                                                           
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/shutil.py", line 566, in move                                                                                                                                                                                                  
    os.rename(src, real_dst)                                                                                                                                                                                                                                                                   
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpgkjszjbxwandb-media/8gnwalfi.png' -> '/home/timbrooks/code/prototypes/wandb/run-20200922_114506-1jkhr8zg/files/media/images/val/0/input_0_0.png'                                                                                       
                                                                                                                                                                                                                                                                                               
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                                             
  File "run_train.py", line 48, in train                                                                                                                                                                                                                                                       
    trainer.fit(model, train_data_loader, val_data_loaders)  # type: ignore                                                                                                                                                                                                                    
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn                                                                                                                                                     
    result = fn(self, *args, **kwargs)                                                                                                                                                                                                                                                         
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1064, in fit                                                                                                                                                         
    results = self.accelerator_backend.train()                                                                                                                                                                                                                                                 
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/accelerators/dp_backend.py", line 97, in train                                                                                                                                                 
    results = self.trainer.run_pretrain_routine(model)                                                                                                                                                                                                                                         
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine                                                                                                                                        
    self.train()
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 1015, in optimizer_closure
    hiddens)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 1197, in training_forward
    output = self.model(*args)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 83, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 147, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 288, in parallel_apply
    raise output
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 245, in _worker
    output = module.training_step(*input, **kwargs)
  File "/home/timbrooks/code/prototypes/models/model.py", line 46, in training_step
    logs.log_values({"loss": loss}, prefix="train")
  File "/home/timbrooks/code/prototypes/logs/wandb_logs.py", line 114, in log_values
    wandb.log(values_out, step=step, commit=commit)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 758, in log
    self.history._row_add(data)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 34, in _row_add
    self._flush()
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 49, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 553, in _history_callback
    self._backend.interface.publish_history(row, step)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/interface/interface.py", line 166, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/data_types.py", line 1698, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/data_types.py", line 1749, in val_to_json
    item.bind_to_run(run, key, namespace, id_=i)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/data_types.py", line 920, in bind_to_run
    super(Image, self).bind_to_run(*args, **kwargs)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/site-packages/wandb/data_types.py", line 209, in bind_to_run
    shutil.move(self._path, new_path)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/shutil.py", line 267, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/home/timbrooks/anaconda3/envs/prototypes/lib/python3.7/shutil.py", line 203, in copystat
    st = lookup("stat")(src, follow_symlinks=follow)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgkjszjbxwandb-media/8gnwalfi.png'
```

**Comment by timothybrooks** [comment]
I've downgraded W&B to 0.9.7 and the problem resolved. So perhaps there is a regression in writing or copying images?

**Comment by vanpelt** [comment]
Yep, looks like it, we'll try to reproduce.

**Comment by ariG23498** [comment]
Hey @timothybrooks 
Does this issue still persist in your system? We have the latest release as `0.10.12`. Thanks for the help in advance :smile:

**Comment by rjbruin** [comment]
I have the same issue with version `0.10.18`.

**Comment by soheeyang** [comment]
I had the same issue as @rjbruin with version `0.12.0`. I managed to solve this issue by changing the location of the root directory of `tempfile` to somewhere on the same shared storage as the wandb directory. This can be done by setting the value of the environment variable `TMPDIR` like `export TMPDIR=somewhere_on_the_same_shared_storage_where_wandb_dir_is_located`. (https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)

**Comment by soheeyang** [comment]
I finally resolved the issue by setting `wandb.init(dir=tempfile.gettemdir())`.

**Comment by dkoguciukml** [comment]
Hi, 

the problem is still not solved for wandb==0.12.16. Initializing with `wandb.init(dir=tempfile.gettempdir())` is only a workaround, which is not possible in our case. And only downgrading to W&B to 0.9.7 as @timothybrooks suggested helped, but of course, we would like to keep up to date. Any plans of addressing it? 

Best,
Daniel

**Comment by dkoguciukml** [comment]
Great, thank you <3

**Comment by hancan0** [comment]
I had the same issue as @rjbruin with version 0.14.0.  I agree with the reasons above. Is there a good solution？Perhaps there is instead a way to specify a different temp directory (on the same filesystem) to use for these images to ensure they can be moved to my run directory?
