### ISSUE TITLE
Couldn't communicate with backend after 15 seconds

### ISSUE THREAD

**Issue by samarth4149** [wandb/client#1287]
Hi,

My run exited with the error message in the title. What could this be from? 
Is it probably just a network error? In that case, I don't think wandb should crash the entire run with no notification.

Here's the full trace
```
Ignoring settings passed to wandb.setup() which has already been configured.
Problem at: /home/grad3/samarthm/bitbucket-misc/ssda_mme/utils/ioutils.py 376 init
Traceback (most recent call last):
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 477, in init
    run = wi.init()
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 356, in init
    _backend=backend, _disable_warning=True, _settings=self.settings
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 102, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/interface/interface.py", line 446, in communicate_login
    "Couldn't communicate with backend after %s seconds" % timeout
wandb.errors.error.Error: Couldn't communicate with backend after 15 seconds
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 477, in init
    run = wi.init()
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 356, in init
    _backend=backend, _disable_warning=True, _settings=self.settings
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 102, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/interface/interface.py", line 446, in communicate_login
    "Couldn't communicate with backend after %s seconds" % timeout
wandb.errors.error.Error: Couldn't communicate with backend after 15 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runners/mme/mme.py", line 57, in <module>
    config=args, reinit=True, project='ssda_mme-runners')
  File "/home/grad3/samarthm/bitbucket-misc/ssda_mme/utils/ioutils.py", line 376, in init
    wandb.init(*args, **kwargs)
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 511, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by tyomhak** [comment]
Hi @samarth4149, looks like this was a network issue on your side. You could try adding resume=True argument to your wandb.init function, to be able to resume the failed/crashed run.

or alternatively you could run it in dry-run mode, and then sync it separately.

@raubitsj do you have a better solution for this issue?

**Comment by samarth4149** [comment]
Thanks, I will do that if I believe network could be unstable (I have not really had the problem with the server I was working on).
As a feature request, maybe wandb can handle this case better? So it does not need to crash the main program?

**Comment by tyomhak** [comment]
Will certainly look into it! Thanks for flagging this issue.

**Comment by cvphelps** [comment]
Hi @samarth4149 could you please use 0.10.4 — it looks like this is should be fixed when the network error happens in the 15 seconds after login, we used to fail, but now we do not

**Comment by samarth4149** [comment]
Thanks

**Comment by samarth4149** [comment]
Hi @cvphelps @tyomhak, I am on version 0.10.4 of the client and I faced a similar error which I'm guessing is network error. It happened on one of the multiple similar runs. 

From what I can tell, it seems something went wrong with login/init. Can the client circumvent this without crashing? Something simple I can think about this is just allowing the user to increase the timeout, so the client just keeps polling the backend till it connects, rather than stopping the run. 

Thanks!

Here's the stack trace:

```
wandb: ERROR Error communicating with backend
Traceback (most recent call last):
  File "runners/mme/mme.py", line 64, in <module>
    config=args, reinit=True, project=project)
  File "/home/grad3/samarthm/bitbucket-misc/ssda_mme/utils/ioutils.py", line 398, in init
    wandb.init(*args, **kwargs)
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 460, in init
    run = wi.init()
  File "/home/grad3/samarthm/anaconda3/envs/pytorch3conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 378, in init
    raise UsageError(error_message)
wandb.errors.error.UsageError: Error communicating with backend
```

**Comment by ariG23498** [comment]
Hey @samarth4149 
Thanks for the ticket. Could you check if the issue still persists? #1409 seems to have a solution to the backend communication problem with just upgrading to the latest version. Do keep us posted :smile:

**Comment by samarth4149** [comment]
Yes, it seems [this](https://github.com/wandb/client/issues/1409#issuecomment-723371808) was the best workaround. [This](https://github.com/wandb/client/issues/1409#issuecomment-723676136) was also helpful.
