### ISSUE TITLE
unspecified error

### ISSUE THREAD

**Issue by saahiluppal** [wandb/client#1293]
Hey, 
I'm encountering this particular error
```bash
2020-09-28 15:11:52.110052: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Initializing Device: cuda
Number of params: 44481793
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
wandb: Currently logged in as: sahiluppal2k (use `wandb login --relogin` to force relogin)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 474, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 162, in setup
    self._log_setup(settings)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 289, in _log_setup
    delete=True,
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 224, in _safe_symlink
    os.rename(tmp_name, name)
IsADirectoryError: [Errno 21] Is a directory: 'latest-run.488' -> 'latest-run'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 474, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 162, in setup
    self._log_setup(settings)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 289, in _log_setup
    delete=True,
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 224, in _safe_symlink
    os.rename(tmp_name, name)
IsADirectoryError: [Errno 21] Is a directory: 'latest-run.488' -> 'latest-run'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 103, in <module>
    main(config)
  File "main.py", line 98, in main
    trainer.fit(model, datasource)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1073, in fit
    results = self.accelerator_backend.train(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/gpu_backend.py", line 51, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1167, in run_pretrain_routine
    self.logger.log_hyperparams(ref_model.hparams)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/loggers/wandb.py", line 143, in log_hyperparams
    self.experiment.config.update(params, allow_val_change=True)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/loggers/base.py", line 450, in experiment
    return get_experiment() or DummyExperiment()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/loggers/base.py", line 449, in get_experiment
    return fn(self)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/loggers/wandb.py", line 130, in experiment
    group=self._group)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 511, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```
Here, i'm using wandb logger with pytorch lightning. 
and here's insight 
```bash
wandb_logger = WandbLogger(project='xyz')
trainer = pl.Trainer(max_epochs=10, logger=wandb_logger, gpus=1)
trainer.fit(model, dm)
```

**Comment by tyomhak** [comment]
Hi there! Thanks for reporting. We're looking into this.

**Comment by cvphelps** [comment]
Hi @saahiluppal, what version of the client were you using? Please upgrade to see if this is still happening.

**Comment by saahiluppal** [comment]
I can confirm that i haven't encountered this issue today. WandbLogger is working perfectly fine with pytorch lightning
