### ISSUE TITLE
bug with matplotlib subplots

### ISSUE THREAD

**Issue by jliu** [wandb/client#1319]
The following example does not work with wandb:
```
from matplotlib import pyplot as plt
import wandb

wandb.init(project='test')
fig, ax = plt.subplots(2)
ax[0].plot([1, 2, 3])
wandb.log({'figure': wandb.Image(plt)}, step=0)

```
and gives error message:

Traceback (most recent call last):
  File "wandb_broken_example.py", line 9, in <module>
    wandb.log({'figure': wandb.Image(plt)}, step=0)
  File "/h/jyliu/miniconda3/envs/geom/lib/python3.8/site-packages/wandb/data_types.py", line 887, in __init__
    util.ensure_matplotlib_figure(data).savefig(buf)
  File "/h/jyliu/miniconda3/envs/geom/lib/python3.8/site-packages/wandb/util.py", line 334, in ensure_matplotlib_figure
    raise ValueError(
ValueError: You attempted to log an empty plot, pass a figure directly or ensure the global plot isn't closed.

This is very similar to [this Comet bug](https://github.com/comet-ml/issue-tracking/issues/312), where the usage of [gca().has_data()](https://github.com/wandb/client/blob/master/wandb/util.py#L333) is causing problems.

**Comment by tyomhak** [comment]
Hi @jliu, thank you for reporting this. We're looking into this.
