### ISSUE TITLE
wandb init on VM causes syntax error

### ISSUE THREAD

**Issue by nemanja-rakicevic** [wandb/client#1338]
Hi, I tried running wandb on a Azure VM. I use the same conda environment as on the local machine, with same version of wandb==0.10.4 and python==3.5.6.

However, when I try to run `wandb login` on the VM to continue the sweep, I get:

```
Traceback (most recent call last):
  File "/home/petar/anaconda3/envs/infosearch_env/bin/wandb", line 11, in <module>
    sys.exit(cli())
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/cli/cli.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/cli/cli.py", line 223, in login
    base_url=host,
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_setup.py", line 235, in setup
    ret = _setup(settings=settings)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_setup.py", line 230, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_setup.py", line 219, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_setup.py", line 92, in __init__
    self._load_viewer(settings=settings)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_setup.py", line 159, in _load_viewer
    s = server.Server(settings=settings)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/lib/server.py", line 17, in __init__
    self._api = api or InternalApi(default_settings=settings)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/apis/internal.py", line 9, in __init__
    self.api = InternalApi(*args, **kwargs)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 78, in __init__
    self.default_settings.update(default_settings or {})
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_settings.py", line 781, in __getitem__
    return getattr(self, k)
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_settings.py", line 387, in _console
    if self._jupyter:
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/sdk_py27/wandb_settings.py", line 368, in _jupyter
    return _get_python_type() != "python"
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/lib/ipython.py", line 16, in _get_python_type
    from IPython import get_ipython
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/petar/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

```
 Any ideas what is causing this?

**Comment by vanpelt** [comment]
This is due to the version of python not supporting our type definitions.  Are you able to run in a python environment version 3.6 or higher?

**Comment by raubitsj** [comment]
The type annotation issue appears to be with the "parso" package, I think
you can avoid this failure by doing:
`pip install -U parso==0.7.1`
0.7.1 is the last release that supports python2

**Comment by nemanja-rakicevic** [comment]
Amazing, thanks @raubitsj this solved my issue!
