### ISSUE TITLE
issue in wandb.init

### ISSUE THREAD

**Issue by VasudevGupta7** [wandb/client#1343]
When I am running wandb.init(project=..., name=..., config=....) in colab, Its showing this error:

```
Thread SenderThread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal_api.py", line 968, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal_api.py", line 128, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Variable "entity" has invalid value null.\nExpected type "String!", found null.', 'locations': [{'line': 1, 'column': 69}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal_util.py", line 33, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal_util.py", line 60, in _run
    self._process(record)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal.py", line 232, in _process
    self._sm.send(record)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/sender.py", line 90, in send
    send_handler(record)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/sender.py", line 360, in send_run
    self._init_run(run, config_dict)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/sender.py", line 396, in _init_run
    commit=repo.last_commit,
  File "/usr/local/lib/python3.6/dist-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal_api.py", line 968, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/internal/internal_api.py", line 128, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
wandb.errors.error.CommError: Variable "entity" has invalid value null.
Expected type "String!", found null.
```

Please help me out.
Thanks

**Comment by vanpelt** [comment]
Hey @VasudevGupta7 this was a temporary error in our backend.  We just rolled back the bad deploy, if you try again it should be working now, sorry about that.  If you're still seeing an error please let us know.

**Comment by VasudevGupta7** [comment]
Its fine now. Thankyou
