### ISSUE TITLE
Running sweep got Error: Variable "entityName" has invalid value null.

### ISSUE THREAD

**Issue by nemanja-rakicevic** [wandb/client#1344]
`wandb --version && python --version && uname`

- wandb, version 0.10.5
- Python 3.5.6 :: Anaconda, Inc.
- Linux

### Description

I am trying to run a sweep using the following config file `wandb_sweep.yaml`:

```
program: main_training_wandb.py
method: grid
metric:
    goal: minimize
    name: error_mean
parameters:
    kernel_lenscale:
        values: [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10]
    kernel_name:
        values: ['se', 'rq', 'mat']
    kernel_sigma:
        values: [0.1, 1., 10]
    pidf_coeff:
        values: [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10]
    seed:
        values: [100, 200, 300, 400, 500]
    config_file:
        values: ['configs/striker_2_link/paper_informed.json']
```
And within my code `main_training_wandb.py` I use wandb as:
```
...
wandb.init(
        project="informed_search_{}".format(task_kwargs['environment']),
        config=task_kwargs,
        allow_val_change=True,
        group="seed")
...
for ntrial_ in range(num_trials):
     ...
     wandb.log({
                'ntrial': ntrial_,
                'error_mean': np.mean(error),
                'error_std': np.std(error),
                'nfail': nfail})
...
```

This works when running individual tests with wandb `python main_training_wandb.py`, and I managed to run the same sweep a couple of days ago using `wandb sweep wandb_sweep.py`. However, I slightly changed `wandb_sweep.yaml` (added more values) and now when I run I get the following error:

```
wandb: Creating sweep from: wandb_sweep.yaml
Traceback (most recent call last):
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 1418, in upsert_sweep
    raise (err)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 1407, in upsert_sweep
    check_retry_fn=no_retry_4xx,
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 128, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Variable "entityName" has invalid value null.\nExpected type "String!", found null.', 'locations': [{'line': 1, 'column': 70}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/cli/cli.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/cli/cli.py", line 728, in sweep
    config, project=project, entity=entity, obj_id=sweep_obj_id
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/apis/internal.py", line 78, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 1418, in upsert_sweep
    raise (err)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 1407, in upsert_sweep
    check_retry_fn=no_retry_4xx,
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/internal/internal_api.py", line 128, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/robin/anaconda3/envs/infosearch_env/lib/python3.5/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
wandb.errors.error.CommError: Variable "entityName" has invalid value null.
Expected type "String!", found null.

Error: Variable "entityName" has invalid value null.
Expected type "String!", found null.

```
Any ideas what "entityName" refers to?

**Comment by ingambe** [comment]
Same error on my side, the problem seems to come from the server response

**Comment by JonBoyleCoding** [comment]
I'm having the same issue, was working fine yesterday but suddenly having issues. Creating a sweep via the website appears to be working still.

**Comment by nemanja-rakicevic** [comment]
I can confirm the sweeps work when initialised using the website.

**Comment by leopd** [comment]
Seems you can workaround the problem by specifying the "entity" on the CLI like:

```
wandb sweep -e my_user_name -p project config.yaml
```

It seems that "entity" means your username in wandb-land, as in the URL often includes `?workspace=user-my_user_name`

**Comment by annirudh** [comment]
This issue should be resolved, really sorry for the trouble this caused. We recently upgraded our backend's GraphQL library, which includes some stricter request validation. When making a sweep, the CLI was making an invalid request that the old version of the library used to allow, but the new one rejects.

We've patched the backend, so you should be able to create sweeps without issue now. Please let us know if you hit any other problems!
