### ISSUE TITLE
StopIteration Error when running wandb sync with wandb local

### ISSUE THREAD

**Issue by aclifton314** [wandb/client#1358]
**System Info**
- Python: 3.7.6
- wandb: 0.9.7

I'm getting the following error when running `wandb sync` from `wandb local`:
```python
user@pop-os:$ wandb sync dryrun-20201013_132838-2w22dip2/
wandb: Syncing dryrun-20201013_132838-2w22dip2/ to:
wandb: dark-serenity-2 http://localhost:8080/user/huggingface/runs/3rqkmquu
wandb: Uploading history metrics
Traceback (most recent call last):
  File "/path/to/anaconda3/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/cli.py", line 156, in wrapper
    return func(*args, **kwargs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/cli.py", line 447, in sync
    path, run_id=id, project=project, entity=entity, ignore_globs=globs)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/wandb_run.py", line 347, in from_directory
    file_api.stream_file(history)
  File "/path/to/anaconda3/lib/python3.7/site-packages/wandb/apis/file_stream.py", line 255, in stream_file
    first_line = next(f)
StopIteration

```
Here are the commands I issued:
```
user@pop-os:$ wandb local
wandb: A new version of W&B local is available, upgrade by calling `wandb local --upgrade`
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
user@pop-os:$ wandb sync dryrun-20201013_132838-2w22dip2/

```
Any thoughts about how to resolve this error?

**Comment by aclifton314** [comment]
The issue was because not enough iterations had happened to log anything. I am using the huggingface integration. I let my training run for longer and everything is now showing up in wandb. Closing this issue!
