### ISSUE TITLE
Execute `wandb sync --sync-all` error

### ISSUE THREAD

**Issue by Soptq** [wandb/client#1381]
Execute `wandb sync --sync-all` error

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/miniconda3/envs/cluster/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/cluster/lib/python3.8/site-packages/wandb/sync/sync.py", line 138, in run
    sm.send(pb)
  File "/root/miniconda3/envs/cluster/lib/python3.8/site-packages/wandb/internal/sender.py", line 90, in send
    send_handler(record)
  File "/root/miniconda3/envs/cluster/lib/python3.8/site-packages/wandb/internal/sender.py", line 372, in send_run
    self._start_run_threads()
  File "/root/miniconda3/envs/cluster/lib/python3.8/site-packages/wandb/internal/sender.py", line 464, in _start_run_threads
    email=self._settings.email,
AttributeError: 'SettingsStatic' object has no attribute 'email'
```

**Comment by vanpelt** [comment]
We have a fix for this coming in the next release.

**Comment by Soptq** [comment]
Thanks very much.
