### ISSUE TITLE
Wandb throws up error ""Function not implemented: wandb-metadata.json"

### ISSUE THREAD

**Issue by prasannapkr** [wandb/client#1398]
Hi,

I'm getting the below exception when i use wandb version 0.9.7. Basically this error shows and the training job i'm running doesn't exit and gives the following output forever

```
wandb: Waiting for W&B process to finish, PID 188
wandb: Program ended successfully.
wandb: Run summary:
wandb:                                               _timestamp 1603275584.2907119
wandb:                                                 _runtime 163.61839818954468
wandb:                                                    _step 0
wandb: Syncing 0 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)
wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)
wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)
```

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/azureml-envs/azureml_9b5d2e8a85b09f3d2185059d10ab455e/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/azureml-envs/azureml_9b5d2e8a85b09f3d2185059d10ab455e/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/azureml-envs/azureml_9b5d2e8a85b09f3d2185059d10ab455e/lib/python3.6/site-packages/wandb/filesync/step_checksum.py", line 46, in _thread_body
    shutil.copy2(req.path, path)
  File "/azureml-envs/azureml_9b5d2e8a85b09f3d2185059d10ab455e/lib/python3.6/shutil.py", line 258, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/azureml-envs/azureml_9b5d2e8a85b09f3d2185059d10ab455e/lib/python3.6/shutil.py", line 225, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/azureml-envs/azureml_9b5d2e8a85b09f3d2185059d10ab455e/lib/python3.6/shutil.py", line 157, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 38] Function not implemented: '/mnt/batch/tasks/shared/LS_root/jobs/ml-dev/azureml/level-exp_1603274857_5daea3a7/mounts/workspacefilestore/azureml/level-exp_1603274857_5daea3a7/wandb/run-20201021_101827-32puzg1u/wandb-metadata.json'

```

ps: I chose to install version 0.9.7 since i couldn't run with the latest version - i got the error below:
```
Traceback (most recent call last):
  File "/azureml-envs/azureml_5b66314353f9e321ec07356dca7802d0/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 474, in init
    wi.setup(kwargs)
  File "/azureml-envs/azureml_5b66314353f9e321ec07356dca7802d0/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 162, in setup
    self._log_setup(settings)
  File "/azureml-envs/azureml_5b66314353f9e321ec07356dca7802d0/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 289, in _log_setup
    delete=True,
  File "/azureml-envs/azureml_5b66314353f9e321ec07356dca7802d0/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 223, in _safe_symlink
    os.symlink(target, tmp_name)
OSError: [Errno 95] Operation not supported: 'run-20201021_112128-eiw76lxr' -> 'latest-run.128'
wandb: ERROR Abnormal program exit
Starting the daemon thread to refresh tokens in background for process with pid = 128

Traceback (most recent call last):
  File "level_optimization_train.py", line 113, in <module>
    wandb.init(project="pytorch-ppo-prod")
  File "/azureml-envs/azureml_5b66314353f9e321ec07356dca7802d0/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 511, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```

I looked for online resources but i couldn't find anything - any help is appreciated.

**Comment by cvphelps** [comment]
Hi, thanks for writing in. Could you please update to 0.10.7 and see if the issue persists?

**Comment by ariG23498** [comment]
Hey @prasannapkr 
We are closing this ticket due to the inactivity. Please feel free to reopen this if the issue still persists with the latest version of wandb. :smile:
