### ISSUE TITLE
wandb.sync() swallowing my script's traceback?

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#14]
It looks like my training script bailed at train.py:76, which attempts to open an h5 file. 

Running from /wandb/gaze at this commit:
https://github.com/wandb/gaze/tree/63e2ddb54f38f8a4a0e621b7bf5b3c1c1b509795

Log when wandb.sync call is not commented out:
```bash
(gaze) Shawns-MacBook-Pro:gaze shawn$ python train.py --max_epochs=1  ~/code/gaze-data/ds-office-shawn-1/ ~/code/gaze-data/ds-office-shawn-2/
Using TensorFlow backend.
Syncing https://app.wandb.ai/shawn/gaze/runs/5bp7ws
Pushing log
Synced https://app.wandb.ai/shawn/gaze/runs/5bp7ws
ERROR: unable to create file (File accessability: Unable to open file)(gaze) Shawns-MacBook-Pro:gaze shawn$
```

Log when wandb.sync call is commented out:
```
(gaze) Shawns-MacBook-Pro:gaze shawn$ python train.py --env=floyd --max_epochs=1  ~/code/gaze-data/ds-office-shawn-1/ ~/code/gaze-data/ds-office-shawn-2/
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 158, in <module>
    main(sys.argv)
  File "train.py", line 76, in main
    [h5py.File(d)['face_img'] for d in args.dataset])
  File "/Users/shawn/.pyenv/versions/gaze/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/Users/shawn/.pyenv/versions/gaze/lib/python2.7/site-packages/h5py/_hl/files.py", line 98, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5f.pyx", line 90, in h5py.h5f.create (h5py/h5f.c:1709)
IOError: unable to create file (File accessability: Unable to open file)
```

**Comment by vanpelt** [comment]
Yeah, I meant to swallow any errors from the client and present a nice message but am catching everything.  We should change that...
