### ISSUE TITLE
If a run is deleted in the web dashboard while its running, run hangs without exiting

### ISSUE THREAD

**Issue by Shreeyak** [wandb/client#1443]
I deleted a run while it was still running (from the web dashboard). I expected a kill cmd to be sent to the process, or for the process to discover that the server-side run had been deleted and hence exit. However, it just printed an error and got stuck, not progressing. Here are my logs:

```shell script
Epoch: 37 | Iter: 1073/100000
------------------------------
Train: 100%|██████████████████████████████████████████| 29/29 [00:32<00:00,  1.12s/it, Loss: 3846.5503603, mIoU: 0.7436]
Test/real: 100%|████████████████████████████████████████| 3/3 [00:06<00:00,  2.01s/it, Loss: 4243.6077474, mIoU: 0.7991]

Epoch: 38 | Iter: 1102/100000
------------------------------
Train:  10%|████▍                                      | 3/29 [00:10<00:55,  2.14s/it, Loss: 3729.6184082, mIoU: ?.????]Traceback (most recent call last):
  File "/opt/conda/bin/segmentation-train", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/opt/conda/lib/python3.7/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_segmentation_deeplab/train.py", line 196, in main
    trainer.train(start_epoch, end_iter_num, total_iter_num)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_segmentation_deeplab/trainer.py", line 178, in train
    total_iter_num = self.run_epoch(curr_epoch, total_iter_num)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_segmentation_deeplab/trainer.py", line 164, in run_epoch
    total_iter_num = self.training_cycle(self.train_dataloader, "Train", epoch, total_iter_num)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_segmentation_deeplab/trainer.py", line 72, in training_cycle
    outputs = self.model.forward(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    thread.join()
  File "/opt/conda/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/opt/conda/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/file_stream.py", line 227, in _thread_body
    self._send(ready_chunks)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/file_stream.py", line 272, in _send
    self._client.post, self._endpoint, json={"files": files}
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/file_stream.py", line 249, in _handle_response
    raise response
  File "/opt/conda/lib/python3.7/site-packages/wandb/util.py", line 607, in request_with_retry
    response.raise_for_status()
  File "/opt/conda/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/<redacted>/1ngwdw9w/file_stream
```

I had to attach to my process and give SIGINT ( ctrl+c ) for the process to exit. At this point, it printed a bunch more logs:

```shell script
^CException ignored in: <module 'threading' from '/opt/conda/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt

wandb: Waiting for W&B process to finish, PID 75
wandb: Program failed with code 255.  Press ctrl-c to abort syncing.
Exception in thread Thread-250:ploaded (0.00MB deduped)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 40, in run
    success = self.push()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 88, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

Exception in thread Thread-248:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 40, in run
    success = self.push()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 88, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

Exception in thread Thread-249:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 40, in run
    success = self.push()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 88, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

Exception in thread Thread-246:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 40, in run
    success = self.push()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 88, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

Exception in thread Thread-247:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 40, in run
    success = self.push()
  File "/opt/conda/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 88, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 1045, in upload_urls
    "Run does not exist {}/{}/{}.".format(entity, project, run_id)
wandb.errors.error.CommError: Run does not exist <redacted>/1ngwdw9w.

wandb:                                                                                
wandb: Find user logs for this run at: wandb/run-20201028_090718-1ngwdw9w/logs/debug.log
wandb: Find internal logs for this run at: wandb/run-20201028_090718-1ngwdw9w/logs/debug-internal.log
wandb: Run summary:
wandb:                           epoch 38
wandb:            Train/BatchWise_Loss 3729.61841
wandb:                           batch 1105
wandb:                           _step 1180
wandb:                        _runtime 1552
wandb:                      _timestamp 1603866790
wandb:                   Learning_Rate 0.0001
wandb:                Train/Epoch_Loss 3846.55036
wandb:                      Train/mIoU 0.74363
wandb:            Test/real/Epoch_Loss 4243.60775
wandb:                  Test/real/mIoU 0.79912
wandb: Run history:
wandb:                  epoch ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:   Train/BatchWise_Loss █▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  batch ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:                  _step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:               _runtime ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
wandb:             _timestamp ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
wandb:          Learning_Rate ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:       Train/Epoch_Loss █▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:             Train/mIoU ▁▃▄▄▅▅▆▆▇▇▇▇▇▇▇▇▇▇▇███████████████████
wandb:   Test/real/Epoch_Loss █▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         Test/real/mIoU ▁▂▃▄▅▆▆▇▇▇▇▇▇▇████████████████████████
wandb: 
wandb: Synced 5 W&B file(s), 152 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: 
wandb: Synced <redacted>/1ngwdw9w
√ Stopped
```

**Comment by cvphelps** [comment]
Hi Shreeyak, thanks for reporting this. I suggest pressing the "stop" button in the project page sidebar run menu.

## Project page sidebar run menu
![image](https://user-images.githubusercontent.com/6355078/97679697-d3eb8480-1a52-11eb-821d-1e09cfe756c8.png)

**Comment by cvphelps** [comment]
Thanks for reporting this, we should not hang forever.

To stop a run from the UI, click the "stop" button on the run overview tab
![image](https://user-images.githubusercontent.com/6355078/97679964-32186780-1a53-11eb-8d8b-75e8e46dec9f.png)

**Comment by Shreeyak** [comment]
Thanks for the tip! I did click on the stop button, but it was taking too long. So I just deleted the run, thinking it'll shut down on its own as a consequence.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
