### ISSUE TITLE
On wandb 0.10.8, wandb sweep agent returns JSON TypeError

### ISSUE THREAD

**Issue by parasj** [wandb/client#1457]
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 5.4.0-40-generic
wandb version: 0.10.8
Python version: Python 3.8.6

Problem: When launching the wandb sweep agent, I receive a JSON TypeError. I do not receive this error in wandb client version 0.10.7.
```
wandb agent --count 1 cfq/sweep_mcd1_bert/bz0242i3
wandb: Starting wandb agent 🕵️
2020-11-03 23:42:48,982 - wandb.wandb_agent - INFO - Running runs: []
2020-11-03 23:42:50,803 - wandb.wandb_agent - INFO - Agent received command: run
2020-11-03 23:42:50,803 - wandb.wandb_agent - INFO - Agent starting run with config:
    <config here>
2020-11-03 23:42:50,977 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python cfq/train.py <config here>
2020-11-03 23:42:55,990 - wandb.wandb_agent - INFO - Running runs: ['66jpdb1t']
I1103 23:43:14.621650 139774860945216 wandb_settings.py:606] setting login settings: {}
wandb: Currently logged in as: paras (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
Thread SenderThread:
Traceback (most recent call last):
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/internal/internal_util.py", line 33, in run
    self._run()
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/internal/internal_util.py", line 60, in _run
    self._process(record)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/internal/internal.py", line 232, in _process
    self._sm.send(record)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/internal/sender.py", line 91, in send
    send_handler(record)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/internal/sender.py", line 358, in send_run
    error = self._maybe_setup_resume(run)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/internal/sender.py", line 319, in _maybe_setup_resume
    summary = json.loads(resume_status["summaryMetrics"])
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Problem at: /data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py 123 experiment
Traceback (most recent call last):
  File "cfq/train.py", line 198, in <module>
    app.run(main)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "cfq/train.py", line 157, in main
    wandb_logger.watch(model, log="all", log_freq=100)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 132, in watch
    self.experiment.watch(model, log=log, log_freq=log_freq)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 475, in experiment
    return get_experiment() or DummyExperiment()
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 35, in wrapped_fn
    return fn(*args, **kwargs)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 474, in get_experiment
    return fn(self)
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 123, in experiment
    self._experiment = wandb.init(
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 472, in init
    run = wi.init()
  File "/data/paras/miniconda3/envs/cfq_wandb_/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 389, in init
    raise UsageError(error_message)
wandb.errors.error.UsageError: Error communicating with backend
2020-11-03 23:43:52,074 - wandb.wandb_agent - INFO - Cleaning up finished run: 66jpdb1t
```

**Comment by tyomhak** [comment]
Hey @parasj , can you update wandb to latest version, and check if this error persists?

**Comment by cvphelps** [comment]
Hi thanks for the 10.7 backtrace, could you please share the one from 10.8 as well?

**Comment by parasj** [comment]
Hi @tyomhak and @cvphelps, thanks for getting back to me. To clarify, the backtrace I shared is from 10.8 where I get the error. I am attaching all the traces from four wandb versions, and it appears the issue is localized to 10.8. I'm closing this issue since it seems like the bug was fixed.

<details>
<summary>On wandb 10.3, backtrace</summary>
<br>
<pre>
wandb agent --count 1 cfq/sweep_mcd1_bert/wxunrt9e
wandb: Starting wandb agent 🕵️
2020-11-09 15:11:21,222 - wandb.wandb_agent - INFO - Running runs: []
2020-11-09 15:11:23,608 - wandb.wandb_agent - INFO - Agent received command: run
2020-11-09 15:11:23,609 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 32
	bert_model_version: bert-base-cased
	cfq_split: mcd1
	cosine_lr_period: 0
	data_root_path: /data/paras/data_cache/cfq
	dropout: 0.5
	gamma: 1
	lr: 2.8486735831438822e-05
	ntl_bilinear: True
	ntl_hidden_dim: 64
	ntl_inp: 64
	num_epochs: 100
	optimizer_name: Adam
	run_dir_root: /data/paras/data_cache/cfq
	seed: 2
	seq_model: bert
	sweep_mode: True
	w_pos: 0.9177750122648644
	wandb_project: cfq_sweep_bert
	warmup_epochs: 8
2020-11-09 15:11:23,889 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python cfq/train.py --batch_size=32 --bert_model_version=bert-base-cased --cfq_split=mcd1 --cosine_lr_period=0 --data_root_path=/data/paras/data_cache/cfq --dropout=0.5 --gamma=1 --lr=2.8486735831438822e-05 --ntl_bilinear=True --ntl_hidden_dim=64 --ntl_inp=64 --num_epochs=100 --optimizer_name=Adam --run_dir_root=/data/paras/data_cache/cfq --seed=2 --seq_model=bert --sweep_mode=True --w_pos=0.9177750122648644 --wandb_project=cfq_sweep_bert --warmup_epochs=8
2020-11-09 15:11:28,906 - wandb.wandb_agent - INFO - Running runs: ['dqivwqg4']
2020-11-09 15:11:35.343 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:11:35.345 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
I1109 15:11:50.393635 140255908607808 wandb_settings.py:547] setting login settings: {}
wandb: Currently logged in as: paras (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
wandb: wandb version 0.10.10 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.3
wandb: Syncing run jolly-sweep-38
wandb: ⭐️ View project at https://wandb.ai/cfq/sweep_mcd1_bert
wandb: 🧹 View sweep at https://wandb.ai/cfq/sweep_mcd1_bert/sweeps/wxunrt9e
wandb: 🚀 View run at https://wandb.ai/cfq/sweep_mcd1_bert/runs/dqivwqg4
wandb: Run data is saved locally in /data/paras/data_cache/cfq/wandb/run-20201109_151150-dqivwqg4
wandb: Run `wandb off` to turn off syncing.

GPU available: True, used: True
I1109 15:11:53.553157 140255908607808 distributed.py:49] GPU available: True, used: True
I1109 15:11:53.553157 140255908607808 distributed.py:49] GPU available: True, used: True
TPU available: False, using: 0 TPU cores
I1109 15:11:53.553440 140255908607808 distributed.py:49] TPU available: False, using: 0 TPU cores
I1109 15:11:53.553440 140255908607808 distributed.py:49] TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:11:53.553716 140255908607808 accelerator_connector.py:402] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:11:53.553716 140255908607808 accelerator_connector.py:402] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
I1109 15:12:01.612756 140255908607808 accelerator.py:209] initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
I1109 15:12:01.612756 140255908607808 accelerator.py:209] initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
2020-11-09 15:12:02.481 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:12:02.482 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
2020-11-09 15:12:08.062 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:12:08.064 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
2020-11-09 15:12:08.859 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:12:08.860 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:12:17.319886 139752311629632 accelerator_connector.py:402] LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
I1109 15:12:17.345858 139752311629632 accelerator.py:209] initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:12:23.822160 139785384843072 accelerator_connector.py:402] LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
I1109 15:12:23.846847 139785384843072 accelerator.py:209] initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:12:25.118607 139684433516352 accelerator_connector.py:402] LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
I1109 15:12:25.134230 139684433516352 accelerator.py:209] initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
Set SLURM handle signals.
Set SLURM handle signals.
Set SLURM handle signals.
I1109 15:12:37.277858 139785384843072 slurm_connector.py:80] Set SLURM handle signals.
Set SLURM handle signals.
I1109 15:12:37.277878 139684433516352 slurm_connector.py:80] Set SLURM handle signals.
I1109 15:12:37.277885 139752311629632 slurm_connector.py:80] Set SLURM handle signals.
I1109 15:12:37.278231 140255908607808 slurm_connector.py:80] Set SLURM handle signals.
I1109 15:12:37.278231 140255908607808 slurm_connector.py:80] Set SLURM handle signals.

  | Name  | Type  | Params
--------------------------------
0 | model | Model | 119 M
I1109 15:12:37.289706 140255908607808 lightning.py:1295]
  | Name  | Type  | Params
--------------------------------
0 | model | Model | 119 M
I1109 15:12:37.289706 140255908607808 lightning.py:1295]
  | Name  | Type  | Params
--------------------------------
0 | model | Model | 119 M
Validation sanity check: 0it [00:00, ?it/s]/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Training: 0it [00:00, ?it/s]/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Epoch 0:   0%|          | 0/842 [00:00<?, ?it/s] /data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Epoch 0:   9%|▉         | 77/842 [00:40<06:44,  1.89it/s, loss=737.822, v_num=wqg4]
</pre>
</details> 

<details>
<summary>On wandb 10.7, backtrace</summary>
<br>
<pre>
wandb agent --count 1 cfq/sweep_mcd1_bert/wxunrt9e
wandb: Starting wandb agent 🕵️
2020-11-09 15:17:41,214 - wandb.wandb_agent - INFO - Running runs: []
2020-11-09 15:17:43,015 - wandb.wandb_agent - INFO - Agent received command: run
2020-11-09 15:17:43,016 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 32
	bert_model_version: bert-base-cased
	cfq_split: mcd1
	cosine_lr_period: 0.5
	data_root_path: /data/paras/data_cache/cfq
	dropout: 0.5
	gamma: 1
	lr: 2.232974298313815e-05
	ntl_bilinear: True
	ntl_hidden_dim: 64
	ntl_inp: 64
	num_epochs: 100
	optimizer_name: Adam
	run_dir_root: /data/paras/data_cache/cfq
	seed: 2
	seq_model: bert
	sweep_mode: True
	w_pos: 0.9892064110281988
	wandb_project: cfq_sweep_bert
	warmup_epochs: 1
2020-11-09 15:17:43,287 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python cfq/train.py --batch_size=32 --bert_model_version=bert-base-cased --cfq_split=mcd1 --cosine_lr_period=0.5 --data_root_path=/data/paras/data_cache/cfq --dropout=0.5 --gamma=1 --lr=2.232974298313815e-05 --ntl_bilinear=True --ntl_hidden_dim=64 --ntl_inp=64 --num_epochs=100 --optimizer_name=Adam --run_dir_root=/data/paras/data_cache/cfq --seed=2 --seq_model=bert --sweep_mode=True --w_pos=0.9892064110281988 --wandb_project=cfq_sweep_bert --warmup_epochs=1
2020-11-09 15:17:48,306 - wandb.wandb_agent - INFO - Running runs: ['ks2k7nhi']
2020-11-09 15:17:53.116 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:17:53.121 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
I1109 15:18:06.540047 140104351926080 wandb_settings.py:606] setting login settings: {}
wandb: Currently logged in as: paras (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
wandb: wandb version 0.10.10 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.7
wandb: Syncing run worldly-sweep-39
wandb: ⭐️ View project at https://wandb.ai/cfq/sweep_mcd1_bert
wandb: 🧹 View sweep at https://wandb.ai/cfq/sweep_mcd1_bert/sweeps/wxunrt9e
wandb: 🚀 View run at https://wandb.ai/cfq/sweep_mcd1_bert/runs/ks2k7nhi
wandb: Run data is saved locally in /data/paras/data_cache/cfq/wandb/run-20201109_151806-ks2k7nhi
wandb: Run `wandb off` to turn off syncing.

GPU available: True, used: True
I1109 15:18:09.425055 140104351926080 distributed.py:49] GPU available: True, used: True
I1109 15:18:09.425055 140104351926080 distributed.py:49] GPU available: True, used: True
TPU available: False, using: 0 TPU cores
I1109 15:18:09.425323 140104351926080 distributed.py:49] TPU available: False, using: 0 TPU cores
I1109 15:18:09.425323 140104351926080 distributed.py:49] TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:18:09.425616 140104351926080 accelerator_connector.py:402] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:18:09.425616 140104351926080 accelerator_connector.py:402] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
I1109 15:18:17.569136 140104351926080 accelerator.py:209] initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
I1109 15:18:17.569136 140104351926080 accelerator.py:209] initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
2020-11-09 15:18:19.748 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:18:19.750 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
2020-11-09 15:18:24.926 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:18:24.929 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
2020-11-09 15:18:25.590 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:18:25.591 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:18:35.910136 140170630072128 accelerator_connector.py:402] LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
I1109 15:18:35.913054 140170630072128 accelerator.py:209] initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:18:43.319181 140409167447872 accelerator_connector.py:402] LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
I1109 15:18:43.330018 140409167447872 accelerator.py:209] initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:18:44.951912 140229273200448 accelerator_connector.py:402] LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
I1109 15:18:44.980495 140229273200448 accelerator.py:209] initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
Set SLURM handle signals.
Set SLURM handle signals.
I1109 15:19:01.609967 140409167447872 slurm_connector.py:80] Set SLURM handle signals.
Set SLURM handle signals.
I1109 15:19:01.613429 140104351926080 slurm_connector.py:80] Set SLURM handle signals.
I1109 15:19:01.613429 140104351926080 slurm_connector.py:80] Set SLURM handle signals.
I1109 15:19:01.609935 140229273200448 slurm_connector.py:80] Set SLURM handle signals.
Set SLURM handle signals.
I1109 15:19:01.617874 140170630072128 slurm_connector.py:80] Set SLURM handle signals.

  | Name  | Type  | Params
--------------------------------
0 | model | Model | 119 M
I1109 15:19:01.666967 140104351926080 lightning.py:1295]
  | Name  | Type  | Params
--------------------------------
0 | model | Model | 119 M
I1109 15:19:01.666967 140104351926080 lightning.py:1295]
  | Name  | Type  | Params
--------------------------------
0 | model | Model | 119 M
Validation sanity check: 0it [00:00, ?it/s]/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Training: 0it [00:00, ?it/s]/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Epoch 0:   3%|▎         | 28/842 [00:35<17:09,  1.27s/it, loss=733.994, v_num=7nhi]
</pre>
</details> 

<details>
<summary>On wandb 10.8, backtrace</summary>
<br>
<pre>
wandb agent --count 1 cfq/sweep_mcd1_bert/wxunrt9e
wandb: Starting wandb agent 🕵️
2020-11-09 15:21:48,138 - wandb.wandb_agent - INFO - Running runs: []
2020-11-09 15:21:49,770 - wandb.wandb_agent - INFO - Agent received command: run
2020-11-09 15:21:49,770 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 32
	bert_model_version: bert-base-cased
	cfq_split: mcd1
	cosine_lr_period: 0
	data_root_path: /data/paras/data_cache/cfq
	dropout: 0.5
	gamma: 1
	lr: 1.7547871301799722e-05
	ntl_bilinear: True
	ntl_hidden_dim: 64
	ntl_inp: 64
	num_epochs: 100
	optimizer_name: Adam
	run_dir_root: /data/paras/data_cache/cfq
	seed: 2
	seq_model: bert
	sweep_mode: True
	w_pos: 0.8714153292350526
	wandb_project: cfq_sweep_bert
	warmup_epochs: 10
2020-11-09 15:21:51,061 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python cfq/train.py --batch_size=32 --bert_model_version=bert-base-cased --cfq_split=mcd1 --cosine_lr_period=0 --data_root_path=/data/paras/data_cache/cfq --dropout=0.5 --gamma=1 --lr=1.7547871301799722e-05 --ntl_bilinear=True --ntl_hidden_dim=64 --ntl_inp=64 --num_epochs=100 --optimizer_name=Adam --run_dir_root=/data/paras/data_cache/cfq --seed=2 --seq_model=bert --sweep_mode=True --w_pos=0.8714153292350526 --wandb_project=cfq_sweep_bert --warmup_epochs=10
2020-11-09 15:21:56,090 - wandb.wandb_agent - INFO - Running runs: ['p0kbpzpb']
2020-11-09 15:22:00.404 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:22:00.405 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
I1109 15:22:12.108021 140439191156544 wandb_settings.py:606] setting login settings: {}
wandb: Currently logged in as: paras (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
wandb: wandb version 0.10.10 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
Thread SenderThread:
Traceback (most recent call last):
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/wandb/internal/internal_util.py", line 33, in run
    self._run()
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/wandb/internal/internal_util.py", line 60, in _run
    self._process(record)
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/wandb/internal/internal.py", line 232, in _process
    self._sm.send(record)
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/wandb/internal/sender.py", line 91, in send
    send_handler(record)
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/wandb/internal/sender.py", line 358, in send_run
    error = self._maybe_setup_resume(run)
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/site-packages/wandb/internal/sender.py", line 319, in _maybe_setup_resume
    summary = json.loads(resume_status["summaryMetrics"])
  File "/data/paras/miniconda3/envs/cfq_wandb_0/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
</pre>
</details>

<details>
<summary>On wandb 10.9, backtrace</summary>
<br>
<pre>
wandb agent --count 1 cfq/sweep_mcd1_bert/wxunrt9e
wandb: Starting wandb agent 🕵️
2020-11-09 15:23:52,538 - wandb.wandb_agent - INFO - Running runs: []
2020-11-09 15:23:54,270 - wandb.wandb_agent - INFO - Agent received command: run
2020-11-09 15:23:54,270 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 32
	bert_model_version: bert-base-cased
	cfq_split: mcd1
	cosine_lr_period: 0
	data_root_path: /data/paras/data_cache/cfq
	dropout: 0
	gamma: 1
	lr: 4.2671198216584705e-05
	ntl_bilinear: True
	ntl_hidden_dim: 64
	ntl_inp: 64
	num_epochs: 100
	optimizer_name: Adam
	run_dir_root: /data/paras/data_cache/cfq
	seed: 2
	seq_model: bert
	sweep_mode: True
	w_pos: 0.7554227800665836
	wandb_project: cfq_sweep_bert
	warmup_epochs: 0
2020-11-09 15:23:54,340 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python cfq/train.py --batch_size=32 --bert_model_version=bert-base-cased --cfq_split=mcd1 --cosine_lr_period=0 --data_root_path=/data/paras/data_cache/cfq --dropout=0 --gamma=1 --lr=4.2671198216584705e-05 --ntl_bilinear=True --ntl_hidden_dim=64 --ntl_inp=64 --num_epochs=100 --optimizer_name=Adam --run_dir_root=/data/paras/data_cache/cfq --seed=2 --seq_model=bert --sweep_mode=True --w_pos=0.7554227800665836 --wandb_project=cfq_sweep_bert --warmup_epochs=0
2020-11-09 15:23:59,354 - wandb.wandb_agent - INFO - Running runs: ['b0py28nb']
2020-11-09 15:24:03.471 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:24:03.477 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
wandb: Currently logged in as: paras (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
wandb: wandb version 0.10.10 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.9
wandb: Resuming run vibrant-sweep-41
wandb: ⭐️ View project at https://wandb.ai/cfq/sweep_mcd1_bert
wandb: 🧹 View sweep at https://wandb.ai/cfq/sweep_mcd1_bert/sweeps/wxunrt9e
wandb: 🚀 View run at https://wandb.ai/cfq/sweep_mcd1_bert/runs/b0py28nb
wandb: Run data is saved locally in /data/paras/data_cache/cfq/wandb/run-20201109_152419-b0py28nb
wandb: Run `wandb off` to turn off syncing.

GPU available: True, used: True
I1109 15:24:22.151832 140224471045952 distributed.py:49] GPU available: True, used: True
I1109 15:24:22.151832 140224471045952 distributed.py:49] GPU available: True, used: True
TPU available: False, using: 0 TPU cores
I1109 15:24:22.152119 140224471045952 distributed.py:49] TPU available: False, using: 0 TPU cores
I1109 15:24:22.152119 140224471045952 distributed.py:49] TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:24:22.152383 140224471045952 accelerator_connector.py:402] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:24:22.152383 140224471045952 accelerator_connector.py:402] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
I1109 15:24:29.963968 140224471045952 accelerator.py:209] initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
I1109 15:24:29.963968 140224471045952 accelerator.py:209] initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
2020-11-09 15:24:33.604 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:24:33.605 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
2020-11-09 15:24:37.642 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:24:37.644 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
2020-11-09 15:24:39.382 | INFO     | cfq.data:setup:149 - Initializing dataset at stage None
2020-11-09 15:24:39.410 | INFO     | cfq.data:setup:154 - Loading data from /data/paras/data_cache/cfq/cfq/splits/mcd1.npz
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:24:51.662750 140498584229696 accelerator_connector.py:402] LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
I1109 15:24:51.666883 140498584229696 accelerator.py:209] initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:24:56.716368 140659797681984 accelerator_connector.py:402] LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
I1109 15:24:56.720593 140659797681984 accelerator.py:209] initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
I1109 15:24:58.293544 140511980914496 accelerator_connector.py:402] LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,3,4]
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
I1109 15:24:58.297935 140511980914496 accelerator.py:209] initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
</pre>
</details>
