### ISSUE TITLE
wandb.init fails when a parent directory has '.git' file

### ISSUE THREAD

**Issue by j-min** [wandb/client#1565]
**Describe the bug**
`wandb.init` fails with the error below.
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
```
It seems to have trouble getting [settings.program_relpath](https://github.com/wandb/client/blob/41ea7537efb50e63471874941904b3d223d6c6b1/wandb/sdk/wandb_settings.py#L784).
Maybe it is related to recent OS upgrade to Ubuntu 20.04

**To Reproduce**

```python3
# wandb_test.py
import wandb
wandb.init('gpt-3')
```
```
python wandb_test.py
```
**Expected behavior**
Runs normally. This actually runs without any error in other server with Ubuntu 18.04

**Screenshots**
```
╰─ python wandb_test.py
Traceback (most recent call last):
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 478, in init
    wi.setup(kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 68, in setup
    self._wl = wandb_setup._setup()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 221, in _setup
    wl = _WandbSetup(settings=settings, _warn=_warn)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 213, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 94, in __init__
    self._settings_setup(settings, self._early_logger)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 119, in _settings_setup
    s._infer_run_settings_from_env()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 710, in _infer_run_settings_from_env
    program_relpath = _get_program_relpath_from_gitrepo(program)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 137, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/lib/git.py", line 47, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 478, in init
    wi.setup(kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 68, in setup
    self._wl = wandb_setup._setup()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 221, in _setup
    wl = _WandbSetup(settings=settings, _warn=_warn)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 213, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 94, in __init__
    self._settings_setup(settings, self._early_logger)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 119, in _settings_setup
    s._infer_run_settings_from_env()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 710, in _infer_run_settings_from_env
    program_relpath = _get_program_relpath_from_gitrepo(program)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 137, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/lib/git.py", line 47, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "wandb_test.py", line 5, in <module>
    wandb.init(project='gpt-3')
  File "/ssd-playpen/home/jmincho/anaconda3/envs/t5/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 515, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```

**Operating System**

Problem
 - OS: Ubuntu 20.04.1 LTS
 - Wandb Version 0.10.11
 - git version: 2.25.1

Works normally in 
 - OS: Ubuntu 18.04.5 LTS
 - Wandb Version 0.10.11
 - git version: 2.17.1

**Additional context**
I don't have `.git/` in the server. I can run wandb normally with the exactly same code in another server.
I'm using a shared server in a university. Our server admin recently upgraded the server including its ubuntu version (18.04 -> 20.04) and I cannot run wandb since then.

**Comment by j-min** [comment]
I found the cause. This is not a linux issue.
Actually `/.git` has been added recently in my server (probably by server admin).
and [this line](https://github.com/wandb/client/blob/41ea7537ef/wandb/sdk/lib/git.py#L26) does not raise `exc.InvalidGitRepositoryError`.

I could make a hotfix by adding a line `raise exc.InvalidGitRepositoryError`.
But this was very hard to debug, since I never guessed that I had to look into a class called [GitRepo](https://github.com/wandb/client/blob/41ea7537ef/wandb/sdk/lib/git.py#L11) even though I do not use git at all in this project.
Is there a flag that forces wandb not look into git repo? (ex. forcing [remote](https://github.com/wandb/client/blob/41ea7537ef/wandb/sdk/lib/git.py#L12)='None')

**Comment by vanpelt** [comment]
Hey @j-min can you try setting the "WANDB_DISABLE_CODE" environment variable to "true"?  That should prevent us from querying the git repository.

**Comment by j-min** [comment]
I tried adding `os.environ['WANDB_DISABLE_CODE']='True'`.
It still results in error as below,
since [this line](https://github.com/wandb/client/blob/41ea7537ef/wandb/sdk/internal/meta.py#L101) also calls `self._git.root`.
```
Thread HandlerThread:
Traceback (most recent call last):
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 33, in run
    self._run()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 60, in _run
    self._process(record)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 203, in _process
    self._hm.handle(record)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/handler.py", line 48, in handle
    handler(record)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/handler.py", line 57, in handle_request
    handler(record)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/handler.py", line 209, in handle_request_run_start
    run_meta.probe()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/meta.py", line 215, in probe
    self._save_patches()
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/internal/meta.py", line 101, in _save_patches
    root = self._git.root
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/wandb/sdk/lib/git.py", line 47, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/ssd-playpen/home/jmincho/anaconda3/envs/wandb_test/lib/python3.7/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'
```

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by j-min** [comment]
Hi, the issue still persists and I have found other people who faced the same issue.
I suggest the same fix - adding a flag that forces wandb not look into git repo.
(ex. forcing [remote](https://github.com/wandb/client/blob/41ea7537ef/wandb/sdk/lib/git.py#L12)='None' or [search_parent_directories](https://github.com/wandb/client/blob/41ea7537ef/wandb/sdk/lib/git.py#L27)=False)

**Comment by vanpelt** [comment]
Hey @j-min you should be able to set the `WANDB_DISABLE_GIT` environment variable to prevent our sdk from probing.  Looking through the code there are still cases where we attempt to detect a git repo to get the relative path of your code or to generate a name for your project if you don't specify it.  If that doesn't work, please provide a stack trace or error so we can be sure we prevent the error you're seeing.

**Comment by j-min** [comment]
@vanpelt I tried `export WANDB_DISABLE_GIT=True`, but it did not help. Below is the error log.

```bash
Traceback (most recent call last):
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 151, in setup
    self._wl = wandb_setup.setup()
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 320, in setup
    ret = _setup(settings=settings)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 315, in _setup
    wl = _WandbSetup(settings=settings)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 301, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 108, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 138, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1426, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 151, in setup
    self._wl = wandb_setup.setup()
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 320, in setup
    ret = _setup(settings=settings)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 315, in _setup
    wl = _WandbSetup(settings=settings)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 301, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 108, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 138, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1426, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/seq2seq_t2i/tasks/coco/run_gpt.py", line 876, in <module>
    main(args)
  File "src/seq2seq_t2i/tasks/coco/run_gpt.py", line 780, in main
    wandb_logger = WandbLogger(
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 311, in __init__
    _ = self.experiment
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 41, in experiment
    return get_experiment() or DummyExperiment()
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 39, in get_experiment
    return fn(self)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 357, in experiment
    self._experiment = wandb.init(**self._wandb_init)
  File "/playpen/home/jmincho/miniconda3/envs/t2i/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1081, in init
    raise Exception("problem") from error_seen
Exception: problem
```

**Comment by vanpelt** [comment]
@j-min sorry about that, as feared this is a part of the code that isn't respecting that setting.  The following should fix the issue.

```
settings = wandb.Settings(program_relpath="src/seq2seq_t2i/tasks/coco/run_gpt.py")
wandb.init(project="XXX", settings=settings)
```
Let me know if that doesn't work.

**Comment by j-min** [comment]
I added `settings` argument into wandb.init, but it did not help. I created a fresh conda environment with python3.8 and installed wandb via pip. The below script can reproduce the same error.

```python3
import wandb
wandb.init()
# or 
# wandb.init(settings = wandb.Settings(program_relpath="./" (or whatever path)))
```

**Comment by vanpelt** [comment]
Is it the same stacktrace?  It should attempt to use git of `program_relpath` is set.  Can you try the following and share the stack trace again.  

```
import wandb
wandb.init(settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True))
```

The other near term fix is for you to fix your git repo.  Instructions for removing an invalid module [are here](https://gist.github.com/myusuf3/7f645819ded92bda6677).

**Comment by j-min** [comment]
Error still persists. Below is the error log. There is `run_gpt.py` in the current directory.

```bash
╰─ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init(settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True))
wandb: Currently logged in as: j-min. Use `wandb login --relogin` to force relogin
Thread SenderThread:
Traceback (most recent call last):
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 304, in send
    send_handler(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 750, in send_run
    run.project = util.auto_project_name(self._settings.program)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/util.py", line 1307, in auto_project_name
    root_dir = wandb.wandb_sdk.lib.git.GitRepo().root_dir
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/lib/git.py", line 143, in root_dir
    return self.repo.git.rev_parse("--show-toplevel")
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'
```

**Comment by vanpelt** [comment]
Yep, this is because you're not setting the project name.  I'm working on a branch that will fix all of these issues in the future, but for now just set `project`:

```
wandb.init(project="gpt-seq2seq", settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True))
```

**Comment by j-min** [comment]
Thanks. Btw I face the same error even with the `project` argument.
```bash
╰─ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init(project="gpt-seq2seq", settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True))
wandb: Currently logged in as: j-min. Use `wandb login --relogin` to force relogin
Thread HandlerThread:
Traceback (most recent call last):
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 265, in _process
    self._hm.handle(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 133, in handle
    handler(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 143, in handle_request
    handler(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 676, in handle_request_run_start
    run_meta.probe()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 248, in probe
    self._save_code()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 93, in _save_code
    root: str = self._git.root or os.getcwd()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'
```

**Comment by vanpelt** [comment]
Brutal, that's a different error.  The following should work once and for all 🙃 

```
wandb.init(project="gpt-seq2seq", settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True, disable_code=True))
```

**Comment by j-min** [comment]
Sorry, adding `disable_code=True` didn't work either.

```bash
╰─ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init(project="gpt-seq2seq", settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True, disable_code=True))
wandb: Currently logged in as: j-min. Use `wandb login --relogin` to force relogin
Thread HandlerThread:
Traceback (most recent call last):
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 265, in _process
    self._hm.handle(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 133, in handle
    handler(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 143, in handle_request
    handler(record)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 676, in handle_request_run_start
    run_meta.probe()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 248, in probe
    self._save_code()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 93, in _save_code
    root: str = self._git.root or os.getcwd()
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/playpen-ssd/jmincho/anaconda3/envs/wandb_test/lib/python3.8/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: not a git repository: /../../.git/modules/PACKAGES/HOSTFIX'
```

**Comment by j-min** [comment]
The error comes from whether wandb can handle the error from command `git rev-parse --show-toplevel`. It outputs error as below.

```bash
╰─ git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by vanpelt** [comment]
Sorry @j-min I gave you the wrong setting before.  The branch I've opend above will fix this once and for all, but the following should work.  5th times a charm?  🤞 

```
wandb.init(project="gpt-seq2seq", settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True, save_code=False))
```

**Comment by j-min** [comment]
Oh, finally `save_code=False` worked! Thanks a lot! @vanpelt 
```bash
╰─ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init(project="gpt-seq2seq", settings=wandb.Settings(program_relpath="run_gpt.py", disable_git=True, save_code=False))
wandb: Currently logged in as: j-min. Use `wandb login --relogin` to force relogin
...
<wandb.sdk.wandb_run.Run object at 0x7f1b408c7f70>
```

**Comment by vanpelt** [comment]
Thank you for your infinite patience!  The next release of wandb will gracefully handle invalid git repo's so you won't need to modify all these settings.  Should be out in early September 🥳 .

**Comment by nick-maykr** [comment]
Any progress here?
On one of the cloud machines when running the hp search I get this warning at every evaluation, which is annoying:

`fatal: not a git repository (or any of the parent directories): .git`

**Comment by ggilley** [comment]
In case anyone is keeping score, it's still happening:

fatal: not a git repository (or any of the parent directories): .git
