### ISSUE TITLE
Can't do two simultaneous wandb runs

### ISSUE THREAD

**Issue by abearman** [wandb/client#165]
* Weights and Biases version: 0.5.8
* Python version: 2.7.5
* Operating System: Ubuntu 16.04

### Description

I tried to run two separate wandb runs, each on one GPU, on the same box. The second one crashed. I expected them both to run independently.

### What I Did

Command:
```
wandb run train_imagenet_model.py --num_gpus=1 --available_gpus=2 --model_json_file=../quantization/experiments/resnet50_hwgq/adjusted/weights_resnet_ap1000_b6_wp1000.json  --model_weights_file=../quantization/experiments/resnet50_hwgq/adjusted/weights_resnet_ap1000_b6_wp1000.h5 --save_models_dir=model_weights/resnet-6b/adjusted/ —saved_model_weights=model_weights/resnet-6b/adjusted/weights.01-3.85.hdf5
```

Stack trace:
```
Traceback (most recent call last):
  File "/usr/bin/wandb", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/wandb/cli.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/wandb/cli.py", line 63, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/wandb/cli.py", line 571, in run
    rm.run_user_process(program, args, env)
  File "/usr/lib/python2.7/site-packages/wandb/run_manager.py", line 399, in run_user_process
    os.getpid()).cmdline()) + "\n\n")
  File "/usr/lib/python2.7/site-packages/wandb/streaming_log.py", line 93, in write_string
    return self.write(message.encode('utf-8'), cur_time)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 352: ordinal not in range(128)
```

**Comment by abearman** [comment]
Sorry, I realized that one of my arguments `--` got autocorrected to a long dash, which is why it was throwing the ASCII error. This is unrelated to multiple wandb runs.

**Comment by lukas** [comment]
We could probably give a more helpful error message here.
