### ISSUE TITLE
Network error connecting to api.wandb.ai:443 during login

### ISSUE THREAD

**Issue by jwallat** [wandb/client#1672]
**Describe the bug**
I am using PyTorch-Lightning and I am running multiple wandb runs on a cluster. Everything works fine for the first one or two jobs that I start. However, for later jobs, I get an HTTPS error when wandb connects to `api.wandb.ai:443`. I remember this working just fine a couple of months back. 

Please find the stack trace from the debug-internal.log below: 
```
2021-01-07 11:17:42,047 INFO    MainThread:1720344 [internal.py:wandb_internal():63] W&B internal server running at pid: 1720344
2021-01-07 11:17:42,050 DEBUG   HandlerThread:1720344 [handler.py:handle_request():55] handle_request: check_version
2021-01-07 11:17:42,050 INFO    WriterThread:1720344 [datastore.py:open_for_write():76] open: /home/wallat/knowledge-probing/data/outputs/t5_tests/t5_small_layer_11_t5-small_trained-True_random_7_1_2021__12-17/wandb/run-20210107_111741-3uyq01gf/run-3uyq01gf.wandb
2021-01-07 11:17:42,054 DEBUG   SenderThread:1720344 [sender.py:send():90] send: header
2021-01-07 11:17:42,054 DEBUG   SenderThread:1720344 [sender.py:send():90] send: request
2021-01-07 11:17:42,054 DEBUG   SenderThread:1720344 [sender.py:send_request():99] send_request: check_version
2021-01-07 11:17:42,058 DEBUG   Thread-4  :1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): pypi.org:443
2021-01-07 11:17:42,061 DEBUG   SenderThread:1720344 [sender.py:send():90] send: run
2021-01-07 11:17:42,066 INFO    SenderThread:1720344 [sender.py:_maybe_setup_resume():281] checking resume status for None/probing-t5/3uyq01gf
2021-01-07 11:17:42,071 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:17:43,219 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:17:45,353 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:17:45,354 ERROR   SenderThread:1720344 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14f9fe746fd0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9fe746fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/wallat/miniconda3/envs/knowledge-probing/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f9fe746fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2021-01-07 11:17:49,427 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:17:58,000 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:18:12,061 DEBUG   HandlerThread:1720344 [handler.py:handle_request():55] handle_request: shutdown
2021-01-07 11:18:12,062 INFO    HandlerThread:1720344 [handler.py:finish():271] shutting down handler
2021-01-07 11:18:12,066 INFO    WriterThread:1720344 [datastore.py:close():257] close: /home/wallat/knowledge-probing/data/outputs/t5_tests/t5_small_layer_11_t5-small_trained-True_random_7_1_2021__12-17/wandb/run-20210107_111741-3uyq01gf/run-3uyq01gf.wandb
2021-01-07 11:18:17,370 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:18:51,135 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-07 11:19:58,047 DEBUG   SenderThread:1720344 [connectionpool.py:_new_conn():941] Starting new HTTPS connection (1): api.wandb.ai:443
```
Has anyone seen a similar error or can explain why it sometimes works and sometimes fails? 
I am thankful for all pointers.

**Operating System**
`wandb --version && python --version && uname`
wandb, version 0.10.12
Python 3.7.7
Linux

**Comment by vanpelt** [comment]
Hmmm, the `Name or service not known` error indicates that our library couldn't reach your DNS server to determine what IP address to connect to.  Do you have any non-standard DNS configuration that you're aware of?  Can you make this happen consistently?

**Comment by jwallat** [comment]
Did not change anything but it works today... So it does not seem to be related to wandb but my side (network/server configuration/maintenance/whatever). Thanks for your answer, though! :+1:
