### ISSUE TITLE
ValueError: I/O operation on closed file using Pytest

### ISSUE THREAD

**Issue by ignacioct** [wandb/client#1686]
**Describe the bug**
While discovering Python tests using pytest, I get the following error trace:
```
Test Discovery failed: 
Error: --- Logging error ---
Traceback (most recent call last):
  File "/home/ignacio/anaconda3/envs/recognai/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
  File "/home/ignacio/anaconda3/envs/recognai/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/home/ignacio/anaconda3/envs/recognai/lib/python3.6/site-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/home/ignacio/anaconda3/envs/recognai/lib/python3.6/site-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/home/ignacio/anaconda3/envs/recognai/lib/python3.6/site-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
ValueError: I/O operation on closed file.
Call stack:
  File "/home/ignacio/anaconda3/envs/recognai/lib/python3.6/site-packages/wandb/sdk/internal/internal.py", line 138, in handle_exit
    logger.info("Internal process exited")
Message: 'Internal process exited'
Arguments: ()
```

**To Reproduce**
I don know if it can be reproduced or it is just me, but I created a pytest file. The test is very simple and doesn't involve wandb.

**Expected behavior**
Test discovery should be made correctly

**Operating System**
 - OS: Ubuntu 20.04
 - Python 3.6.12
 - WandB  0.10.12

**Comment by vanpelt** [comment]
When you're running tests you should set `WANDB_MODE=disabled` this will prevent wandb from attempting to capture stdout / stderr. and from creating runs in your account.

**Comment by ignacioct** [comment]
> When you're running tests you should set `WANDB_MODE=disabled` this will prevent wandb from attempting to capture stdout / stderr. and from creating runs in your account.

Do you know where can I find that option? Or i just set that variable to disabled at the beggining of my test file?

**Comment by vanpelt** [comment]
You can set it in your environment, or you can pass the `mode` keyword argument to wandb.init.  i.e.

```
import os
os.environ["WANDB_MODE"] = "disabled"

# or
wandb.init(mode="disabled")
```

**Comment by ignacioct** [comment]
Thank you so much
