### ISSUE TITLE
Cannot import wandb after importing attributedict 

### ISSUE THREAD

**Issue by borundev** [wandb/client#1690]
**Describe the bug**

If one imports wandb *after* import attributedict there is an error. However, this doesn't happen always. I do not yet know why it doesn't happen when it doesn't, but below I give a Dockerfile that will reproduce the error

**To Reproduce**
1. Create a Dockerile
```Dockerfile
FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y python3 python3-pip

RUN pip3 install attributedict==0.3.0
RUN pip3 install wandb==0.10.13

RUN useradd -m -s /bin/bash feynman
USER feynman
WORKDIR /home/feynman

RUN echo "import wandb;print('imported wandb');import attributedict;print('imported attributedict')" > non-buggy.py
RUN echo "import attributedict;print('imported attributedict');import wandb;print('imported wandb')" > buggy.py
CMD /bin/bash
```
2. Build the dockerfile `docker build . -t wandb_bug`
3. Run a container `docker run -it wandb_bug`
4. In the container run `python3 non-buggy.py` to see that there is no bug if wandb is imported before attributedict
5. Now run `python3 buggy.py` to see the following bug
```feynman@e5fb9cee4fb0:~$ python buggy.py 
imported attributedict
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/pkgutil.py", line 416, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feynman/buggy.py", line 1, in <module>
    import attributedict;print('imported attributedict');import wandb;print('imported wandb')
  File "/usr/local/lib/python3.9/site-packages/wandb/__init__.py", line 38, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/__init__.py", line 12, in <module>
    from .wandb_init import init  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 30, in <module>
    from .backend.backend import Backend
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 16, in <module>
    from ..internal.internal import wandb_internal
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 33, in <module>
    from . import sender
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 15, in <module>
    from pkg_resources import parse_version
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1961, in find_distributions
    importer = get_importer(path_item)
  File "/usr/local/lib/python3.9/pkgutil.py", line 420, in get_importer
    importer = path_hook(path_item)
  File "<frozen zipimport>", line 66, in __init__
  File "/usr/local/lib/python3.9/os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Expected behavior**
Wandb import before or after attributedict import should give the same behavior and in particular should not give an error.

**Operating System**
 I have tried this on various flavors of Ubuntu and its always there. The Dockerfile captures all the state info in any case.

**Additional context**

There is one curious feature which I cannot give details for reproducing. If I mount my home directory onto the container and run the script from there then there is no error. I show this in the video. Obviously I cannot share contents of my home directory and therefore this is not reproducible but it is curious to see that while the bug is there on a fresh install, it is not there when the script is being launched from my home directory where presumably some wandb files already exist and are interacting with wandb when it initializes.

https://user-images.githubusercontent.com/8229727/104322426-406c1080-54e5-11eb-9a51-ecd68fbe9bab.mov

**Comment by tyomhak** [comment]
Hey @borundev , thank you for reporting the issue. We're looking into it.

**Comment by borundev** [comment]
@tyomhak anyone working on this? This is a really annoying bug and blocking bug.

**Comment by borundev** [comment]
Actually I figured out the problem. It is not with wandb but with attributedict via rootpath. I have made a [pull request with the bug fix] (https://github.com/grimen/python-rootpath/pull/8).
