### ISSUE TITLE
Sweep python agent hangs on Google Colab

### ISSUE THREAD

**Issue by michalmisiewicz** [wandb/client#1693]
Sweep Python agent hangs on `wandb.init()` with following warning:
```
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:55: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
```

debug.log:
```
2021-01-12 21:10:45,752 INFO    Thread-17 :59 [wandb_setup.py:_flush():70] setting env: {'project': 'multimodal', 'entity': 'mm_magisterka', 'root_dir': '/content/deep-learning-video-recommendation', 'sweep_id': '8zwu6pqm', 'run_id': 'aenujn0n', 'config_paths': '/content/deep-learning-video-recommendation/wandb/sweep-8zwu6pqm/config-aenujn0n.yaml'}
2021-01-12 21:10:45,753 INFO    Thread-17 :59 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-12 21:10:45,753 INFO    Thread-17 :59 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-12 21:10:45,753 INFO    Thread-17 :59 [wandb_init.py:_log_setup():303] Logging user logs to /content/deep-learning-video-recommendation/wandb/run-20210112_211045-aenujn0n/logs/debug.log
2021-01-12 21:10:45,753 INFO    Thread-17 :59 [wandb_init.py:_log_setup():304] Logging internal logs to /content/deep-learning-video-recommendation/wandb/run-20210112_211045-aenujn0n/logs/debug-internal.log
2021-01-12 21:11:20,901 ERROR   Thread-17 :59 [wandb_init.py:init():601] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 411, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 542, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 533, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 447, in _communicate
    return future.get(timeout)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 63, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
Exception
```
Previously the same code was working. Are you facing some issues ?

**Comment by michalmisiewicz** [comment]
Similar to #1409

**Comment by vanpelt** [comment]
Hey @michalmisiewicz can you share a colab that reproduces this?

**Comment by michalmisiewicz** [comment]
The same code is working today.

**Comment by ariG23498** [comment]
Hey @michalmisiewicz Would it be okay to close the issue as the problem has resolved? :smile:

**Comment by michalmisiewicz** [comment]
Sure

**Comment by w4zir** [comment]
I am getting this error on you example code 
https://colab.research.google.com/github/wandb/examples/blob/master/colabs/intro/Intro_to_Weights_%26_Biases.ipynb#scrollTo=-VE3MabfZAcx

**Comment by ariG23498** [comment]
Hey @w4zir 
I do not get any issue while running the colab

Could you send us a screenshot of what you are seeing right now? Thanks!

**Comment by w4zir** [comment]
Working fine now. Ty
