### ISSUE TITLE
Emojis still show on AWS even if it's turn off: UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)

### ISSUE THREAD

**Issue by alexiej** [wandb/client#1723]
**Describe the bug**
When I init the second time project:

```
wandb.init(
                project=project_name, name=name, config=config, tags=tags,
                settings=wandb.Settings(show_emoji=False)
            )
````

The output show the emoji "star" from the code, but on the AWS server this shows below error. I try turn off the emoji by settings but still got the error.

https://github.com/wandb/client/blob/613af063b55f7706a3ecb9ce3f622684b4d9f78f/wandb/sdk/wandb_run.py#L1227
```
  wandb.termlog(
      "{} View project at {}".format(
          emojis.get("star", ""),
          click.style(project_url, underline=True, fg="blue"),
      )
  )
```

```
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 443, in init
    run._on_start()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1272, in _on_start
    self._display_run()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1080, in _display_run
    click.style(project_url, underline=True, fg="blue"),
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/wandb/errors/term.py", line 41, in termlog
    silent=not _show_info,
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/wandb/errors/term.py", line 94, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/click/utils.py", line 272, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)
wandb: ERROR Abnormal program exit
```

**To Reproduce**
AWS login

**Expected behavior**
No errors

**Comment by tyomhak** [comment]
Hey @alexiej , thanks for reporting. We're looking into this.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
