### ISSUE TITLE
Can't download artifact from colab and another google cloud vm

### ISSUE THREAD

**Issue by blizda** [wandb/client#1726]
I trying to donload artifct from W&B inside colab and google cloud vm, and get error 

```
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

From web ui, artifact donloading normally, from my local pc - too

colab  notebook to reprodusing: https://colab.research.google.com/drive/1WPXkW5pmCDDQ_YCc6hwaZmPmpZJcaonv?usp=sharing

full stacktrace

```
wandb: Downloading large artifact T5_model_tasks:v0, 1145.17MB. 1 files... Traceback (most recent call last):
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svintus05/.local/lib/python3.8/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/svintus05/.local/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvld.py", line 8, in <module>
    get_model_from_w_b_without_run()
  File "dvld.py", line 6, in get_model_from_w_b_without_run
    artifact.download()
  File "/home/svintus05/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 2763, in download
    pool.map(partial(self._download_file, root=dirpath), manifest.entries)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/svintus05/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 2801, in _download_file
    return self.get_path(name).download(root)
  File "/home/svintus05/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 2671, in download
    cache_path = storage_policy.load_file(
  File "/home/svintus05/.local/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 485, in load_file
    for data in response.iter_content(chunk_size=16 * 1024):
  File "/home/svintus05/.local/lib/python3.8/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by annirudh** [comment]
Hi @blizda, we just pushed a change that makes the downloads go directly through GCS so you shouldn't experience download failures. Could you confirm whether your downloads work now?

**Comment by blizda** [comment]
> Hi @blizda, we just pushed a change that makes the downloads go directly through GCS so you shouldn't experience download failures. Could you confirm whether your downloads work now?

Yes, now downloading works normally, thanks
