### ISSUE TITLE
Sweeps are unable to change values from config-defaults.yaml with allow_val_change=True in wandb.init()

### ISSUE THREAD

**Issue by bashkanov** [wandb/client#1737]
**Describe the bug**
Unable to start the sweep when using local config file `config-defaults.yaml` containing some default parameters.

My issue is related to this one [#1159](https://github.com/wandb/client/issues/1159). With default parameters as dictionary passed to it works well `wandb.init()`, but when I use local config file in the root of the project `config-defaults.yaml` and the option `allow_val_change=True` in `wandb.init()` I get the following error:
``` python
Problem at: train.py 13 <module>
Traceback (most recent call last):
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 379, in init
    run = Run(config=config, settings=s)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 251, in __init__
    self._config._update(config)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 152, in _update
    sanitized = self._sanitize_dict(parsed_dict, allow_val_change)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 198, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 218, in _sanitize
    ).format(key, self._items[key], val)
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "filter_size" from 0.5 to 6
If you really want to do this, pass allow_val_change=True to config.update()
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 379, in init
    run = Run(config=config, settings=s)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 251, in __init__
    self._config._update(config)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 152, in _update
    sanitized = self._sanitize_dict(parsed_dict, allow_val_change)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 198, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 218, in _sanitize
    ).format(key, self._items[key], val)
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "filter_size" from 0.5 to 6
If you really want to do this, pass allow_val_change=True to config.update()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    wandb.init(project="xxx", entity="xxx", allow_val_change=True,)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 612, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```
**To Reproduce use a modified minimum example from: [#1159](https://github.com/wandb/client/issues/1159).**

#### Train.py
```python
import wandb

# defaults = dict(seed=42, filter_size=3)
# wandb.init(entity="xxx", allow_val_change=True, project="xxx",config=defaults)

wandb.init(entity="xxx", allow_val_change=True, project="xxx")
print('\n\nHyperparams:')
print(wandb.config)
print('\n\n')
log = 2*wandb.config["filter_size"] - 0.01*wandb.config["seed"]
wandb.log({"output":log})
wandb.finish()
```

#### Sweep.yml
```yml
project: xxx
entity: xxx
program: train.py
method: bayes
metric:
  goal: minimize
  name: output
parameters:
  seed:
    distribution: int_uniform
    max: 100
    min: 42
  filter_size:
    distribution: int_uniform
    max: 7
    min: 3
```

#### config-defaults.yml
```yml
seed:
  value: 42
filter_size:
  value: 0.5
```

```
1. activate your env
2. wandb sweep sweep.yaml
3. start an agent
```

**Versions:**
 - Ubuntu 20.04
 - wandb0.10.12 and wandb0.10.14
 - python3.6.9

**Comment by tyomhak** [comment]
Hey @bashkanov , thanks for reporting this. Can you please check if the issue persists for you in the latest wandb version (0.10.15)?

**Comment by bashkanov** [comment]
Hi. Yes, I can confirm that with in version (0.10.15) the problem still persists.
Here are some logs:
``` python
user@host:~/reproduce-wandb$ wandb --version
wandb, version 0.10.15
user@host:~/reproduce-wandb$ wandb agent agent_id
wandb: Starting wandb agent 🕵️
2021-01-26 09:41:35,633 - wandb.wandb_agent - INFO - Running runs: []
2021-01-26 09:41:35,933 - wandb.wandb_agent - INFO - Agent received command: run
2021-01-26 09:41:35,933 - wandb.wandb_agent - INFO - Agent starting run with config:
	filter_size: 7
	seed: 46
2021-01-26 09:41:35,934 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python train.py --filter_size=7 --seed=46
wandb: Currently logged in as: bashkanov (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
Problem at: train.py 13 <module>
Traceback (most recent call last):
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    run = wi.init()
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 401, in init
    run = Run(config=config, settings=s, sweep_config=sweep_config)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 311, in __init__
    self._config.update_locked(sweep_config, user="sweep")
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 200, in update_locked
    k, v = self._sanitize(k, v)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 238, in _sanitize
    ).format(key, self._items[key], val)
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "filter_size" from 0.5 to 7
If you really want to do this, pass allow_val_change=True to config.update()
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    run = wi.init()
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 401, in init
    run = Run(config=config, settings=s, sweep_config=sweep_config)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 311, in __init__
    self._config.update_locked(sweep_config, user="sweep")
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 200, in update_locked
    k, v = self._sanitize(k, v)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_config.py", line 238, in _sanitize
    ).format(key, self._items[key], val)
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "filter_size" from 0.5 to 7
If you really want to do this, pass allow_val_change=True to config.update()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    wandb.init(project="xxx", entity="xxx", allow_val_change=True,)
  File "/path/to/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 726, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
2021-01-26 09:41:40,947 - wandb.wandb_agent - INFO - Running runs: ['p3stvvlu']
^Cwandb: Ctrl-c pressed. Waiting for runs to end. Press ctrl-c again to terminate them.
^Cwandb: Terminating and syncing runs. Press ctrl-c to kill.
```

**Comment by tyomhak** [comment]
Thanks! we're looking into this issue.

**Comment by raubitsj** [comment]
@bashkanov
Thanks for finding this.  We have been working to simplify how config values are set and missed the case of using config-defaults.yaml with sweeps.

We have a fix that is staged for the next release.  You can try it early with:

```
pip install --upgrade git+git://github.com/wandb/client.git@fix/issue-1737
```

**Comment by bashkanov** [comment]
Thanks. It works well now!

**Comment by datduong** [comment]
Was this fix been released in the version 0.12.10? I am seeing the same issue in my code. Thanks.

**Comment by aidanjdonohue** [comment]
Hi @datduong , can you share the error message you're getting?

**Comment by aidanjdonohue** [comment]
@datduong bumping this thread

**Comment by marxav** [comment]
The weird thing is that I have this same wandb problem in a .py file, but that it works well in a Jupyter .ipynb file.

**Comment by RuihanGao** [comment]
> @bashkanov Thanks for finding this. We have been working to simplify how config values are set and missed the case of using config-defaults.yaml with sweeps.
> 
> We have a fix that is staged for the next release. You can try it early with:
> 
> ```
> pip install --upgrade git+git://github.com/wandb/client.git@fix/issue-1737
> ```

I tried this method but received the following error
```
  Running command git clone --filter=blob:none --quiet git://github.com/wandb/client.git /tmp/pip-req-build-1oumkf83    
  WARNING: Did not find branch or tag 'fix/issue-1737', assuming revision or ref.                                       
  Running command git checkout -q fix/issue-1737                                                                        
  error: pathspec 'fix/issue-1737' did not match any file(s) known to git                                               
  error: subprocess-exited-with-error    

```

**Comment by nanowhiter** [comment]
> @bashkanov Thanks for finding this. We have been working to simplify how config values are set and missed the case of using config-defaults.yaml with sweeps.
> 
> We have a fix that is staged for the next release. You can try it early with:
> 
> ```
> pip install --upgrade git+git://github.com/wandb/client.git@fix/issue-1737
> ```

I tried this method but received the following error. Any tip would be appreciated
```

  Running command git clone --filter=blob:none --quiet git://github.com/wandb/client.git /tmp/pip-req-build-1oumkf83    
  WARNING: Did not find branch or tag 'fix/issue-1737', assuming revision or ref.                                       
  Running command git checkout -q fix/issue-1737                                                                        
  error: pathspec 'fix/issue-1737' did not match any file(s) known to git                                               
  error: subprocess-exited-with-error    
```
