### ISSUE TITLE
Can't log in "module" object is not callable

### ISSUE THREAD

**Issue by lucastononrodrigues** [wandb/client#1743]
How do I solve this problem?

Apparently, every time I try to log in it won't work for any reason whatsoever.

I could actually turn this around by just launching the code normally and then the API will ask me to log in.

When I logged in to my virtual machine it worked just fine (no type error), the only difference is that in my PC I'm using anaconda prompt as terminal.

But I need to fix this in my cpu because my sweeps will not work if I don't (I get the same error when I run a sweep).

```
wandb login (my id hidden)
Traceback (most recent call last):
  File "C:\Users\lucas\anaconda3\envs\tcc\Scripts\wandb-script.py", line 9, in <module>
    sys.exit(cli())
TypeError: 'module' object is not callable
```

After uninstalling conda wandb and installing only pip install --upgrade wandb I get:

```
Traceback (most recent call last):
  File "c:\users\lucas\anaconda3\envs\tcc\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lucas\anaconda3\envs\tcc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lucas\anaconda3\envs\tcc\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "c:\users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\__init__.py", line 38, in <module>
    from wandb import sdk as wandb_sdk
  File "c:\users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\__init__.py", line 12, in <module>
    from .wandb_init import init  # noqa: F401
  File "c:\users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from .backend.backend import Backend
  File "c:\users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\backend\backend.py", line 15, in <module>
    from ..interface import interface
  File "c:\users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\sdk\interface\interface.py", line 18, in <module>
    from wandb.proto import wandb_internal_pb2  # type: ignore
  File "c:\users\lucas\anaconda3\envs\tcc\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'

```
After installing protobuf from conda it worked, although I can conclude that conda install won't work for wandb?

**Comment by vanpelt** [comment]
@lucastononrodrigues we don't publish our library in conda currently.  We're working with conda to get the current `wandb` package that's in conda removed, it's not something we authored.  Is everything working for you now?

**Comment by lucastononrodrigues** [comment]
> @lucastononrodrigues we don't publish our library in conda currently. We're working with conda to get the current `wandb` package that's in conda removed, it's not something we authored. Is everything working for you now?

Yes. Thank you.
