### ISSUE TITLE
[CLI] init fails

### ISSUE THREAD

**Issue by davidsvaughn** [wandb/client#1754]
`wandb --version && python --version && uname`
wandb, version 0.10.15
Python 3.8.7
Linux

**Description**
Just trying to simply run wandb.init().  
I created account and copied API_KEY.
I install wandb and login from shell:
```
pip install --upgrade wandb
wandb login <API_KEY>
```
Then run python script:
```
import wandb
wandb.init(project="test")
```
And I keep getting this error.  I've tried repeatedly deleting .netrc file.... does not help....
```
Traceback (most recent call last):
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 382, in viewer
    res = self.gql(query)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 131, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 41, in execute
    result = request.json()
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 331, in init
    viewer = api.viewer()
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/apis/internal.py", line 45, in viewer
    return self.api.viewer()
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 382, in viewer
    res = self.gql(query)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 131, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 41, in execute
    result = request.json()
  File "/home/david/code/repo/ai2/test/venv/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
wandb.errors.error.CommError: Expecting value: line 1 column 1 (char 0)
```

**Comment by vanpelt** [comment]
Can you share the tail of your `wandb/debug-internal.log`?  Have you ever logged that machine into a self-hosted instance of wandb?  If so, you could try `wandb login --cloud` to ensure it's communicating with our cloud servers instead of a potentially non-existent local server.

**Comment by davidsvaughn** [comment]
Thanks @vanpelt --  that solved it! 
In fact I _had_ logged into a self-hosted instance previously. 
`wandb login --cloud` resolved the error.

**Comment by lukas** [comment]
I also ran into this and I think we should reopen to give clearer guidance or ideally not force the user to call wandb login --cloud.
