### ISSUE TITLE
[CLI] Unable to import WandbCallback w/ Tf2.4

### ISSUE THREAD

**Issue by hv10** [wandb/client#1756]
**Description**
When using Tensorflow 2.4.0 the import of the keras WandbCallback results in the following error:
```
Traceback (most recent call last):
  File "minimal_fail.py", line 1, in <module>
    from wandb.keras import WandbCallback
  File "/home/nodanz/anaconda3/envs/py38tf24/lib/python3.8/site-packages/wandb/keras/__init__.py", line 8, in <module>
    from wandb.integration.keras import WandbCallback  # type: ignore
  File "/home/nodanz/anaconda3/envs/py38tf24/lib/python3.8/site-packages/wandb/integration/keras/__init__.py", line 5, in <module>
    from .keras import WandbCallback
  File "/home/nodanz/anaconda3/envs/py38tf24/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 168, in <module>
    patch_tf_keras()
  File "/home/nodanz/anaconda3/envs/py38tf24/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 53, in patch_tf_keras
    from tensorflow.python.keras.engine import training_arrays
  File "/home/nodanz/anaconda3/envs/py38tf24/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 594, in <module>
    class ArrayLikeTrainingLoop(training_utils.TrainingLoop):
AttributeError: module 'tensorflow.python.keras.engine.training_utils' has no attribute 'TrainingLoop'
```
The issue is most likely happening because in Tf2.4 the class `TrainingLoop` can be found in `tensorflow/tensorflow/python/keras/engine/training_utils_v1.py` instead. The issue is not present at Tf2.3 or Tf2.2 (I stopped testing here).

**Wandb features**
Nothing, planned on using the WandbCallback.

**How to reproduce**
Within an environment where `tensorflow==2.4` is present.
```python
from wandb.keras import WandbCallback
``` 

**Environment**
- OS: Ubuntu 16.04
- Environment: Commandline
- Python Version: 3.8.5

**Comment by hv10** [comment]
On closer inspection it seems that the origin of the error is within tensorflow, if that should be the case I will remove the Issue.

**Comment by hv10** [comment]
Issue was resolved by properly updating tensorflow. Sorry for the trouble.
