### ISSUE TITLE
wandb in DETR Pytorch StopIteration

### ISSUE THREAD

**Issue by lucastononrodrigues** [wandb/client#1778]
I am using the code from detr github https://github.com/facebookresearch/detr
When I use wandb I get StopIteration error for no reason whatsoever (It accuses the backbone for not working).

I set up the whole wandb init, config, watch and log.
By only removing the: wandb.watch(model_without_ddp) it works normally.

So my conclusion is that wandb.watch might be changing something inside the model? This is so weird.

Could that be because it actually sends the model to another code for training? (from main.py to engine.py -> train_one_epoch() )
If you would like to replicate the error, it would be too complicated (clone github+download coco dataset).

```

number of params: 41302880
loading annotations into memory...
Done (t=2.72s)
creating index...
index created!
loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
Start training
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    main(args)
  File "main.py", line 228, in main
    args.clip_max_norm)
  File "/home/projet21/PAr104/depr/depr-alpha/engine.py", line 32, in train_one_epoch
    outputs = model(samples)
  File "/home/projet21/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/projet21/PAr104/depr/depr-alpha/models/detr.py", line 62, in forward
    features, pos = self.backbone(samples)
  File "/home/projet21/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/projet21/PAr104/depr/depr-alpha/models/backbone.py", line 101, in forward
    xs = self[0](tensor_list)
  File "/home/projet21/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 738, in _call_impl
    var = next((v for v in var.values() if isinstance(v, torch.Tensor)))
StopIteration

wandb: Waiting for W&B process to finish, PID 19485
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb:
wandb: Find user logs for this run at: /home/projet21/PAr104/depr/depr-alpha/wandb/run-20210131_072740-16af2or9/logs/debug.log
wandb: Find internal logs for this run at: /home/projet21/PAr104/depr/depr-alpha/wandb/run-20210131_072740-16af2or9/logs/debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
```

**Comment by ariG23498** [comment]
Hey @lucastononrodrigues thanks for the ticket
We will be looking into this.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
