### ISSUE TITLE
[CLI] wandb not compatible with ipdb package

### ISSUE THREAD

**Issue by myaisv** [wandb/client#1815]
**Description**
It is known that ```import ipdb``` after ```import wandb``` will cause a "prompt_toolkit" error, and this has been disscused in #1498 

```import ipdb``` firstly and then  ```import wandb``` can be a temporary solution, but the ```print``` funcition in worker process will  cause  wandb to raise a exception.

**Wandb features**
auto collect the output of print funciton

**How to reproduce**
import ```ipdb``` first, and print something in worker procress (for example, the worker procress of pytorch's dataloader ), wandb will collection the output. But it seems  the `self._process` in `wandb/sdk/interface/interface.py` will be main procress, which will case a exception when calling `self._process.is_alive()`

```
import ipdb 
import torch
from torch.utils.data import DataLoader
import wandb
import os


def worker_init_fn(worker_id):
    print("hello form worker:" + str(worker_id))


class Dataset(torch.utils.data.Dataset):

    def __len__(self):
        return 3

    def __getitem__(self, index):
        return index


if __name__ == "__main__":
    os.environ["WANDB_BASE_URL"] = "http://8.111.143.241:8080"
    os.environ['WANDB_MODE'] = 'dryrun'
    wandb.login(key="local-501c6d83fce8b76bfde49287cf9d74d5399c1aa9")
    wandb.init(project="1", name="1.1")

    train_iter = DataLoader(Dataset(), num_workers=1, batch_size=1, worker_init_fn=worker_init_fn)
    for data in train_iter:
        pass

```
exception:

```
Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable
wandb: Offline run mode, not syncing to the cloud.
wandb: W&B is disabled in this directory.  Run `wandb on` to enable cloud syncing.
Traceback (most recent call last):
  File "38_wandb_issue.py", line 28, in <module>
    for data in train_iter:
  File "/home/my/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/my/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/my/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/my/.local/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/my/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 146, in _worker_loop
    init_fn(worker_id)
  File "38_wandb_issue.py", line 9, in worker_init_fn
    print("hello form worker:" + str(worker_id))
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 91, in new_write
    cb(name, data)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 598, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 146, in publish_output
    self._publish_output(o)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 151, in _publish_output
    self._publish(rec)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 431, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

```

**Environment**
- OS: [Ubuntu 20.04]
- Environment: [Python]
- Python Version: [Python 3.8.5 ]

**Comment by ariG23498** [comment]
Hey @myaisv 
Thanks for the ticket!
We will be looking into this.

**Comment by sydholl** [comment]
Hi @myaisv, this issue should have been fixed in Jun 2020. Please let us know if you're still experiencing issues.
