### ISSUE TITLE
wandb sweeps and agent bug

### ISSUE THREAD

**Issue by tulasiram58827** [wandb/client#1859]
**Configuration File Used**:

```
program: train.py
method: bayes

project: information_extraction

metric:
        name: test_pos_rec
        goal: maximize

parameters:
        learning_rate:
                min: 0.001
                max: 0.1
        emb_dim:
                min: 32
                max: 256
        attention_heads:
                min: 2
                max: 12
        max_neighbors:
                min: 15
                max: 50
```

After that I ran `wandb sweep sweep.yaml`

**Output**:

```
wandb: Creating sweep from: search.yaml
wandb: Created sweep with ID: m82su4as
```

After than I ran `wandb agent m2su4as`

This is the error 

```
400 response executing GraphQL.
{"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
wandb: ERROR Error while calling W&B API: name required for project query (<Response [400]>)
Traceback (most recent call last):
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 534, in sweep
    response = self.gql(
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/home/ram/anaconda3/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ram/anaconda3/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/ram/anaconda3/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
```

It seems some project name is missing but I already added project name in YAML file.

@ariG23498

**Comment by ariG23498** [comment]
Hey @tulasiram58827 
I tried reproducing your issue.
These are the steps that I followed 👇 
### train.py
```python
import wandb

# Set up your default hyperparameters before wandb.init
# so they get properly set in the sweep
hyperparameter_defaults = {
    'learning_rate':1,
    'emb_dim':32,
    'attention_heads':2,
    'max_neighbors':15
}

# Pass your defaults to wandb.init
wandb.init(config=hyperparameter_defaults)
config = wandb.config

# Log metrics inside your training loop
metrics = {'test_pos_rec': config["learning_rate"]*config["emb_dim"]+config["attention_heads"]/config["max_neighbors"]}
wandb.log(metrics)
```

### sweep.yaml
```python
program: train.py
method: bayes
project: information_extraction
entity: repro
metric:
  name: test_pos_rec
  goal: maximize
parameters:
  learning_rate:
    min: 0.001
    max: 0.1
  emb_dim:
    min: 32
    max: 256
  attention_heads:
    min: 2
    max: 12
  max_neighbors:
    min: 15
    max: 50
```
1. Providing the command `wandb sweep sweep.yaml` gives out the following console output
```bash
wandb: Created sweep with ID: 0dtitg6z
wandb: View sweep at: https://wandb.ai/repro/information_extraction/sweeps/0dtitg6z
wandb: Run sweep agent with: wandb agent repro/information_extraction/0dtitg6z
```
2. Copying the whole command from the output is a must. Here I copied the command `wandb agent repro/information_extraction/0dtitg6z` and tried running this.
3. The sweep works at it should

> Note: I have tried coming up with a basic example here to repro the ticket, the `train.py` has a very illogical expression that is logged 😓

**Comment by tulasiram58827** [comment]
Instead of copying the entire path I just used agent id. Thanks, @ariG23498 Problem solved.
