### ISSUE TITLE
Client quietly fails when backend isn't available

### ISSUE THREAD

**Issue by adrianbg** [wandb/client#186]
I tried running an example in headless mode against a local backend, except I didn't actually have the local backend running. The user script exited without an error:

```(wandb-3.6) adrian@MacBook-Pro:~/src/wandb-public-examples/keras-cnn-fashion$ ./train.py
Using TensorFlow backend.
/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
wandb: Syncing http://app.test/adrianbg/garbage/runs/hvkxps4u
wandb: Run directory: wandb/run-20180423_175946-hvkxps4u

(wandb-3.6) adrian@MacBook-Pro:~/src/wandb-public-examples/keras-cnn-fashion$```

Then, eventually,

```wandb network error (RetryError), entering retry loop. See wandb/debug.log for full traceback.```

It seems like either the user script should fail with an error, or it should let the user script run while it retries.

**Comment by adrianbg** [comment]
When I eventually did start my local services:

```
Traceback (most recent call last):
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/internal_cli.py", line 96, in <module>
    main()
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/internal_cli.py", line 88, in main
    headless(args)
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/internal_cli.py", line 37, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/run_manager.py", line 584, in wrap_existing_process
    self._sync_etc(headless=True)
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/run_manager.py", line 605, in _sync_etc
    res = self._socket.recv(2)
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/wandb_socket.py", line 107, in recv
    return bytearray(self.socket.recv(limit))
ConnectionResetError: [Errno 54] Connection reset by peer
```
