### ISSUE TITLE
[CLI] Runs end with: RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1862]
**Description**
This error happens after the end of the training script in about 50% of my runs. All files & artifacts seem to be uploaded correctly by that moment, but something goes wrong and wandb crashes.

```
...
wandb: Adding directory to artifact (D:\GK-Pattern-Data-Gen\nn_pred_210219-11-09-30)... Done. 0.7s

wandb: Waiting for W&B process to finish, PID 21616
wandb: Program ended successfully.
Thread WriterThread:
Traceback (most recent call last):
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\sdk\internal\internal_util.py", line 34, in run
    self._run()
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\sdk\internal\internal_util.py", line 61, in _run
    self._process(record)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\sdk\internal\internal.py", line 258, in _process
    self._wm.write(record)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\sdk\internal\writer.py", line 35, in write
    self._ds.write(record)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\sdk\internal\datastore.py", line 250, in write
    raw_size = obj.ByteSize()
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\python_message.py", line 1076, in ByteSize
    size += field_descriptor._sizer(field_value)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\encoder.py", line 308, in FieldSize
    l = value.ByteSize()
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\python_message.py", line 1076, in ByteSize
    size += field_descriptor._sizer(field_value)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\encoder.py", line 308, in FieldSize
    l = value.ByteSize()
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\python_message.py", line 1076, in ByteSize
    size += field_descriptor._sizer(field_value)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\encoder.py", line 302, in RepeatedFieldSize
    l = element.ByteSize()
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\python_message.py", line 1075, in ByteSize
    for field_descriptor, field_value in self.ListFields():
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\python_message.py", line 833, in ListFields
    all_fields = [item for item in self._fields.items() if _IsPresent(item)]
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\google\protobuf\internal\python_message.py", line 833, in <listcomp>
    all_fields = [item for item in self._fields.items() if _IsPresent(item)]
RuntimeError: dictionary changed size during iteration

```
 

**Wandb features**
I'm using run initialization, metrics logging (wandb.init(), wandb.log()), save files to run dir, upload artifacts. Some important points that could be related to the issue:
* I do not explicitly call to finish runs
* I create a lot of artifacts (versions)
* I have troubles with hard-drive memory sometimes (see #1193), but the memory was NOT exhausted the last time I got that crash. 
* The error is not stable: it sometimes happens and sometimes doesn't, on the same machine with similar run setups. 

**How to reproduce**
Unfortunately, I don't know what the error means, where it could be coming from, so I have trouble with creating minimum reproducible examples. I hope you could help me with that. Simple runs outside of my framework appear to work fine.

This is the last run the problem happened to: https://wandb.ai/maria_korosteleva/Garments-Reconstruction/runs/rrwdeiqo/overview?workspace=user-maria_korosteleva

**Environment**
- OS: Win 10
- Environment: (local) Anaconda 1.9.12
- Python Version: 3.8.5
- Editor (running in): VS Code 1.52.1
- wandb 10.12

**Comment by ariG23498** [comment]
Hey @maria-korosteleva 
Thanks for the ticket we will be looking at this one.
In the meantime could you also upgrade the version for `wandb` and check whether the issue persists?

**Comment by maria-korosteleva** [comment]
Hey @ariG23498 
Thank you for your consideration. I will upgrade and try, but this might take a while -- as I said, the issue is not stably reproducible =(

One more thing that I missed in the original post is that I run the core from within Visual Studio Code. Might be helpful. (I will update the above description)

**Comment by maria-korosteleva** [comment]
Reproduced for 0.10.20

**Comment by vanpelt** [comment]
Hey @maria-korosteleva this looks like an issue with the google protobuf library.  Can you try running `pip install --upgrade protobuf` and report back if you see this agin?

**Comment by maria-korosteleva** [comment]
I will try, thanks!

**Comment by adrnswanberg** [comment]
Hi Maria, can you confirm whether this worked for you?

**Comment by maria-korosteleva** [comment]
Hi @adrnswanberg
The problem has not reproduced for a while, so I hope it is resolved. The issue was unstable though, and I don't run as many experiments lately as I used to, so I'm not 100% sure

**Comment by maria-korosteleva** [comment]
I have not seen the problem for a long time, so I figure that it's resolved with the above-mentioned solution
