### ISSUE TITLE
[Q] How to correctly execute `!wandb agent SWEEP_ID` in Google Colab?

### ISSUE THREAD

**Issue by Hongbo-Miao** [wandb/client#1955]
Thanks for the awesome tool! I am trying to run Sweeps in Google Colab, however, I spent hours and cannot figure out how based on https://docs.wandb.ai/sweeps/python-api#initialize-a-sweep

I saw

> Using wandb.agent() with jupyter notebook environments can hang when using GPUs.
> There can be a bad interaction between wandb.agent() and jupyter environments due to how GPU/CUDA resources are initialized by frameworks.
> A temporary workaround (until we can fix these interactions) is to avoid using the python interface for running the agent. Instead, use the command line interface by setting the `program` key in the sweep configuration, and execute: `!wandb agent SWEEP_ID` in your notebook.

`program` is usually a file like "train.py", if I run it on my local machine, that will be helpful. However, all my codes are in Google Colab code blocks.

Anyway, I did set `program` in my sweep configuration. (This `SWEEP_ID` here is misleading, I assume it wants me run something like `wandb agent username/project/1v7q0bci`)

Now when I run `!wandb agent SWEEP_ID` in Google Colab, it shows error:

```
wandb: Starting wandb agent 🕵️
2021-03-15 00:12:48,387 - wandb.wandb_agent - INFO - Running runs: []
400 response executing GraphQL.
{"errors":[{"message":"ValueError: Couldn't find full","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: ValueError: Couldn't find full (<Response [400]>)
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1313, in agent_heartbeat
    timeout=60,
  File "/usr/local/lib/python3.7/dist-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/cli/cli.py", line 829, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/usr/local/lib/python3.7/dist-packages/wandb/wandb_agent.py", line 568, in agent
    count=count,
  File "/usr/local/lib/python3.7/dist-packages/wandb/wandb_agent.py", line 519, in run_agent
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wandb/wandb_agent.py", line 252, in run
    commands = self._api.agent_heartbeat(agent_id, {}, run_status)
  File "/usr/local/lib/python3.7/dist-packages/wandb/apis/internal.py", line 95, in agent_heartbeat
    return self.api.agent_heartbeat(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1317, in agent_heartbeat
    message = ast.literal_eval(e.args[0])["message"]
  File "/usr/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
             ^
SyntaxError: invalid syntax
```

Any suggestions? Thanks

**Comment by Hongbo-Miao** [comment]
After struggling hours, I found two things.

One is when I create Sweep Configuration, I imported previous runs by click the button "Configure prior runs", however, somehow I guess previous runs (some early run results do not have certain args which I am guessing cause this bug) cause my sweep failed to run which shows the error I got in the question. If I create a new sweep without previous runs, then it works well. (W&B team, please feel free to fix this issue or provide better error descriptions)

![image](https://user-images.githubusercontent.com/3375461/111090557-1bd6f800-856b-11eb-8645-ffb39aacfeff.png)

Second is I think currently there is no easy to run in Google Colab if all your codes are in code blocks due to

> Using wandb.agent() with jupyter notebook environments can hang when using GPUs.
> There can be a bad interaction between wandb.agent() and jupyter environments due to how GPU/CUDA resources are initialized by frameworks.
> A temporary workaround (until we can fix these interactions) is to avoid using the python interface for running the agent. Instead, use the command line interface by setting the program key in the sweep configuration, and execute: !wandb agent SWEEP_ID in your notebook.

So my workaround way is uploading my files in the Google Colab by 

![image](https://user-images.githubusercontent.com/3375461/111090780-de269f00-856b-11eb-8be2-cac52e0e6f26.png)

Then run

```
!wandb agent username/project/1v7q0bci
```

in a Google Colab code block, this time everything works. Hopefully it helps future people who meet the same issue.
