### ISSUE TITLE
TypeError for agentHeartbeat after a few runs in sweep

### ISSUE THREAD

**Issue by aliFrancis** [wandb/client#1989]
When I start my sweep, it works fine. I spawn a few agents and they do 2 or 3 runs each. Then, they all fail with the same error:

```
400 response executing GraphQL.
{"errors":[{"message":"TypeError: '\u003e' not supported between instances of 'str' and 'float'","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: TypeError: '>' not supported between instances of 'str' and 'float' (<Response [400]>)
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1308, in agent_heartbeat
    response = self.gql(
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ali/miniconda3/envs/TF2/bin/wandb", line 10, in <module>
    sys.exit(cli())
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/cli/cli.py", line 815, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/wandb_agent.py", line 562, in agent
    return run_agent(
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/wandb_agent.py", line 519, in run_agent
    agent.run()
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/wandb_agent.py", line 252, in run
    commands = self._api.agent_heartbeat(agent_id, {}, run_status)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/apis/internal.py", line 95, in agent_heartbeat
    return self.api.agent_heartbeat(*args, **kwargs)
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1319, in agent_heartbeat
    message = ast.literal_eval(e.args[0])["message"]
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/ali/miniconda3/envs/TF2/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
        ^
SyntaxError: invalid syntax
```

My sweep's yaml is as follows:

```
program: fit_sensei.py
project: SEnSeI
name: SEnSeI Architecture
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  batch_size:
    values: [32,128,512]
  learning_rate:
    values: [0.000033,0.0001,0.00033,0.001,0.0033,0.01]
  momentum:
    min: 0.7
    max: 0.99
  lr_decay:
    min: 0.0
    max: 0.2
  descriptor_block_depth:
    distribution: int_uniform
    min: 0
    max: 8
  descriptor_block_width:
    values: [8,32,128]
  descriptor_block_output:
    values: [8,32,128]
  permuted_block_depth:
    distribution: int_uniform
    min: 0
    max: 8
  permuted_block_width:
    values: [8,32,128]
  permuted_block_output:
    values: [8,32,128]
  concat_input_output:
    values: [true, false]
  combined_block_depth:
    distribution: int_uniform
    min: 0
    max: 8
  combined_block_width:
    values: [8,32,128]
  combined_block_output:
    values: [8,32,128]
  skips:
    values: [true, false]
  lasso:
    values: [true, false]
  pooling:
    values: ["mean", "sum", "max"]
```

As I say, the sweep does work for a few runs, and then all agents fail. If I try to restart them, they also fail with the same message, without starting a new run.

I'm using w&b with the keras callback.

Thanks,

Ali

**Comment by aliFrancis** [comment]
**Work around found:**

In my wandb.ai project page, I deleted some runs that had val_loss=infinity, and the agents then ran correctly.
