### ISSUE TITLE
[CLI] Disable wandb does not work in unittests

### ISSUE THREAD

**Issue by mjohenneken** [wandb/client#1991]
**Description**
I try to disable `wandb.log()` when executing unittests. The unittests are executed via PyCharm in a Conda environment that are both located on C:. The codebase is located on D:. 

**Wandb features**

```
import unittest
import os
import wandb

class TestModelEvaluation(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        os.environ["WANDB_MODE"] = "disabled"
        wandb.init()
```
and this
```
wandb.init(settings=wandb.Settings(mode="disabled"))
wandb.log()
```
fails with the same error:

```
C:\ProgramData\Anaconda3\envs\ml\python.exe "C:\Program Files\JetBrains\PyCharm 2020.3.2\plugins\python\helpers\pycharm\_jb_unittest_runner.py" --path D:/workspace/thesis/raisinnet/raisinnet
Testing started at 17:55 ...
Launching unittests with arguments python -m unittest discover -s D:/workspace/thesis/raisinnet/raisinnet -t D:\workspace\thesis\raisinnet\raisinnet in D:\workspace\thesis\raisinnet\raisinnet

2021-03-22 17:55:37.508280: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
    wi.setup(kwargs)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_init.py", line 80, in setup
    self._wl = wandb_setup._setup()
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 242, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 231, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 92, in __init__
    self._settings_setup(settings, self._early_logger)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 118, in _settings_setup
    s._infer_run_settings_from_env(_logger=early_logger)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_settings.py", line 848, in _infer_run_settings_from_env
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_settings.py", line 141, in _get_program_relpath_from_gitrepo
    relative_path = os.path.relpath(full_path_to_program, start=root)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'

Failure
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
    wi.setup(kwargs)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_init.py", line 80, in setup
    self._wl = wandb_setup._setup()
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 242, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 231, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 92, in __init__
    self._settings_setup(settings, self._early_logger)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_setup.py", line 118, in _settings_setup
    s._infer_run_settings_from_env(_logger=early_logger)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_settings.py", line 848, in _infer_run_settings_from_env
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_settings.py", line 141, in _get_program_relpath_from_gitrepo
    relative_path = os.path.relpath(full_path_to_program, start=root)
  File "C:\ProgramData\Anaconda3\envs\ml\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ml\lib\unittest\suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "D:\workspace\thesis\raisinnet\raisinnet\test_create_report.py", line 25, in setUpClass
    wandb.init()
  File "C:\ProgramData\Anaconda3\envs\ml\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```
I would expect no error and being able to test code that contains wandb.log() class without side effects.

**How to reproduce**

Execute the code similar to this:
`C:\ProgramData\Anaconda3\envs\ml\python.exe "C:\Program Files\JetBrains\PyCharm 2020.3.2\plugins\python\helpers\pycharm\_jb_unittest_runner.py" --path D:/workspace/thesis/raisinnet/raisinnet`

**Environment**
OS: Windows-10-10.0.19041-SP0
Python version: 3.8.8
Environment: Anaconda

**Comment by vanpelt** [comment]
This is happening because you're running a program from a different drive.  We should handle this case, but until then you can just disable our code syncing by setting `os.environ["WANDB_DISABLE_CODE"]="true"`

**Comment by mjohenneken** [comment]
```
class TestModelEvaluation(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        os.environ["WANDB_DISABLE_CODE"] = "true"
        os.environ["WANDB_MODE"] = "disabled"
        wandb.init(settings=wandb.Settings(mode="disabled"))
```
I tried this but the same error occurs.

**Comment by mjohenneken** [comment]
My current workaround is to refactor wandb logging code out of unit-tested classes or setting flags.

```
if log_wandb:
    wandb.log({"foo":bar})
```

**Comment by vanpelt** [comment]
This specific error would be fixed if your anaconda environment was on the same drive as your code.  Looking closer at the code, I believe this would work for you:

```
wandb.init(settings=wandb.Settings(mode="disabled", program="test.py", program_relpath="test.py"))
```

**Comment by mjohenneken** [comment]
In [this line](https://github.com/wandb/client/blob/5759bab2d11d91ae4a545a85a92c2e9938ce9c11/wandb/sdk/wandb_settings.py#L154) full_path_to_program is `'C:\\Program Files\\JetBrains\\PyCharm 2020.3.2\\plugins\\python\\helpers\\pycharm\\_jb_unittest_runner.py'` and root `'D:/workspace/thesis/raisinnet'` which can can not be expressed relative to each other. I tested with and without setting `program` and `program_relpath` but they seem to have no effect on the method i linked to. It seems that the the settings from` wandb.init() `are not passed to `wandb_setup.setup(`) ([see here](https://github.com/wandb/client/blob/5759bab2d11d91ae4a545a85a92c2e9938ce9c11/wandb/sdk/wandb_init.py#L80))

The method currently assumes that the executing script is within the root of the project. Therefore the workaround only works if we call the test_file directly and then call `unittest.main()` and maybe if one would use a venv located in the project directory. 

In my case, I use the PyCharm IDE Unit testing tools but also calling the unittest package does not work (same error):

`D:\workspace\thesis\raisinnet>python -m unittest raisinnet.test_create_report`

Hope it helps!

**Comment by vanpelt** [comment]
@mjohenneken thanks max, and apologies for all this back and forth.  I just tested this locally and confirmed it works:

```
wandb.setup(wandb.Settings(program="test.py", program_relpath="test.py"))
```

Just be sure to call this before you call wandb.init when you're running tests and the error should go away.

**Comment by mjohenneken** [comment]
Ok, I can run the unit tests now. To prepare a test environment this setup method can be used:

```
import tempfile
import shutil

class TestModelEvaluation(unittest.TestCase):

    tempdir = None

    @classmethod
    def setUpClass(cls):
        cls.tempdir = tempfile.mkdtemp()
        print(f"Using temporary directory: {cls.tempdir}")
        wandb.setup(wandb.Settings(mode="disabled", program=__name__, program_relpath=__name__, disable_code=True))
        wandb.init(dir=cls.tempdir)

    #@classmethod
    #def tearDownClass(cls) -> None:
    #    wandb.finish()
    #    shutil.rmtree(cls.tempdir)

    ...
```

Although, log files will still be written. With this snippet, they are put into a temporary dir. I was not able to clean up afterward because the wandb process has still open file descriptors to the debug.log file even after calling `finish()`. For now, this can serve as a workaround because it's not much that is written to the file system.

**Comment by PawKanarek** [comment]
You can also patch whole wandb init method to disable logging. 
```python
@patch.object(wandb, wandb.init.__name__)
def test(self, mock_wandb_init):
    mock_wandb_init.return_value = MagicMock()
```
