### ISSUE TITLE
wandb.Image() doesn't accept 3d array

### ISSUE THREAD

**Issue by adrianbg** [wandb/client#202]
The generator in the Keras MNIST GAN example outputs numpy arrays with shape (<batch-size>, 28, 28, 1). If you try to log them in the most convenient way the `wandb.Image` constructor fails:

```
    wandb.log({'examples': [wandb.Image(i) for i in gen_imgs]})
```

```
Traceback (most recent call last):
  File "./train.py", line 245, in <module>
    main()
  File "./train.py", line 236, in main
    sample_images(generator)
  File "./train.py", line 187, in sample_images
    wandb.log({'examples': [wandb.Image(i) for i in gen_imgs]})
  File "./train.py", line 187, in <listcomp>
    wandb.log({'examples': [wandb.Image(i) for i in gen_imgs]})
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/media.py", line 31, in __init__
    self.to_uint8(data), mode=mode or self.guess_mode(data))
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/PIL/Image.py", line 2436, in fromarray
    raise ValueError("Too many dimensions: %d > %d." % (ndim, ndmax))
ValueError: Too many dimensions: 3 > 2.
```

**Comment by jjkindergarten** [comment]
hi, i met the same issue. do you know how to solve it?

thanks!
