### ISSUE TITLE
Exception uploading images

### ISSUE THREAD

**Issue by adrianbg** [wandb/client#203]
With the Keras MNIST GAN example:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/file_pusher.py", line 74, in _thread_body
    self._handle_event(event)
  File "/Users/adrian/src/wandb-core/frontends/client/wandb/file_pusher.py", line 91, in _handle_event
    self._jobs.pop(job.save_name)
KeyError: 'media/images/examples_9.jpg'
```

**Comment by adrianbg** [comment]
Fixed in @f8188e221b1be16896c2a070d425cf9a638de4c6
