### ISSUE TITLE
wandb.login() hangs and then disconnects me every time I try on Google Colab

### ISSUE THREAD

**Issue by codeananda** [wandb/client#2074]
**Description**
I've been using wandb and Google Colab successfully for the last couple of months. But over the last week, I have had so many connection issues. 

One thing that has been happening all morning (the last 4 hours) is that when I run this code block, Colab hangs, then disconnects, and cannot reconnect for several minutes.

```python
!pip install wandb -qqq
import wandb
from wandb.keras import WandbCallback
wandb.login()
```

It installs wandb and does both imports fine. But it hangs when it tries to do wandb.login().

Here's the [link](https://colab.research.google.com/drive/13FeVuT9UTPab_oj7xW3S1f6ZTfvkhddo?usp=sharing) but there isn't much to see since no error message comes up.

**Environment**
- Environment: Google Colab

**Comment by ariG23498** [comment]
Hey @theadammurphy 
Could you try doing `wandb.init(settings=wandb.Settings(start_method="thread"))` and report back?
We are aware of some issues with google colab, sorry for the inconvenience. I think the code above should bypass the hanging colab notebook.

**Comment by vanpelt** [comment]
We actually haven't seen this one before.  I'm not able to make it happen consistently.  For others that are coming to this issue, the brute force way to login colab without producing this hang is:`wandb.login(key="XXXXX")`.  Where key is your wandb API key from https://wandb.ai/authorize

It's important to do do this in it's own cell and not to save the notebook with your key in it to prevent other users viewing your notebook from having your credentials.

**Comment by theadammurphy** [comment]
@ariG23498 setting `wandb.init(settings=wandb.Settings(start_method="thread"))` didn't work because I was not logged in and so nothing happened. 

@vanpelt setting `wandb.login(key="XXXXX")` in its own cell seems to have worked! Thank you!

Out of interest, why does it have to be in its own cell?

**Comment by vanpelt** [comment]
It shouldn't actually need to be in it's own cell.  I'm still not sure why your notebook is hanging, as I can't get any other notebooks to hang.  My best guess is colab is literally looking for the word "bitcoin" in your notebook and trying to prevent users from using colab as a free mining platform.  We're still digging.

**Comment by theadammurphy** [comment]
Yeah it was working great for weeks and has suddenly just stopped. I may have gone over my usage limits... but I've been using it for ~8 hours/day 4 days/week and only for training DL models so I doubt it. 

Haha you know you may be onto something with the bitcoin thing. 

I've switched over to Paperspace now and everything is running smoothly. I appreciate your help!

**Comment by JayThibs** [comment]
Just ran into this issue myself. Using wandb.login(key=key) worked.

**Comment by aegonwolf** [comment]
I have the same issue on google colab I run
```
!pip install wandb
import wandb
```

then in a new cell
`wandb.login()`

It just keeps spinning
`wandb.init(settings=wandb.Settings(start_method="thread"))`

does the same when added before `wandb.login()` so it isn't a solution really

any update on this?

**Comment by aegonwolf** [comment]
> We actually haven't seen this one before. I'm not able to make it happen consistently. For others that are coming to this issue, the brute force way to login colab without producing this hang is:`wandb.login(key="XXXXX")`. Where key is your wandb API key from https://wandb.ai/authorize
> 
> It's important to do do this in it's own cell and not to save the notebook with your key in it to prevent other users viewing your notebook from having your credentials.

I can make this happen everytime, my problem is that it never does not happen :-\

**Comment by JayThibs** [comment]
@aegonwolf I've had it work in some notebooks and not others. It may be helpful to try creating a new notebook and just copy-paste the code there and see if it runs without error.

**Comment by Vftdan** [comment]
I have encountered the same problem.

If I disable iframe login by running this code:

``` python
import wandb.jupyter
wandb.jupyter.attempt_colab_login = (lambda api_key: None)
```

then I am able to login (sometimes it requires to interrupt and rerun `wandb.login()` cell) and the problem is postponed to the moment when I start training the model, so apparently when `wandb.log(...)` is called.

**Comment by aidanjdonohue** [comment]
@aegonwolf what version of the client library are you running and did `wandb.login(key='XXX')` fix your issue?

**Comment by vishhvak** [comment]
This is happening to me every time for the past few days with the latest version, even while running `wandb.login(key='XXX')` in a separate cell. Any fixes? Its so annoying.

**Comment by MBakirWB** [comment]
@vishhvak ,

Thank you for writing in. We are not currently aware of any major issues with the latest release that prevents users from using `wandb.login() `or `wandb.init()`. Can you please share any error messages from your jupyter cells or from browser console.  Also please try uninstalling / reinstalling wandb to see if that provides a quick fix.

**Comment by MBakirWB** [comment]
Hi @vishhvak ,

As we have not heard back from you, I will be closing out this thread. Please do reach out again if you run into additional issues with out latest release. 

Regards,

Mohammad

**Comment by datasith** [comment]
Experiencing this issue at the moment, fwiw.

**Comment by MBakirWB** [comment]
@datasith ,

Thank you for writing in. I will take note of the reemergence of this issue. We released a client (0.12.18) update today. Please update to the latest version. If are still encountering issues with your login, let us know and we will take a closer look.

**Comment by maPiche** [comment]
Been having the same issue, and can't seem to fix it without providing the key.
Interestingly enough, if I open a new notebook and wandb.login() ; it works just fine.

So there might be something with the notebook ?

**Comment by vanpelt** [comment]
@maPiche would you mind sharing the notebook with vanpelt@wandb.com?  Would like to try and reproduce this.

**Comment by maPiche** [comment]
of course

**Comment by vanpelt** [comment]
@maPiche thanks!  I was able to reproduce the issue but I don't understand the root cause.  It seems to have something to do with some other data that's been rendered in your notebook.  If I create a new colab and call `wandb.login()` it works fine.  I was able to find a super hacky workaround:

```python
import sys

def wandb_colab_login():
  """Temporary hack to prevent colab from hanging"""
  sys.modules["google.colab2"] = sys.modules["google.colab"]
  del sys.modules["google.colab"]
  wandb.login()
  sys.modules["google.colab"] = sys.modules["google.colab2"]
wandb_colab_login()
```

I'll keep digging and see if I can figure out what's actually happening here...  Thanks for reporting and providing the notebook!

**Comment by maPiche** [comment]
Thank you for you magic, it works perfectly.

**Comment by gurugecl** [comment]
Hi I'm experiencing the same issue running wandb in a local jupyter-lab notebook using wandb version 0.13.5. wandb.login() just hangs even if I provide a key and other suggestions mentioned in this thread. Has there been a fix implemented for this?

**Comment by jerpint** [comment]
I just experienced this same issue on a colab notebook, and @vanpelt solution worked flawlessly. Nice hack :)

**Comment by aegonwolf** [comment]
> ```python
> import sys
> 
> def wandb_colab_login():
>   """Temporary hack to prevent colab from hanging"""
>   sys.modules["google.colab2"] = sys.modules["google.colab"]
>   del sys.modules["google.colab"]
>   wandb.login()
>   sys.modules["google.colab"] = sys.modules["google.colab2"]
> wandb_colab_login()
> ```

This works for the login, 
I can't init though still, just for some runtimes not for all. QUite annoying.

**Comment by skengman1312** [comment]
I'm experiencing the same issues, passing the key to `wandb.init()` partially solves the problem as `wandb.log()` and `wandb.init()` still result in the same problem.

**Comment by drachs** [comment]
I was running a local google colab instance when this blew up on me, so I was able to capture the console output from jupyter.

[2023-12-05T05:14:14.838Z]  INFO: app/1 on 982c79e28c90: DAP creating Socket to /tmp/debugger_2aq3pgczio for session 0
[2023-12-05T05:14:14.852Z]  INFO: app/1 on 982c79e28c90: LSP 0 new session, 1 now active
[2023-12-05T05:14:37.412Z]  INFO: app/1 on 982c79e28c90: LSP 1 new session, 2 now active
[2023-12-05T05:14:37.414Z]  INFO: app/1 on 982c79e28c90: LSP 0 closed session, 1 remaining active
[2023-12-05T05:14:37.418Z]  INFO: app/1 on 982c79e28c90: LSP 1 closed session, 0 remaining active
[2023-12-05T05:14:37.425Z]  INFO: app/1 on 982c79e28c90: LSP 2 new session, 1 now active
E1205 05:14:50.004091      51 ipython_mitm.go:1943] demux: channelForMessage({'\x01' "{\"header\":{\"msg_id\":\"d4bf9bd2-b23f-448b-b30b-dce52bd2e56f\",\"username\":\"username\",\"session\":\"1c3f37f9-c4ee-4ba9-be53-f99fbc8d09c4\",\"msg_type\":\"input_reply\",\"version\":\"5.0\"},\"metadata\":{},\"content\":{\"value\":{\"type\":\"colab_reply\",\"colab_msg_id\":1,\"data\":{\"ipynb\":{\"nbformat\":4,\"nbformat_minor\":0,\"metadata\":{\"colab\":{\"provenance\":[]},\"kernelspec\":{\"name\":\"python3\",\"display_name\":\"Python 3\"},\"language_info\":{\"name\":\"python\"},\"widgets\":{\"application/vnd.jupyter.widget-state+json\":{\"a591e0e7b0534a45a52e926e7a6592ee\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HBoxModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HBoxModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HBoxView\",\"box_style\":\"\",\"children\":[\"IPY_MODEL_4ef586aeae234b06a7f43cba253c009d\",\"IPY_MODEL_791c4108c04246a89b3b1d1da36a497a\",\"IPY_MODEL_2355e99fec0944deb3756fe5b7ca3b33\"],\"layout\":\"IPY_MODEL_7228bbff426d49f1a52088272b45a795\",\"tabbable\":null,\"tooltip\":null}},\"4ef586aeae234b06a7f43cba253c009d\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HTMLModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HTMLView\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_cc5928e6510b4610b8848d2d62ace5a6\",\"placeholder\":\"\u200b\",\"style\":\"IPY_MODEL_0d794f7ff082451c9078260057817f30\",\"tabbable\":null,\"tooltip\":null,\"value\":\"Downloading builder script: 100%\"}},\"791c4108c04246a89b3b1d1da36a497a\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"FloatProgressModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"FloatProgressModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"ProgressView\",\"bar_style\":\"success\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_918d94897bcd49158c9e4092d63d8a71\",\"max\":3141,\"min\":0,\"orientation\":\"horizontal\",\"style\":\"IPY_MODEL_740e9d5fe45c4768a86d0a94c790daac\",\"tabbable\":null,\"tooltip\":null,\"value\":3141}},\"2355e99fec0944deb3756fe5b7ca3b33\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HTMLModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HTMLView\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_f31f39166e3245a6874175f9a17a4ccd\",\"placeholder\":\"\u200b\",\"style\":\"IPY_MODEL_c4b08b90ebfc4945a193323f0b63b2b9\",\"tabbable\":null,\"tooltip\":null,\"value\":\" 3.14k/3.14k [00:00&lt;00:00, 436kB/s]\"}},\"7228bbff426d49f1a52088272b45a795\":{\"model_module\":\"@jupyter-widgets/base\",\"model_name\":\"LayoutModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"cc5928e6510b4610b8848d2d62ace5a6\":{\"model_module\":\"@jupyter-widgets/base\",\"model_name\":\"LayoutModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"0d794f7ff082451c9078260057817f30\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HTMLStyleModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLStyleModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"StyleView\",\"background\":null,\"description_width\":\"\",\"font_size\":null,\"text_color\":null}},\"918d94897bcd49158c9e4092d63d8a71\":{\"model_module\":\"@jupyter-widgets/base\",\"model_name\":\"LayoutModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"740e9d5fe45c4768a86d0a94c790daac\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"ProgressStyleModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"ProgressStyleModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"StyleView\",\"bar_color\":null,\"description_width\":\"\"}},\"f31f39166e3245a6874175f9a17a4ccd\":{\"model_module\":\"@jupyter-widgets/base\",\"model_name\":\"LayoutModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"c4b08b90ebfc4945a193323f0b63b2b9\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HTMLStyleModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLStyleModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"StyleView\",\"background\":null,\"description_width\":\"\",\"font_size\":null,\"text_color\":null}},\"f0e7c98379c040e0a01dd46f5f80e428\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HBoxModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HBoxModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HBoxView\",\"box_style\":\"\",\"children\":[\"IPY_MODEL_3fed16209f114c99a4d842e1ac9e837a\",\"IPY_MODEL_6315914faece4873adbfd4b0a507a711\",\"IPY_MODEL_d1316d15e67845339880e4da1149aaa0\"],\"layout\":\"IPY_MODEL_f104dddad14844b892132e83e26996fb\",\"tabbable\":null,\"tooltip\":null}},\"3fed16209f114c99a4d842e1ac9e837a\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HTMLModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HTMLView\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_792c2494e72c4edfab4dd98d716e24ce\",\"placeholder\":\"\u200b\",\"style\":\"IPY_MODEL_c6a1c53339c74cb39d15bc366ceca87a\",\"tabbable\":null,\"tooltip\":null,\"value\":\"Downloading metadata: 100%\"}},\"6315914faece4873adbfd4b0a507a711\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"FloatProgressModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"FloatProgressModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"ProgressView\",\"bar_style\":\"success\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_eff3b42483f74e72bcd53a6c4674c39d\",\"max\":3811,\"min\":0,\"orientation\":\"horizontal\",\"style\":\"IPY_MODEL_e191195438024058ac8c970234f58688\",\"tabbable\":null,\"tooltip\":null,\"value\":3811}},\"d1316d15e67845339880e4da1149aaa0\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_name\":\"HTMLModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HTMLView\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_cc3f17aa542f4c2dbd5512a0d9a1037e\",\"placeholder\":\"\u200b\",\"style\":\"IPY_MODEL_2677d54967174ad8a54d151a5b473258\",\"tabbable\":null,\"tooltip\":null,\"value\":\" 3.81k/3.81k [00:00&lt;00:00, 612kB/s]\"}},\"f104dddad14844b892132e83e26996fb\":{\"model_module\":\"@jupyter-widgets/base\",\"model_name\":\"LayoutModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"792c2494e72c4edfab4dd98d716e24ce\":{\"model_module\":\"@jupyter-widgets/base\",\"model_name\":\"LayoutModel\",\"model_module_version\":\"2.0.0\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"c6a1c53339c74cb39d15bc366ceca87a\":{\"model_module\":\"@jupyter-widg
[2023-12-05T05:14:50.005Z] ERROR: app/1 on 982c79e28c90: Jupyter server returned error. (err.code=ECONNRESET)
    Error: read ECONNRESET
        at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
TypeError: response.writeHead is not a function
    at ProxyServer.errorHandler (/datalab/web/jupyter.js:198:14)
    at ProxyServer.emit (/datalab/web/node_modules/eventemitter3/index.js:204:33)
    at Socket.onOutgoingError (/datalab/web/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:157:16)
    at Socket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-12-05T05:14:50.005Z] ERROR: app/1 on 982c79e28c90: Unhandled exception
    TypeError: response.writeHead is not a function
        at ProxyServer.errorHandler (/datalab/web/jupyter.js:198:14)
        at ProxyServer.emit (/datalab/web/node_modules/eventemitter3/index.js:204:33)
        at Socket.onOutgoingError (/datalab/web/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:157:16)
        at Socket.emit (events.js:327:22)
        at emitErrorNT (internal/streams/destroy.js:106:8)
        at emitErrorCloseNT (internal/streams/destroy.js:74:3)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-12-05T05:14:50.005Z]  INFO: app/1 on 982c79e28c90: app: exit
[2023-12-05T05:14:50.005Z]  INFO: app/1 on 982c79e28c90: jupyter close: PID: 99
[2023-12-05T05:14:50.006Z]  INFO: app/1 on 982c79e28c90: app: exit: stopped

**Comment by Negatix092** [comment]
I am having the same issues with wandb.login() and wandb.init(). The solution for the wandb.login() that @vanpelt suggested, worked. But, I am still unable to run the wandb.init() command without any issues. It just keeps killing the local runtime. Does somebody of the wandb team have a solution for this issue?

**Comment by jleppert** [comment]
I am faced with same issue and no resolution in any of the solutions here. What is strange is this was working fine this week and stopped working today. On Google Colab

**Comment by shahzain110** [comment]
This worked for me.

Prepare a new colab copy all cells from old colab in new one. run it.

**Comment by ali-khayat** [comment]
Just run `!wandb login` instead and then paste your key, will work perfectly fine.
