### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by altay** [wandb/client#209]
* Weights and Biases version:  0.6.6
* Python version:  2.7.12
* Operating System:  Mac OSX 10.13.4

### Description

I'm trying to run perceptron-single.py from Lukas's ML tutorial

### What I Did

(lukas_tutorial-2.7) Altays-MacBook-Pro:keras-perceptron altayguvench$ python perceptron-single.py 

...
Epoch 9/10
60000/60000 [==============================] - 2s 29us/step - loss: 0.0350 - acc: 0.9649 - val_loss: 0.0333 - val_acc: 0.9666
Epoch 10/10
60000/60000 [==============================] - 2s 30us/step - loss: 0.0352 - acc: 0.9647 - val_loss: 0.0303 - val_acc: 0.9697

wandb: Waiting for wandb process to finish, PID 54666
wandb: Program ended.
wandb: Run summary:
wandb:        acc 0.963083333333
wandb:       loss 0.0367756377678
wandb:    val_acc 0.9708
wandb:   val_loss 0.0290675483726
wandb: Run history:
Traceback (most recent call last):
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/wandb/internal_cli.py", line 95, in <module>
    main()
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/wandb/internal_cli.py", line 87, in main
    headless(args)
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/wandb/internal_cli.py", line 41, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/wandb/run_manager.py", line 735, in wrap_existing_process
    self._sync_etc(headless=True)
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/wandb/run_manager.py", line 866, in _sync_etc
    wandb.termlog(format_str.format(key, line))
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/wandb/core.py", line 62, in termlog
    click.echo(line, file=sys.stderr, nl=newline)
  File "/Users/altayguvench/.pyenv/versions/lukas_tutorial-2.7/lib/python2.7/site-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-40: ordinal not in range(128)
(lukas_tutorial-2.7) Altays-MacBook-Pro:keras-perceptron altayguvench$ wandb --version
wandb, version 0.6.6

**Comment by cvphelps** [comment]
I think this is fixed by the newer versions of wandb.
