### ISSUE TITLE
[CLI] It seems that wanbd make my parallel model fail to backward my loss!?

### ISSUE THREAD

**Issue by amssljc** [wandb/client#2091]
**Description**
I've been using wanbd for a long time, but recently when I update my code for parallel GPU training by adding only one single line code:
```
model = DataParallel(mymodel)
```
, there raised a ValueError:
```
Traceback (most recent call last):

  File "D:\Users\*****\*****\main.py", line 175, in <module>
    train_part(config, model, device, train_loader,

  File "D:\Users\*****\*****\fit.py", line 36, in train_part
    loss.backward()

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\torch\autograd\__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\wandb_torch.py", line 398, in backward_hook
    wandb.run.summary["graph_%i" % graph_idx] = graph

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\wandb_summary.py", line 57, in __setitem__
    self.update({key: val})

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\wandb_summary.py", line 79, in update
    self._update(record)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\wandb_summary.py", line 133, in _update
    self._update_callback(record)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\wandb_run.py", line 756, in _summary_update_callback
    self._backend.interface.publish_summary(summary_record)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\interface\interface.py", line 615, in publish_summary
    pb_summary_record = self._make_summary(summary_record)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\interface\interface.py", line 388, in _make_summary
    json_value = self._summary_encode(item.value, path_from_root)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\interface\interface.py", line 351, in _summary_encode
    data_types.val_to_json(

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\data_types.py", line 2134, in val_to_json
    return val.to_json(run)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\data_types.py", line 1280, in to_json
    json_dict = super(Graph, self).to_json(run)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\site-packages\wandb\sdk\data_types.py", line 493, in to_json
    os.path.relpath(self._path, self._run.dir)

  File "D:\Users\*****\Anaconda3\envs\torch18\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (

ValueError: path is on mount 'C:', start on mount 'D:'
```

Where ***** in path is my private content.
I'm sure it is related with wanbd, because when i run a copy of my code without wanbd but with parallel part, there is no problem.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder 

**Environment**
- OS: Windows server 2012 R2
- Environment: [e.g. Google Colab]
- Python Version: 3.8.8

**Comment by amssljc** [comment]
After a test, I found that it was caused by adding `wandb.watch(model)`

```
import torch
import wandb
from torch.nn.parallel import DataParallel

import time


class test(torch.nn.Module):
    def __init__(self):
        super(test, self).__init__()
        self.fc = torch.nn.Linear(10, 10)
    
    def forward(self,x):
        x = self.fc(x)
        return x
    
    
x = torch.rand(1000,10).to('cuda')
y = (x>0.5).float()


wandb.init(project="DeepDiffNet_v2")
model = test().to('cuda')

model = DataParallel(model)
loss = torch.nn.MSELoss()   
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
wandb.watch(model, 'all')
t1 = time.time()
for i in range(1000):
    y_ = model(x)
    losss = loss(y_,y)
    losss.backward()    
    optimizer.step()
    wandb.log({
        "loss":losss.item()
        }
              )
x = torch.rand(1,10).cuda()
t2 = time.time()
print(t2-t1)
```

**Comment by vanpelt** [comment]
Hey @amssljc it looks like your system temporary directory is on a different drive than the wandb directory.  When you call `wandb.init` can you try specifying `dir="C:\SomeTempDirectory"` and see if you still get the error with wandb.watch?

**Comment by amssljc** [comment]
Thanks for your reply!! It did work! However, what should I do if I want to save them (wandb directories) in other disks or somewhere is not tempdirectory such like the directory when I do not use `DataParallel(model)` code.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by amorehead** [comment]
Hello, I believe I am encountering a problem with `wandb==0.15.12` and `lightning=2.0.9` very similar to the title of this issue (`wandb` making my data-parallel model to raise an out of memory error when calling `loss.backward()`).

Around 50 epochs into my model's training (which coincidentally takes place just after I call a special model_evaluation function where I essentially run a lightweight form of inference with the current model weights to measure inference metrics), during the next training epoch my model shortly thereafter raises a CUDA out of memory error which, even when handling manually with a try-catch clause, causes all 4 of my DDP ranks to freeze no matter what, thereby preventing my model training script from proceeding. When I disable my `WandbLogger` in my `Lightning.Trainer`, I no longer encounter this issue.

For context, I am not (as far as I know) calling `wandb.watch()` anywhere, so `wandb` shouldn't be tracking my model's computational graph, gradients, or similar items during training. It should only be logging loss values and metrics periodically. Nonetheless, it looks like `wandb`'s `online` usage is causing a spike in GPU memory during my model's backward pass. 

Has anyone else experienced an issue like this before, and if so, how have you resolved it? Will I simply have to set `offline=true` for my `WandbLogger` and then `wandb sync` my run data to remote later on to work around this issue?
