### ISSUE TITLE
funny error when setting up wandb on server

### ISSUE THREAD

**Issue by lukas** [wandb/client#21]
* Weights and Biases version: 0.4.16
* Python version: 2.7.12
* Operating System: ubuntu

Let's setup this directory for W&B!
You can find your API keys here: https://app.wandb.ai/profile
Not authenticated! Paste an API key from your profile []: 53326a0434aab4846d127b65fd0d79471071715f
Appending to netrc /home/ubuntu/.netrc
Traceback (most recent call last):
  File "/usr/local/bin/wandb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wandb/cli.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wandb/cli.py", line 349, in init
    entity = click.prompt("What username or org should we use?", default=api.viewer().get('entity', 'models'))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by vanpelt** [comment]
This was caused by you copying a newline from the interface.  I now handle this case, good find!
