### ISSUE TITLE
[Q] How to deal with frequent network error (ReadTimeout)

### ISSUE THREAD

**Issue by zxhuang97** [wandb/client#2100]
I started to use wandb on a cluster one month ago and it worked pretty well until recently. I usually launch multiple jobs to the cluster simultaneously, and some of them will 'crash' in the middle of training. 

```
Exception in thread Thread-5:                                                   
Traceback (most recent call last):
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 255, in _thread_body
    self._send(ready_chunks)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 301, in _send
    self._client.post, self._endpoint, json={"files": fs}
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 277, in _handle_response
    raise response
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/util.py", line 731, in request_with_retry
    response.raise_for_status()
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/279src4s/file_stream

wandb: Network error (ReadTimeout), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: Network error resolved after 0:01:05.390972, resuming normal operation.
```

Although the program is still running and the log suggests that it has resumed to normal operation, the status of that job is still "crashed" on the dashboard. I know I can use `wandb sync run_dir`  to manually sync each disconnected run, but is there any method that wandb can reconnect by itself?

Also, what might be the possible reasons for the internet error? Multiple wandb programs on a single machine?

Thanks!

**Comment by vanpelt** [comment]
Hey @zxhuang97 this is not good.  The error is a 500 error which indicates you may be streaming too much data, or our systems are overloaded.  We should resume training automatically.  Which version of wandb are you using?  Can you also share the `debug-internal.log` from one of the runs that exhibited this behavior?

**Comment by zxhuang97** [comment]
Thank you for your quick response. I'm using 0.10.24. As for the data I sent, it's only a few metrics so I think it's fine. I check the log and it says something like "too many connections". As I said before, slurm may allocate multiple jobs to the same node, does it create some kind of conflict?
```
2021-04-22 16:24:26,356 ERROR   SenderThread:302857 [internal_api.py:execute():127] 500 response executing GraphQL.
2021-04-22 16:24:26,357 ERROR   SenderThread:302857 [internal_api.py:execute():128] {"error":"Error 1040: Too many connections"}

2021-04-22 16:24:46,716 WARNING Thread-5  :302857 [util.py:request_with_retry():769] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/1uh62w06/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fef5f1435f8>>, args: ('https://api.wandb.ai/files/zxhuang/Occluded cloth/1uh62w06/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 176, 'content': ['{"system.gpu.0.gpu": 20.0, "system.gpu.0.memory": 2.07, "system.gpu.0.memoryAllocated": 17.76, "system.gpu.0.temp": 47.0, "system.gpu.process.0.gpu": 20.0, "system.gpu.process.0.memory": 2.07, "system.gpu.process.0.memoryAllocated": 17.76, "system.gpu.process.0.temp": 47.0, "system.gpu.0.powerWatts": 87.21, "system.gpu.0.powerPercent": 34.89, "system.gpu.process.0.powerWatts": 87.21, "system.gpu.process.0.powerPercent": 34.89, "system.gpu.1.gpu": 9.87, "system.gpu.1.memory": 3.67, "system.gpu.1.memoryAllocated": 73.01, "system.gpu.1.temp": 47.0, "system.gpu.1.powerWatts": 62.99, "system.gpu.1.powerPercent": 25.2, "system.gpu.2.gpu": 12.2, "system.gpu.2.memory": 2.13, "system.gpu.2.memoryAllocated": 11.71, "system.gpu.2.temp": 40.67, "system.gpu.2.powerWatts": 61.58, "system.gpu.2.powerPercent": 24.63, "system.gpu.3.gpu": 12.47, "system.gpu.3.memory": 1.0, "system.gpu.3.memoryAllocated": 29.98, "system.gpu.3.temp": 40.47, "system.gpu.3.powerWatts": 66.14, "system.gpu.3.powerPercent": 26.46, "system.cpu": 28.75, "system.memory": 4.85, "system.disk": 0.1, "system.proc.memory.availableMB": 366654.42, "system.proc.memory.rssMB": 83.35, "system.proc.memory.percent": 0.02, "system.proc.cpu.threads": 12.0, "system.network.sent": 768729197, "system.network.recv": 10682228623, "_wandb": true, "_timestamp": 1619123037, "_runtime": 5759}']}}}}
2021-04-22 16:24:49,621 ERROR   SenderThread:302857 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/http/client.py", line 1379, in getresponse
    response.begin()
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 124, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/zixuanhu/anaconda3/envs/softgym/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/zixuanhu/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2021-04-22 16:24:49,809 WARNING Thread-5  :302857 [util.py:request_with_retry():769] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/1uh62w06/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fef5f1435f8>>, args: ('https://api.wandb.ai/files/zxhuang/Occluded cloth/1uh62w06/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 176, 'content': ['{"system.gpu.0.gpu": 20.0, "system.gpu.0.memory": 2.07, "system.gpu.0.memoryAllocated": 17.76, "system.gpu.0.temp": 47.0, "system.gpu.process.0.gpu": 20.0, "system.gpu.process.0.memory": 2.07, "system.gpu.process.0.memoryAllocated": 17.76, "system.gpu.process.0.temp": 47.0, "system.gpu.0.powerWatts": 87.21, "system.gpu.0.powerPercent": 34.89, "system.gpu.process.0.powerWatts": 87.21, "system.gpu.process.0.powerPercent": 34.89, "system.gpu.1.gpu": 9.87, "system.gpu.1.memory": 3.67, "system.gpu.1.memoryAllocated": 73.01, "system.gpu.1.temp": 47.0, "system.gpu.1.powerWatts": 62.99, "system.gpu.1.powerPercent": 25.2, "system.gpu.2.gpu": 12.2, "system.gpu.2.memory": 2.13, "system.gpu.2.memoryAllocated": 11.71, "system.gpu.2.temp": 40.67, "system.gpu.2.powerWatts": 61.58, "system.gpu.2.powerPercent": 24.63, "system.gpu.3.gpu": 12.47, "system.gpu.3.memory": 1.0, "system.gpu.3.memoryAllocated": 29.98, "system.gpu.3.temp": 40.47, "system.gpu.3.powerWatts": 66.14, "system.gpu.3.powerPercent": 26.46, "system.cpu": 28.75, "system.memory": 4.85, "system.disk": 0.1, "system.proc.memory.availableMB": 366654.42, "system.proc.memory.rssMB": 83.35, "system.proc.memory.percent": 0.02, "system.proc.cpu.threads": 12.0, "system.network.sent": 768729197, "system.network.recv": 10682228623, "_wandb": true, "_timestamp": 1619123037, "_runtime": 5759}']}}}}
2021-04-22 16:24:54,802 WARNING Thread-5  :302857 [util.py:request_with_retry():769] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/1uh62w06/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fef5f1435f8>>, args: ('https://api.wandb.ai/files/zxhuang/Occluded cloth/1uh62w06/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 176, 'content': ['{"system.gpu.0.gpu": 20.0, "system.gpu.0.memory": 2.07, "system.gpu.0.memoryAllocated": 17.76, "system.gpu.0.temp": 47.0, "system.gpu.process.0.gpu": 20.0, "system.gpu.process.0.memory": 2.07, "system.gpu.process.0.memoryAllocated": 17.76, "system.gpu.process.0.temp": 47.0, "system.gpu.0.powerWatts": 87.21, "system.gpu.0.powerPercent": 34.89, "system.gpu.process.0.powerWatts": 87.21, "system.gpu.process.0.powerPercent": 34.89, "system.gpu.1.gpu": 9.87, "system.gpu.1.memory": 3.67, "system.gpu.1.memoryAllocated": 73.01, "system.gpu.1.temp": 47.0, "system.gpu.1.powerWatts": 62.99, "system.gpu.1.powerPercent": 25.2, "system.gpu.2.gpu": 12.2, "system.gpu.2.memory": 2.13, "system.gpu.2.memoryAllocated": 11.71, "system.gpu.2.temp": 40.67, "system.gpu.2.powerWatts": 61.58, "system.gpu.2.powerPercent": 24.63, "system.gpu.3.gpu": 12.47, "system.gpu.3.memory": 1.0, "system.gpu.3.memoryAllocated": 29.98, "system.gpu.3.temp": 40.47, "system.gpu.3.powerWatts": 66.14, "system.gpu.3.powerPercent": 26.46, "system.cpu": 28.75, "system.memory": 4.85, "system.disk": 0.1, "system.proc.memory.availableMB": 366654.42, "system.proc.memory.rssMB": 83.35, "system.proc.memory.percent": 0.02, "system.proc.cpu.threads": 12.0, "system.network.sent": 768729197, "system.network.recv": 10682228623, "_wandb": true, "_timestamp": 1619123037, "_runtime": 5759}']}}}}
2021-04-22 16:24:55,058 ERROR   SenderThread:302857 [internal_api.py:execute():127] 500 response executing GraphQL.
2021-04-22 16:24:55,059 ERROR   SenderThread:302857 [internal_api.py:execute():128] {"error":"Error 1040: Too many connections"}

2021-04-22 16:25:02,961 WARNING Thread-5  :302857 [util.py:request_with_retry():769] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/1uh62w06/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fef5f1435f8>>, args: ('https://api.wandb.ai/files/zxhuang/Occluded cloth/1uh62w06/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 176, 'content': ['{"system.gpu.0.gpu": 20.0, "system.gpu.0.memory": 2.07, "system.gpu.0.memoryAllocated": 17.76, "system.gpu.0.temp": 47.0, "system.gpu.process.0.gpu": 20.0, "system.gpu.process.0.memory": 2.07, "system.gpu.process.0.memoryAllocated": 17.76, "system.gpu.process.0.temp": 47.0, "system.gpu.0.powerWatts": 87.21, "system.gpu.0.powerPercent": 34.89, "system.gpu.process.0.powerWatts": 87.21, "system.gpu.process.0.powerPercent": 34.89, "system.gpu.1.gpu": 9.87, "system.gpu.1.memory": 3.67, "system.gpu.1.memoryAllocated": 73.01, "system.gpu.1.temp": 47.0, "system.gpu.1.powerWatts": 62.99, "system.gpu.1.powerPercent": 25.2, "system.gpu.2.gpu": 12.2, "system.gpu.2.memory": 2.13, "system.gpu.2.memoryAllocated": 11.71, "system.gpu.2.temp": 40.67, "system.gpu.2.powerWatts": 61.58, "system.gpu.2.powerPercent": 24.63, "system.gpu.3.gpu": 12.47, "system.gpu.3.memory": 1.0, "system.gpu.3.memoryAllocated": 29.98, "system.gpu.3.temp": 40.47, "system.gpu.3.powerWatts": 66.14, "system.gpu.3.powerPercent": 26.46, "system.cpu": 28.75, "system.memory": 4.85, "system.disk": 0.1, "system.proc.memory.availableMB": 366654.42, "system.proc.memory.rssMB": 83.35, "system.proc.memory.percent": 0.02, "system.proc.cpu.threads": 12.0, "system.network.sent": 768729197, "system.network.recv": 10682228623, "_wandb": true, "_timestamp": 1619123037, "_runtime": 5759}']}}}}
2021-04-22 16:25:05,042 ERROR   SenderThread:302857 [internal_api.py:execute():127] 500 response executing GraphQL.
2021-04-22 16:25:05,043 ERROR   SenderThread:302857 [internal_api.py:execute():128] {"error":"Error 1040: Too many connections"}

2021-04-22 16:25:19,252 WARNING Thread-5  :302857 [util.py:request_with_retry():769] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/1uh62w06/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fef5f1435f8>>, args: ('https://api.wandb.ai/files/zxhuang/Occluded cloth/1uh62w06/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 176, 'content': ['{"system.gpu.0.gpu": 20.0, "system.gpu.0.memory": 2.07, "system.gpu.0.memoryAllocated": 17.76, "system.gpu.0.temp": 47.0, "system.gpu.process.0.gpu": 20.0, "system.gpu.process.0.memory": 2.07, "system.gpu.process.0.memoryAllocated": 17.76, "system.gpu.process.0.temp": 47.0, "system.gpu.0.powerWatts": 87.21, "system.gpu.0.powerPercent": 34.89, "system.gpu.process.0.powerWatts": 87.21, "system.gpu.process.0.powerPercent": 34.89, "system.gpu.1.gpu": 9.87, "system.gpu.1.memory": 3.67, "system.gpu.1.memoryAllocated": 73.01, "system.gpu.1.temp": 47.0, "system.gpu.1.powerWatts": 62.99, "system.gpu.1.powerPercent": 25.2, "system.gpu.2.gpu": 12.2, "system.gpu.2.memory": 2.13, "system.gpu.2.memoryAllocated": 11.71, "system.gpu.2.temp": 40.67, "system.gpu.2.powerWatts": 61.58, "system.gpu.2.powerPercent": 24.63, "system.gpu.3.gpu": 12.47, "system.gpu.3.memory": 1.0, "system.gpu.3.memoryAllocated": 29.98, "system.gpu.3.temp": 40.47, "system.gpu.3.powerWatts": 66.14, "system.gpu.3.powerPercent": 26.46, "system.cpu": 28.75, "system.memory": 4.85, "system.disk": 0.1, "system.proc.memory.availableMB": 366654.42, "system.proc.memory.rssMB": 83.35, "system.proc.memory.percent": 0.02, "system.proc.cpu.threads": 12.0, "system.network.sent": 768729197, "system.network.recv": 10682228623, "_wandb": true, "_timestamp": 1619123037, "_runtime": 5759}']}}}}
2021-04-22 16:25:23,336 ERROR   SenderThread:302857 [internal_api.py:execute():127] 500 response executing GraphQL.
2021-04-22 16:25:23,338 ERROR   SenderThread:302857 [internal_api.py:execute():128] {"error":"Error 1040: Too many connections"}

2021-04-22 16:25:54,108 WARNING Thread-5  :302857 [util.py:request_with_retry():769] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/zxhuang/Occluded%20cloth/1uh62w06/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fef5f1435f8>>, args: ('https://api.wandb.ai/files/zxhuang/Occluded cloth/1uh62w06/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 176, 'content': ['{"system.gpu.0.gpu": 20.0, "system.gpu.0.memory": 2.07, "system.gpu.0.memoryAllocated": 17.76, "system.gpu.0.temp": 47.0, "system.gpu.process.0.gpu": 20.0, "system.gpu.process.0.memory": 2.07, "system.gpu.process.0.memoryAllocated": 17.76, "system.gpu.process.0.temp": 47.0, "system.gpu.0.powerWatts": 87.21, "system.gpu.0.powerPercent": 34.89, "system.gpu.process.0.powerWatts": 87.21, "system.gpu.process.0.powerPercent": 34.89, "system.gpu.1.gpu": 9.87, "system.gpu.1.memory": 3.67, "system.gpu.1.memoryAllocated": 73.01, "system.gpu.1.temp": 47.0, "system.gpu.1.powerWatts": 62.99, "system.gpu.1.powerPercent": 25.2, "system.gpu.2.gpu": 12.2, "system.gpu.2.memory": 2.13, "system.gpu.2.memoryAllocated": 11.71, "system.gpu.2.temp": 40.67, "system.gpu.2.powerWatts": 61.58, "system.gpu.2.powerPercent": 24.63, "system.gpu.3.gpu": 12.47, "system.gpu.3.memory": 1.0, "system.gpu.3.memoryAllocated": 29.98, "system.gpu.3.temp": 40.47, "system.gpu.3.powerWatts": 66.14, "system.gpu.3.powerPercent": 26.46, "system.cpu": 28.75, "system.memory": 4.85, "system.disk": 0.1, "system.proc.memory.availableMB": 366654.42, "system.proc.memory.rssMB": 83.35, "system.proc.memory.percent": 0.02, "system.proc.cpu.threads": 12.0, "system.network.sent": 768729197, "system.network.recv": 10682228623, "_wandb": true, "_timestamp": 1619123037, "_runtime": 5759}']}}}}
2021-04-22 16:25:58,604 DEBUG   SenderThread:302857 [sender.py:send():160] send: stats
2021-04-22 16:25:58,606 DEBUG   SenderThread:302857 [sender.py:send():160] send: stats
2021-04-22 16:25:58,607 DEBUG   SenderThread:302857 [sender.py:send():160] send: stats
2021-04-22 16:26:07,431 DEBUG   SenderThread:302857 [sender.py:send():160] send: stats

```

**Comment by vanpelt** [comment]
@zxhuang97 running multiple instances on the same machine will be fine.  We think we've found a bug in our exception handling logic and are working on a hotfix ASAP.  We patched one issue in 0.10.26 so I would suggest upgrading ASAP.  There's likely one more edge case that we'll be addressing in 0.10.28 due out first thing next week.  

These errors were happening because we had a load spike in our servers earlier today that we've since addressed.  Once we've full patched the remaining issues everything should retry and recover smoothly.  Apologies for this causing syncing issues, this is priority #1 for us right now.

**Comment by zxhuang97** [comment]
> @zxhuang97 running multiple instances on the same machine will be fine. We think we've found a bug in our exception handling logic and are working on a hotfix ASAP. We patched one issue in 0.10.26 so I would suggest upgrading ASAP. There's likely one more edge case that we'll be addressing in 0.10.28 due out first thing next week.
> 
> These errors were happening because we had a load spike in our servers earlier today that we've since addressed. Once we've full patched the remaining issues everything should retry and recover smoothly. Apologies for this causing syncing issues, this is priority #1 for us right now.

No worries. Thanks for making this useful tool for the community!

**Comment by zxhuang97** [comment]
@vanpelt Hi Chris, I have updated my wandb to 0.10.28. However, in the outrage this afternoon, all my runs crashed and they cannot resume syncing with the server.  Is it another edge case or it hasn't been fixed in 0.10.28?

**Comment by andravin** [comment]
@zxhuang97 I experienced the same issue you reported multiple times, using versions 0.10.24 through 0.10.28. Basically every training run from my workstation that lasted more than ~16 hours would be marked "crashed" even though training continued just fine.

I shared console output and log files with support multiple times for different versions. Support told me that 0.10.28 should have fixed the issue, but it did not.

The changelogs for 0.10.28, 0.10.29, and 0.10.30 each say they fixed this issue: https://github.com/wandb/client/blob/master/CHANGELOG.md

Network programming is hard. ;-)

I will likely test 0.1.30 for the first time later today, and should know by tomorrow if it fixed the problem for me.

**Comment by zxhuang97** [comment]
@andravin Hi, I got an email this morning that prompts me to update wandb to 0.10.30. 

I have launched a few more experiments. Hope this time the problem is fully solved ;(

**Comment by adrnswanberg** [comment]
Hi folks, thanks for writing in here. As you said, network programming is hard :(

For 0.10.30, we conducted a bunch of disaster testing (found new and interesting ways to break our staging deployment) and validated that 0.10.30 was resilient to all kinds of failures (where previous versions hadn't been). I'm hopeful you'll see much better results here, but please do let us know if you still run into any problems.

**Comment by andravin** [comment]
Just a quick note.. I have been unable to test 0.10.30 because the workstation that frequently produced the error with earlier versions broke last week and could take another week to repair.

I otherwise run on Amazon on EC2 spot instances, and have never produced the error there with any version of the client. Not sure if the different behavior on EC2 is because of different networking or simply because my spot instances tend to be killed after lest than 12 hours of use.
