### ISSUE TITLE
[Q] Error while logging artifacts.

### ISSUE THREAD

**Issue by bfs18** [wandb/client#2103]
When logging artifacts, the following error would occur randomly. Sometimes the artifacts would be uploaded successfully.

```
def wandb_save_code(H):
    exp_name = H.save_dir.split(os.sep)[-2]
    code = wandb.Artifact(exp_name, type='code')
    temp = tempfile.NamedTemporaryFile('wb', suffix='.tar.gz', delete=False)
    tar = tarfile.open(fileobj=temp, mode='w:gz')
    proj_dir = Path(__file__).absolute().parent.parent
    for py in Path(proj_dir).glob('**/*.py'):
        py_name = py.relative_to(proj_dir.parent).as_posix()
        code.add_file(py, name=py_name)
        tar.add(py, arcname=py_name)
    tar.close()
    temp.close()
    code.add_file(temp.name, name=proj_dir.name + '.tar.gz')
    wandb.run.log_artifact(code)
    code.wait()
    shutil.copyfile(temp.name, Path(H.save_dir) / 'code.tar.gz')
```

```
Failed to upload file: /root/.cache/wandb/artifacts/obj/md5/d4/1d8cd98f00b204e9800998ecf8427e
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/old/retry.py", line 132, in wrapped_fn
    return retrier(*args, **kargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 1128, in upload_file
    util.sentry_reraise(e)
  File "/usr/local/lib/python3.6/site-packages/wandb/util.py", line 120, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 1116, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 411 Client Error: Length Required for url: http://9.72.16.243:8080/local-files/wandb_artifacts/15/76/d41d8cd98f00b204e9800998ecf8427e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=O0GtGj1e0R3RsJWbuCB85A%3D%3D%2F20210423%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20210423T031853Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-Amz-Signature=903665405f5d352187b97a9f4f31a0804f1bcaac4a74b813a560d8b8f1a2dd8f
```

**Comment by ariG23498** [comment]
Hey @bfs18 
Thanks for the ticket. We will be tracking it internally.

**Comment by vanpelt** [comment]
@bfs18 are you running local behind any kind of proxy in front of your wandb/local server?  Is there a specific file that makes this happen consistently?

**Comment by bfs18** [comment]
Hi @vanpelt Thanks for your reply.
I am using a proxy. I cannot reproduce the error consistently. However, the following error happens consistently if I add `code.delete()` after `code.wait()`.

```
wandb: ERROR <Response [400]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/apis/public.py", line 2873, in delete
    self.client.execute(mutation, variable_values={"id": self.id,})
  File "/usr/local/lib/python3.6/site-packages/wandb/old/retry.py", line 132, in wrapped_fn
    return retrier(*args, **kargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/apis/public.py", line 182, in execute
    return self._client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://9.72.16.243:8080/graphql
```

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
