### ISSUE TITLE
[CLI] WandbCallback() NoneTypeError with python3.9.2

### ISSUE THREAD

**Issue by oldenstreeter** [wandb/client#2179]
**Description**
I added the quickstart steps to my tensorflow.keras model and can't run the fit function with the WandbCallback function

**Wandb features**
```
import wandb
from wandb.keras import WandbCallback

project_name='intro-demo'
group_name='test_test'

# init wandb
wandb.init(project=project_name, group=group_name)
...
modelCNN.fit(train_data, target_data, 
             epochs=1,
             batch_size=16,
             verbose=1,
             validation_data=(train_test, target_test),
             callbacks=[WandbCallback()])
```

**Environment**
- OS: Scientific Linux 7.7 (Nitrogen)
- Python Version: 3.9.2

**Error**
```
Traceback (most recent call last):
  File "/pd/home/user-l/radar_reflectivity/python_files/cnn_wandb-Copy1.py", line 134, in <module>
    train_model()
  File "/pd/home/user-l/radar_reflectivity/python_files/cnn_wandb-Copy1.py", line 131, in train_model
    callbacks=[WandbCallback()])
  File "/home/user-l/miniconda3/envs/artemis/lib/python3.9/site-packages/wandb/integration/keras/keras.py", line 407, in __init__
    previous_best = wandb.run.summary.get(
  File "/home/user-l/miniconda3/envs/artemis/lib/python3.9/site-packages/wandb/sdk/wandb_summary.py", line 37, in get
    return self._as_dict().get(key, default)
  File "/home/user-l/miniconda3/envs/artemis/lib/python3.9/site-packages/wandb/sdk/wandb_summary.py", line 130, in _as_dict
    return self._get_current_summary_callback()
  File "/home/user-l/miniconda3/envs/artemis/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 792, in _summary_get_current_summary_callback
    return proto_util.dict_from_proto_list(ret.item)
AttributeError: 'NoneType' object has no attribute 'item'
```

**Comment by vanpelt** [comment]
@oldenstreeter we haven't seen this issue before.  Can you provide a colab or single file with dummy data and the specific version of tensorflow you're using so we can reproduce?

**Comment by oldenstreeter** [comment]
Here is some sample data with a Python file with which I could reproduce the problem
[github_issue_2179.zip](https://github.com/wandb/client/files/6443604/github_issue_2179.zip)

**Comment by ariG23498** [comment]
Hey, @oldenstreeter I have tried reproducing your code with the data that you have sent in.
## Version
1. wandb: wandb, version 0.10.30
2. tensorflow: 2.5.0
3. OS: Ubuntu 20.04.2 LTS

## Code
```python
import os
os.environ["WANDB_BASE_URL"]="https://api.wandb.ai"

# imports
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, GlobalMaxPooling2D
from tensorflow.keras.optimizers import SGD
from sklearn.model_selection import train_test_split
import wandb
from wandb.keras import WandbCallback

# load data
train_data = np.load('train_data.npy')
target_data = np.load('target_data.npy')
# reshape train data from shape (100, 9) to (100, 3, 3, 1)
train_data = train_data.reshape(-1,3,3,1)
# split data in training and test data
train_x, test_x, train_y, test_y = train_test_split(train_data, target_data, test_size=0.33, random_state=42)

run = wandb.init(project='xxx', entity='xxx')

# build model
modelCNN = Sequential()
#add model layers
modelCNN.add(Conv2D(16,
                     kernel_size=(3,3),
                     strides=(1,1),
                     padding='valid',
                     activation='relu',
                     input_shape=(3,3,1)))
modelCNN.add(GlobalMaxPooling2D())
modelCNN.add(Dense(24, activation='relu'))
modelCNN.add(Dense(1, activation='relu'))

#Stochastic gradient descent
sgd = SGD(lr=0.00001, decay=1e-6, momentum=0.9, nesterov=True)

modelCNN.compile(
    optimizer=sgd, 
    loss='mse', 
    metrics=['mse', 'mean_absolute_error'])


#train model
historyCNN=modelCNN.fit(train_x, train_y, 
                        epochs=20,
                        batch_size=16,
                        verbose=1,
                        validation_data=(test_x, test_y),
                        callbacks=[WandbCallback()]
                        )

# evaluate the model
score = modelCNN.evaluate(test_x, test_y, verbose=0)
print(score[0])
print(score[1])
run.log({'evaluate_loss': score[0]})
run.log({'evaluate_mse': score[1]})

#finish run
run.finish()
```

I have used the data that you had sent in. I did not find any issue with the implementation.
![image](https://user-images.githubusercontent.com/36856589/118603855-1350a700-b7d2-11eb-8232-580f7e02deb5.png)

**Comment by LucaUrbinati44** [comment]
I have the EXACT same issue `AttributeError: 'NoneType' object has no attribute 'item'` with the same traceback:
![traceback](https://user-images.githubusercontent.com/25516806/122092637-7140d080-ce0a-11eb-9a59-a5b5bb194c6a.jpg)

In accordance with this issue [https://github.com/wandb/client/issues/724](url), I also experience this: `This doesn't happen all the time but randomly like 1 out of 3 time a script is run`.

I can provide my conda environment if it can help.
[environment.yml.zip](https://github.com/wandb/client/files/6657327/environment.yml.zip)

**Comment by vanpelt** [comment]
@LucaUrbinati44 thanks for the report.  We'll be pushing a fix in the next release, next week.

**Comment by LucaUrbinati44** [comment]
I solved by creating my own callback instead of using WandbCallback():

```
class MyLogger(tf.keras.callbacks.Callback):
    
    def on_epoch_end(self, epoch, logs=None):
    
        wandb.log({"loss": logs["loss"], "val_loss": logs["val_loss"], "my_metric": logs["my_metric"], "val_my_metric": logs["val_my_metric"]})
```
