### ISSUE TITLE
[CLI] - WandB and Pytorch Lightning - PermissionError if WandB is disabled

### ISSUE THREAD

**Issue by oliviersalaun** [wandb/client#2181]
**Description**
I am using WandB integrated in Pytorch Lightning library. Everything works fine except when I disable wandb (I do so for debugging my code). If I enable wandb back, everything goes back to normal.

**Wandb features**
The WandB features come from the PyTorch Lightning library. More below.

**How to reproduce**
from terminal:
`wandb disabled`

The script:
```
import pytorch_lightning as pl
from pytorch_lightning.loggers import WandbLogger
from pytorch_lightning.callbacks import ModelCheckpoint

[...]

wandb_logger = WandbLogger(project=project_name)
wandb_logger.log_hyperparams({'machine': socket.gethostname()})
wandb_logger.log_hyperparams({'env': os.environ['CONDA_DEFAULT_ENV']})

[...]

wandb_logger.log_hyperparams(dict_args)

[...]

wandb_logger.log_hyperparams({'model': model.model_name})

checkpoint_callback = ModelCheckpoint(verbose=True,
                                      monitor='epoch_val_acc',
                                      mode='max',
                                      save_top_k=2)

trainer = pl.Trainer(logger=wandb_logger,
                     max_epochs=args.epochs,
                     gpus=1,
                     callbacks=[checkpoint_callback],
                     )

trainer.fit(model=model, datamodule=train_valid_test_data_module)
```

**Environment**

```
Operating System: Debian GNU/Linux 9 (stretch)
Python 3.8.8 (default, Feb 24 2021, 21:46:12)
[GCC 7.3.0] :: Anaconda, Inc. on linux

_libgcc_mutex             0.1                        main                                                                                                                            
absl-py                   0.12.0                   pypi_0    pypi                                                                                                                    
adapter-transformers      2.0.0                    pypi_0    pypi                                                                                                                    
aiohttp                   3.7.4.post0              pypi_0    pypi                                                                                                                    
argon2-cffi               20.1.0           py38h25fe258_2    conda-forge                                                                                                             
async-timeout             3.0.1                    pypi_0    pypi                                                                                                                    
async_generator           1.10               pyhd3eb1b0_0                                                                                                                            
attrs                     20.3.0             pyhd3deb0d_0    conda-forge                                                                                                             
backcall                  0.2.0              pyhd3eb1b0_0    
backports                 1.0                pyhd3eb1b0_2                                                                                                                  
backports.functools_lru_cache 1.6.3              pyhd3eb1b0_0                                                                                                                        
beautifulsoup4            4.9.3                    pypi_0    pypi                                                                                                                    
blas                      1.0                         mkl                                                                                                                            
bleach                    3.3.0              pyh44b312d_0    conda-forge                                                                                                             
brotlipy                  0.7.0           py38h27cfd23_1003                                                                                                                          
ca-certificates           2021.1.19            h06a4308_1                                                                                                                            
cachetools                4.2.1                    pypi_0    pypi                                                                                                                    
certifi                   2020.12.5        py38h578d9bd_1    conda-forge                                                                                                             
cffi                      1.14.5           py38h261ae71_0                                                                                                                            
chardet                   4.0.0                    pypi_0    pypi                                                                                                                    
click                     7.1.2                    pypi_0    pypi                                                                                                                    
configparser              5.0.2                    pypi_0    pypi                                                                                                                    
cryptography              3.4.7            py38hd23ed53_0                                                                                                                            
cudatoolkit               10.1.243             h6bb024c_0                                                                                                                            
cycler                    0.10.0                     py_2    conda-forge                                                                                                             
dbus                      1.13.18              hb2f20db_0                                                                                                                            
decorator                 5.0.6              pyhd3eb1b0_0                                                                                                                            
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge                                                                                                             
docker-pycreds            0.4.0                    pypi_0    pypi                                                                                                                    
elasticsearch             7.12.0                   pypi_0    pypi                                                                                                                    
emoji                     1.2.0                    pypi_0    pypi                                                                                                                    
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge                                                                                                             
expat                     2.3.0                h2531618_2                                                                                                                            
filelock                  3.0.12                   pypi_0    pypi                                                                                                                    
fontconfig                2.13.1            he4413a7_1000    conda-forge                                                                                                             
freetype                  2.10.4               h5ab3b9f_0                                                                                                                            
fsspec                    0.9.0                    pypi_0    pypi                                                                                                                    
future                    0.18.2                   pypi_0    pypi                                                                                                                    
gitdb                     4.0.7                    pypi_0    pypi                                                                                                                    
gitpython                 3.1.14                   pypi_0    pypi                                                                                                                    
glib                      2.68.1               h36276a3_0                                                                                                                            
google                    3.0.0                    pypi_0    pypi                                                                                                                    
google-auth               1.28.1                   pypi_0    pypi                                                                                                                    
google-auth-oauthlib      0.4.4                    pypi_0    pypi                                                                                                                    
grpcio                    1.37.0                   pypi_0    pypi                                                                                                                    
gst-plugins-base          1.14.0               hbbd80ab_1                                                                                                                            
gstreamer                 1.14.0               h28cd5cc_2                                                                                                                            
icu                       58.2              hf484d3e_1000    conda-forge                                                                                                             
idna                      2.10                     pypi_0    pypi                                                                                                                    
importlib-metadata        3.10.0           py38h06a4308_0                                                                                                                            
intel-openmp              2020.2                      254                                                                                                                            
ipykernel                 5.5.3            py38hd0cf306_0    conda-forge                                                                                                             
ipython                   7.22.0           py38hd0cf306_0    conda-forge                                                                                                             
ipython_genutils          0.2.0              pyhd3eb1b0_1                                                                                                                            
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge                                                                                                             
jedi                      0.18.0           py38h578d9bd_2    conda-forge                                                                                                             
jinja2                    2.11.3             pyhd3eb1b0_0    
joblib                    1.0.1              pyhd3eb1b0_0                                                                                                                   
jpeg                      9b                   h024ee3a_2                                                                                                                            
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge                                                                                                             
jupyter_client            6.1.12             pyhd3eb1b0_0                                                                                                                            
jupyter_contrib_core      0.3.3                      py_2    conda-forge                                                                                                             
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge                                                                                                          
jupyter_core              4.7.1            py38h06a4308_0                                                                                                                            
jupyter_highlight_selected_word 0.2.0           py38h578d9bd_1002    conda-forge                                                                                                     
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge                                                                                                             
jupyter_nbextensions_configurator 0.4.1            py38h578d9bd_2    conda-forge                                                                                                     
jupyterlab_pygments       0.1.2                      py_0                                                                                                                            
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge                                                                                                             
kiwisolver                1.3.1            py38h82cb98a_0    conda-forge                                                                                                             
lcms2                     2.12                 h3be6417_0                                                                                                                            
ld_impl_linux-64          2.33.1               h53a641e_7                                                                                                                            
libffi                    3.3                  he6710b0_2                                                                                                                            
libgcc-ng                 9.1.0                hdf63c60_0                                                                                                                            
libgfortran-ng            7.5.0               h14aa051_18    conda-forge                                                                                                             
libgfortran4              7.5.0               h14aa051_18    conda-forge                                                                                                             
libpng                    1.6.37               hbc83047_0                                                                                                                            
libprotobuf               3.14.0               h8c45485_0                                                                                                                            
libsodium                 1.0.18               h36c2ea0_1    conda-forge                                                                                                             
libstdcxx-ng              9.1.0                hdf63c60_0                                                                                                                            
libtiff                   4.1.0                h2733197_1                                                                                                                            
libuuid                   2.32.1            h14c3975_1000    conda-forge                                                                                                             
libuv                     1.40.0               h7b6447c_0                                                                                                                            
libxcb                    1.13              h14c3975_1002    conda-forge                                                                                                             
libxml2                   2.9.10               hb55368b_3                                                                                                                            
libxslt                   1.1.34               hc22bd24_0                                                                                                                            
lxml                      4.6.3            py38h9120a33_0                                                                                                                            
lz4-c                     1.9.3                h2531618_0                                                                                                                            
markdown                  3.3.4                    pypi_0    pypi                                                                                                                    
markupsafe                1.1.1            py38h8df0ef7_2    conda-forge                                                                                                             
matplotlib                3.3.4            py38h06a4308_0                                                                                                                            
matplotlib-base           3.3.4            py38h62a2d02_0                                                                                                                            
mistune                   0.8.4           py38h25fe258_1002    conda-forge                                                                                                           
mkl                       2020.2                      256                                                                                                                            
mkl-service               2.3.0            py38he904b0f_0                                                                                                                            
mkl_fft                   1.3.0            py38h54f3939_0                                                                                                                            
mkl_random                1.1.1            py38h0573a6f_0                                                                                                                            
multidict                 5.1.0                    pypi_0    pypi                                                                                                                    
nbclient                  0.5.3              pyhd3eb1b0_0                                                                                                                            
nbconvert                 6.0.7            py38h578d9bd_3    conda-forge                                                                                                             
nbformat                  5.1.3              pyhd3eb1b0_0                                                                                                                            
ncurses                   6.2                  he6710b0_1                                                                                                                            
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge                                                                                                             
ninja                     1.10.2           py38hff7bd54_0                                                                                                                            
notebook                  6.3.0            py38h06a4308_0                                                                                                                            
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0                                                                                                                   
oauthlib                  3.1.0                    pypi_0    pypi                                                                                                                    
olefile                   0.46                       py_0                                                                                                                            
openssl                   1.1.1k               h27cfd23_0                                                                                                                            
packaging                 20.9               pyh44b312d_0    conda-forge                                                                                                             
pandas                    1.2.3            py38ha9443f7_0                                                                                                                            
pandoc                    2.12                 h06a4308_0                                                                                                                            
pandocfilters             1.4.3            py38h06a4308_1                                                                                                                            
parso                     0.8.2              pyhd3eb1b0_0                                                                                                                            
pathtools                 0.1.2                    pypi_0    pypi                                                                                                                    
pcre                      8.44                 he1b5a44_0    conda-forge                                                                                                             
pexpect                   4.8.0              pyhd3eb1b0_3                                                                                                                            
pickleshare               0.7.5           pyhd3eb1b0_1003                                                                                                                            
pillow                    8.2.0            py38he98fc37_0                                                                                                                            
pip                       21.0.1           py38h06a4308_0                                                                                                                            
prometheus_client         0.10.1             pyhd8ed1ab_0    conda-forge                                                                                                             
promise                   2.3                      pypi_0    pypi                                                                                                                    
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge                                                                                                             
protobuf                  3.14.0           py38h2531618_1                                                                                                                            
psutil                    5.8.0                    pypi_0    pypi                                                                                                                    
pthread-stubs             0.4               h36c2ea0_1001    conda-forge                                                                                                             
ptyprocess                0.7.0              pyhd3eb1b0_2                                                                                                                            
pyasn1                    0.4.8                    pypi_0    pypi                                                                                                                    
pyasn1-modules            0.2.8                    pypi_0    pypi                                                                                                                    
pycparser                 2.20                       py_2                                                                                                                            
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge                                                                                                             
pyopenssl                 20.0.1             pyhd3eb1b0_1                                                                                                                            
pyparsing                 2.4.7              pyhd3eb1b0_0                                                                                                                            
pyqt                      5.9.2            py38h05f1152_4                                                                                                                            
pyrsistent                0.17.3           py38h25fe258_1    conda-forge                                                                                                             
pysocks                   1.7.1            py38h06a4308_0                                                                                                                            
python                    3.8.8                hdb3f193_4                                                                                                                            
python-dateutil           2.8.1              pyhd3eb1b0_0                                                                                                                            
python_abi                3.8                      1_cp38    huggingface                                                                                                             
pytorch                   1.7.1           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch                                                                                                 
pytorch-lightning         1.2.10                   pypi_0    pypi                                                                                                                    
pytz                      2021.1             pyhd3eb1b0_0                                                                                                                            
pyyaml                    5.3.1                    pypi_0    pypi                                                                                                                    
pyzmq                     20.0.0           py38h2531618_1                                                                                                                            
qt                        5.9.7                h5867ecd_1                                                                                                                            
readline                  8.1                  h27cfd23_0                                                                                                                            
regex                     2021.4.4                 pypi_0    pypi                                                                                                                    
requests                  2.25.1                   pypi_0    pypi                                                                                                                    
requests-oauthlib         1.3.0                    pypi_0    pypi                                                                                                                    
rsa                       4.7.2                    pypi_0    pypi     
sacremoses                0.0.44                   pypi_0    pypi
scikit-learn              0.24.1           py38ha9443f7_0
scipy                     1.6.2            py38h91f5cce_0
seaborn                   0.11.1             pyhd3eb1b0_0
semantic-version          2.8.5                    pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1
sentry-sdk                1.0.0                    pypi_0    pypi
setuptools                52.0.0           py38h06a4308_0
setuptools-rust           0.12.1                   pypi_0    pypi
shortuuid                 1.0.1                    pypi_0    pypi
sip                       4.19.13          py38he6710b0_0
six                       1.15.0           py38h06a4308_0
smmap                     4.0.0                    pypi_0    pypi
soupsieve                 2.2.1                    pypi_0    pypi
sqlite                    3.35.4               hdfb4753_0
subprocess32              3.5.4                    pypi_0    pypi
tensorboard               2.4.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
terminado                 0.9.4            py38h06a4308_0
testpath                  0.4.4              pyhd3eb1b0_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               hbc83047_0
tokenizers                0.10.2                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.7.2                      py38    pytorch
torchmetrics              0.2.0                    pypi_0    pypi
torchvision               0.8.2                py38_cu101    pytorch
tornado                   6.1              py38h27cfd23_0
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5              pyhd3eb1b0_0
transformers              4.6.0.dev0               pypi_0    pypi
typing_extensions         3.7.4.3            pyha847dfd_0
urllib3                   1.26.4             pyhd3eb1b0_0
wand                      0.6.6                    pypi_0    pypi
wandb                     0.10.30                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
yarl                      1.6.3                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0
```

**Terminal output**

```LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "21F_berticles.py", line 280, in <module>
    trainer.fit(model=model, datamodule=train_valid_test_data_module)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 602, in run_train
    self._pre_training_routine()
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _pre_training_routine
    self.on_pretrain_routine_start(ref_model)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 130, in on_pretrain_routine_start
    callback.on_pretrain_routine_start(self, model)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 205, in on_pretrain_routine_start
    self.__resolve_ckpt_dir(trainer)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 464, in __resolve_ckpt_dir
    self._fs.makedirs(self.dirpath, exist_ok=True)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/site-packages/fsspec/implementations/local.py", line 41, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/u/salaunol/anaconda3/envs/e21_c101_t17/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/VF25Cr4g6JbJm9jGexBnKx'```

**Comment by ariG23498** [comment]
Hey @oliviersalaun 
Could you please send in a minimal implementation of the issue you are seeing? A colab notebook would be great.
Thanks.

**Comment by vanpelt** [comment]
@oliviersalaun the error is coming from pytorch lightning attempting to create the runs directory at `/`.  You should configure pytorch lightning to use a directory that's writable such as `/tmp`.

**Comment by oliviersalaun** [comment]
@ariG23498 The data I use is confidentiel, so I cannot show an implementation with it.

@vanpelt The directory seems to be the answer, I added the argument `weights_save_path` in the trainer:

```
trainer = pl.Trainer(logger=wandb_logger,
                     max_epochs=args.epochs,
                     gpus=1,
                     callbacks=[checkpoint_callback],
                     weights_save_path='./pl-output/'
                     )```

Thanks!
