### ISSUE TITLE
[CLI] Sweep agent receiving GraphQL 500s on large project with 3000+ runs

### ISSUE THREAD

**Issue by oscarclivio** [wandb/client#2183]
**Description**
Sweep agent is waiting for a job, but instead 500 errors come. Sometimes, the agent does have a job but it takes several tries to obtain it. Is it a connection error on my side? Or on the W&B servers? This error appeared today on my end.

**Wandb features**
Whether in the original sweep command, or when launching a new sweep through `wandb.agent(sweep_id, function=func)` where `sweep_id` is the ID of the sweep and `func` is the training function, the error comes back over and over. I am running 3 agents at the same time.

**How to reproduce**
I prefer not to disclose the code publicly but can share in private. This seems to be a general issue about sweeps and bad connection.

Here's an example of errors + final successful try. It does like this at every new run.
```
wandb: Sweep Agent: Waiting for job.
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
Retry attempt failed:
Traceback (most recent call last):
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/oscar/miniconda3/envs/matchvae/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
wandb: Network error (HTTPError), entering retry loop. See wandb/debug-internal.log for full traceback.
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Post \"http://anaconda.default.svc.cluster.local/search\": context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Post "http://anaconda.default.svc.cluster.local/search": context deadline exceeded (<Response [500]>)
wandb: Network error resolved after 0:09:17.372202, resuming normal operation.
wandb: Job received.
```

**Environment**
- OS: Ubuntu 20.04.2 LTS
- Environment: Anaconda
- Python Version: Python 3.8.8

**Comment by ariG23498** [comment]
Hey @oscarclivio 
Thanks for the report.
We will try to track it internally.

**Comment by oscarclivio** [comment]
Thanks @ariG23498 for taking care of this. Some update on my side : I realised it was applying to one of my "big" sweeps (with more than 3000 runs inside) : others are fine. I'd be happy to pass more details privately if it helps.

**Comment by oscarclivio** [comment]
Hi @cvphelps . Sorry for the delay in responding. It did block this sweep as it succeeds in finding a run but not until a few minutes. So at a speed much slower than usual.

**Comment by dreamflasher** [comment]
I can confirm this bug.

**Comment by maivincent** [comment]
I am experiencing the same bug on a very big sweep. It happens once the number of runs is higher than 3000 (around 3200 or 3300).

**Comment by dannygoldstein** [comment]
@tsholmes redeploying your backend changes to sweeps with some rate limiting would fix this

**Comment by dannygoldstein** [comment]
@maivincent we have figured out the issue here and are working on a fix. we
have to update some things on our backend. we hope to have this ready soon
for a future release.

**Comment by huangwl18** [comment]
Is there any update to this? I'm also experiencing this issue with only ~500 runs in a sweep. Would greatly appreciate it if there is a fix soon!

**Comment by andreimargeloiu** [comment]
I'm also experiencing the issue on a sweep with 300 runs.

**Comment by RobRomijnders** [comment]
Same here. Seeing the issue on a (relatively) larger sweep. I usually do sweeps of ~2-5, but see this occur for sweeps larger than 10
