### ISSUE TITLE
[CLI] wandb.sweep requires numpy

### ISSUE THREAD

**Issue by noncuro** [wandb/client#2187]
**Description**
Calling `wandb.sweep()` requires numpy, but numpy isn't listed as a dependency for `wandb`

Stack trace:
```
Traceback (most recent call last):
  ...
  File "src/app.py", line 56, in create_sweep_endpoint
    sweep_id = wandb.sweep(sweep_config, entity='instabase', project=project)
  File "/usr/local/lib/python3.8/site-packages/wandb/wandb_controller.py", line 741, in sweep
    from wandb.sweeps.config import SweepConfig
  File "/usr/local/lib/python3.8/site-packages/wandb/sweeps/__init__.py", line 1, in <module>
    from wandb.sweeps.bayes_search import BayesianSearch
  File "/usr/local/lib/python3.8/site-packages/wandb/sweeps/bayes_search.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Wandb features**
`wandb.sweep()`

**How to reproduce**
Run `wandb.sweep()` without `numpy` installed

**Environment**
I'm using the Docker image `python:3.8`

This is my `pip freeze`

```
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
configparser==5.0.2
docker-pycreds==0.4.0
Flask==1.1.2
Flask-Cors==3.0.10
gitdb==4.0.7
GitPython==3.1.14
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==1.1.1
pathtools==0.1.2
promise==2.3
protobuf==3.16.0
psutil==5.8.0
python-dateutil==2.8.1
PyYAML==5.4.1
redis==3.5.3
requests==2.25.1
sentry-sdk==1.1.0
shortuuid==1.0.1
six==1.16.0
smmap==4.0.0
subprocess32==3.5.4
urllib3==1.26.4
wandb==0.10.29
Werkzeug==1.0.1
```

**Comment by dannygoldstein** [comment]
Thanks for catching this @noncuro ! I opened a PR which should hopefully solve this
