### ISSUE TITLE
[Q] Invalid hyperparameter service response (<Response [500]>)

### ISSUE THREAD

**Issue by PhilippS893** [wandb/client#2200]
Dear all, we have recently tried to run sweeps on local machines as well as on colab and encountered the following error:

With wandb version 0.10.30

```
500 response executing GraphQL.
{"errors":[{"message":"Invalid hyperparameter service response","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Invalid hyperparameter service response (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Invalid hyperparameter service response","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Invalid hyperparameter service response (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"Invalid hyperparameter service response","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Invalid hyperparameter service response (<Response [500]>)
Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
wandb: Network error (HTTPError), entering retry loop.
wandb: Sweep Agent: Waiting for job.
500 response executing GraphQL.
{"errors":[{"message":"Invalid hyperparameter service response","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: Invalid hyperparameter service response (<Response [500]>)
```

This interestingly occurs after all sweeps finished. This Error also seems to persist indefinetly such that the program (or cell in Colab) does not terminate. Is this an issue from our side since something in the 'client.py' appears to go wrong?
This errors occurs in another project as well which was previously working fine (about 3-4 days ago).

**Comment by ariG23498** [comment]
Hey @PhilippS893 
Thanks for the ticket. We will be looking into it internally. We will also try providing updates as soon as we have something.

**Comment by cvphelps** [comment]
@PhilippS893 we tracked down an issue related to this and believe it has been resolved. Closing this ticket, please reopen if there are still problems.
