### ISSUE TITLE
[CLI] Updating Dict Values in Config not reflected in Web App

### ISSUE THREAD

**Issue by hv10** [wandb/client#2201]
**Description**
When updating a dictionary based value of the wandb.config of a run, the change is reflected in the script of the run but not in the web app.

**Wandb features**
wandb.init()
wandb.config
wandb.config.update()

**How to reproduce**
```python
import wandb

wandb.init(project="test_nested_update")
config = wandb.config
config.d = {"a": 1}
print(config.d) # shows {"a":1}
config.d["b"] = 2
print(config.d) # shows {"a":1, "b":2}
config.update({"d": {**config.d, "b": 3}}) # fails with error (as expected)
```
Console Output:
```bash
{'a': 1}
{'a': 1, 'b': 2}
wandb: ERROR Attempted to change value of key "d" from {'a': 1, 'b': 2} to {'a': 1, 'b': 3}
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/home/nodanz/RapLyricGeneration/experiments/tests/wandb_nest_issue.py", line 9, in <module>
    config.update({"d": {**config.d, "b": 3}})
  File "/home/nodanz/anaconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 169, in update
    sanitized = self._update(d, allow_val_change)
  File "/home/nodanz/anaconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 162, in _update
    sanitized = self._sanitize_dict(
  File "/home/nodanz/anaconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 218, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/nodanz/anaconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 231, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "d" from {'a': 1, 'b': 2} to {'a': 1, 'b': 3}
If you really want to do this, pass allow_val_change=True to config.update()
```
Screenshot showing that the cfg value was not updated in Web App:

![2021-05-16-152345_841x234_scrot](https://user-images.githubusercontent.com/12249918/118398977-3d338d80-b65b-11eb-80f3-c3c4cb1558ec.png)

**Environment**
- OS: linux (arch)
- Environment: pyenv
- Python Version: 3.8.8

**Comment by ariG23498** [comment]
Hey @hv10 
I tried reproducing the issue and had the following solution for it:
```python
run = wandb.init(project="GH-2201", entity="repro")
with run:
    cfg = wandb.config
    print(cfg)
    cfg.d = {"a": 1}
    print(cfg.d)
    cfg.d["b"] = 2
    print(cfg.d)
    run.config.update({"d": {**cfg.d, "b": 3}})
```

This does not fail and also updates the config of the run.

![image](https://user-images.githubusercontent.com/36856589/118506244-c7a6ea80-b74a-11eb-829a-b2cc1ad7c0c4.png)

**Comment by hv10** [comment]
Sadly the proposed solution did not work for me. Nonetheless adding the `allow_val_change=True` keyword parameter to `run.config.update` did work, which is also fine in my case as I do not change but only add a new value.

**Comment by smartinezai** [comment]
I am also having the same issue
