### ISSUE TITLE
[CLI] Logging dataframe  will rasie an exception

### ISSUE THREAD

**Issue by myaisv** [wandb/client#2210]
**Description**
Logging a table with DataFrame will casue an exception in wandb 0.10.30 ( but version 0.10.11 is ok ):
Code:

```
data = [
    {"c": 1},
    {"c": 2},
]
df = pd.DataFrame(data)

wandb.log({
    "table": wandb.Table(dataframe=df)
})

```

Exception:

```
wandb: ERROR Problem finishing run
Traceback (most recent call last):
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1543, in _atexit_cleanup
    self._on_finish()
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1679, in _on_finish
    self.history._flush()
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 846, in _history_callback
    self._backend.interface.publish_history(
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 217, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2067, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2141, in val_to_json
    return val.to_json(run)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/data_types.py", line 492, in to_json
    json_dict = super(Table, self).to_json(run_or_artifact)
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 500, in to_json
    artifact_entry = self._get_artifact_reference_entry()
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 258, in _get_artifact_reference_entry
    self._artifact_target.artifact.wait()
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 631, in wait
    return self._logged_artifact.wait()
  File "/home/my/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2474, in wait
    assert isinstance(self._instance, ArtifactInterface)
AssertionError
```

**Wandb features**
wandb.log()

**Environment**
- OS: Ubuntu 20.04
- Python Version: 3.8.5

**Comment by vanpelt** [comment]
@myaisv this is an error with the way we're passing around settings.  Are you running this against our cloud hosted server or a server that you're running yourself?  This generally happens if you call `wandb.login()` from within jupyter notebook instead of logging in the host machine.  Can you try running `wandb login` from the command line to configure the machine and see if this error is still occuring.  

You can also set the `WANDB_API_KEY` environment variable, and the `WANDB_BASE_URL` environment variable if you're using a server that you're running yourself.
