### ISSUE TITLE
[Q]How to run self-hosting using Singularity?

### ISSUE THREAD

**Issue by yllgl** [wandb/client#2265]
I want to run W&B locally, Could anybody give me an example for self-hosting using Singularity, not docker? I can't install docker on my computer because I'm not an administrator, but Singularity is availiable. I learn that Singularity could run docker image. So if possible, I want somebody to help me to use Singualrity to run self-hosting.

**Comment by vanpelt** [comment]
Hey @yllgl we don't officially support singularity.  You should be able to follow existing tutorials on running docker containers in singularity however.

**Comment by yllgl** [comment]
> Hey @yllgl we don't officially support singularity. You should be able to follow existing tutorials on running docker containers in singularity however.

Could I run self-hosting without root?
I think it's a huge problem because I'm not administrator.

**Comment by yllgl** [comment]
> Hey @yllgl we don't officially support singularity. You should be able to follow existing tutorials on running docker containers in singularity however.

Could you tell me which file I should run if I'm in containers? I use singularity shell to run wandb, and want to run wandb manually.
```shell
Singularity> cd /home/wandb
Singularity> ls -FR
./service:
anaconda/  gorilla/  gorilla-filemeta/  jobber/  local/  loginsrv/  minio/  mysql/  netdata/  nginx/  redis/

./service/anaconda:
run*

./service/gorilla:
run*  schema2.graphql  schema.graphql

./service/gorilla-filemeta:
run*

./service/jobber:
run*

./service/local:
run*

./service/loginsrv:
run*

./service/minio:
run*

./service/mysql:
mysql/  run*

./service/mysql/mysql:
fixtures/  migrations/

./service/mysql/mysql/fixtures:
custom_charts.tsv  README.md  shared_views.tsv

./service/mysql/mysql/migrations:
001_init.down.sql                          057_report_images.up.sql
001_init.up.sql                            058_artifacts.down.sql
002_run_delete.down.sql                    058_artifacts.up.sql
002_run_delete.up.sql                      059_files_digest_index.down.sql
003_line_count.down.sql                    059_files_digest_index.up.sql
003_line_count.up.sql                      060_runs_sweep_index.down.sql
004_sweeps.down.sql                        060_runs_sweep_index.up.sql
004_sweeps.up.sql                          061_published_works.down.sql
005_run_stopped.down.sql                   061_published_works.up.sql
005_run_stopped.up.sql                     062_run_created_index.down.sql
006_run_keyset.down.sql                    062_run_created_index.up.sql
006_run_keyset.up.sql                      063_artifact_collections.down.sql
007_tag_coloring.down.sql                  063_artifact_collections.up.sql
007_tag_coloring.up.sql                    064_artifact_aliases_fix.down.sql
008_run_agent.down.sql                     064_artifact_aliases_fix.up.sql
008_run_agent.up.sql                       065_collaborative_reports.down.sql
009_auth_user_index.down.sql               065_collaborative_reports.up.sql
009_auth_user_index.up.sql                 066_view_backups.down.sql
010_view_spec.down.sql                     066_view_backups.up.sql
010_view_spec.up.sql                       067_user_deleted_at.down.sql
011_project_docker.down.sql                067_user_deleted_at.up.sql
011_project_docker.up.sql                  068_photo_url_text.down.sql
012_benchmarks.down.sql                    068_photo_url_text.up.sql
012_benchmarks.up.sql                      069_user_onboarding_steps.down.sql
013_benchmark_run_json.down.sql            069_user_onboarding_steps.up.sql
013_benchmark_run_json.up.sql              070_artifact_manifest.down.sql
014_user_info.down.sql                     070_artifact_manifest.up.sql
014_user_info.up.sql                       071_run_queues.down.sql
015_badge.down.sql                         071_run_queues.up.sql
015_badge.up.sql                           072_artifact_attributes.down.sql
016_integration.down.sql                   072_artifact_attributes.up.sql
016_integration.up.sql                     073_view_showcased_at.down.sql
017_user_private.down.sql                  073_view_showcased_at.up.sql
017_user_private.up.sql                    074_artifact_user_references.down.sql
018_alert.down.sql                         074_artifact_user_references.up.sql
018_alert.up.sql                           075_entity_rate_limit.down.sql
019_default_access.down.sql                075_entity_rate_limit.up.sql
019_default_access.up.sql                  076_entity_settings.down.sql
020_tags_json.down.sql                     076_entity_settings.up.sql
020_tags_json.up.sql                       077_artifact_updated_at.down.sql
021_project_tags_name.down.sql             077_artifact_updated_at.up.sql
021_project_tags_name.up.sql               078_project_deleted_at.down.sql
022_run_tags_backfill.down.sql             078_project_deleted_at.up.sql
022_run_tags_backfill.up.sql               079_artifacts_cleanup.down.sql
023_alert_timestamps.down.sql              079_artifacts_cleanup.up.sql
023_alert_timestamps.up.sql                080_discussion_thread_deleted_at.down.sql
024_run_display_name.down.sql              080_discussion_thread_deleted_at.up.sql
024_run_display_name.up.sql                081_files_bigger.down.json
025_run_display_name_as_test.down.sql      081_files_bigger.up.json
025_run_display_name_as_test.up.sql        082_artifact_manifest_file_id.down.sql
026_remove_tag_keys.down.sql               082_artifact_manifest_file_id.up.sql
026_remove_tag_keys.up.sql                 083_alerts_view_id.down.sql
027_drop_tags.down.sql                     083_alerts_view_id.up.sql
027_drop_tags.up.sql                       084_access_tokens.down.sql
028_run_created_at_index.down.sql          084_access_tokens.up.sql
028_run_created_at_index.up.sql            085_artifacts_overhaul.down.sql
029_task.down.sql                          085_artifacts_overhaul.up.sql
029_task.up.sql                            086_custom_charts.down.sql
030_sweeps_controller.down.sql             086_custom_charts.up.sql
030_sweeps_controller.up.sql               087_convert_custom_charts.down.sql
031_hidden_benchmark_runs.down.sql         087_convert_custom_charts.up.sql
031_hidden_benchmark_runs.up.sql           088_artifact_collections.down.sql
032_project_tags_collation.down.sql        088_artifact_collections.up.sql
032_project_tags_collation.up.sql          089_storage_stats.down.sql
033_views_spec_utf8.down.sql               089_storage_stats.up.sql
033_views_spec_utf8.up.sql                 090_deleted_runs_with_artifacts.down.sql
034_discussion_threads.down.sql            090_deleted_runs_with_artifacts.up.sql
034_discussion_threads.up.sql              091_alert_event_title_text.down.sql
035_invite_admin.down.sql                  091_alert_event_title_text.up.sql
035_invite_admin.up.sql                    092_local_licenses.down.sql
036_anonymous_claims.down.sql              092_local_licenses.up.sql
036_anonymous_claims.up.sql                093_artifact_dependencies.down.sql
037_github_backed_benchmarks.down.sql      093_artifact_dependencies.up.sql
037_github_backed_benchmarks.up.sql        094_storage_stats_reset.down.sql
038_run_color_idx.down.sql                 094_storage_stats_reset.up.sql
038_run_color_idx.up.sql                   095_artifact_nullable_type.down.sql
039_project_fields.down.sql                095_artifact_nullable_type.up.sql
039_project_fields.up.sql                  096_optional_stripe.down.sql
040_views_type_updated_idx.down.sql        096_optional_stripe.up.sql
040_views_type_updated_idx.up.sql          097_users_utf8mb4.down.sql
041_views_longtext.down.sql                097_users_utf8mb4.up.sql
041_views_longtext.up.sql                  098_fix_email_subscriptions.down.sql
042_user_info_text.down.sql                098_fix_email_subscriptions.up.sql
042_user_info_text.up.sql                  099_pricing_stats.down.sql
043_sweep_priors.down.sql                  099_pricing_stats.up.sql
043_sweep_priors.up.sql                    100_organizations_is_org.down.sql
044_sweep_display_names.down.sql           100_organizations_is_org.up.sql
044_sweep_display_names.up.sql             101_project_entity_storage_key_ix.down.sql
045_project_display_name.down.sql          101_project_entity_storage_key_ix.up.sql
045_project_display_name.up.sql            102_local_licenses_note.down.sql
046_project_storage_key.down.sql           102_local_licenses_note.up.sql
046_project_storage_key.up.sql             103_distributed_artifacts.down.sql
047_payments.down.sql                      103_distributed_artifacts.up.sql
047_payments.up.sql                        104_audit_mutation_events.down.sql
048_project_storage_key_backfill.down.sql  104_audit_mutation_events.up.sql
048_project_storage_key_backfill.up.sql    105_audit_action_effect.down.sql
049_star_views.down.sql                    105_audit_action_effect.up.sql
049_star_views.up.sql                      106_delete_benchmark_runs_in_deleted_benchmarks.down.sql
050_shared_views.down.sql                  106_delete_benchmark_runs_in_deleted_benchmarks.up.sql
050_shared_views.up.sql                    107_storage_stats_reset.down.sql
051_payments_timestamps.down.sql           107_storage_stats_reset.up.sql
051_payments_timestamps.up.sql             108_organization_subscription_status.down.sql
052_organization_invites.down.sql          108_organization_subscription_status.up.sql
052_organization_invites.up.sql            109_add_indices_collections_projects.down.sql
053_drop_file_index.down.sql               109_add_indices_collections_projects.up.sql
053_drop_file_index.up.sql                 110_fix_organization_status.down.sql
054_file_project_index.down.sql            110_fix_organization_status.up.sql
054_file_project_index.up.sql              111_update_discussion_poster_entity_id_constraints.down.sql
055_drop_file_foreign_key.down.sql         111_update_discussion_poster_entity_id_constraints.up.sql
055_drop_file_foreign_key.up.sql           112_add_runs_scrubber_state.down.sql
056_file_storage_keys.down.sql             112_add_runs_scrubber_state.up.sql
056_file_storage_keys.up.sql               README.md
057_report_images.down.sql

./service/netdata:
down  run*

./service/nginx:
run*

./service/redis:
run*
```

**Comment by joelrorseth** [comment]
Hey @yllgl, thanks for raising this issue. I am also trying to self-host using Singularity, which is my only option given that sweeps are not supported in offline mode, and that my HPC system is not connected to internet. I feel like this issue deserves more attention, as I'm sure many researchers will use wandb with offline HPC systems.

I was able to create a Singularity image (eg. `wandb.sif`) from the Docker Hub wandb container, but I get an error when I run the image. Would you mind providing the steps you followed to download / convert / run the wandb Docker container?

I am also hoping to see your `singularity run` command, since I'm not sure how to convert the full Docker command with arguments) to the Singularity equivalent. For reference, here is the full Docker command from wandb docs: `docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local`

Thanks!

**Comment by yllgl** [comment]
@joelrorseth make sure your error is the same as me. If not, I can't help you.
```
[hugpu1@th-es-ln0 ~]$ yhrun -N 1 -p TH_GPU singularity run ./wandb.sif
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (122) bind mounts
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 430, in <module>
  File "/sbin/my_init", line 341, in main
    export_envvars()
  File "/sbin/my_init", line 116, in export_envvars
    with open("/etc/container_environment/" + name, "w") as f:
OSError: [Errno 30] Read-only file system: '/etc/container_environment/BASH_FUNC_module()'
INFO:    Cleaning up image...
yhrun: error: gn24: task 0: Exited with exit code 1
```
As you can see, the main error is `Read-only file system` error. So all you should do is to make the file system writable.
Firstly, check you could run command `singularity shell wandb.sif` successfully. For me , it can only run in compute node, otherwise an error occurs when running in login node.
All you need is the following flag.
`-B, --bind strings           a user-bind path specification.  spec has the format src[:dest[:opts]], where src and dest are outside and inside paths.`
For example, run `mkdir $HOME/wandb_files && cd $HOME/wandb_files && mkdir ./tmp` to create tmp directory.
1. run `singularity shell -B  $HOME/wandb_files/tmp:/tmp wandb.sif`, then you should be in shell command mode. 
2. you need to move `/etc`,`/home`,`/vol`,`/var`,`/run` to `/tmp` in order to make them outside the container. For example,run `cp -r /etc /tmp` in shell.
3. then exit the shell. The `/etc`,`/home`,`/vol`,`/var`,`/run` should be in your `$HOME/wandb_files/tmp`.
4. then use `-B` flag to bind your `/etc`,`/home`,`/vol`,`/var`,`/run` outside container . As for me, I move all files in `$HOME/wandb_files/tmp` to `$HOME/wandb_files`. So I run `singularity run -B $HOME/wandb_files/etc:/etc -B $HOME/wandb_files/home:/home -B $HOME/wandb_files/vol:/vol -B $HOME/wandb_files/var:/var -B $HOME/wandb_files/run:/run wandb.sif`

Finally, it should run successfully.
By the way, if you want to make port mapping, you could use `--network-args` flag, but I have not tried it.

**Comment by joelrorseth** [comment]
@yllgl Thanks for the quick reply! Yes this is exactly the error I am getting, `OSError: [Errno 30] Read-only file system:`.

I tried your steps, which all work just fine, expect for copying those fives directories to `/tmp` in Step 2. Since I don't have sudo access on my HPC system, I get permission denied errors when copying several files located within `/etc` and `/var`. Did you experience this?

Despite a few of these files not copying, I was still able to run singularity without any read-only errors. However I think something is wrong, since my first run eventually hangs, and subsequent runs just fail. It may be due to those files that did not copy. Would you mind reviewing my console output below?

**1st Run:**
```
[rorsethj@gra286 wandb-local]$ singularity run -B wandb_volume/tmp/home:/home -B wandb_volume/tmp/vol:/vol -B wandb_volume/tmp/run:/run -B wandb_volume/tmp/etc:/etc -B wandb_volume/tmp/var:/var wandb.sif
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
chgrp: changing group of '/vol/env': Operation not permitted
*** Loading settings...
2021/06/13 17:18:33 Created default user
2021/06/13 17:18:33 Generating new certificate and key for auth...
*** Booting runit daemon...
*** Runit started as PID 1838
*** Setting up mysql database...
*** Starting wandb servers...
*** Configuring minio...
Bucket created successfully `local/local-files`.
Successfully added arn:minio:sqs:wandb-local:_:redis
chgrp: changing group of '/home/rorsethj/.mc': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/session': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/certs': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/certs/CAs': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/config.json.old': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/config.json': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/share': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/share/uploads.json': Operation not permitted
chgrp: changing group of '/home/rorsethj/.mc/share/downloads.json': Operation not permitted
chgrp: changing group of '/vol/env/minio-config.json': Operation not permitted
```

**2nd Run:**
```
[rorsethj@gra286 wandb-local]$ singularity run -B wandb_volume/tmp/home:/home -B wandb_volume/tmp/vol:/vol -B wandb_volume/tmp/run:/run -B wandb_volume/tmp/etc:/etc -B wandb_volume/tmp/var:/var wandb.sif
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
mv: cannot stat '/home/wandb/service/*': No such file or directory
mv: cannot stat '/home/wandb/wandb-logrotate': No such file or directory
*** Copying jobber template
*** Enabling production mode
ln: failed to create symbolic link '/etc/nginx/sites-enabled/wandb.conf': File exists
*** /etc/my_init.d/01_enable-services.sh failed with status 1

*** Killing all processes...
```

Thanks for your help!

**Comment by yllgl** [comment]
After running first time will delete /home/wandb files automatically, I don't know if it will delete other files. So I copy those `/etc`,`/home`... directories again when running second time. And I upload `/etc`,`/var` for you. I think it will help. If not, I have no idea.
[var_etc.zip](https://github.com/wandb/client/files/6646624/var_etc.zip)
