### ISSUE TITLE
[CLI] Error while calling W&B API: Error 1213: Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by yqsony** [wandb/client#2269]
**Description**
I was running a pytorch training session for three days. There seemed to be a network issue last night. But the wandb crashed when it tried to resume network connection

wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error resolved after 0:11:03.206268, resuming normal operation.
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: 500 encountered ({"errors":[{"message":"Error 1213: Deadlock found when trying to get lock; try restarting transaction","path":["createArtifactManifest"]}],"data":{"c
reateArtifactManifest":null}}), retrying request
wandb: Network error resolved after 0:00:45.015387, resuming normal operation.
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Problem finishing run
Traceback (most recent call last):
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1532, in _atexit_cleanup
    self._on_finish()
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1668, in _on_finish
    self.history._flush()
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 836, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 217, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/data_types.py", line 2066, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/data_types.py", line 2138, in val_to_json                                           [17/5166]
    run.log_artifact(art)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2096, in log_artifact
    return self._log_artifact(artifact_or_path, name, type, aliases)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2217, in _log_artifact
    self._assert_can_log_artifact(artifact)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2256, in _assert_can_log_artifact
    public_api.settings["project"],
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/apis/public.py", line 2852, in expected_type
    "name": name,
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/old/retry.py", line 139, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/old/retry.py", line 100, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/apis/public.py", line 182, in execute
    return self._client.execute(*args, **kwargs)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/quan/anaconda3/envs/pytorch/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

**Environment**
- OS: [Ubuntu 18.04]
- Environment: [anaconda3]
- Python Version: [3.7.7]
- Pytorch version: [1.7.0]

**Comment by vanpelt** [comment]
Thanks for reporting, we'll look into the root cause.  What version of wandb were you running?  You can run `wandb sync path_to_run_directory` to push any unstreamed metrics to the server.

**Comment by yqsony** [comment]
I was running it in 0.10.28. Yes, I was able to upload the data later by Wandb sync. Thanks, -Quan
