### ISSUE TITLE
[CLI] wandb.agent() does not pass config parameter to train function

### ISSUE THREAD

**Issue by 7Z0nE** [wandb/client#2299]
**Description**
I am trying to run a sweep using the python sweeps api but wand fails with an erro upon calling wandb.agent(...)

**Script output**
```
wandb: Agent Starting Run: ecuc9ew8 with config:
wandb: 	decay: 1e-07
wandb: 	dropout: 0.3
wandb: 	epochs: 27
wandb: 	hidden_layer_size: 96
wandb: 	layer_1_size: 18
wandb: 	layer_2_size: 28
wandb: 	learn_rate: 0.01
wandb: 	momentum: 0.9
Problem finishing run
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 303, in _run_job
    self._function()
TypeError: train() missing 1 required positional argument: 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1543, in _atexit_cleanup
    self._on_finish()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1681, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1579, in _console_stop
    self._restore()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1513, in _restore
    self._err_redir.uninstall()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 631, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/usr/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 563, in remove_fd
    self._unregister()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 551, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/usr/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
wandb: ERROR Problem finishing run
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 303, in _run_job
    self._function()
TypeError: train() missing 1 required positional argument: 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1543, in _atexit_cleanup
    self._on_finish()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1681, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1579, in _console_stop
    self._restore()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1513, in _restore
    self._err_redir.uninstall()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 631, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/usr/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 563, in remove_fd
    self._unregister()
  File "/usr/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 551, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/usr/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Script (for reproduction)**
 ```
import wandb

wandb.init(project='test-project')

def train(config):
    print(wandb.config)

config = dict(
    method= 'bayes',
    metric=dict(
        goal= 'minimize',
        name= 'val_loss'),
    parameters=dict(
        dropout=dict(
            values= [0.15, 0.2, 0.25, 0.3, 0.4]),
        hidden_layer_size=dict(
            values= [96, 128, 148]),
        layer_1_size=dict(
            values= [10, 12, 14, 16, 18, 20]),
        layer_2_size=dict(
            values= [24, 28, 32, 36, 40, 44]),
        learn_rate=dict(
            values= [0.001, 0.01, 0.003]),
        decay=dict(
            values= [1e-5, 1e-6, 1e-7]),
        momentum=dict(
            values= [0.8, 0.9, 0.95]),
        epochs=dict(
            value= 27)
    )
)

sweep_id = wandb.sweep(config, project='test-project')
wandb.agent(
    sweep_id=sweep_id,
    function=train,
    count=1)
```
**Environment**
- OS: [Linux version 5.12.10-arch1-1 (linux@archlinux)]
- Environment: [conda]
- Python Version: [eg. 3.9]
- wandb version: [0.10.32]

**Comment by vanpelt** [comment]
This is correct.  Instead of passing in config as an argument you can access it via `wandb.config` or `wandb.run.config`.  You should be calling `wandb.init` inside of your `train` function.  After which you'll be able to access the current trials config.

**Comment by 7Z0nE** [comment]
Thanks a lot for clearing this up!
