### ISSUE TITLE
[CLI] Get error when using wandb with multiprocessing package

### ISSUE THREAD

**Issue by xjh19971** [wandb/client#2330]
**Description**
With wandb, when I am using multiprocessing.Pool related function, it reports that it cannot find a corresponding function in my program.

**Wandb features**
wandb.init(), wandb.agent()

**How to reproduce**
Unfortunately, I cannot share the scripts, but I will describe the program's structure for you and let me know if you need more information.

```
import wandb
from multiprocessing import Pool

def process_one_episode(**kwargs):
    ...

def train(**kwargs):
    ...

def eval(**kwargs):
    pool = Pool(num_processes)
    result_list = []
    for i in range(n_examples):
        result_list.append(
        pool.apply_async(
             process_one_episode, (
                    **kwargs
                )
            )
       )

def main(**kwargs):
    wandb.init()
    train(**kwargs)
    eval(**kwargs)

if __name__ == '__init__':
    wandb.agent(sweep_id, function=lambda: main(**kwargs), count=1)

```
The error message is:
```
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "***/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "***/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "***/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "***/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_one_episode' on <module 'wandb.mpmain.__main__' from '***/lib/python3.7/site-packages/wandb/mpmain/__main__.py'>
```

**Environment**
- OS:  Red Hat Enterprise Linux 8.2 (Ootpa)
- Environment: anaconda
- Python Version: 3.7.9

**Comment by cvphelps** [comment]
Hi there, this should be fixed in the next client release
