### ISSUE TITLE
Getting error when using Sweep

### ISSUE THREAD

**Issue by VirajBagal** [wandb/client#2357]
I have made the following sweep.yaml file:

```
program: main.py
method: bayes
metric:
  name: val_epoch_loss
  goal: minimize
parameters:
  lr:
    distribution: normal
    min: 0.00001
    max: 0.001
name: debug
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
project: axial_disc_classification
entity: vbagal
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --image_size=256 --num_epochs=15 --batch_size=64 --use_fp16 --mode=train --model=resnet18 --num_classes=3 --type=image mask sagittal
 ```

I get the following error when I execute `wandb agent sweep-id`

```
wandb: Starting wandb agent 🕵️
400 response executing GraphQL.
{"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
wandb: ERROR Error while calling W&B API: name required for project query (<Response [400]>)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 534, in sweep
    response = self.gql(
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/cli/cli.py", line 815, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/wandb_agent.py", line 562, in agent
    return run_agent(
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/wandb_agent.py", line 519, in run_agent
    agent.run()
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/wandb_agent.py", line 181, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/apis/internal.py", line 86, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/home/user/anaconda3/envs/synapsica_pytorch_new/lib/python3.8/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.error.CommError: <Response [400]>

Error: <Response [400]>
```

**Comment by dannygoldstein** [comment]
Hi Viraj,

Sorry you ran into this - when starting a sweep with `agent`, you need to pass the full sweep path,

`wandb agent vbagal/axial_disc_classification/o2v6ld0v`

rather than just the sweep name

`wandb agent o2v6ld0v`

When I run the command above ^^ I reproduce the error you are seeing.

Can you try it with the full path and let me know if that fixes it?

**Comment by Danielohayon** [comment]
> Hi Viraj,
> 
> Sorry you ran into this - when starting a sweep with `agent`, you need to pass the full sweep path,
> 
> `wandb agent vbagal/axial_disc_classification/o2v6ld0v`
> 
> rather than just the sweep name
> 
> `wandb agent o2v6ld0v`
> 
> When I run the command above ^^ I reproduce the error you are seeing.
> 
> Can you try it with the full path and let me know if that fixes it?

I had the same issue and this did the trick for me.
Thanks!

**Comment by VirajBagal** [comment]
Hi Danny,

I tried with full path and it is working for me but there is one peculiarity! 

When I use the following sweep.yaml, it works normally:

```
program: main.py
method: bayes
metric:
  name: val_epoch_loss
  goal: minimize
parameters:
  lr:
    distribution: normal
    min: 0.00001
    max: 0.001
name: debug
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
project: axial_disc_classification
entity: vbagal
```

But when I use the following sweep.yaml with arguments, I get error:

```
program: main.py
method: bayes
metric:
  name: val_epoch_loss
  goal: minimize
parameters:
  lr:
    distribution: normal
    min: 0.00001
    max: 0.001
name: debug
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
project: axial_disc_classification
entity: vbagal
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --image_size=256 --num_epochs=15 --batch_size=64 --use_fp16 --mode=train --model=resnet18 --num_classes=3 --type=image mask sagittal
 ```

The error:

```
wandb: Starting wandb agent 🕵️
2021-07-07 12:03:36,175 - wandb.wandb_agent - INFO - Running runs: []
2021-07-07 12:03:36,625 - wandb.wandb_agent - INFO - Agent received command: run
2021-07-07 12:03:36,625 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.3673609308758731
2021-07-07 12:03:36,626 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python main.py "--image_size=256 --num_epochs=15 --batch_size=64 --use_fp16 --mode=train --model=resnet18 --num_classes=3 --type=image mask sagittal"
usage: main.py [-h] [--json_path JSON_PATH] [--ckpt_path CKPT_PATH]
               [--num_epochs NUM_EPOCHS] [--num_classes NUM_CLASSES]
               [--batch_size BATCH_SIZE] [--image_size IMAGE_SIZE]
               [--threshold THRESHOLD] [--num_image_save NUM_IMAGE_SAVE]
               [--lr LR] [--smoothing SMOOTHING] [--model MODEL] [--mode MODE]
               [--use_fp16] [--swa] [--multilabel] [--type TYPE [TYPE ...]]
               [--use_original] [--cyclelr] [--review]
main.py: error: argument --image_size: invalid int value: '256 --num_epochs=15 --batch_size=64 --use_fp16 --mode=train --model=resnet18 --num_classes=3 --type=image mask sagittal'
```

How can I fix it?

The argument parser in my main.py file is the following:

```
    parser = argparse.ArgumentParser()
    parser.add_argument("--json_path", default='/SSD1TB/viraj/axial_disc/data_jsons/all_data_with_folds_changedcrop.json', help='path to data folder')
    parser.add_argument("--ckpt_path", default='/SSD1TB/viraj/axial_disc/code/classification/checkpoints', help='path to main checkpoints dir')
    parser.add_argument("--num_epochs", default=15, type=int, help="num_epochs")
    parser.add_argument("--num_classes", default=3, type=int, help="number of classes")
    parser.add_argument("--batch_size", default=32, type=int, help="batch_size")
    parser.add_argument("--image_size", default=384, type=int)
    parser.add_argument("--threshold", default=0.5, type=float, help = 'for each class')
    parser.add_argument("--num_image_save", default=100, type=int, help="Number of images to save of validation")
    parser.add_argument("--lr", default=1e-4, type=float, help='learning_rate')
    parser.add_argument("--smoothing", default=0, type=float, help='label smoothing')
    parser.add_argument("--model", default='resnet18', help="resnet18, resent34, resnet50, resnet101, resnet152")
    parser.add_argument("--mode", default = 'train', help='use one among "train, test, analysis')
    parser.add_argument("--use_fp16", action = 'store_true', help='use fp16 training')
    parser.add_argument("--swa", action = 'store_true', help='use SWA for potential generalization')
    parser.add_argument("--multilabel", action = 'store_true', help='multilabel training with granular classes')
    parser.add_argument("--type", nargs = "+", default = ['image', 'mask', 'sagittal'], help='list of input modalities to be used for training')
    parser.add_argument("--use_original", action = 'store_true', help='use original mask for training')
    parser.add_argument("--cyclelr", action = 'store_true', help='use cyclic learning rate')
    parser.add_argument('--review', action='store_true', help='use this to NOT save anything during review run')
```

Thank you in advance.

**Comment by Danielhp95** [comment]
To add to this conversation:

The current state of the official documentation state that you only need to pass the `sweep_id` to the `wandb agent` command. I suggest to change the official docs to reflect that more info is needed!

https://docs.wandb.ai/ref/cli/wandb-agent

Thanks for everything

**Comment by dannygoldstein** [comment]
> To add to this conversation:
> 
> The current state of the official documentation state that you only need to pass the `sweep_id` to the `wandb agent` command. I suggest to change the official docs to reflect that more info is needed!
> 
> https://docs.wandb.ai/ref/cli/wandb-agent
> 
> Thanks for everything

Done. 

Closing this as the original issue has now been addressed. @VirajBagal I am moving your latest question to a separate issue.
