### ISSUE TITLE
[CLI] TypeError: 'DataGenerator' object is not an iterator

### ISSUE THREAD

**Issue by bmabir17** [wandb/client#2371]
**Description**
I am trying to log the validation results(model output) of a classification model to wandb. My dataset is of type keras DataGenerator. And i am using the following to fit my model and call wandb
 ```python
    log = model.fit(x=training_gen,
                          validation_data=validation_gen,
                          workers=9,  # realtime loading with parallel processing
                          epochs=config.epochs, verbose=1,
                          callbacks=[
                              WandbCallback(
                                  save_model=True,
                                  mode="auto",
                                  input_type="image",
                                  labels=['bad','good'],
                                  predictions=1)])
```
And get the following error:
```
Traceback (most recent call last):
  File "./train.py", line 79, in <module>
    log = model.fit(x=training_gen,
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 124, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 470, in on_epoch_end
    self.validation_data = next(self.generator)
TypeError: 'SmartDataGenerator' object is not an iterator
```
**My model gets trained properly if I don't pass any parameters inside wandbCallback().**

I have also tried the following and get the same error
```python
    log = model.fit(x=training_gen,
                          validation_data=validation_gen,
                          workers=9,  # realtime loading with parallel processing
                          epochs=config.epochs, verbose=1,
                          callbacks=[
                              WandbCallback(
                                  save_model=True,
                                  mode="auto",
                                  input_type="image",
                                  generator=validation_gen,
                                  validation_steps=100,
                                  labels=['bad','good'],
                                  predictions=1)])
```

**Wandb features**
WandbCallback(save_model=True,
                                  mode="auto",
                                  input_type="image",
                                  labels=['bad','good'],
                                  predictions=1)

**How to reproduce**
https://gist.github.com/bmabir17/78cdf6766469efb1212a2fab71114c70

**Environment**
- OS: Ubuntu 18.04
- Environment: GCP instance with Anaconda
- wandb version 0.10.33 (installed with pip)
- Python Version:  3.8.10

**Comment by vanpelt** [comment]
Our callback currently assumes the generator will adhear to the python iterator protocol.  Can you try turning your sequence into an iterator when specifying it in the callback?

```
WandbCallback(
                                  save_model=True,
                                  mode="auto",
                                  input_type="image",
                                  generator=iter(validation_gen),
                                  validation_steps=100
                                  labels=['bad','good'],
                                  predictions=1)
```

**Comment by bmabir17** [comment]
@vanpelt using `iter()` gives me the following error
```
File "./train.py", line 85, in <module>
    log = model.fit(x=training_gen,
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 124, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/home/bmabir/anaconda3/envs/360_image_clf/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 470, in on_epoch_end
    self.validation_data = next(self.generator)
TypeError: 'SmartDataGenerator' object is not an iterator
```

**Comment by JordanMakesMaps** [comment]
@vanpelt this worked for me. @bmabir17 my data generator is of class `keras.utils.Sequence`, and the callback for me looks like:

```python

    WandbCallback(generator = iter(test_gen), validation_steps = test_steps, labels = class_labels, 
                           class_colors = class_colors, predictions = 5, 
                           input_type = 'segmentation_mask', output_type = 'segmentation_mask')
```
