### ISSUE TITLE
[CLI] One Wandb-tracked run failing causes other wandb-tracked runs to fail

### ISSUE THREAD

**Issue by MatthewGleeson** [wandb/client#2391]
**Description**
I was running 4 different experiments on an Oracle Grid Engine(aka Sun Grid Engine) cluster. This morning one of my experiments failed from running out of the memory I had allocated to it, and immediately afterwards 2 of the other experiments failed, with identical errors:

Error in atexit._run_exitfuncs:  
Traceback (most recent call last):  
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1602, in _atexit_cleanup  
    self._on_finish()   
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1738, in _on_finish  
    self.history._flush()   
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush  
    self._callback(row=self._data, step=self._step)   
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 933, in _history_callback  
    row, step, publish_step=not_using_tensorboard   
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 232, in publish_history  
    self._publish_history(history)  
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 211, in _publish_history  
    self._publish(rec)  
  File "/home/mgleeson/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 536, in _publish  
    raise Exception("The wandb backend process has shutdown")  
Exception: The wandb backend process has shutdown

Interestingly, the remaining experiment of the 4 remained intact. It was also coincidentally running on the same machine that encountered the out of memory error, while the experiments that failed were running on different machines.

This is the second time I've had this issue with one experiment failing causing the others to fail, but it doesn't happen every time an experiment fails.

**Wandb features**
wandb.init(), wandb.log(), wandb.watch()

**How to reproduce**
run multiple experiments on cluster, one experiment fails causing others to fail
-only happens once in a while

**Environment**
- OS: linux
- Environment: Python Script
- Python Version:  3.7.0
- Wandb Version: '0.10.32'

**Comment by anmolmann** [comment]
Hi @MatthewGleeson, so sorry about this. For a bit more context, there is a logfile (the debug logs) that will give us details about the root cause.  Do you still have access to the filesystems any of these failed runs happen on?

**Comment by sydholl** [comment]
Because this issue has gone stale, we are closing it. Please comment to reopen.
