### ISSUE TITLE
Agents stall in errors

### ISSUE THREAD

**Issue by emanuelevivoli** [wandb/client#2408]
**Describe the bug**
When running agents, I got:
```python
500 response executing GraphQL.
{"errors":[{"message":"context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
Retry attempt failed:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/user/miniconda3/envs/thesis/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
wandb: Network error (HTTPError), entering retry loop.
500 response executing GraphQL.
{"errors":[{"message":"context deadline exceeded","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
```

**To Reproduce**
1. Go to ''create_sweep'
2. Run locally multiple agents
3. See error appear in the agents' console logs

**Expected behavior**
The agents to run and log to wandb artifacts. Not  to crush.

**Additional context**
I read [here](https://github.com/wandb/client/issues/1323#issuecomment-704609031) it may be caused by some boolean settings on sweep configuration. I do not have any boolean variables here.

**Comment by vanpelt** [comment]
Hey @emanuelevivoli this is likely due to your search parameters being too complex causing the backend to timeout.  Can you share your sweep config?

**Comment by emanuelevivoli** [comment]
hi @vanpelt ,
sorry for the late answer, but I shifted on another project and I totaly forgot about this issue.
From what I remember, I had something like 7k runs in a sweep, with grid search.
I close the issue because it is from 3 months ago. 
Thanks anyway.
