### ISSUE TITLE
[CLI]  wandb: ERROR Problem finishing run ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by hazel-erickson** [wandb/client#2413]
**Description**
At the end of the current run, I encounter this error which crashes my runtime.

**Wandb features**
Using wandb.init() and wb.log(), attempted to use wb.finish() to stop run and avoid the crash but this doesn't help. 

Full error:

Traceback (most recent call last): File "/miniconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1601, in _atexit_cleanup self._on_finish() File "/miniconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1739, in _on_finish self._console_stop() # TODO: there's a race here with jupyter console logging File "/miniconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1637, in _console_stop self._restore() File "/miniconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1569, in _restore self._out_redir.uninstall() File "/miniconda3/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 735, in uninstall os.dup2(self._orig_src_fd, self.src_fd) File "/miniconda3/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 508, in src_fd return self.src_stream.fileno()

ValueError: I/O operation on closed file

wandb: ERROR Problem finishing run

**Environment**
Sagemaker ml.m5.xlarge
Python 3.7.10

**Comment by vanpelt** [comment]
@hazel-erickson we'll try to reproduce in sagemaker, until then you can set the following environment variable to disable console logging:

```
os.environ["WANDB_CONSOLE"] = "off"
```

**Comment by hazel-erickson** [comment]
Unfortunately setting that enviroment variable didn't stop it from crashing

**Comment by vanpelt** [comment]
@hazel-erickson Can you share the exception with the WANDB_CONSOLE environment variable set?  It must be set before `wandb.init` is called.  If you an provide us with a docker image or the sagemaker api calls being made we can reproduce on our end and figure out the root cause.

**Comment by sydholl** [comment]
Because this issue has gone stale, we are closing it. Please comment to reopen.
