### ISSUE TITLE
Proxy Issue on GPU Cluster

### ISSUE THREAD

**Issue by amorehead** [wandb/client#2483]
Hello.

For the past month or so, I have been training machine learning models on a GPU cluster called Summit. Previously, I reached out to Summit's support staff to enable their compute nodes to reach external web endpoints using the following proxy URLs.

export all_proxy=socks://proxy.ccs.ornl.gov:3128/
export ftp_proxy=ftp://proxy.ccs.ornl.gov:3128/
export http_proxy=http://proxy.ccs.ornl.gov:3128/
export https_proxy=https://proxy.ccs.ornl.gov:3128/
export no_proxy='localhost,127.0.0.0/8,.ccs.ornl.gov,.ncrc.gov'
export LC_ALL=en_US.utf8

However, as of yesterday, using the exact same configuration on Summit that previously worked for me, I am now no longer able to reach WandB's servers in my Python script.

Would you have any ideas why these proxy URLs no longer appear to be working for remote web calls on compute nodes? I have verified with Summit support staff that nothing has changed on the proxy configuration side of things.

------------------------
For completeness, here is the error I am seeing in my Python script which is coming from the WandB:

Traceback (most recent call last):
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/ccs/home/acmwhb/.conda/envs/DeepInteract/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

**Comment by vanpelt** [comment]
Hey @amorehead this indicates your proxy stopped serving valid SSL to the libraries making requests to HTTPS services.  You can set the `WANDB_INSECURE_DISABLE_SSL=true` environment variable, however this will mean your connection isn't being verified which could open you up to an attacker.  The ultimate solution is contacting your IT administrator about configuring trusted certificates with your proxy.

I do believe urllib3 changed it behavior recently.  Before, if it couldn't find a secure connection to the proxy it would fallback to the insecure proxy.  You could try setting `export https_proxy=https://proxy.ccs.ornl.gov:3128/` to `export https_proxy=http://proxy.ccs.ornl.gov:3128/` but this means all traffic is being proxied through an unencrypted connection.

https://serverfault.com/questions/817680/https-through-an-http-only-proxy/817684

**Comment by amorehead** [comment]
Thanks, @vanpelt! This gives me something to go off of for the time being. If I find out anything more (that may be relevant for others), I will let you all know
