### ISSUE TITLE
[CLI] wandb.init() fails with HTTPError entity <username> not found during upsertBucket

### ISSUE THREAD

**Issue by vkostyuk** [wandb/client#2484]
**Description**
wandb==0.11.1
python==3.8.10
OS==Linux/Ubuntu 20.04.2 LTS

Running `wandb.init(settings=wandb.Settings(start_method="fork"))` in the beginning of a notebook or script works fine, but fails when run after setup steps with the following debug.log (I replaced my username with `<username>` everywhere below):

```
wandb: Currently logged in as: <username> (use `wandb login --relogin` to force relogin)
wandb: ERROR Error while calling W&B API: entity <username> not found during upsertBucket (<Response [404]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    six.reraise(*sys.exc_info())
  File "/project/path/env/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 121, in execute
    return self.client.execute(*args, **kwargs)
  File "/project/path/env/lib/python3.8/site-packages/wandb/apis/client.py", line 91, in execute
    raise requests.HTTPError(message, response=response)
requests.exceptions.HTTPError: entity <username> not found during upsertBucket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/path/env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 916, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/project/path/env/lib/python3.8/site-packages/wandb/util.py", line 726, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 55, in run
    self._run()
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 105, in _run
    self._process(record)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 292, in _process
    self._sm.send(record)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 181, in send
    send_handler(record)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 604, in send_run
    self._init_run(run, config_value_dict)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 626, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/project/path/env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 36, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/project/path/env/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/project/path/env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 916, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/project/path/env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/project/path/env/lib/python3.8/site-packages/wandb/util.py", line 726, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
```

A few things I tried:

1. Omitting `settings=wandb.Settings(start_method="fork")` or changing to "thread" does not help (same error for "thread", `Error communicating with wandb process` when I omit this setting).
2. Logged in from CLI just fine. API key correctly set as `WANDB_API_KEY` environment variable, and WANDB_ENTITY set to `<username>`.
3. Again, when I run `wandb.init` in the beginning of the pipeline, everything works fine.
4. Perhaps related to #1409, but the [workaround](https://github.com/wandb/client/issues/1409#issuecomment-723371808) of retrying doesn't solve the problem -- I get the same error on each retry.

**Comment by vanpelt** [comment]
Definitely a bug.  Can you try adding entity=<username> to your wandb.init call?

**Comment by vkostyuk** [comment]
I tried adding `entity=<username>` as a `wandb.init` argument -- no effect: same error as above.

**Comment by vanpelt** [comment]
Very strange.  It's almost like we're losing your credentials for the second call to `wandb.init`.  Are you able to share your code or psuedo code so we can reproduce.  Can you also try running `pip install --force wandb==0.11.0` and see if the error still persists?

**Comment by vkostyuk** [comment]
My bad: the username was misspelled in my `.env`. Doh!  

When I just ran `wandb.init()` at the beginning of a script, it ran prior to loading the `.env` into the environment -- hence everything was fine. Running it after produced the above error due to the misspelling.
