### ISSUE TITLE
[Q]AttributeError: 'NoneType' object has no attribute '_global_run_stack'

### ISSUE THREAD

**Issue by Taitai6521** [wandb/client#2558]
wandb --version && python --version && uname

Explanation:

This error appeared while I was building and training a model using efficientnet via timm.
It happened when I built an array like [0], a string in the scheduler.
By the way, 
I had no problem with the hyperparameters, which are just numbers.

Does it not support anything other than numbers?
Or is there a way to do something like these as well?
Thank you very much for your help.

Weighting and bias version: 0.8.18
Python version: 3.7
Operating system: kaggle note book

PS:

Ok!!====>>>>>>

        'batch_size': {
            'values': [256, 128, 64, 48,32,16]
        },

No!!!====>>>>>>
                  'trn_fold': {
            'values': [[0],[1],[2] ,[3] ,[4],[5] ]
        },
        'scheduler': {
            'values': [('CosineAnnealingLR'),('ReduceLROnPlateau')]
#             'CosineAnnealingLR', 'CosineAnnealingWarmRestarts']
        } 

Traceback::

Waiting for W&B process to finish, PID 10589
Program failed with code 1. Press ctrl-c to abort syncing.
Find user logs for this run at: /kaggle/working/wandb/run-20210819_032843-2m4y9auo/logs/debug.log
Find internal logs for this run at: /kaggle/working/wandb/run-20210819_032843-2m4y9auo/logs/debug-internal.log
Synced 5 W&B file(s), 0 media file(s), 4 artifact file(s) and 1 other file(s)

Synced exp1: https://wandb.ai/taiyo_/G2Net-Public-experiments/runs/2m4y9auo
Exception in thread Thread-50:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/agents/pyagent.py", line 303, in _run_job
    self._function()
  File "<ipython-input-46-168332173d27>", line 30, in main
    _oof_df = train_loop(train, fold)
  File "<ipython-input-40-2d6f93c0a340>", line 73, in train_loop
    avg_loss = train_fn(fold, train_loader, model, criterion, optimizer, epoch, scheduler, device)
  File "<ipython-input-24-39987e602e2f>", line 58, in train_fn
    y_preds = model(images)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-23-17c3e5267344>", line 13, in forward
    output = self.model(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../input/pytorch-image-models/pytorch-image-models-master/timm/models/efficientnet.py", line 401, in forward
    x = self.forward_features(x)
  File "../input/pytorch-image-models/pytorch-image-models-master/timm/models/efficientnet.py", line 394, in forward_features
    x = self.blocks(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../input/pytorch-image-models/pytorch-image-models-master/timm/models/efficientnet_blocks.py", line 264, in forward
    x = self.conv_pw(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 15.90 GiB total capacity; 14.80 GiB already allocated; 11.75 MiB free; 15.07 GiB reserved in total by PyTorch)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    wandb.finish(exit_code=1)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2471, in finish
    wandb.run.finish(exit_code=exit_code)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1259, in finish
    if self._wl and len(self._wl._global_run_stack) > 0:
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in __getattr__
    return getattr(self._instance, name)
AttributeError: 'NoneType' object has no attribute '_global_run_stack'

wandb: Agent Starting Run: u3suwusp with config:
wandb: 	batch_size: 16
wandb: 	learning_rate: 3e-05
wandb: 	scheduler: CosineAnnealingLR
wandb: 	trn_fold: [1]
========== fold: 0 training ==========

**Comment by vanpelt** [comment]
The actual error here is your GPU using all memory.  It also looks like you have multiple versions of wandb in your environment.  The current version of wandb is 0.12.0, 0.8.18 is over a year old.  You should upgrade with `pip install wandb --upgrade`
