### ISSUE TITLE
[CLI] artifact download from wandb local

### ISSUE THREAD

**Issue by karthi0804** [wandb/client#2565]
**Description**
I am using wandb local and storing artifacts in one PC. It works fine. When I want to download the artifact dataset and train in another PC, the specified `artifact.download` is downloading but it throws the below error at the end. The same behaviour is observed using `wandb artifact get`. Please help me. I could find the files are downloaded in the filesystem.

```
wandb: Downloading large artifact lyft-scenes:intgbhv3, 117.87MB. 318 files... Traceback (most recent call last):
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f29a0573690>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  [Previous line repeated 13 more times]
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/karthi/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /local-files/karthi0804/IntentionPrediction/wandb_artifacts/6/13/7e23d446a2114cad095b578e54a6e5ef?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=LqYYuKnwmu%2BDiNOpkSZ0LA%3D%3D%2F20210820%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20210820T091336Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=cc32f7ec124062a4e73c589cbf13dea48b85b1afdd68463f6a78e1b4d17cc415 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29a0573690>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karthi/.local/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/karthi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/karthi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/karthi/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthi/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karthi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karthi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/karthi/.local/lib/python3.7/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/karthi/.local/lib/python3.7/site-packages/wandb/cli/cli.py", line 1235, in get
    path = artifact.download(root=root)
  File "/home/karthi/.local/lib/python3.7/site-packages/wandb/apis/public.py", line 3005, in download
    pool.map(partial(self._download_file, root=dirpath), manifest.entries)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/karthi/.local/lib/python3.7/site-packages/wandb/apis/public.py", line 3095, in _download_file
    return self.get_path(name).download(root)
  File "/home/karthi/.local/lib/python3.7/site-packages/wandb/apis/public.py", line 2556, in download
    self._parent_artifact, self.name, manifest.entries[self.name]
  File "/home/karthi/.local/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 882, in load_file
    stream=True,
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/karthi/.local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /local-files/karthi0804/IntentionPrediction/wandb_artifacts/6/13/7e23d446a2114cad095b578e54a6e5ef?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=LqYYuKnwmu%2BDiNOpkSZ0LA%3D%3D%2F20210820%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20210820T091336Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=cc32f7ec124062a4e73c589cbf13dea48b85b1afdd68463f6a78e1b4d17cc415 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29a0573690>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Environment**
- OS: Ubuntu 18.04
- Environment: Docker 
- Python Version: 3.7.5
- Wandb Client Version: 0.10.29

**Comment by vanpelt** [comment]
In your local instance, have you updated the Frontend Host in your system-settings?  You can find it at "http://YOUR_URL/system-admin".

**Comment by karthi0804** [comment]
> In your local instance, have you updated the Frontend Host in your system-settings? You can find it at "http://YOUR_URL/system-admin".

Thanks for your suggestion. it is solved.
