### ISSUE TITLE
AttributeError: 'Remote' object has no attribute 'url' 

### ISSUE THREAD

**Issue by insurgent92** [wandb/client#257]
* Weights and Biases version: 0.6.27
* Python version: 3.6
* Operating System: Ubuntu 16.04

### Description
Hi! 
First of all, As one of PyTorch users, I appreciate **wandb** :D 
Unfortunately I had a problem(seen below logs) when my project has git & remotes 
but don't have a remote named 'origin'.
So When i add a remote named 'origin', the errors are solved. 
And i knew that I have to remote named 'origin'.
Although 'origin' is ordinary for name of remote, even so why i should have it? 
 
### What I Did

```
wandb: Started W&B process version 0.6.27 with PID 13381
/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/git/remote.py", line 428, in __getattr__
    return self._config_reader.get(attr)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/git/config.py", line 124, in <lambda>
    return lambda *args, **kwargs: self._call_config(attr, *args, **kwargs)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/git/config.py", line 130, in _call_config
    return getattr(self._config, method)(self._section_name, *args, **kwargs)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/git/config.py", line 79, in assure_data_present
    return func(self, *args, **kwargs)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'url' in section: 'remote "origin"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/internal_cli.py", line 101, in <module>
    main()
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/internal_cli.py", line 93, in main
    headless(args)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/internal_cli.py", line 46, in headless
    raise e
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/internal_cli.py", line 41, in headless
    port=args['port'])
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/run_manager.py", line 395, in __init__
    self._meta = meta.Meta(api, self._run.dir)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/meta.py", line 29, in __init__
    self.setup()
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/meta.py", line 40, in setup
    "remote": self._api.git.remote_url,
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/wandb/git_repo.py", line 96, in remote_url
    return self.remote.url
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/git/remote.py", line 430, in __getattr__
    return super(Remote, self).__getattr__(attr)
  File "/home/visionnoob/anaconda3/envs/py36tf17/lib/python3.6/site-packages/gitdb/util.py", line 255, in __getattr__
    return object.__getattribute__(self, attr)
AttributeError: 'Remote' object has no attribute 'url'
Terminated
```

**Comment by vanpelt** [comment]
Ahh, it is incorrect of us to assume there is a remote on origin.  We'll update the code to handle this.

**Comment by insurgent92** [comment]
@vanpelt 
I got it! Thank you 👍

**Comment by DevJake** [comment]
I've also just experienced this issue. The fix is the following:
```
cd [root of project with .git directory]
git remote add origin https://github.com/[Username]/[Repository name].git
```
Basically, wandb expects a URL for the origin. If this doesn't exist - which oddly enough it seems can be a circumstance - then it crashes. @vanpelt would it be possible to integrate some sort of descriptive error message for this case? It's not a big issue, but just one that would benefit from an error message. Thanks!
