### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by kevinbro96** [wandb/client#2600]
**Description**
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 562, in init
    run._on_start()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1618, in _on_start
    self._display_run()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1423, in _display_run
    if platform.system() != "Windows" and sys.stdout.encoding == "UTF-8":
AttributeError: 'Logger' object has no attribute 'encoding'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 562, in init
    run._on_start()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1618, in _on_start
    self._display_run()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1423, in _display_run
    if platform.system() != "Windows" and sys.stdout.encoding == "UTF-8":
AttributeError: 'Logger' object has no attribute 'encoding'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_withvae.py", line 606, in <module>
    main()
  File "train_withvae.py", line 202, in main
    run = wandb.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 812, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem

**Wandb features**
wandb.init()

**Environment**
- UBUNTU 16.04
- Environment: CUDA11.0
- Python Version: [eg. 3.8.7]

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
