### ISSUE TITLE
[CLI] Permission Denied Error in middle of run

### ISSUE THREAD

**Issue by andyp05** [wandb/client#2614]
**Description**

Running a fast.ai learn.fit() script in VScode. Running 2 epochs. After about 10-15 minutes, I get the following error:

```
PermissionError: [Errno 13] Permission denied: 'F:\\OneDrive\\Documents\\Projects\\wandb\\run-20210830_150651-3jgzq3r7\\files\\wandb-summary.json'

wandb: ERROR Internal wandb error: file data was not synced
--------------------------------------------| 23.87% [828/3469 06:40<21:17 0.3653]
```

The file: wandb-summary.json is created and has information stored in it.

Last couple lines in debug file:

```
2021-08-30 15:13:42,304 INFO    Thread-12 :22444 [dir_watcher.py:_on_file_modified():230] file/dir modified: F:\OneDrive\Documents\Projects\wandb\run-20210830_150651-3jgzq3r7\files\wandb-summary.json
2021-08-30 15:13:43,247 DEBUG   SenderThread:22444 [sender.py:send():182] send: history
2021-08-30 15:13:43,248 DEBUG   SenderThread:22444 [sender.py:send():182] send: summary
2021-08-30 15:13:43,311 INFO    Thread-12 :22444 [dir_watcher.py:_on_file_modified():230] file/dir modified: F:\OneDrive\Documents\Projects\wandb\run-20210830_150651-3jgzq3r7\files\output.log
2021-08-30 15:13:43,669 INFO    HandlerThread:22444 [handler.py:finish():683] shutting down handler
2021-08-30 15:13:43,669 INFO    WriterThread:22444 [datastore.py:close():281] close: F:\OneDrive\Documents\Projects\wandb\run-20210830_150651-3jgzq3r7\run-3jgzq3r7.wandb
2021-08-30 15:13:44,081 ERROR   MainThread:22444 [internal.py:wandb_internal():157] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "C:\Python\lib\site-packages\wandb\sdk\internal\internal_util.py", line 102, in _run
    self._process(record)
  File "C:\Python\lib\site-packages\wandb\sdk\internal\internal.py", line 290, in _process
    self._sm.send(record)
  File "C:\Python\lib\site-packages\wandb\sdk\internal\sender.py", line 184, in send
    send_handler(record)
  File "C:\Python\lib\site-packages\wandb\sdk\internal\sender.py", line 758, in send_summary
    self._update_summary()
  File "C:\Python\lib\site-packages\wandb\sdk\internal\sender.py", line 770, in _update_summary
    with open(summary_path, "w") as f:
PermissionError: [Errno 13] Permission denied: 'F:\\OneDrive\\Documents\\Projects\\wandb\\run-20210830_150651-3jgzq3r7\\files\\wandb-summary.json'
2021-08-30 15:13:45,325 INFO    Thread-12 :22444 [dir_watcher.py:_on_file_modified():230] file/dir modified: F:\OneDrive\Documents\Projects\wandb\run-20210830_150651-3jgzq3r7\files\output.log
2021-08-30 15:13:46,100 INFO    MainThread:22444 [internal.py:handle_exit():76] Internal process exited
```

If I log into wanb.ai, the run is there and says crashed.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder 

**Environment**
Windows 10
Python 3.9.6
wandb 0.12.1
fastai 2.5.2
Running in VScode with No debugging turned on.

**Comment by vanpelt** [comment]
Hey @andyp05 this could be related to logging data to a network syncing `OneDrive` path.  Can you try changing the directory to a non-networked path?  i.e. `wandb.init(dir="C:\Windows\TEMP")`

**Comment by andyp05** [comment]
That was it. Thanks for the quick response.
