### ISSUE TITLE
Having trouble with wandb local

### ISSUE THREAD

**Issue by optimass** [wandb/client#2657]
**Description**
Hello. I was using `wandb local` just fine and now I'm having some issues with it.
It might be related to the fact that i'm relogin into wandb with my original account (seems like I needed to create a new one the first time I launch `wandb local`

Anyhow, here is the error
```bash
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 136, in execute
    six.reraise(*sys.exc_info())
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://localhost:8080/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1087, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/util.py", line 805, in no_retry_auth
    raise CommError("Invalid or missing api_key.  Run wandb login")
wandb.errors.CommError: Invalid or missing api_key.  Run wandb login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 52, in run
    self._run()
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 290, in _process
    self._sm.send(record)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 184, in send
    send_handler(record)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 623, in send_run
    self._init_run(run, config_value_dict)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 645, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1087, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/util.py", line 805, in no_retry_auth
    raise CommError("Invalid or missing api_key.  Run wandb login")
wandb.errors.CommError: Invalid or missing api_key.  Run wandb login
wandb: ERROR Internal wandb error: file data was not synced
^CProblem at: /home/ubuntu/dev/rl_4_cl/code/main_cl.py 204 <module>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.9.1191016588/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.9.1191016588/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.9.1191016588/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/dev/rl_4_cl/code/main_cl.py", line 204, in <module>
    wandb.init(project=args.wandb_project, name=args.log_id)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 796, in init
    raise e
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 514, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 661, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 649, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 77, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
^CTraceback (most recent call last):
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2021.9.1191016588/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2143, in __wait_for_threads_to_finish
    self._wait_for_threads_to_finish_called_event.wait(timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ubuntu/anaconda3/envs/py1.9/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

**Environment**
- OS: Linux 5.4.0-1055-aws x86_64
- Python Version: 3.8

**Comment by optimass** [comment]
If I don't login prior to launching `wandb local`, then http://localhost:8080/authorize brings me here:
![image](https://user-images.githubusercontent.com/26232819/132859332-970d781d-156a-43b9-ac44-0d8fcf537295.png)
Where my both WandB accounts credential do not work, and neither does the one suggested here https://docs.wandb.ai/guides/self-hosted/local#authentication

**Comment by optimass** [comment]
If I login with my original WandB account, then run `wandb local`, here's what I will see at  http://localhost:8080/
![image](https://user-images.githubusercontent.com/26232819/132881366-adc1ddf0-2452-4d9a-b827-5285cbf844dc.png).

**Comment by vanpelt** [comment]
@optimass you'll need to login with the account you originally created for the local instance.  If you can't remember that password you can reset it by shelling into the container.

```
docker exec -it wandb-local bash
/usr/local/bin/local password your@email.com
```

Then you should be able to login and get the appropriate api key to authenticate.

**Comment by optimass** [comment]
Ok thanks that worked!
