### ISSUE TITLE
Stuck indefinitely on exit while syncing files

### ISSUE THREAD

**Issue by rmst** [wandb/client#269]
* Weights and Biases version: 0.6.28
* Python version: 3.6 Anaconda
* Operating System: Ubuntu 18.04

### Description

Sometimes wandb gets stuck when syncing files after a script exits. This doesn't seem to be a connection or server-side problem since waiting doesn't help but instead restarting and immediately exiting again usually works.

The stuck processes can become a real problem when running in a scheduled cluster context where it can block resources for days if it is not manually resolved.

I have no idea why the upload gets stuck but as a first measure adding an (optional) timeout would at least resolve the resource blockage issue.

EDIT: Example output:
```
wandb: Waiting for wandb process to finish, PID 66
wandb: Program ended.
wandb: Run summary:
wandb:             cur_epoch 0
wandb:             test_step 10000
wandb:   test_total_episodes 275
wandb: Waiting for final file modifications.
wandb: Syncing files in ../tmp/tmpv3t6dusj/wandb/run-20181126_220625-1hv489xd:
wandb:   model
wandb: plus 6 W&B file(s) and 0 media file(s)
wandb: \ 4 of 7 files, 413159.000 of 5054822.000 bytes uploaded
```

**Comment by vanpelt** [comment]
Hey @rmst, that sucks.  We'll look into this ASAP.

**Comment by rmst** [comment]
So far it only happend twice in 200 or so runs. At first I thought it might have to do with the shared file system but the folder used for syncing is actually a local one (it's in /tmp/..., idk why the logs say ../tmp)

**Comment by adrianbg** [comment]
I reproduced this. The issue is that our list of retryable HTTP response codes is incomplete:

```
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/apis/__init__.py", line 49, in wrapper
    return func(*args, **kwargs)
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/apis/internal.py", line 789, in upload_file
    raise e
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/apis/internal.py", line 770, in upload_file
    response.raise_for_status()
  File "/Users/adrian/.pyenv/versions/3.6.0/envs/wandb-3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 408 Client Error: Request Timeout for url: https://storage.googleapis.com/wandb-production.appspot.com/adrianbg/wandb-examples-pytorch-cnn-mnist/n66rlcmm/file?Expires=1543535300&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=BCO9y6xCpsUJ6VgiUdbjsK%2F34gB5SaPcfpN8wWUFn5y0XCITrtCK27Tb2BI1NWg1vWFraWo1k3d3NBHu0sgbjwsFqesR0BqOlqkFTpknDCKqo7wk1bcM159%2BLaDd9waGfcM6O%2BtaYavjmyl6hSMuuVcFbMeY727UVYVNciwctzb8h9rE%2FXEzSopFGBmwMOPcHni%2BzeSpjbZ9hKnXPR0BKV1H83KQHSLqTPZjyMjruWp9SwlvOBB3QMJO%2BQxVH30y%2FhFVq0VhYoDsL7%2BJN1Iv%2Fzy1ZtwNR0fPjWylFhWGNLRb6RGscXIlz3l4Zi6ZtZ1ZQfcTUcUhMM56v7Z5MtEY8A%3D%3D&upload_id=AEnB2Ur5A7JFyPXlvMZkrOcx4yNxiocFpPAXfQmuYXFdmLLtEy9NKUMgHceW4eI20-PQ3sA8dCuaaSCGyLWDC42dRLL5Up6hpg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adrian/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/file_pusher.py", line 33, in run
    self._push_function(self.save_name, save_path)
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/run_manager.py", line 426, in _push_function
    progress=lambda _, total: self._file_upload_stats.update_progress(save_name, total))
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/apis/__init__.py", line 49, in wrapper
    return func(*args, **kwargs)
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/apis/internal.py", line 968, in push
    file_info['url'], open_file, progress))
  File "/Users/adrian/go/src/github.com/wandb/core/frontends/client/wandb/apis/__init__.py", line 51, in wrapper
    raise CommError(err.response, err)
wandb.apis.CommError: <Response [408]>

wandb: \ 3 of 5 files, 4784949.000 of 5252222.000 bytes uploadedaded
```

**Comment by adrianbg** [comment]
Also, of course, we don't properly detect that the file failed.
