### ISSUE TITLE
FileNotFoundError wandb-history.jsonl on startup

### ISSUE THREAD

**Issue by lukas** [wandb/client#271]
* Weights and Biases version: master
* Python version: 3.6
* Operating System: linux

### Description

I ran a tensorflow run and got a crash right in the beginning:

```

WARNING:tensorflow:From /home/ubuntu/models/tutorials/image/cifar10/cifar10_input.py:79: FixedLengthRecordReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.FixedLengthRecordDataset`.
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
WARNING:tensorflow:From /home/ubuntu/models/tutorials/image/cifar10/cifar10_input.py:126: shuffle_batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.shuffle(min_after_dequeue).batch(batch_size)`.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/watchdog/events.py", line 454, in dispatch
    _method_map[event_type](event)
  File "/home/ubuntu/client/wandb/run_manager.py", line 478, in _on_file_created
    self._get_file_event_handler(event.src_path, save_name).on_created()
  File "/home/ubuntu/client/wandb/run_manager.py", line 226, in on_created
    self._setup()
  File "/home/ubuntu/client/wandb/run_manager.py", line 241, in _setup
    self.file_path, on_read, seek_end=self._seek_end)
  File "/home/ubuntu/client/wandb/run_manager.py", line 64, in __init__
    self._file = open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/models/tutorials/image/cifar10/wandb/run-20181130_044927-9201lt39/wandb-history.jsonl'
```

**Comment by cvphelps** [comment]
I think this is fixed with the more recent versions of wandb. Let's reopen it if the problem comes up again.
