### ISSUE TITLE
[CLI] not able to run hyperopt sweep

### ISSUE THREAD

**Issue by stefanalgopolis** [wandb/client#2732]
I've just created a hyperopt sweep config file and tried to run it using `wandb sweep` CLI command. Unfortunately, I got a following error:

```
wandb: Creating sweep from: gscore/sweep_config/sweep-tune-hyperopt.yaml
400 response executing GraphQL.
{"errors":[{"message":"Invalid sweep config: Sweep config must contain method section","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
wandb: ERROR Error while calling W&B API: Invalid sweep config: Sweep config must contain method section (<Response [400]>)
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1322, in upsert_sweep
    raise (e)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1308, in upsert_sweep
    response = self.gql(
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/old/retry.py", line 105, in __call__
    if not check_retry_fn(e):
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1304, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.UsageError: Invalid sweep config: Sweep config must contain method section

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/cli/cli.py", line 776, in sweep
    sweep_id = api.upsert_sweep(
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/apis/internal.py", line 89, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1322, in upsert_sweep
    raise (e)
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1308, in upsert_sweep
    response = self.gql(
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/old/retry.py", line 105, in __call__
    if not check_retry_fn(e):
  File "/home/user/.cache/pypoetry/virtualenvs/quant-optimizer-ijt0t4H--py3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1304, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.CommError: Invalid sweep config: Sweep config must contain method section

```
The same error appears when I try to create a sweep through wandb web app. I'm using **0.10.24** wanb version (newer version had hyperopt implementation removed).

**Comment by aidanjdonohue** [comment]
Hi Stefan! Sorry you're encountering this issue. Could you share the error.log files (should be in your wandb directory)? If you don't want to post them here you can alternatively send them to support@wandb.com

**Comment by stefanalgopolis** [comment]
Hello @aidanjdonohue! Thanks for your reply, I tried to run it on cloud wandb version - is it possible to access error.log there?
