### ISSUE TITLE
[CLI] ModuleNotFoundError: No module named 'pwd'

### ISSUE THREAD

**Issue by ABD-01** [wandb/client#2737]
**Description**
Wandb is unable to login as 'pwd' module is  not found. However this module is for UNIX like os, but I am using windows

**Wandb features**
Both `wandb.login()` and `!wandb login` show the same error

**Environment**
- OS: Windows 11 Home
- Environment: Jupyter Notebook
- Python Version: 3.9.7

**Comment by vanpelt** [comment]
Hey @ABD-01 can you share the exact error message / traceback you're seeing?

**Comment by mjan2021** [comment]
```
(venv) C:\Users\mjan2021\Documents\GitHub\SkinCancer\src>wandb offline
Traceback (most recent call last):
  File "C:\Users\mjan2021\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mjan2021\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mjan2021\Documents\GitHub\SkinCancer\venv\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "C:\Users\mjan2021\Documents\GitHub\SkinCancer\venv\lib\site-packages\wandb\cli\cli.py", line 45, in <module>
    _username = getpass.getuser()
  File "C:\Users\mjan2021\AppData\Local\Programs\Python\Python38\lib\getpass.py", line 168, in getuser
    import pwd
ModuleNotFoundError: No module named 'pwd'
```
I tried to reinstall wandb but still gives the same error..
