### ISSUE TITLE
[CLI] OSError: [Errno 18] Invalid cross-device link:

### ISSUE THREAD

**Issue by Wilann** [wandb/client#2790]
**Description**
When logging multiple tables with relatively long names in the UI,  only the first table is logged and I get an error message. 

**Wandb features**
```
for data in multiple_data_lists:
      table = wandb.Table(data=data, columns=columns)
      wandb.log({table_name: table})
```

Error Message:
```
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpfgmsj1jjwandb-media/wx1cbx2g.table.json' -> './CALF/wandb/run-20211018_170848-3nuk7qkt/files/media/table/Predictions fo
r YONEX All England Open 2018: WS _ TAI Tzu Ying (TPE) [1] vs Saina NEHWAL (IND) _ BWF 2018_3_34a8e27be30377cd5860.table.json'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CALF/src/main.py", line 346, in <module>
    main()
  File "CALF/src/main.py", line 285, in main
    predictions.upload_predictions()
  File "/media/wilsonchan/Giratina/Projects/BadmintonAI/AceOne-BadmintonAI/CALF/src/predictions.py", line 121, in upload_predictions
    wandb.log({table_name: table})
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1193, in log
    self.history._row_add(data)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 937, in _history_callback
    self._backend.interface.publish_history(
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 214, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2318, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2398, in val_to_json
    val.bind_to_run(run, key, namespace)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/data_types.py", line 427, in bind_to_run
    super(Table, self).bind_to_run(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 518, in bind_to_run
    shutil.move(self._path, new_path)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: './CALF/wandb/run-20211018_170848-3nuk7qkt/files/media/table/Predictions for YONEX All England Open 2018: WS _ TAI Tzu Ying (TPE) [1] vs
Saina NEHWAL (IND) _ BWF 2018_3_34a8e27be30377cd5860.table.json'
```

**How to reproduce**
N/A

**Environment**
- OS: Pop! OS 20_04 
- Environment: Conda Env + Python scripts
- Python Version: 3.8.11

**Comment by Wilann** [comment]
Related to #1252 - issue still persists in wandb version `0.12.4`

**Comment by vanpelt** [comment]
@Wilann we cache all data in your home directory by default.  The error is coming from windows mounting the tmp directory on a different drive than the cache directory.  You can override the cache directory to be on the same device as your tmp directory by setting the `WANDB_CACHE_DIR` environment variable.  If you want to maintain the cache you can copy `~/.cache/wandb` into the directory you set `WANDB_CACHE_DIR` to.
