### ISSUE TITLE
Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by rmst** [wandb/client#280]
* Weights and Biases version: 0.6.30
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description
Sometimes I am getting this error which I don't know how to resolve. After getting this error, my job continues to run fine but all logging to wandb seems to be disabled:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/apis/__init__.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/apis/internal.py", line 586, in upsert_run
    mutation, variable_values=variable_values, **kwargs)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/retry.py", line 90, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/gql/client.py", line 52, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Error 1213: Deadlock found when trying to get lock; try restarting transaction', 'path': ['upsertBucket']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/watchdog/events.py", line 454, in dispatch
    _method_map[event_type](event)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/run_manager.py", line 535, in _on_file_created
    self._get_file_event_handler(event.src_path, save_name).on_created()
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/run_manager.py", line 193, in on_created
    self._eventually_update()
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/run_manager.py", line 204, in _eventually_update
    self._update()
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/run_manager.py", line 226, in _update
    self._api.upsert_run(id=self._run.storage_id, config=config_dict)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/apis/__init__.py", line 78, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/apis/__init__.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/apis/internal.py", line 586, in upsert_run
    mutation, variable_values=variable_values, **kwargs)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/wandb/retry.py", line 90, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mnt/home/rmst/dev/anaconda3/lib/python3.6/site-packages/gql/client.py", line 52, in execute
    raise Exception(str(result.errors[0]))
wandb.apis.CommError: Error 1213: Deadlock found when trying to get lock; try restarting transaction
```

### What I Did

I am running experiments with wandb on a cluster. The wandb client package is installed as part of a shared anaconda environment (shared across all my jobs since the directories containing anaconda are mounted at every job).

**Comment by vanpelt** [comment]
This should be fixed, it was a backend issue no need to upgrade the client.

**Comment by YigitDemirag** [comment]
I am starting getting the same error
```
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)
wandb: ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)```

**Comment by jsbroks** [comment]
@YigitDemirag Issue is fixed. You can check https://status.wandb.com/ for status updates.

**Comment by raoulraft** [comment]
I am getting the same error (a lot) this morning, even though logging to wandb seems to be working fine

**Comment by vanpelt** [comment]
@raoulraft can you share a debug-internal.log file from the run that's causing these errors?
