### ISSUE TITLE
[CLI] Sweep - wandb: ERROR Problem finishing run

### ISSUE THREAD

**Issue by Wilann** [wandb/client#2802]
**Description**
Running a sweep with a dictionary config has an issue "finishing run"

**Wandb features**
```
def main(model_name = config.model_name,
                batch_size = config.batch_size, 
                 ...):
      ...
      wandb.define_metric("loss/train_loss", summary="min")
      ...

hparams = {
    'lr': 0.01
}

run = wandb.init(project='CALF',
                           entity='wilan',
                           name=config.output_name,
                           dir='./CALF',
                           tags=[config.task_complexity],
                           config=hparams)

sweep_config = {
    'name': 'test-sweep',
    'method': 'bayes',
     'metric': {
        'goal': 'minimize',
        'name': 'loss/train_loss'
    },
        'parameters': {
            'lr': {
                'min': 0.0001,
                'max': 0.1
          }
}}
 sweep_id = wandb.sweep(sweep_config)
 count = 3
 wandb.agent(sweep_id, function=main, count=count)
```

Error:
```
wandb: ERROR Problem finishing run
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1629, in _atexit_cleanup
    self._on_finish()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1770, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1665, in _console_stop
    self._restore()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1599, in _restore
    self._err_redir.uninstall()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 754, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 667, in remove_fd
    self._unregister()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 655, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at
shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

This is the associated `debug-internal.log` file:
[debug-internal.log](https://github.com/wandb/client/files/7374429/debug-internal.log)

**How to reproduce**
N/A

**Environment**
- OS: Pop! OS 20_04
- Environment: Conda Env + Python scripts
- Python Version: 3.8.11

**Comment by lucakbetter** [comment]
Has there been a resolution to this problem?

**Comment by Wilann** [comment]
Don't think so
