### ISSUE TITLE
ValueError: signal only works in main thread of the main interpreter, sweep [CLI] 

### ISSUE THREAD

**Issue by sradc** [wandb/client#2854]
**Description**
Testing out sweeps, and get this error, seems to only run the first value of the sweep.

**Wandb features**
wandb.init(), wandb.log(), wandb.sweep()

**Environment**
- OS: Mac OS Big Sur 11.6, M1
- Python Version: 3.9.7
- wandb version: 0.12.6

**How to reproduce**

```python
import wandb

PROJECT = "test-project"

sweep_config = {"method": "grid"}
sweep_config["metric"] = {"name": "count", "goal": "minimize"}
sweep_config["parameters"] = {
    "thing": {"values": [1, 2, 3]},
}
sweep_id = wandb.sweep(sweep_config, project=PROJECT)


def train(config=None):
    print(config)
    wandb.log({"count": 1})


wandb.init(project=PROJECT)
wandb.agent(sweep_id, train)
```

Output:

```bash
Create sweep with ID: ...
Sweep URL: ...
wandb: Currently logged in as: ... (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.6
wandb: Syncing run noble-flower-9
wandb:  View project at ...
wandb:  View run at ...
wandb: Run data is saved locally in /Users/user/repos/pre-pruned-layers/wandb/run-20211029_200820-1a43ciu8
wandb: Run `wandb offline` to turn off syncing.

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
None
wandb: Agent Starting Run: xryv589b with config:
wandb:  thing: 1
wandb: ERROR Problem finishing run
Traceback (most recent call last):
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1671, in _atexit_cleanup
    self._on_finish()
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1817, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1711, in _console_stop
    self._restore()
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1641, in _restore
    self._err_redir.uninstall()
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 754, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 667, in remove_fd
    self._unregister()
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 655, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/Users/user/miniforge3/envs/prepruned/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
/Users/user/miniforge3/envs/prepruned/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by vanpelt** [comment]
We're working on a fix for this issue.  In the meantime you can add:

```
import os
os.environ["WANDB_CONSOLE"] = "off"
```

To your script at the top of the file and that should prevent the error.

**Comment by sradc** [comment]
@vanpelt, thanks. Added...

```python
import os
os.environ["WANDB_CONSOLE"] = "off"
``` 

... to the script (no other changes), get the following error:

```bash
Create sweep with ID: ...
Sweep URL: ...
wandb: Currently logged in as: <user> (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.6
wandb: Syncing run phantom-hex-1
wandb:  View project at https://wandb.ai/<user>/test-project-2
wandb:  View run at https://wandb.ai/<user>/test-project-2/runs/8mmot01n
wandb: Run data is saved locally in /Users/<user>/repos/my-project/wandb/run-20211030_104602-8mmot01n
wandb: Run `wandb offline` to turn off syncing.

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
wandb: Agent Starting Run: ukxhkuw1 with config:
wandb:  thing: 1
None

wandb: Waiting for W&B process to finish, PID 17185... (success).
wandb:                                                                                
wandb: Run history:
wandb:   count ▁
wandb: 
wandb: Run summary:
wandb:   count 1
wandb: 
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced phantom-hex-1: https://wandb.ai/<user>/test-project-2/runs/8mmot01n
wandb: Find logs at: ./wandb/run-20211030_104602-8mmot01n/logs/debug.log
wandb: 
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 304, in _run_job
    wandb.finish()
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2714, in finish
    wandb.run.finish(exit_code=exit_code, quiet=quiet)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1354, in finish
    if self._wl and len(self._wl._global_run_stack) > 0:
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 259, in __getattr__
    return getattr(self._instance, name)
AttributeError: 'NoneType' object has no attribute '_global_run_stack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    wandb.finish(exit_code=1)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2714, in finish
    wandb.run.finish(exit_code=exit_code, quiet=quiet)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1354, in finish
    if self._wl and len(self._wl._global_run_stack) > 0:
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 259, in __getattr__
    return getattr(self._instance, name)
AttributeError: 'NoneType' object has no attribute '_global_run_stack'
wandb: Agent Starting Run: z3flci0y with config:
wandb:  thing: 2
None
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 303, in _run_job
    self._function()
  File "/Users/<user>/repos/my-project/src/experiments/sweep_test.py", line 19, in train
    wandb.log({"count": 1})
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1229, in log
    self.history._row_add(data)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 972, in _history_callback
    self._backend.interface.publish_history(
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 501, in publish_history
    self._publish_history(history)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 74, in _publish_history
    self._publish(rec)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 223, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    wandb.finish(exit_code=1)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2714, in finish
    wandb.run.finish(exit_code=exit_code, quiet=quiet)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1354, in finish
    if self._wl and len(self._wl._global_run_stack) > 0:
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 259, in __getattr__
    return getattr(self._instance, name)
AttributeError: 'NoneType' object has no attribute '_global_run_stack'
wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: hz1ms4yv with config:
wandb:  thing: 3
None
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 303, in _run_job
    self._function()
  File "/Users/<user>/repos/my-project/src/experiments/sweep_test.py", line 19, in train
    wandb.log({"count": 1})
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1229, in log
    self.history._row_add(data)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 972, in _history_callback
    self._backend.interface.publish_history(
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 501, in publish_history
    self._publish_history(history)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 74, in _publish_history
    self._publish(rec)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 223, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    wandb.finish(exit_code=1)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2714, in finish
    wandb.run.finish(exit_code=exit_code, quiet=quiet)
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1354, in finish
    if self._wl and len(self._wl._global_run_stack) > 0:
  File "/Users/<user>/miniforge3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 259, in __getattr__
    return getattr(self._instance, name)
AttributeError: 'NoneType' object has no attribute '_global_run_stack'
wandb: Sweep Agent: Waiting for job.
wandb: Sweep Agent: Exiting.
```

**Comment by robinlomans** [comment]
Hi,

Is this issue still being worked on? The issue (and the proposed workaround of setting the WANDB_CONSOLE env variable to "off") makes it impossible to visualize a sweep run's logs in the Logs tab of the web UI. Are there any other ways to show a run's logs in the web UI if the run was started by an Agent?

Thanks!
