### ISSUE TITLE
UnicodeEncodeError when using python 2.7 wandb client

### ISSUE THREAD

**Issue by syllogismos** [wandb/client#286]
* Weights and Biases version: 0.6.32
* Python version: 2.7
* Operating System: OSX

### Description

Error because of how unicode is handled in python 2. I had a unicode character in the description of one of the projects. I don't have issues with this when using python 3 cli.

### What I Did

```
$ wandb projects
Latest projects for "syllogismos"
lulz -
mnist-v1 -
mnist -
roboschoolhumanoid-v1 -
roboschoolhumanoid-v0 -
mountaincar -
Traceback (most recent call last):
  File "/usr/local/bin/wandb", line 11, in <module>
    sys.exit(cli())
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/wandb/cli.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/Users/anil/.pyenv/versions/2.7.13/lib/python2.7/site-packages/wandb/cli.py", line 242, in projects
    str(project['description'] or "").split("\n")[0])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 37: ordinal not in range(128)
```

### Possible Fix:

In python 2, you shouldn't be using `str(input)` on unicode input. instead use `input.encode('utf-8')`. Above error is from this line https://github.com/wandb/client/blob/master/wandb/cli.py#L242

More details of what the problem is [here in stackoverflow](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20)

Behaviour of str, unicode in python 2 and python 3.
```
$ python
Python 2.7.13 (default, Aug 14 2018, 10:01:19)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> u = unichr(10000) + u'abcd'
>>> u
u'\u2710abcd'
>>> type(u)
<type 'unicode'>
>>> str(u)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2710' in position 0: ordinal not in range(128)
>>> type(u.encode('utf-8'))
<type 'str'>
>>>
[20:23] [] anil at pan in /Users/anil/
$ ipython
Python 3.6.4 (default, Aug 14 2018, 10:06:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: u = chr(10000) + u'abcd'

In [2]: u
Out[2]: '✐abcd'

In [3]: str(u)
Out[3]: '✐abcd'

In [4]: u.encode('utf-8')
Out[4]: b'\xe2\x9c\x90abcd'

In [5]: type(u.encode('utf-8'))
Out[5]: bytes

In [6]: type(str(u))
Out[6]: str

In [7]: type(u)
Out[7]: str
```

**Comment by cvphelps** [comment]
I think this is fixed with the more recent versions of wandb. Let's reopen it if the problem comes up again.
