### ISSUE TITLE
[CLI] Histogram can't be used in a Table

### ISSUE THREAD

**Issue by tuero** [wandb/client#2881]
**Description**
I'm trying to add a histogram to a table, as seen [here](https://docs.wandb.ai/guides/data-vis), and Histogram is one of the wandb types listed that's supported as a [rich media](https://docs.wandb.ai/ref/python/data-types). When running the python script, I get a TypeError indicating the type Histogram is not JSON serializable. I can log the histogram as an individual metric, but not inside the table.

**Wandb features**
```python
wandb.init(project="test_project", entity="tuero")
table_columns = ["index", "histogram"]
table_data = [[0, wandb.Histogram([1,1,2])]]
table = wandb.Table(columns=table_columns, data=table_data)
wandb.log({"table": table})
```

The error produced is as such:
```
Traceback (most recent call last):
  File "wand_test.py", line 49, in <module>
    main()
  File "wand_test.py", line 34, in main
    wandb.log({"table": table})
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1229, in log
    self.history._row_add(data)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 972, in _history_callback
    self._backend.interface.publish_history(
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 491, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2325, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2405, in val_to_json
    val.bind_to_run(run, key, namespace)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/data_types.py", line 425, in bind_to_run
    util.json_dump_safer(data, codecs.open(tmp_path, "w", encoding="utf-8"))
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/util.py", line 745, in json_dump_safer
    return json.dump(obj, fp, cls=WandBJSONEncoder, **kwargs)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/site-packages/wandb/util.py", line 705, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/tuero/anaconda3/envs/deep-learning/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Histogram is not JSON serializable

```

**How to reproduce**
See above.

**Environment**
- OS: Ubuntu 20.04.2 LTS
- Wandb version: 0.12.6
- Python Version: 3.8.11

**Comment by anmolmann** [comment]
Hey @tuero  - we do not support adding the histogram object to the table. However, if you just log the data list instead of `table_data`, then the table will make a histogram for you. For example:
```
table = wandb.Table(columns=table_columns)
for i in range(0, 5):
  table.add_data(
        i, np.random.rand(5).tolist()
  )
wandb.log({"table": table})
```
Hope this helps.

**Comment by tuero** [comment]
@anmolmann Thanks for pointing that out, that is exactly the functionality that I am looking for!
