### ISSUE TITLE
[CLI] Error during data syncing

### ISSUE THREAD

**Issue by kevinghst** [wandb/client#2928]
Hi,

I have been running the same code for months now, but only did I run into this problem from yesterday:

This is the log:

0% [##########################    ] 100% | ETA: 00:38:45
0% [###########################   ] 100% | ETA: 00:29:04wandb: ERROR Droppped streaming file chunk (see wandb/debug.log)
ERROR:root:dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/kevinghst/SGI/frostbite_1_11-16-1/file_stream
Exception in thread FileStreamThread:
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/ext3/miniconda3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 288, in _thread_except_body
    raise e
  File "/ext3/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 282, in _thread_except_body
    self._thread_body()
  File "/ext3/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 265, in _thread_body
    self._handle_response(
  File "/ext3/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 295, in _handle_response
    raise response
  File "/ext3/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 382, in request_with_retry
    response.raise_for_status()
  File "/ext3/miniconda3/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/kevinghst/SGI/frostbite_1_11-16-1/file_stream

0% [############################  ] 100% | ETA: 00:19:22
0% [############################# ] 100% | ETA: 00:09:41[34m[1mwandb[0m: 502 encountered (

Anyone has any ideas?
Thanks,
Kevin

**Comment by kevinghst** [comment]
And this is how I initiate wandb in my code:

```
  wandb.init(
      resume=resume,
      id=exp_name if config["group_add"] == "none" else str(randint(0, 10000000000)),
      config=config,
      project=config["wandb"]["project"],
      reinit=True,
      anonymous="allow",
      name=exp_name,
      group=group_name
  )
```

**Comment by armanhar** [comment]
Hey kevinghst, can you share the debug logs for this run that are in the run directory? Also which wandb version are you using?

**Comment by kevinghst** [comment]
Hi Arman,

Actually, I reran the code today and the problem seemed to have went away. I also updated wandb to the latest version for posterity. 
I am closing this for now. 

Kevin
