### ISSUE TITLE
[Q] How to download artifact model from a run ID using API

### ISSUE THREAD

**Issue by Wilann** [wandb/client#2998]
Hi,

I've used the API to find the run id of my best run, and want to download its associated model artifact. How can I do this? 

I've seen ways to use the artifact API to download artifacts, but need to download the best model, and therefore need to iterate through my runs to find the best one. 

Here's the run metadata:
```
Best Run:
- Name: 2021-12-07_11-19-01_NetVLAD++_Essential
- ID: k3xyplvz
- test_metric.max: 0.4192
- Model Filename: 2021-12-07_11-19-01_NetVLAD++_Essential.pth.tar
```

My code structure:
```
api = wandb.Api()

runs = api.runs(
        path="{}/{}".format(wandb_username, project_name),
        order="-summary_metrics.test_metric.max"
    )

# Logic to find best run 

best_run = api.run(path="{}/{}/{}".format(wandb_username, project_name, best_run_id))
best_model = best_run.file(best_model_name).download()
```

Gives me this error:
```
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/apis/public.py", line 2384, in download
    util.download_file_from_url(path, self.url, Api().api_key)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/util.py", line 1130, in download_file_from_url

    response.raise_for_status()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/wilan/Automatic-Highlight-Generation/k3xyplvz/2021-12-07_11-19-01_NetVLAD++_Essenti
al.pth.tar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 159, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/util.py", line 821, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Automatic-Highlight-Generation/create_highlight_videos.py", line 47, in <module>
    download_best_model(tag_name=initial_configs.model_name,
  File "Automatic-Highlight-Generation/create_highlight_videos.py", line 42, in download_best_model
    best_model = best_run.file(best_model_name).download()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 159, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/util.py", line 821, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
```

**Comment by ramit-wandb** [comment]
Hi @Wilann,

Looking at your [run](https://wandb.ai/wilan/Automatic-Highlight-Generation/runs/k3xyplvz/overview), there seems to be no model files in the `files` tab.

You can access your artifacts through our [Artifacts API](https://docs.wandb.ai/ref/python/public-api/artifact), which you should be able to use to get your artifact. For this project, you should be able to access your artifact as:

```python
import wandb
run = wandb.init()
artifact = run.use_artifact('wilan/Automatic-Highlight-Generation/Trained_Model:v1141', type='model')
artifact_dir = artifact.download()
```

**Comment by Wilann** [comment]
Hi @ramit-wandb, 

Thank you for the quick reply! 

I understand that I can access my artifact model with the Artifacts API, but I need to query my runs to find the run with the best metric. Based on your code snipet, I see you've placed `:v1141` at the end of the model name. How would I retrieve this number from my run ID? 

Alternatively, is there a better way to get my best model from a group of runs?

**Comment by vanpelt** [comment]
@Wilann you can call `run.logged_artifacts()` or `run.used_artifacts()` to get a collection of all artifacts logged or used and then find the artifact you want to download.

**Comment by Wilann** [comment]
@vanpelt Printing either of those functions gives me `<wandb.apis.public.RunArtifacts object at 0x7f2b34827100>`, but using `best_run.file('0x7ff8ce40b070').download()` gives me the same error as above.

**Comment by ramit-wandb** [comment]
Hi @Wilann, you should be able to use the following script to get this working:

```python
import wandb

entity = '<Your-Entity-Name>'
project='<Your-Project-Name>'

api = wandb.Api()

runs = api.runs(f'{entity}/{project}', order='<Your-Metric>') # Sorted by <Your-Metric>
best_run = runs[0]

artifacts = best_run.logged_artifacts()
best_model = [artifact for artifact in artifacts if artifact.type == 'model'][0]

best_model.download()
```

**Comment by Wilann** [comment]
Thank you so miuch @ramit-wandb! Worked perfectly.
