### ISSUE TITLE
suddenly i get error with wandb while previously no error with no change in code -- wandb: Network error (ProxyError), entering retry loop.

### ISSUE THREAD

**Issue by monajalal** [wandb/client#3008]
**Describe the bug**

```
Traceback (most recent call last):
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8a4298b1c0>: Failed to establish a new connection: [Errno 111] Connection refused')))
wandb: Network error (ProxyError), entering retry loop.
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
wandb: Network error (ProxyError), entering retry loop.

```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System**
```
 $ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Additional context**

**Comment by monajalal** [comment]
No sweeps. Just using wanna.log for seeing how my losses change across epochs.

**Comment by aidanjdonohue** [comment]
Hi @monajalal just following up here

**Comment by aidanjdonohue** [comment]
Hi @monajalal , we're going to close out this issue.

**Comment by kalyani7195** [comment]
I facing the same issue as well .. 
--------------------
| distributed init (rank 0): env://, gpu 0
wandb: Network error (ProxyError), entering retry loop.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...
wandb: \ Waiting for wandb.init()...
wandb: | Waiting for wandb.init()...
wandb: Network error (ProxyError), entering retry loop.
wandb: / Waiting for wandb.init()...
wandb: - Waiting for wandb.init()...
wandb: \ Waiting for wandb.init()...
wandb: | Waiting for wandb.init()...
wandb: / Waiting for wandb.init()...
wandb: - Waiting for wandb.init()...
wandb: \ Waiting for wandb.init()...
wandb: | Waiting for wandb.init()...
wandb: / Waiting for wandb.init()...
