### ISSUE TITLE
[App] wandb was workng and now is not

### ISSUE THREAD

**Issue by monajalal** [wandb/client#3018]
```
wandb: Currently logged in as: monajalal (use `wandb login --relogin` to force relogin)
Problem at: main.py 7 <module>
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    wandb.init(project="my-test-project", entity="my-test-project")
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 568, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
```

and

```
$ lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

**Comment by aidanjdonohue** [comment]
Hi @monajalal, if you're still encountering this issue please let us know.

**Comment by monajalal** [comment]
Hi @aidanjdonohue thanks for your response.
I really don't know what was the cause of this transient error. I ran it again with no problem today

```
wandb: 
wandb: Synced 5 W&B file(s), 1 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced atomic-darkness-109: https://wandb.ai/my-test-project/my-test-project/runs/3nmbq2re
wandb: Find logs at: ./wandb/run-20211213_180200-3nmbq2re/logs/debug.log
wandb: 
```

You can perhaps check the URL I shared with you internally.

Here are the related pieces of code I use for wandb. For now, no sweep, just logging my metrics and loss.

```
import wandb
wandb.init(project="my-test-project", entity="my-test-project")

# wandb.init(mode="disabled")

wandb.config = {
   "learning_rate": 1e-3,
   "epochs": 50,
   "batch_size": 8
 }
wandb.watch(model)


                wandb.log({"Epoch": epoch,
                        "Train Loss": train_loss,
                        "val Loss": val_loss,
                        "val MSE": val_mse,
                        "val R2": val_r2,
                        "val_MAE": val_mae,
                        "val RMSLE": val_rmsle,
                        "val NRMSE": val_nrmse})

    wandb.log({'train loss over epochs figure': wandb.Image(plt)})

```

**Comment by monajalal** [comment]
hmm I am now running a 5-fold experiement at the same time so it's possible that this is causing the error? Any chance, I could run the same instance of the code across multiple GPUs with no problem? 

```
wandb: Currently logged in as: monajalal (use `wandb login --relogin` to force relogin)
Problem at: main.py 7 <module>
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    wandb.init(project="my-test-project", entity="my-test-project")
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/SeaExp/mona/venv/dpcc/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 568, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error

```

**Comment by vanpelt** [comment]
@monajalal the error your seeing is due to how you're using multiprocessing.  More information about the error and multiprocessing can be found here: https://docs.wandb.ai/library/init#init-start-error

**Comment by vanpelt** [comment]
The earlier error was do to issues on our server and should be resolved now.

**Comment by monajalal** [comment]
@vanpelt would you like me to create a new issue for the 5-fold cross-validation scenario and close this one?

**Comment by monajalal** [comment]
@vanpelt so I used
`wandb.init(project="my-test-project", entity="my-test-project", settings=wandb.Settings(start_method="thread"))`

from the link you shared and now I am not getting error if I am running my code for 3-fold cross validation across 3 GPUs (somewhat simultaneously). Could you please confirm this is correct way to go about it?

Still, I am not fully sure how adding `settings=wandb.Settings(start_method="thread")` is taking care of the bug.

Thanks a lot for your recommendation.
