### ISSUE TITLE
[CLI] Error:  Error while calling W&B API: cannot use artifact

### ISSUE THREAD

**Issue by alvesraisa** [wandb/client#3117]
Hi,

I am having a problem with wandb
This error is happening when I am training the dataset in Colab:

**wandb: ERROR Error while calling W&B API: cannot use artifact QXJ0aWZhY3Q6NTg3MDk4NDU= as it has not committed (<Response [400]>)
Traceback (most recent call last):**
File "train.py", line 636, in
main(opt)
File "train.py", line 533, in main
train(opt.hyp, opt, device, callbacks)
File "train.py", line 95, in train
loggers = Loggers(save_dir, weights, opt, hyp, LOGGER) # loggers instance
File "/content/yolov5/utils/loggers/init.py", line 73, in init
self.wandb = WandbLogger(self.opt, run_id)
File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 186, in init
self.setup_training(opt)
File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 234, in setup_training
opt.artifact_alias)
File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 274, in download_dataset_artifact
dataset_artifact = wandb.use_artifact(artifact_path.as_posix().replace("\", "/"))
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 2423, in use_artifact
artifact.id, use_as=use_as or artifact_or_name,
File "/usr/local/lib/python3.7/dist-packages/wandb/apis/internal.py", line 126, in use_artifact
return self.api.use_artifact(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 2072, in use_artifact
"usedAs": use_as,
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/retry.py", line 102, in call
result = self._call_fn(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
six.reraise(*sys.exc_info())
File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
raise value
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
return self.client.execute(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
result = self._get_result(document, *args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
return self.transport.execute(document, *args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
request.raise_for_status()
File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

wandb: Waiting for W&B process to finish, PID 588... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced proud-frog-5: https://wandb.ai/catisa/custom_yolov5_siac/runs/3p32tf1c
wandb: Find logs at: ./wandb/run-20220106_131436-3p32tf1c/logs/debug.log

**Before, I imported my dataset to the cloud in wandb platform and my final mensage was this:**

![image](https://user-images.githubusercontent.com/55215618/148391857-2bc3015c-88c2-47df-b472-b715821300bf.png)

**Also, on the wandb platform my log status is this:**

Scanning 'custom_dataset\train.cache' images and labels... 1881 found, 0 missing, 105 empty, 0 corrupted: 100%|██████████████████████████| 1881/1881 [00:00<?, ?it/s]
  0%|                                                                                                                                          | 0/1 [00:00<?, ?it/s]wandb: Adding directory to artifact (.\custom_dataset\train)... Done. 1.1s
wandb: Adding directory to artifact (.\custom_dataset\train)... Done. 1.2s
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/it]
wandb: Adding directory to artifact (.\custom_dataset\val)... Done. 0.2s
Scanning 'custom_dataset\val.cache' images and labels... 394 found, 0 missing, 16 empty, 0 corrupted: 100%|████████████████████████████████| 394/394 [00:00<?, ?it/s]
  0%|                                                                                                                                          | 0/1 [00:00<?, ?it/s]wandb: Adding directory to artifact (.\custom_dataset\val)... Done. 0.2s
wandb: Adding directory to artifact (.\custom_dataset\val)...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.99it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 394/394 [00:21<00:00, 18.24it/s]
Created dataset config file data\custom_dataset_wandb.yaml

**I don't know why they aren't finding my artifacts, thus preventing my training from continuing. Can someone help me? Thank you!**

**Comment by alvesraisa** [comment]
Hi,

I am having a problem with wandb
This error is happening when I am training the dataset in Colab:

**wandb: ERROR Error while calling W&B API: cannot use artifact QXJ0aWZhY3Q6NTg3MDk4NDU= as it has not committed (<Response [400]>)
Traceback (most recent call last):
File "train.py", line 636, in
main(opt)
File "train.py", line 533, in main
train(opt.hyp, opt, device, callbacks)
File "train.py", line 95, in train
loggers = Loggers(save_dir, weights, opt, hyp, LOGGER) # loggers instance
File "/content/yolov5/utils/loggers/init.py", line 73, in init
self.wandb = WandbLogger(self.opt, run_id)
File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 186, in init
self.setup_training(opt)
File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 234, in setup_training
opt.artifact_alias)
File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 274, in download_dataset_artifact
dataset_artifact = wandb.use_artifact(artifact_path.as_posix().replace("\", "/"))
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 2423, in use_artifact
artifact.id, use_as=use_as or artifact_or_name,
File "/usr/local/lib/python3.7/dist-packages/wandb/apis/internal.py", line 126, in use_artifact
return self.api.use_artifact(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 2072, in use_artifact
"usedAs": use_as,
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/retry.py", line 102, in call
result = self._call_fn(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
six.reraise(*sys.exc_info())
File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
raise value
File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
return self.client.execute(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
result = self._get_result(document, *args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
return self.transport.execute(document, *args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
request.raise_for_status()
File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

wandb: Waiting for W&B process to finish, PID 588... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced proud-frog-5: https://wandb.ai/catisa/custom_yolov5_siac/runs/3p32tf1c
wandb: Find logs at: ./wandb/run-20220106_131436-3p32tf1c/logs/debug.log
wandb:**


I imported my dataset to the cloud in wandb platform and my final mensage was this:

![image](https://user-images.githubusercontent.com/55215618/148391857-2bc3015c-88c2-47df-b472-b715821300bf.png)

**Comment by aidanjdonohue** [comment]
@alvesraisa, could you link me to your project page so I can take a look things from our end for you?

**Comment by Saleh-Gholam-Zadeh** [comment]
I'm getting similar error sometimes
