### ISSUE TITLE
how to log optimizer hyperparameters?

### ISSUE THREAD

**Issue by cpoptic** [wandb/client#312]
* Weights and Biases version: 0.7.2
* Python version: 3.6
* Operating System: Mac

### Description

I've got a bunch of hyperparameters being logged via wandb, and I'm trying to do the same for optimizer choice on each experiment run.  Unfortunately, wandb is throwing errors about the 

### What I Did

```
wandb.init()
config = wandb.config

config.dropout = 0.2
config.hidden_layer_size = 128
config.layer_1_num_units = 16
config.layer_2_num_units = 32
config.learn_rate = 0.01
config.epochs = 25
config.batch_size = 32

config.decay = 1e-6
config.momentum = 0.9
config.nesterov = True

config.rho=0.9, 
config.epsilon=1e-6

config.beta_1 = 0.9
config.beta_2 = 0.999
config.amsgrad = False

```

The above code is fine; no issues, and I could just do
```
model.compile(optimizer = 'rmsprop', loss = 'mean_squared_error')
```
or
```
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
```
to compile the model with whatever optimizer.

But suppose I want to also track/log the optimizer's configuration. then I try using some of those tracked config variables to in turn track my optimizer choices:

```
from keras.optimizers import Optimizer, SGD, Adam, RMSprop, Adagrad, Adadelta

sgd = SGD(lr=config.learn_rate, 
          decay=config.decay, 
          momentum=config.momentum,
          nesterov=config.nesterov
         )

rms = RMSprop(lr=config.learn_rate, 
              rho=config.rho, 
              epsilon=config.epsilon
             )

adam = Adam(lr=config.learn_rate,
            beta_1=config.beta_1,
            beta_2=config.beta_2,
            epsilon=config.epsilon,
            decay=config.decay,
            amsgrad=config.amsgrad
           )
```

Theoretically this should be fine, but WandB complains that the objects for those above 3 optimizers are not JSON serializable:

```

> ERROR:wandb.run_manager:communication error with wandb Object of type 'Adam' is not JSON serializable
Traceback (most recent call last):
  File "/anaconda3/envs/metrics/lib/python3.6/site-packages/wandb/apis/__init__.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/envs/metrics/lib/python3.6/site-packages/wandb/apis/internal.py", line 614, in upsert_run
    config = json.dumps(config)
  File "/anaconda3/envs/metrics/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/anaconda3/envs/metrics/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/anaconda3/envs/metrics/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/anaconda3/envs/metrics/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Adam' is not JSON serializable



So my question is: how to track the optimizer in wandb?

**Comment by lukas** [comment]
Are you setting a config object to the optimizer object itself?  I.e. like config.optimizer = adam?  The current expectation is that the config objects are simple things like strings and numbers and hashes, so we would expect you to set config.optimizer = "adam" and then separately config.learn_rate =0.1 etc.  Does that make sense?
