### ISSUE TITLE
[CLI] Wandb import pollutes sys.modules with deprecated graphql version

### ISSUE THREAD

**Issue by RunOrVeith** [wandb/client#3234]
**Description**
When importing wandb, it also imports graphql from the vendors folder. This is version 1.1, which is really old. The latest version is 3.2.0. This breaks other libraries that want to use graphql and require a newer version, if wandb is imported before that library.

**Wandb features**
`import wandb`

**How to reproduce**
First install the latest graphql and wandb:

```
pip install wandb==0.12.10 graphql-core==3.2.0
```

The following script demonstrates and explains the error. 
Uncomment one of the lines in the main to see how the behavior changes. I also added a workaround that deletes the modules from sys.modules again after the import, but I am not sure how that affects wandb functionality.

The line that is currently uncommented produces the following error:
```
Traceback (most recent call last):
  File "/home/veith/Projects/debug-graphql/wandb_graphql_demo/break_the_import.py", line 51, in <module>
    demo_wandb_breaks_graphql_import()
  File "/home/veith/Projects/debug-graphql/wandb_graphql_demo/break_the_import.py", line 22, in demo_wandb_breaks_graphql_import
    do_graphql_import()
  File "/home/veith/Projects/debug-graphql/wandb_graphql_demo/break_the_import.py", line 5, in do_graphql_import
    _ = graphql.GraphQLResolveInfo  # will cause an AttributeError if graphql version is too low
AttributeError: module 'graphql' has no attribute 'GraphQLResolveInfo'
```

```python

def do_graphql_import() -> None:
    import graphql
    print(graphql.__version__)
    _ = graphql.GraphQLResolveInfo  # will cause an AttributeError if graphql version is too low


def demo_wandb_breaks_graphql_import(do_workaround: bool = False) -> None:
    # noinspection PyUnresolvedReferences
    import wandb
    if do_workaround:
        import sys
        # remove the graphql module exposed by wandb
        # not sure if this breaks any wandb functionality
        remove = []
        for name in sys.modules.keys():
            if "graphql" in name:
                remove.append(name)
        print(f"Removing the following modules as a workaround: {remove}")
        for remove_module in remove:
            sys.modules.pop(remove_module)
    do_graphql_import()


"""
Executing this file will result in the following unexpected / potentially breaking behavior:

wandb is imported first, which exposes the "graphql" module that is bundled with wandb
under wandb/vendor/gql-0.2.0 as a module in sys.modules.
This is graphql version 1.1.0 (contradicting the folder name?), which is really old. The latest version in 3.2.0.

Now when the graphql import happens, and it is already exposed in sys.modules from wandb,
it does not import the version that is required (>=3.2.0) by this package,
but (correctly) assumes that it is already imported.
The problem is that the version is so old that some things don't exist anymore, which breaks 3rd party libraries.
An example of this is the "apischema" library, which can now not be imported any more if wandb is imported first.
(E.g. install apischema and try `python -c "import wandb; import apischema"`)

This is very confusing behavior. If wandb still depends on such an old version of graphql, it would be great
if it could not globally expose that module.
If you first import graphql and then wandb, it seems to work, but I am not sure if wandb can handle the newer version.
"""

if __name__ == '__main__':
    # TODO Uncomment one of these lines and execute to see that wandb overwrites the graphql import
    #  It only works if you
    #  - don't import wandb first
    #  - or do the workaround of removing the graphql modules after the wandb import

    # do_graphql_import()
    demo_wandb_breaks_graphql_import()
    # demo_wandb_breaks_graphql_import(do_workaround=True)


```

If wandb really depends on such an old graphql version and even bundles it with the package (it is not listed in the dependencies), then I would expect that it does not pollute the namespace for other libraries that require a newer version.

**Environment**
- OS: [Ubuntu 20.04]
- Environment: [e.g. Local virtual environment]
- Python Version: [3.8]

**Comment by RunOrVeith** [comment]
This seems to be resolved with the 0.12.11 release, so I will close the issue. Thanks!
