### ISSUE TITLE
Ugly error messages in log streaming

### ISSUE THREAD

**Issue by lukas** [wandb/client#33]
* Weights and Biases version: 0.4.19
* Python version: 2.7
* Operating System: os x

### Description

Error messages from the log thread showing up in my console like:

Exception in thread Thread-240234:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/wandb/streaming_log.py", line 122, in write
    super(StreamingLog, self).write(chars)
  File "/usr/local/lib/python2.7/site-packages/wandb/streaming_log.py", line 77, in flush
    self.posting = False
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 216, in __exit__
    self.release()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock

**Comment by shawnlewis** [comment]
I think these were due to ctrl-c'ing and not getting a clean shutdown. Should be better now.
