### ISSUE TITLE
The wandb backend process has shutdown

### ISSUE THREAD

**Issue by bigssmart** [wandb/client#3326]
Has anyone had a problem similar to me ？I ran this code on the Colab platform。
/content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts
env is MPE, scenario is simple_spread, algo is rmappo, exp is check, max seed is 1
seed is 1:
choose to use cpu...
wandb: Currently logged in as: yi-li (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.11
wandb: Run data is saved locally in /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_092843-1t4tb6nn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run rmappo_check_seed1
wandb: ⭐️ View project at https://wandb.ai/yi-li/MPE
wandb: 🚀 View run at https://wandb.ai/yi-li/MPE/runs/1t4tb6nn
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 149, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 397, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 167, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 387, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

and this is my debug.log:
2022-03-03 09:28:43,805 INFO    MainThread:4971 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-03-03 09:28:43,806 INFO    MainThread:4971 [wandb_setup.py:_flush():75] Loading settings from /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/wandb/settings
2022-03-03 09:28:43,806 INFO    MainThread:4971 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-03 09:28:43,806 INFO    MainThread:4971 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train/train_mpe.py', 'program': 'train/train_mpe.py'}
2022-03-03 09:28:43,808 INFO    MainThread:4971 [wandb_init.py:_log_setup():405] Logging user logs to /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_092843-1t4tb6nn/logs/debug.log
2022-03-03 09:28:43,808 INFO    MainThread:4971 [wandb_init.py:_log_setup():406] Logging internal logs to /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_092843-1t4tb6nn/logs/debug-internal.log
2022-03-03 09:28:43,809 INFO    MainThread:4971 [wandb_init.py:init():439] calling init triggers
2022-03-03 09:28:43,809 INFO    MainThread:4971 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {'algorithm_name': 'rmappo', 'experiment_name': 'check', 'seed': 1, 'cuda': True, 'cuda_deterministic': True, 'n_training_threads': 1, 'n_rollout_threads': 128, 'n_eval_rollout_threads': 1, 'n_render_rollout_threads': 1, 'num_env_steps': 20000000, 'user_name': 'yi-li', 'use_wandb': True, 'env_name': 'MPE', 'use_obs_instead_of_state': False, 'episode_length': 25, 'share_policy': True, 'use_centralized_V': True, 'stacked_frames': 1, 'use_stacked_frames': False, 'hidden_size': 64, 'layer_N': 1, 'use_ReLU': False, 'use_popart': False, 'use_valuenorm': True, 'use_feature_normalization': True, 'use_orthogonal': True, 'gain': 0.01, 'use_naive_recurrent_policy': False, 'use_recurrent_policy': True, 'recurrent_N': 1, 'data_chunk_length': 10, 'lr': 0.0007, 'critic_lr': 0.0007, 'opti_eps': 1e-05, 'weight_decay': 0, 'ppo_epoch': 10, 'use_clipped_value_loss': True, 'clip_param': 0.2, 'num_mini_batch': 1, 'entropy_coef': 0.01, 'value_loss_coef': 1, 'use_max_grad_norm': True, 'max_grad_norm': 10.0, 'use_gae': True, 'gamma': 0.99, 'gae_lambda': 0.95, 'use_proper_time_limits': False, 'use_huber_loss': True, 'use_value_active_masks': True, 'use_policy_active_masks': True, 'huber_delta': 10.0, 'use_linear_lr_decay': False, 'save_interval': 1, 'log_interval': 5, 'use_eval': False, 'eval_interval': 25, 'eval_episodes': 32, 'save_gifs': False, 'use_render': False, 'render_episodes': 5, 'ifi': 0.1, 'model_dir': None, 'scenario_name': 'simple_spread', 'num_landmarks': 3, 'num_agents': 3}
2022-03-03 09:28:43,809 INFO    MainThread:4971 [wandb_init.py:init():492] starting backend
2022-03-03 09:28:43,809 INFO    MainThread:4971 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-03 09:28:43,831 INFO    MainThread:4971 [backend.py:ensure_launched():219] starting backend process...
2022-03-03 09:28:43,840 INFO    MainThread:4971 [backend.py:ensure_launched():225] started backend process with pid: 4987
2022-03-03 09:28:43,851 INFO    MainThread:4971 [wandb_init.py:init():501] backend started and connected
2022-03-03 09:28:43,867 INFO    MainThread:4971 [wandb_init.py:init():565] updated telemetry
2022-03-03 09:28:43,873 INFO    MainThread:4971 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-03 09:28:45,203 INFO    MainThread:4971 [wandb_run.py:_on_init():1759] communicating current version
2022-03-03 09:28:45,250 INFO    MainThread:4971 [wandb_run.py:_on_init():1763] got version response 
2022-03-03 09:28:45,251 INFO    MainThread:4971 [wandb_init.py:init():625] starting run threads in backend
2022-03-03 09:28:49,989 INFO    MainThread:4971 [wandb_run.py:_console_start():1733] atexit reg
2022-03-03 09:28:49,993 INFO    MainThread:4971 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-03-03 09:28:49,994 INFO    MainThread:4971 [wandb_run.py:_redirect():1611] Redirecting console.
2022-03-03 09:28:50,000 INFO    MainThread:4971 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-03 09:28:50,001 INFO    MainThread:4971 [wandb_init.py:init():664] run started, returning control to user process

**Comment by bigssmart** [comment]
this is my debug-internal.log ,thanks for your help! @ramit-wandb
2022-03-03 10:05:15,988 INFO    MainThread:5830 [internal.py:wandb_internal():95] W&B internal server running at pid: 5830, started at: 2022-03-03 10:05:15.984282
2022-03-03 10:05:15,993 INFO    WriterThread:5830 [datastore.py:open_for_write():77] open: /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_100513-1pdkzs4p/run-1pdkzs4p.wandb
2022-03-03 10:05:15,997 DEBUG   SenderThread:5830 [sender.py:send():235] send: header
2022-03-03 10:05:16,000 DEBUG   SenderThread:5830 [sender.py:send():235] send: run
2022-03-03 10:05:16,145 DEBUG   HandlerThread:5830 [handler.py:handle_request():141] handle_request: check_version
2022-03-03 10:05:16,152 INFO    SenderThread:5830 [dir_watcher.py:__init__():169] watching files in: /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_100513-1pdkzs4p/files
2022-03-03 10:05:16,152 INFO    SenderThread:5830 [sender.py:_start_run_threads():815] run started: 1pdkzs4p with start time 1646301914
2022-03-03 10:05:16,154 DEBUG   SenderThread:5830 [sender.py:send():235] send: summary
2022-03-03 10:05:16,161 INFO    SenderThread:5830 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-03-03 10:05:16,163 DEBUG   SenderThread:5830 [sender.py:send_request():249] send_request: check_version
2022-03-03 10:05:16,201 DEBUG   HandlerThread:5830 [handler.py:handle_request():141] handle_request: run_start
2022-03-03 10:05:17,602 INFO    Thread-7  :5830 [dir_watcher.py:_on_file_created():217] file/dir created: /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_100513-1pdkzs4p/files/wandb-summary.json
2022-03-03 10:05:23,290 INFO    Thread-7  :5830 [dir_watcher.py:_on_file_created():217] file/dir created: /content/drive/MyDrive/MAPPO/on-policy-main/onpolicy/scripts/results/MPE/simple_spread/rmappo/check/wandb/run-20220303_100513-1pdkzs4p/files/output.log

**Comment by ramit-wandb** [comment]
Hi @bigssmart,

These logs do not belong to the same run. The `debug.log` you posted belongs to run `1t4tb6nn` and this `debug-internal.log` belongs to run `1pdkzs4p`. I would appreciate it if you could share the logs corresponding to the same run.

This `debug-internal.log` also seems to be incomplete. Would it be possible to send the complete log files over? It might be easier to attach them to an email as files and send them over to support@wandb.com.

Thanks,
Ramit

**Comment by bigssmart** [comment]
Thank you very much for your help！ I'm sorry to have brought you so much  trouble。@[ramit-wandb](https://github.com/ramit-wandb)
[debug-internal.log](https://github.com/wandb/client/files/8215318/debug-internal.log)
[debug.log](https://github.com/wandb/client/files/8215319/debug.log)

**Comment by ramit-wandb** [comment]
Hi @bigssmart,

I looked through your debug logs, nothing seems to be abnormal over there. Could you share a little bit about how you are setting up your process? In particular, are you using multiprocessing/multithreading anywhere in your code? It would also help to know some about the behavior of the bug. Does it crash on startup (i.e calling `wandb.init()`), near the end of your run (i.e. calling wandb.finish()) or does it seem to crash on random?

I noticed you are running this project on a Linux based environment. This is a known issue for some users (though it does not always seem to cause an error): could you try setting the environment variable `WANDB_START_METHOD` to `"thread"`?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @bigssmart,

I wanted to circle back around here. Has this issue been resolved for you? Please let me know if we can be of further assistance.

Thanks,
Ramit

**Comment by bigssmart** [comment]
Thank you very much for your help！ I'm sorry to have brought you so much trouble。maybe i have get it, the process is running without this error.I add   'os.environ["WANDB_START_METHOD"] = "thread" '  as you say ,and Changed the address about model_dir to run it. Thanks for your help! @ramit-wandb

**Comment by ramit-wandb** [comment]
Glad to hear that the error is gone! I'll close this request out in that case.
