### ISSUE TITLE
[CLI]: OSError [Errno 24] when running many experiments from same script

### ISSUE THREAD

**Issue by guydav** [wandb/client#3329]
### Describe the bug

I have a use-case where I'm running a whole bunch of different conditions of an experiment, one at a time, from the same Python script. I loop over different experimental conditions, create the appropriate model and synthetic dataset, run the experiment (usually 1-10 minutes of wallclock time), tear everything down, and move on to the next condition. 

I am also repeating this in parallel over multiple slurm jobs, each with a different random seed. Each job throws a similar error to the one below, each after getting through a different number of conditions, but with a different filename at the end.  Sometimes this happens for other temp files, sometimes for checkpoints -- I've pasted a few stack traces below.

All of these jobs are writing to the same wandb_cache location, which is on network storage -- could either of those things be related?

One final note: this error is thrown repeatedly toward the end of my error logs for each slurm job. If I tail the last 1000 lines of the error log for each of these jobs, I see dozens of identical copies of the same stack trace. 

Environment: Python 3.7.4, wandb 0.12.11, pytorch .10.2+cu102, and pytorch-lightning 1.5.10.

## Minimal (pseudo)code:
 I'm happy to try to share a more of my code, but the below is at least partially pseudocode:

```python 
import wandb
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint
from pytorch_lightning.loggers.wandb import WandbLogger

for experiment_conditions in itertools.product(*condition_options):
    # create model and dataset
    model = create_model(experiment_conditions)
    dataset = create_dataset(model_conditions)
    # do some other setup other setup ...
    # set up wandb logger and other callbacks
    logger = WandbLogger(args.wandb_run_name, args.wandb_dir, project=args.wandb_project, entity=args.wandb_entity, log_model=True)
    logger.log_hyperparams(vars(args))
    checkpoint_callback = ModelCheckpoint(dirpath=wandb.run.dir, filename=f'{args.wandb_run_name}-{{epoch:d}}-{{val_loss:.5f}}',
                                            save_top_k=1, verbose=True, monitor=args.early_stopping_monitor_key, mode='min')
    early_stopping_callback = EarlyStopping(args.early_stopping_monitor_key, patience=args.patience_epochs, verbose=True,
                                            min_delta=args.early_stopping_min_delta)
    # create pytorch_lightning trainer
    trainer = Trainer(logger=logger, gpus=args.use_gpu, max_epochs=args.max_epochs,
                        callbacks=[checkpoint_callback, early_stopping_callback],
                        log_every_n_steps=min(max(1, args.subsample_train_size // args.batch_size), 50))
    # train the model
    trainer.fit(model)
    # start tearing everything down
    logger.save()
    logger.finalize('Done')

    wandb.finish()

    del logger
    del trainer
    del model
```
## Several stack traces from different slurm jobs

```shell
Traceback (most recent call last):
  File "run/quinn.py", line 219, in <module>
    main()
  File "run/quinn.py", line 215, in main
    run_single_setting_all_models(args_copy)
  File "run/quinn.py", line 91, in run_single_setting_all_models
    trainer.fit(model)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run
    self._call_teardown_hook()
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1476, in _call_teardown_hook
    self.logger.finalize("success")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 463, in finalize
    self._scan_and_log_checkpoints(self._checkpoint_callback)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 502, in _scan_and_log_checkpoints
    artifact.add_file(p, name="model.ckpt")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 386, in add_file
    return self._add_local_file(name, local_path, digest=digest)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 698, in _add_local_file
    shutil.copyfile(path, f.name)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 24] Too many open files: '/misc/vlgscratch4/LakeGroup/guy/wandb_cache/artifacts/obj/md5/df/tmp_0D64AE84'
```

```shell
OSError: [Errno 24] Too many open files: '/misc/vlgscratch4/LakeGroup/guy/wandb_cache/artifacts/obj/md5/61/tmp_64A5274B'
Traceback (most recent call last):
  File "run/quinn.py", line 219, in <module>
    main()
  File "run/quinn.py", line 215, in main
    run_single_setting_all_models(args_copy)
  File "run/quinn.py", line 91, in run_single_setting_all_models
    trainer.fit(model)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run
    self._call_teardown_hook()
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1476, in _call_teardown_hook
    self.logger.finalize("success")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 463, in finalize
    self._scan_and_log_checkpoints(self._checkpoint_callback)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 502, in _scan_and_log_checkpoints
    artifact.add_file(p, name="model.ckpt")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 386, in add_file
    return self._add_local_file(name, local_path, digest=digest)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 698, in _add_local_file
    shutil.copyfile(path, f.name)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 24] Too many open files: '/misc/vlgscratch4/LakeGroup/guy/wandb_cache/artifacts/obj/md5/61/tmp_64A5274B'
```

```shell
Traceback (most recent call last):
  File "run/quinn.py", line 219, in <module>
    main()
  File "run/quinn.py", line 215, in main
    run_single_setting_all_models(args_copy)
  File "run/quinn.py", line 91, in run_single_setting_all_models
    trainer.fit(model)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run
    self._call_teardown_hook()
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1476, in _call_teardown_hook
    self.logger.finalize("success")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 463, in finalize
    self._scan_and_log_checkpoints(self._checkpoint_callback)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 502, in _scan_and_log_checkpoints
    artifact.add_file(p, name="model.ckpt")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 386, in add_file
    return self._add_local_file(name, local_path, digest=digest)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 698, in _add_local_file
    shutil.copyfile(path, f.name)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 24] Too many open files: '/misc/vlgscratch4/LakeGroup/guy/wandb/run-20220302_222956-pim6k2dl/files/predi-net-108-epoch=1090-val_loss=0.00011.ckpt'
```

```shell
Traceback (most recent call last):
  File "run/quinn.py", line 219, in <module>
    main()
  File "run/quinn.py", line 215, in main
    run_single_setting_all_models(args_copy)
  File "run/quinn.py", line 91, in run_single_setting_all_models
    trainer.fit(model)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run
    self._call_teardown_hook()
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1476, in _call_teardown_hook
    self.logger.finalize("success")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 463, in finalize
    self._scan_and_log_checkpoints(self._checkpoint_callback)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 502, in _scan_and_log_checkpoints
    artifact.add_file(p, name="model.ckpt")
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 386, in add_file
    return self._add_local_file(name, local_path, digest=digest)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py", line 698, in _add_local_file
    shutil.copyfile(path, f.name)
  File "/misc/vlgscratch4/LakeGroup/guy/anaconda3/envs/rainbow/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 24] Too many open files: '/misc/vlgscratch4/LakeGroup/guy/wandb/run-20220302_200602-fxdddq20/files/predi-net-107-epoch=1210-val_loss=0.00009.ckpt'
```

### Environment

WandB version: 0.12.11

OS: CentOS 7, 3.10.0-1160.36.2.el7.x86_64

Python version: 3.7.4

Versions of relevant libraries: pytorch .10.2+cu102, and pytorch-lightning 1.5.10.

**Comment by ramit-wandb** [comment]
Hi @guydav,

I'm sorry this is happening to you. This is a known bug - I'll bump the priority on this issue for you. As a temporary workaround, you can increase the number of file pointers that your filesystem uses by using `ulimit -n`, which should atleast reduce the frequency of this error if not get rid of it completely.

Thanks,
Ramit

**Comment by guydav** [comment]
Thanks @ramit-wandb. I'll try that workaround in the meantime, assuming there's a way to run slurm jobs with a different ulimit. Good to know it's a known issue -- I searched around and any references I found to this OSError seemed outdated.
