### ISSUE TITLE
[Q]Error while importing wandb or executing "wandb login"

### ISSUE THREAD

**Issue by KeKK1N** [wandb/client#3364]
When I try to import wandb in my code or executing "wandb login" in the CMD, this error always happen:

Traceback (most recent call last):
  File "d:\anac\envs\lemonade\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anac\envs\lemonade\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ANAC\envs\lemonade\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\__init__.py", line 40, in <module>
    from wandb import sdk_py27 as wandb_sdk
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\sdk_py27\__init__.py", line 9, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\sdk_py27\wandb_artifacts.py", line 15, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\apis\__init__.py", line 32, in <module>
    from .internal import Api as InternalApi  # noqa
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\apis\internal.py", line 9, in <module>
    from wandb.sdk_py27.internal.internal_api import Api as InternalApi
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\sdk_py27\internal\internal_api.py", line 35, in <module>
    from ..lib.git import GitRepo
  File "d:\anac\envs\lemonade\lib\site-packages\wandb\sdk_py27\lib\git.py", line 195, in <module>
    from git import Repo, exc  # type: ignore
  File "d:\anac\envs\lemonade\lib\site-packages\git\__init__.py", line 42, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "d:\anac\envs\lemonade\lib\site-packages\git\config.py", line 238, in <module>
    class GitConfigParser(with_metaclass(MetaParserBuilder, cp.RawConfigParser, object)):  # type: ignore ## mypy does not understand dynamic class creation # noqa: E501
  File "d:\anac\envs\lemonade\lib\site-packages\git\config.py", line 279, in GitConfigParser
    repo: Union['Repo', None] = None) -> None:
  File "d:\anac\envs\lemonade\lib\typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "d:\anac\envs\lemonade\lib\typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "d:\anac\envs\lemonade\lib\typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "d:\anac\envs\lemonade\lib\site-packages\typing_extensions.py", line 636, in __subclasscheck__
    raise TypeError("Literal cannot be used with issubclass().")
TypeError: Literal cannot be used with issubclass().

This issue happens under the wandb 0.11.2 and python 3.5.2. Do you have an idea how to solve this please ?

**Comment by KeKK1N** [comment]
> Hi @KeKK1N,
> 
> Thanks for writing in. Could you share what version of `wandb` and Python you are using which resulted in this error?
> 
> Thanks, Ramit

The python is 3.5.2 and the wandb is 0.11.2. Thanks.

**Comment by ramit-wandb** [comment]
​Hi @KeKK1N, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by KeKK1N** [comment]
Thanks. I don't have any questions currently
