### ISSUE TITLE
[CLI]: `jnp.bfloat16` device arrays not supported by `wandb.log`

### ISSUE THREAD

**Issue by sanchit-gandhi** [wandb/client#3464]
### Describe the bug

Calling `wandb.log` on a dictionary containing jax.numpy (`jnp`) bfloat16 device arrays throws a recursion error.

```python 
import wandb
import jax.numpy as jnp

wandb.init(project="dummy_project")

metrics = {"loss": jnp.array(1., dtype=jnp.float32)}

wandb.log(metrics, step=1) # works fine!

metrics = {"loss": jnp.array(1., dtype=jnp.bfloat16)}

wandb.log(metrics, step=2) # recursion error
```

```shell
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    wandb.log(metrics, step=2) # recursion error
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1422, in log
    self._log(data=data, step=step, commit=commit)
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1235, in _log
    self._partial_history_callback(data, self.history_step)
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1083, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 511, in publish_partial_history
    item.value_json = json_dumps_safer_history(v)
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/util.py", line 810, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/util.py", line 773, in default
    obj, converted = json_friendly(obj)
  File "/Users/sanchitgandhi/venv/lib/python3.8/site-packages/wandb/util.py", line 624, in json_friendly
    if getsizeof(obj) > VALUE_BYTES_LIMIT:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Environment

WandB version:
0.12.11
OS:
MacOS (local) & Ubuntu 20.04 (gcloud)
Python version:
3.8
Versions of relevant libraries:
JAX 0.3.1

**Comment by sanchit-gandhi** [comment]
Brilliant, thanks!
