### ISSUE TITLE
[CLI]: openai wandb sync exception

### ISSUE THREAD

**Issue by sidyakinian** [wandb/client#3588]
### Describe the bug

After running `openai wandb sync` in the terminal as per [documentation](https://docs.wandb.ai/guides/integrations/other/openai), this happens. I have the latest versions of `openai` and `wandb`. Seems somewhat similar to [this issue](https://github.com/wandb/client/issues/3223), tried `WANDB_START_METHOD="thread"` but it didn't work.

```shell
openai wandb sync
wandb: Currently logged in as: sidyakinian (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.15
wandb: Run data is saved locally in /Users/sidyakinian/wandb/run-20220428_164026-ft-jdOTgW5l5kZZ8zwfz7CQlC52
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ft-jdOTgW5l5kZZ8zwfz7CQlC52
wandb: ⭐️ View project at https://wandb.ai/sidyakinian/GPT-3
wandb: 🚀 View run at https://wandb.ai/sidyakinian/GPT-3/runs/ft-jdOTgW5l5kZZ8zwfz7CQlC52
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    self.run()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_network_status()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
    status_response = self._interface.communicate_stop_status()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    resp = self._communicate_stop_status(status)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
    resp = self._communicate(req, local=True)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Problem at: /Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/openai/wandb_logger.py 149 _log_fine_tune
Traceback (most recent call last):
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 683, in init
    run._on_start()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1946, in _on_start
    self._on_ready()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1961, in _on_ready
    self._telemetry_flush()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 683, in init
    run._on_start()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1946, in _on_start
    self._on_ready()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1961, in _on_ready
    self._telemetry_flush()
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sidyakinian/opt/miniconda3/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/openai/_openai_scripts.py", line 63, in main
    args.func(args)
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/openai/cli.py", line 543, in sync
    resp = openai.wandb_logger.WandbLogger.sync(
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/openai/wandb_logger.py", line 74, in sync
    fine_tune_logged = [
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/openai/wandb_logger.py", line 75, in <listcomp>
    cls._log_fine_tune(
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/openai/wandb_logger.py", line 149, in _log_fine_tune
    wandb.init(
  File "/Users/sidyakinian/opt/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1033, in init
    raise Exception("problem") from error_seen
Exception: problem
/Users/sidyakinian/opt/miniconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Environment

WandB version: 0.12.15

OS: macOS 12.0 Monterey

Python version: `python --version` 3.9.5

**Comment by nate-wandb** [comment]
Hi @sidyakinian, do you have any issues running a basic run of W&B or is the issue isolated to the Open AI integration?

For example do you see this when running the following script:

```
import wandb
run = wandb.init()
run.log({"metric":1})
run.finish()
```

**Comment by sidyakinian** [comment]
@nate-wandb Yes, I see the same issue!

**Comment by sidyakinian** [comment]
Downgrading conda python to 3.7.10 solved the issue.
