### ISSUE TITLE
[Q] Disable symlinks "latest-run" 

### ISSUE THREAD

**Issue by samgelman** [wandb/client#3733]
Hi! I'm using HTCondor, and the "latest-run" directory symlink is causing problems with file transfer. Is there a way to disable or prevent W&B from creating this symlink? Thanks!

**Comment by armanhar** [comment]
Hey @samgelman, I believe it is not possible. But I'll file a ticket for an option to disable the symlink creation.

**Comment by samgelman** [comment]
Thanks for filing a ticket. Having this option would definitely makes things easier for me!

**Comment by armanhar** [comment]
Hey @samgelman, you can do this by initializing the run like this: `wandb.init(settings=wandb.Settings(symlink=False))`

**Comment by puraminy** [comment]
When I run a project on colab I would like to transfer offline files physically to my server and then sync them. But when I copy them to server and run sync I got:

Traceback (most recent call last):
  File "/home/pouramini/.local/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 79, in push
    deduped = self.save_fn(
  File "/home/pouramini/.local/lib/python3.8/site-packages/wandb/filesync/step_checksum.py", line 105, in <lambda>
    return lambda progress_callback: save_fn(
  File "/home/pouramini/.local/lib/python3.8/site-packages/wandb/sdk/internal/artifacts.py", line 224, in <lambda>
    lambda entry, progress_callback: self._manifest.storage_policy.store_file(
  File "/home/pouramini/.local/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 1003, in store_file
    with open(entry.local_path, "rb") as file:
PermissionError: [Errno 13] Permission denied: '/root/.local/share/wandb/artifacts/staging/tmp1cit5_bn'
