### ISSUE TITLE
wandb without a project configured throws an error

### ISSUE THREAD

**Issue by lukas** [wandb/client#4]
* Weights and Biases version: 4.1
* Python version: 2.7
* Operating System: ubuntu

```
wandb sdf
```

```
l2k@l2k-Oryx-Pro:~$ wandb sdf
Traceback (most recent call last):
  File "/home/l2k/.local/bin/wandb", line 11, in <module>
    sys.exit(cli())
  File "/home/l2k/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/l2k/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/l2k/.local/lib/python2.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/l2k/.local/lib/python2.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/l2k/.local/lib/python2.7/site-packages/wandb/cli.py", line 60, in get_command
    project, bucket = api.parse_slug(cmd_name)
  File "/home/l2k/.local/lib/python2.7/site-packages/wandb/api.py", line 128, in parse_slug
    raise Error("No default project configured.")
wandb.api.Error: No default project configured.
```

**Comment by vanpelt** [comment]
Fixed in 0.4.2
