### ISSUE TITLE
struct.error: ushort format requires 0 <= number <= (32767 *2 +1)

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#401]
I'm seeing this error on wandb.init
```
(main) ÷19-06-28 09:14:41|ttys010|trippings-mbp-3|~/git0/mindscribe-question-ai\÷ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init(project='moonscrub')
wandb: Started W&B process version 0.8.3 with PID 33316
wandb: Local directory: wandb/run-20190628_161454-0ti1q1zb
wandb: Syncing run easy-lion-3: https://app.wandb.ai/yaroslavvb/moonscrub/runs/0ti1q1zb
wandb: Run `wandb off` to turn off syncing.
Traceback (most recent call last):
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/internal_cli.py", line 105, in <module>
    main()
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/internal_cli.py", line 97, in main
    headless(args)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/internal_cli.py", line 53, in headless
    util.sentry_reraise(e)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/util.py", line 88, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/internal_cli.py", line 51, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/run_manager.py", line 1053, in wrap_existing_process
    io_wrap.SIGWINCH_HANDLER.add_fd(stdout_read_fd)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/io_wrap.py", line 118, in add_fd
    self._set_win_sizes()
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/io_wrap.py", line 138, in _set_win_sizes
    win_size = struct.pack("HHHH", rows, cols, xpix, ypix)
struct.error: ushort format requires 0 <= number <= (32767 *2 +1)
```

Here are offending values
```
> /Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/io_wrap.py(139)_set_win_sizes()
-> win_size = struct.pack("HHHH", rows, cols, xpix, ypix)
(Pdb) p rows
36
(Pdb) p cols
80
(Pdb) p xpix
-15360
(Pdb) p ypix
1542
```
This seems to be backend problem, I haven't upgraded any packages recently

**Comment by vanpelt** [comment]
Is this on Mac OS?  Is this in the stock terminal app?

**Comment by yaroslavvb** [comment]
This is on Mac Emacs, used through shell mode https://www.gnu.org/software/emacs/manual/html_node/emacs/Shell-Mode.html

I'm also filing this bug from Emacs (jk)

**Comment by vanpelt** [comment]
Hey @yaroslav #408 should fix the issue.  If you can try installing this branch and confirming that would be helpful.  We’ll cut a new release this week.

**Comment by yaroslavvb** [comment]
Hard to reproduce, but from http://man7.org/linux/man-pages/man2/ioctl_tty.2.html this seems like correct fix

**Comment by yaroslavvb** [comment]
Seeing this again

The relevant values
```
(Pdb) p fcntl.ioctl(sys.stdout.fileno(), termios.TIOCGWINSZ, '\0' * 8)
b'%\x00P\x00\x00\xc4\x06\x06'
(Pdb) p array.array('h', win_size)
array('h', [37, 80, -15360, 1542])
```

Maybe the code should just check for exception and fallback to default window size

```
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/run_manager.py", line 1053, in wrap_existing_process
    io_wrap.SIGWINCH_HANDLER.add_fd(stdout_read_fd)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/io_wrap.py", line 118, in add_fd
    self._set_win_sizes()
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/io_wrap.py", line 140, in _set_win_sizes
    win_size = struct.pack("HHHH", rows, cols, xpix, ypix)
struct.error: ushort format requires 0 <= number <= (32767 *2 +1)
wandb: ERROR W&B process (PID 85223) did not respond
wandb crash with W&B process failed to launch, see: wandb/debug.log
```

Looking at relevant values:

**Comment by adrianbg** [comment]
Hi Yaroslav,

Are you sure you've upgraded your W&B package? That value unpacks successfully for me with the new code:

```python
import struct
win_size = b'%\x00P\x00\x00\xc4\x06\x06'
struct.unpack('HHHH', win_size)
(37, 80, 50176, 1542)
```

The values look strange/impossible but there at least isn't an exception.

**Comment by vanpelt** [comment]
Yeah, weird.  We'll catch the error in the next release.  Do you have a sense for what the best default values would be?

**Comment by adrianbg** [comment]
I don’t think it will throw an error the way it is right now. If I’m
missing something, I think it would be good to understand what is going on
rather than handling an exception that we don’t understand.

There are a couple of default values in there already: 25x80, the
“standard” terminal size.

**Comment by yaroslavvb** [comment]
sorry for noise, that was indeed issue with old version of wandb

the new version unapcks it to following values
(37, 80, 50176, 1542)
