### ISSUE TITLE
Should fail more gracefully when you forget to do wandb init

### ISSUE THREAD

**Issue by lukas** [wandb/client#41]
* Weights and Biases version: 0.4.21
* Python version: 2.7.11
* Operating System: os X

### Description

If I forget to run wandb init in my directory I get an unhelpful error message

`Traceback (most recent call last):

  File "/usr/local/bin/wandb", line 11, in <module>

    sys.exit(cli())

  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func

    return f(get_current_context(), *args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/wandb/cli.py", line 37, in wrapper

    return func(*args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/wandb/cli.py", line 369, in run

    dir = wandb_run.run_dir_path(id, dry=False)

  File "/usr/local/lib/python2.7/site-packages/wandb/wandb_run.py", line 58, in run_dir_path

    return os.path.join(__stage_dir__, '%s-%s' % (prefix, run_id))

  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join

    elif path == '' or path.endswith('/'):

AttributeError: 'NoneType' object has no attribute 'endswith'

`

**Comment by shawnlewis** [comment]
Fixed by: https://github.com/wandb/client/commit/14d771c1059f5ac962d20e4200fd9bcd32675187
