### ISSUE TITLE
You do not have permission to access Project: l2k owned by mnist-test  as anonymous

### ISSUE THREAD

**Issue by lukas** [wandb/client#42]
* Weights and Biases version: 0.4.21 
* Python version: 2.7
* Operating System: os x

### Description

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/usr/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/usr/local/lib/python2.7/site-packages/watchdog/events.py", line 454, in dispatch
    _method_map[event_type](event)
  File "/usr/local/lib/python2.7/site-packages/wandb/sync.py", line 358, in on_file_created
    self._get_handler(event.src_path, save_name).on_created()
  File "/usr/local/lib/python2.7/site-packages/wandb/sync.py", line 136, in on_created
    self.on_modified()
  File "/usr/local/lib/python2.7/site-packages/wandb/sync.py", line 142, in on_modified
    progress=False)
  File "/usr/local/lib/python2.7/site-packages/wandb/api.py", line 96, in wrapper
    raise CommError(message)
CommError: You do not have permission to access Project: l2k owned by mnist-test  as anonymous
```

**Comment by lukas** [comment]
https://app.wandb.ai/l2k/mnist-test/runs/69yp6q

**Comment by lukas** [comment]
lukass-MacBook:wandb l2k$ more settings 
[default]
entity: l2k
project: mnist-test

**Comment by shawnlewis** [comment]
We've seen this in other runs. Ex: https://app.wandb.ai/l2k/mnist-test/runs/ld97ui

Chris is adding some more logging on the server to help debug.

**Comment by shawnlewis** [comment]
@lukas, Have you seen this happening lately?
