### ISSUE TITLE
Argparse config with methods as values

### ISSUE THREAD

**Issue by ghost** [wandb/client#437]
* Weights and Biases version: 0.8.5
* Python version: 3.7
* Operating System: Ubuntu Linux 19.04 

### Description
I was trying to log the configuration of the run using argparse Namespace object. In my Namespace object, I use default arguments that are functions. This results in WANB freaking out because it doesn't know how to handle that. A suggestion is to handle such cases by using the `__name__` of the function.

### Error

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/watchdog/events.py", line 454, in dispatch
    _method_map[event_type](event)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 627, in _on_file_created
    self._get_file_event_handler(event.src_path, save_name).on_created()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 237, in on_created
    self._eventually_update()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 248, in _eventually_update
    self._update()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 262, in _update
    config_dict = util.load_yaml(open(self.file_path))
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/util.py", line 657, in load_yaml
    return yaml.full_load(file)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/__init__.py", line 142, in full_load
    return load(stream, FullLoader)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 94, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 551, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 538, in find_python_name
    "module %r is not imported" % module_name, mark)
yaml.constructor.ConstructorError: while constructing a Python object
module 'envs.fl_tx.model_based' is not imported
  in "/home/stelios/Documents/RL/spoonfed-experience/wandb/run-20190717_153737-ja60k6e5/config.yaml", line 9, column 10

Mean Reward ::8.501:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20000/20000 [00:04<00:00, 4970.87it/s]

wandb: Waiting for W&B process to finish, PID 25883
wandb: Program ended successfully.
Traceback (most recent call last):
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/internal_cli.py", line 105, in <module>
    main()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/internal_cli.py", line 97, in main
    headless(args)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/internal_cli.py", line 53, in headless
    util.sentry_reraise(e)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/util.py", line 89, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/internal_cli.py", line 51, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 1064, in wrap_existing_process
    self._sync_etc(headless=True)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 1255, in _sync_etc
    self.shutdown(exitcode)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 984, in shutdown
    self._end_file_syncing(exitcode)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 608, in _end_file_syncing
    handler.finish()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 279, in finish
    self._update()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/run_manager.py", line 262, in _update
    config_dict = util.load_yaml(open(self.file_path))
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/wandb/util.py", line 657, in load_yaml
    return yaml.full_load(file)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/__init__.py", line 142, in full_load
    return load(stream, FullLoader)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 94, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 551, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/site-packages/yaml/constructor.py", line 538, in find_python_name
    "module %r is not imported" % module_name, mark)
yaml.constructor.ConstructorError: while constructing a Python object
module 'envs.fl_tx.model_based' is not imported
  in "/home/stelios/Documents/RL/spoonfed-experience/wandb/run-20190717_153737-ja60k6e5/config.yaml", line 9, column 10
^CException ignored in: <module 'threading' from '/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/stelios/anaconda3/envs/spoonfed-experience/lib/python3.7/threading.py", line 1273, in _shutdown
wandb: Killing W&B process, PID 25883
```

### Temporary Solution

```python
wandb.init(
    project="project name",
    config={x: (y if not callable(y) else y.__name__) for x, y in args.__dict__.items()},
)
```

**Comment by cvphelps** [comment]
We believe this is resolved with an upgrade to the 0.10.x release.
