### ISSUE TITLE
Can not login due to graphql error

### ISSUE THREAD

**Issue by umgupta** [wandb/client#454]
`wandb --version && python --version && uname`
* Weights and Biases version:
Can't execute (most probably latest)
* Python version:
3.7.3
* Operating System:
Linux

### Description
I just started using wandb. I am using `pipenv` to manage package so I installed it via that. I installed it using pipenv and tried to login using `wand login` command. 

### What I Did

```
umang@X > wandb login
Traceback (most recent call last):
  File "/home/umang/.local/share/virtualenvs/folder-J0sgQLGZ/bin/wandb", line 6, in <module>
    from wandb.cli import cli
  File "/home/umang/.local/share/virtualenvs/folder-J0sgQLGZ/lib/python3.7/site-packages/wandb/__init__.py", line 40, in <module>
    from wandb.apis import InternalApi, PublicApi, CommError
  File "/home/umang/.local/share/virtualenvs/folder-J0sgQLGZ/lib/python3.7/site-packages/wandb/apis/__init__.py", line 7, in <module>
    from gql.client import RetryError
  File "/home/umang/.local/share/virtualenvs/folder-J0sgQLGZ/lib/python3.7/site-packages/gql/__init__.py", line 2, in <module>
    from .client import Client
  File "/home/umang/.local/share/virtualenvs/folder-J0sgQLGZ/lib/python3.7/site-packages/gql/client.py", line 3, in <module>
    from graphql import parse, introspection_query, build_ast_schema, build_client_schema
ImportError: cannot import name 'introspection_query' from 'graphql' (/home/umang/.local/share/virtualenvs/folder-J0sgQLGZ/lib/python3.7/site-packages/graphql/__init__.py)

```

**Comment by umgupta** [comment]
I tried it with python3.6 and it works. So the problem is python3.7 specific.

**Comment by umgupta** [comment]
To anyone facing this, just install graphql-core==2.0 before installing wandb.

**Comment by cgebbe** [comment]
Thanks @umgupta . For me, I could simply downgrade graphql-core to 2.0 even after wandb was already installed.

**Comment by pacifictoy** [comment]
For those using conda, pls check this URL for graphql-core version 2.x
https://anaconda.org/conda-forge/graphql-core
For me, I had to use this one:
conda install -c conda-forge/label/cf201901 graphql-core

So I uninstall the one that came when I install wandb by doing 'conda remove graphql-core'
then I had to re-install wandb, and it still uses ver 2.x and it worked
