### ISSUE TITLE
Another network error

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#47]
wandb: Script ended.
wandb: Run summary:
wandb:   epoch 7
wandb:     acc 0.9425042652743575
wandb: Run history:
wandb:   epoch ▁▂▃▃▄▅▆▆▇█
wandb:     acc ▃▇▄▇▅▁▇█▅▄
wandb: Waiting for final file modifications.
wandb: Syncing files in wandb/run-5z0byl:
wandb:   config.yaml
wandb:   diff.patch
wandb:   modify_file.txt
wandb:   wandb-history.jsonl
wandb:   events.out.tfevents.1485040358.gpu
wandb:   wandb-summary.json
wandb:   model.txt
Exception in thread Thread-9:000 of 53295.000 bytes uploaded
Traceback (most recent call last):
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 525, in upload_file
    url, data=progress, headers=extra_headers)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/api.py", line 124, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 533, in upload_file
    completed = int(status.headers['Range'].split("-")[-1])
  File "/Users/shawn/.pyenv/versions/wandb_cli-3.6/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 608, in push
    responses.append(self.upload_file(file_info['url'], open_file, progress))
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 93, in wrapper
    raise CommError(message)
wandb.api.CommError: 'range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shawn/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/shawn/code/wandb/client/wandb/file_pusher.py", line 26, in run
    self._push_function(self.save_name, self.path)
  File "/Users/shawn/code/wandb/client/wandb/sync.py", line 266, in push_function
    progress=lambda _, total: self._stats.update_progress(path, total))
  File "/Users/shawn/code/wandb/client/wandb/api.py", line 93, in wrapper
    raise CommError(message)
wandb.api.CommError: 'range'

wandb: File changed while uploading, restarting: wandb-summary.json
wandb: Synced https://app.wandb.ai/shawn/example-simple1/runs/5z0byl
wandb: job (python) Process exited with code: 0

**Comment by shawnlewis** [comment]
After more investigation I believe this is only happening to wandb-summary.json. My guess is wandb-summary.json is being truncated during the upload, and the upload code / Google doesn't handle that well.

Current fix is to just delay uploading all files til the end of the run. A potentially decent fix is to copy non-deferred files to a temporary location before uploading them.

**Comment by shawnlewis** [comment]
Closing as fixed for now since I haven't seen it since abee525bf580b953ef1db8a69a5a2297245b384b
