### ISSUE TITLE
Importing WandBKerasCallback without running wandb init leads to strange error

### ISSUE THREAD

**Issue by lukas** [wandb/client#48]
* Weights and Biases version: 0.4.22
* Python version: 2.7
* Operating System: OS X

### Description

Traceback (most recent call last):
  File "mnist-cnn.py", line 6, in <module>
    from wandb.wandb_keras import WandBKerasCallback
  File "/Users/l2k/client/wandb/__init__.py", line 144, in <module>
    _do_sync(run.dir)
  File "/Users/l2k/client/wandb/__init__.py", line 107, in _do_sync
    syncer.watch(files='*')
  File "/Users/l2k/client/wandb/sync.py", line 278, in watch
    config=self._config.as_dict(), description=self._description, host=socket.gethostname())
  File "/Users/l2k/client/wandb/api.py", line 398, in upsert_run
    'host': host, 'debug': os.getenv('DEBUG')})
  File "/usr/local/lib/python2.7/site-packages/gql/client.py", line 52, in execute
    raise Exception(str(result.errors[0]))
Exception: {u'message': u"'_model'", u'code': 500, u'locations': [{u'column': 3, u'line': 2}]}

**Comment by lukas** [comment]
hmm, this might not be the reason

**Comment by shawnlewis** [comment]
Can you reproduce this now?

I commented out "import wandb" in wandb-examples/keras/mnist-cnn.py, and got:
Traceback (most recent call last):
  File "mnist-cnn.py", line 10, in <module>
    config = wandb.run.config
NameError: name 'wandb' is not defined

Which seems reasonable.

**Comment by lukas** [comment]
It works great now.
