### ISSUE TITLE
wandb fails on CUDA 8 and python3

### ISSUE THREAD

**Issue by the-lay** [wandb/client#539]
* Weights and Biases version: 0.8.9 (according to pip)
* Python version: 3.7.1
* Operating System: linux

### Description

During any action with wandb, it fails on import (SyntaxError). This happens both in any script or any CLI action. We are running CUDA 8.0, and I guess `pynvml` that is being imported doesn't support python3.

Here's CUDA version:
```
> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
 
Traceback on wandb import:
```
> python3 main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import wandb
  File "/home/username/.local/lib/python3.7/site-packages/wandb/__init__.py", line 42, in <module>
    from wandb.apis import InternalApi, PublicApi, CommError
  File "/home/username/.local/lib/python3.7/site-packages/wandb/apis/__init__.py", line 95, in <module>
    from .public import Api as PublicApi
  File "/home/username/.local/lib/python3.7/site-packages/wandb/apis/public.py", line 21, in <module>
    from wandb.summary import HTTPSummary, download_h5
  File "/home/username/.local/lib/python3.7/site-packages/wandb/summary.py", line 15, in <module>
    from wandb.meta import Meta
  File "/home/username/.local/lib/python3.7/site-packages/wandb/meta.py", line 6, in <module>
    import pynvml
  File "/cm/local/apps/cuda/libs/current/pynvml/pynvml.py", line 1671
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?
```

Traceback on CLI usage:
```
>  wandb
Traceback (most recent call last):
  File "/home/username/.local/bin/wandb", line 7, in <module>
    from wandb.cli import cli
  File "/home/username/.local/lib/python3.7/site-packages/wandb/__init__.py", line 42, in <module>
    from wandb.apis import InternalApi, PublicApi, CommError
  File "/home/username/.local/lib/python3.7/site-packages/wandb/apis/__init__.py", line 95, in <module>
    from .public import Api as PublicApi
  File "/home/username/.local/lib/python3.7/site-packages/wandb/apis/public.py", line 21, in <module>
    from wandb.summary import HTTPSummary, download_h5
  File "/home/username/.local/lib/python3.7/site-packages/wandb/summary.py", line 15, in <module>
    from wandb.meta import Meta
  File "/home/username/.local/lib/python3.7/site-packages/wandb/meta.py", line 6, in <module>
    import pynvml
  File "/cm/local/apps/cuda/libs/current/pynvml/pynvml.py", line 1671
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?
```

### Potential fix

I skimmed the code and the repo, it seems pynvml (Python bindings for NVIDIA Management Library) is used only in `meta.py` and `stats.py` to log used GPU stats and GPU count. A possible fix would be to wrap imports with try-catch + fail flag, or maybe an environment flag to skip that part entirely.

I can make a pull request over this weekend, but let me know if you have something else in mind.

**Comment by the-lay** [comment]
You are right, thank you! Apparently old pynvml was in `PYTHONPATH`, and it was listed before site-packages. I've installed pynvml through pip, as you pointed out, and then run the script with custom PYTHONPATH where site-package is earlier than old pynvml path, and now it works OK.

I will close both the issue and the associated PR, since it's a configuration problem, not the library issue.

**Comment by Qnlp** [comment]
@aclifton314 @borisdayma @vanpelt hi，
How can I solve this problem as follows?  The installed wandb can not be used normally, and other different versions of wandb have been tried. I also have try 0.9.5 version or oldest version and I have search in stackoverflow and baidu search engine. 

`  File "finetune.py", line 399, in <module>
    main(args)
  File "finetune.py", line 373, in main
    logger=logger,
  File "path/github/transformers/examples/lightning_base.py", line 380, in generic_train
    trainer.fit(model)
  File "path/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1003, in fit
    results = self.single_gpu_train(model)
  File "path/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 186, in single_gpu_train
    results = self.run_pretrain_routine(model)
  File "path/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1127, in run_pretrain_routine
    self.logger.log_hyperparams(ref_model.hparams)
  File "path/miniconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 12, in wrapped_fn
    return fn(*args, **kwargs)
  File "path/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 129, in log_hyperparams
    self.experiment.config.update(params, allow_val_change=True)
AttributeError: 'function' object has no attribute 'update'
`

**Comment by vanpelt** [comment]
Hey @Qnlp this is really strange.  Can you print what `experiment.config` is after you've initialized the WandbLogger?  A quick thing to try is our prerelease library.  You can install with `pip install wandb -U --pre`.

**Comment by Qnlp** [comment]
@vanpelt thank you for your tips, I have try your command `pip install wandb -U --pre`, and runing, I have a trouble as follows, which means I need connect internet during training ?
`
Network error (SSLError), entering retry loop. See TODO_refactor.txt for full traceback.
wandb: Network error (SSLError), entering retry loop. See TODO_refactor.txt for full traceback.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
`
