### ISSUE TITLE
wandb crashing with "W&B process failed to launch"

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#546]
```
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.log
Traceback (most recent call last):
  File "train.py", line 806, in <module>
    logging_setup()
  File "/home/ubuntu/log.py", line 39, in logging_setup
    wandb.init(project=project_name, name=logdir_name, dir=wandb_dir)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wandb/__init__.py", line 976, in init
    _init_headless(run)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wandb/__init__.py", line 258, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.log
```
Here's the debbug log
[debug (1).log](https://github.com/wandb/client/files/3612330/debug.1.log)

One potential weirdness is that I saw it trying to upload data to someone else's account
```
https://app.wandb.ai/sokolov-yas/Transformer-XL+source+code/runs/bbecxm7m
```

This is an account of of a person who created an image I'm running. Does `wandb login` save credentials to disk?

**Comment by vanpelt** [comment]
Yes, wandb login writes your key to ~/.netrc. That debug log is for a completed run.  Most likely the launch failed because of permissions, but I thought we had a better error message in that case.

**Comment by yaroslavvb** [comment]
I had wrong debug.log, actual log is pretty short and looks like this

```
2019-09-14 17:47:02,424 DEBUG   MainThread:22297 [wandb_config.py:_load_defaults():87] no defaults not found in config-defaults.yaml
2019-09-14 17:47:02,434 DEBUG   MainThread:22297 [cmd.py:execute():722] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/ubuntu, universal_newlines=False, shell=None, istream=<valid stream>)
2019-09-14 17:47:02,441 DEBUG   MainThread:22297 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/ubuntu, universal_newlines=False, shell=None, istream=None)
2019-09-14 17:47:02,445 DEBUG   MainThread:22297 [cmd.py:execute():722] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/ubuntu, universal_newlines=False, shell=None, istream=None)
```

The python stack trace was
```
Traceback (most recent call last):
  File "train.py", line 845, in <module>
    g.logger.exception('Failed')
AttributeError: 'NoneType' object has no attribute 'exception'
Traceback (most recent call last):
  File "train.py", line 806, in <module>
    logging_setup()
  File "/home/ubuntu/log.py", line 41, in logging_setup
    sync_tensorboard=True)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wand
b/__init__.py", line 980, in init
    _init_headless(run, False)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wand
b/__init__.py", line 258, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.lo
g
Traceback (most recent call last):
  File "train.py", line 806, in <module>
    logging_setup()
  File "/home/ubuntu/log.py", line 41, in logging_setup
    sync_tensorboard=True)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wand
b/__init__.py", line 980, in init
    _init_headless(run, False)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wand
b/__init__.py", line 258, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.lo
g
```

it seems transient, rerunning again works

**Comment by vanpelt** [comment]
This one looks like it was blowing up in your training script:
```
Traceback (most recent call last):
  File "train.py", line 845, in <module>
    g.logger.exception('Failed')
AttributeError: 'NoneType' object has no attribute 'exception'
```
Looks like g.logger can be Null sometimes.  We should make stacktraces prettier because this looks like we caused it.

**Comment by yaroslavvb** [comment]
That's because you did cause it :)

The stacktrace shows exception in wandb, my code intercepted this exception, and then crashed with its own error

https://github.com/cybertronai/transformer-xl/blob/github-saturday/train.py#L836

My guess was that this crash is connected to ~/.netrc containing someone else's credentials (different from WANDB_API_KEY), have not seen this since deleting this file. Will reopen if I see this again

**Comment by piyush-bagad** [comment]
Tried deleting `~/.netrc` and logging back in. Still facing the same issue.
