### ISSUE TITLE
logs not syncing

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#548]
I'm seeing the following in my console. The link leads me to "run not found" page
https://app.wandb.ai/yaroslavvb/Transformer-XL+source+code/runs/jrvwsxrc

Here's the debug log -- https://s3.amazonaws.com/yaroslavvb2/data/debug3.log

```
wandb: Started W&B process version 0.8.10 with PID 28187
wandb: Local directory: ../../tmp/wandb/wandb/dryrun-20190914_181203-c4nf0oyh

wandb: Local directory: ../../tmp/wandb/wandb/run-20190914_181203-jrvwsxrc
wandb: Syncing run saturdaytxl: https://app.wandb.ai/yaroslavvb/Transformer-XL+source+code/runs/jrvwsxrc
wandb: Run `wandb off` to turn off syncing.

Torch version: 1.1.0
```

**Comment by yaroslavvb** [comment]
Not sure if related, but if I send keyboard interrupt, I see this
```
wandb: plus 8 W&B file(s) and 0 media file(s)
val | loss: 1.12 | accuracy@1: 0.78 | accuracy@5: 0.90 | MRR@5: 0.83 : : 4it [00:01,  2.10it/s]wandb: | 0.60MB of 0.60MB val | loss: 1.08 | accuracy@1: 0.79 | accuracy@5: 0.90 | MRR@5: 0.83 : : 5it [00:02,  1.95it/s]wandb: \ 0.60MB of 0.60MB wandb:
wandb: Synced saturdaytxl: https://app.wandb.ai/yaroslavvb/Transformer-XL+source+code/runs/jk33wosq

wandb: Waiting for W&B process to finish, PID 29901
Exception ignored in: <bound method tqdm.__del__ of val | loss: 1.08 | accuracy@1: 0.79 | accuracy@5: 0.90 | MRR@5: 0.83 : : 5it [00:03,  1.95it/s]>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1019, in __del__
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1202, in close
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tqdm/_tqdm.py", line 542, in _decr_instances
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tqdm/_monitor.py", line 51, in exit
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/threading.py", line 521, in set
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/threading.py", line 364, in notify_all
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
```

**Comment by yaroslavvb** [comment]
Seems transient, I reran, and now it's syncing again
https://app.wandb.ai/yaroslavvb/Transformer-XL%20source%20code/runs/hyxhg8qm

**Comment by yaroslavvb** [comment]
Also tried manual wandb sync, it seems to succeed, but run is not found

```
(pytorch_p36) ubuntu@ip-172-31-65-115:~$ wandb: You can sync this run to the cloud by running:
wandb: wandb sync ../../tmp/wandb/wandb/dryrun-20190914_195033-1czeay84


^C
(pytorch_p36) ubuntu@ip-172-31-65-115:~$ wandb sync ../../tmp/wandb/wandb/dryrun-20190914_195033-1czeay84
wandb: Syncing ../../tmp/wandb/wandb/dryrun-20190914_195033-1czeay84 to:
wandb: lrfix2 https://app.wandb.ai/yaroslavvb/Transformer-XL+source+code/runs/uihhmvmn
wandb: Uploading history metrics
wandb: Updating run and uploading files
wandb:
wandb: Finished!
```

**Comment by yaroslavvb** [comment]
Found the problem, it's an an issue with spaces in project name
