### ISSUE TITLE
AttributeError: module 'os' has no attribute 'setpgrp'`

### ISSUE THREAD

**Issue by TKassis** [wandb/client#618]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.13
* Python version: 3.6.7
* Operating System: Windows 10

### Description

When I run a sweep using `wandb agent [sweepID]` I get the following error:

`AttributeError: module 'os' has no attribute 'setpgrp'``

Full traceback below:

`2019-10-15 20:39:25,932 - wandb.wandb_agent - INFO - Running runs: []
2019-10-15 20:39:26,111 - wandb.wandb_agent - INFO - Agent received command: run
2019-10-15 20:39:26,112 - wandb.wandb_agent - INFO - Agent starting run with config:
        batch_size: 16
        image_size: 246
        learning_rate: 0.0004520644327596513
2019-10-15 20:39:26,117 - wandb.wandb_agent - ERROR - Exception while processing command: {'args': {'batch_size': {'value': 16}, 'image_size': {'max': 300, 'min': 64, 'value': 246}, 'learning_rate': {'max': 0.01, 'min': 0.0001, 'value': 0.0004520644327596513}}, 'program': 'train.py', 'run_id': 'jldigqhv', 'run_storage_id': 'UnVuOnYxOmpsZGlncWh2OnJzbmEtaW50cmFjcmFuaWFsLWhlbW9ycmhhZ2UtZGV0ZWN0aW9uOnRrYXNzaXM=', 'type': 'run'}
Traceback (most recent call last):
  File "c:\users\timothy\miniconda3\envs\tf\lib\site-packages\wandb\wandb_agent.py", line 198, in _process_command
    result = self._command_run(command)
  File "c:\users\timothy\miniconda3\envs\tf\lib\site-packages\wandb\wandb_agent.py", line 247, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "c:\users\timothy\miniconda3\envs\tf\lib\site-packages\wandb\wandb_agent.py", line 41, in __init__
    env=env, preexec_fn=os.setpgrp)
AttributeError: module 'os' has no attribute 'setpgrp'`

**Comment by raubitsj** [comment]
Windows support was improved with 0.8.13 but `wandb agent` still has a dependency on unix specific process handling.  We will look into a windows workaround for this path.

**Comment by raubitsj** [comment]
Looks like we can likely implement this in windows with:
https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NEW_PROCESS_GROUP

The change shouldn't be too complex, we will just need to test it with:https://docs.wandb.com/library/sweeps/configuration#stopping-criteria

Since this stopping criteria will send a signal to the process group.

**Comment by vanpelt** [comment]
0.8.14 now has sweep support on Windows!
