### ISSUE TITLE
AttributeError: module 'tensorflow.python.data.ops.dataset_ops' has no attribute 'DatasetV1'

### ISSUE THREAD

**Issue by WaGGstoun** [wandb/client#624]
* Weights and Biases version: 0.8.13
* TensorFlow version: 2.0
* Python version: 3.5
* Operating System: Windows 10 Pro --- Version: 1903

### Description

When submitting data for validation to "validation_data" or through "validation_split" in the class "tf.keras.Sequential" function "fit". It turns out an error. Without "wandb.keras.WandbCallback()" everything works fine. But also without "validation_data" or "validation_split" also works. I have to choose a validation or entry in "wandb".

### What I Did

```
history = model.fit(
    X_train, y_train, batch_size=len(X_train), epochs=epochsNum, verbose=True, 
    callbacks=[wandb.keras.WandbCallback()], validation_data=(X_test, y_test), shuffle=True
    )
```

### Terminal output

```
Traceback (most recent call last):
  File "PATH/Training_NN.py", line 171, in <module>
    callbacks=[wandb.keras.WandbCallback()], validation_data=(X_test, y_test), shuffle=True
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1363, in fit
    validation_steps=validation_steps)
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 92, in new_arrays
    set_wandb_attrs(cbk, (val_inputs[0], val_targets[0]))
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 70, in set_wandb_attrs
    elif is_dataset(val_data):
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 32, in is_dataset
    return isinstance(data, (dataset_ops.DatasetV1, dataset_ops.DatasetV2))
AttributeError: module 'tensorflow.python.data.ops.dataset_ops' has no attribute 'DatasetV1'
```

**Comment by vanpelt** [comment]
Hey @WaGGstoun, that's so strange we've been testing on the latest versions of tensorflow and didn't see this.  I've created a branch that should address this issue.  You can access try it now by running:  `pip install --upgrade git+git://github.com/wandb/client.git@feature/fix-tf2#egg=wandb`.  Let me know if that doesn't fix the issue for you.  We'll target a new official release for early next week.

**Comment by WaGGstoun** [comment]
Hi @vanpelt, thank you for your prompt response. If I understand everything correctly. The error still remained, but changed from this:
```
File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 32, in is_dataset
    return isinstance(data, (dataset_ops.DatasetV1, dataset_ops.DatasetV2))
```
, on this:
```
File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 32, in is_dataset
    dataset_types = (dataset_ops.DatasetV2,)
```
### Terminal output
```
Traceback (most recent call last):
  File "PATH/Training_NN.py", line 171, in <module>
    callbacks=[wandb.keras.WandbCallback()], validation_data=(X_test, y_test), shuffle=True
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1363, in fit
    validation_steps=validation_steps)
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 95, in new_arrays
    set_wandb_attrs(cbk, (val_inputs[0], val_targets[0]))
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 73, in set_wandb_attrs
    elif is_dataset(val_data):
  File "C:\Users\user\Anaconda3\envs\Main\lib\site-packages\wandb\keras\__init__.py", line 32, in is_dataset
    dataset_types = (dataset_ops.DatasetV2,)
AttributeError: module 'tensorflow.python.data.ops.dataset_ops' has no attribute 'DatasetV2'
```

**Comment by vanpelt** [comment]
Ahh, I see what’s happening.  Instead of importing keras in your script, you should do `from tensorflow import keras`.  I’ll fix this case tomorrow, but tf2 now includes a special version of keras.

**Comment by vanpelt** [comment]
Whoops, just pushed a new version that should fix this!

**Comment by WaGGstoun** [comment]
Thanks @vanpelt , everyone is working.
