### ISSUE TITLE
Traceback when running mnist example (using plaidml/keras)

### ISSUE THREAD

**Issue by lemonad** [wandb/client#676]
* Weights and Biases version: 0.8.15
* Python version: 3.7.4
* Keras version: 2.2.4
* Plaidml version: 0.6.4
* Operating System: Darwin

### Description

I'm trying to run the example at <https://docs.wandb.com/library/example-projects/keras> with the addition of

```
import os

import plaidml.keras

os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
```

before the example code (I need it to use Radeon VII on OSX).

### What I Did
Running the code, I get a traceback

```
Using plaidml.keras.backend backend.
wandb: Tracking run with wandb version 0.8.15
wandb: Run data is saved locally in wandb/run-20191113_204208-mg5eih6v
wandb: Syncing run gallant-jazz-1
wandb: ⭐️ View project at https://app.wandb.ai/lemonad/uncategorized
wandb: 🚀 View run at https://app.wandb.ai/lemonad/uncategorized/runs/mg5eih6v
wandb: Run `wandb off` to turn off syncing.

INFO:plaidml:Opening device "metal_amd_radeon_vii.0"
Train on 60000 samples, validate on 10000 samples
Epoch 1/25
   32/60000 [..............................] - ETA: 24:04 - loss: 2.3314 - acc: 0.0312Traceback (most recent call last):
  File "try_wandb.py", line 67, in <module>
    callbacks=[WandbCallback(data_type="image", labels=labels)])
  File "/Users/lemonad/.local/share/virtualenvs/Deep_Learning_HT19-O0LExEKV/lib/python3.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/Users/lemonad/.local/share/virtualenvs/Deep_Learning_HT19-O0LExEKV/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 204, in fit_loop
    callbacks.on_batch_end(batch_index, batch_logs)
  File "/Users/lemonad/.local/share/virtualenvs/Deep_Learning_HT19-O0LExEKV/lib/python3.7/site-packages/keras/callbacks.py", line 115, in on_batch_end
    callback.on_batch_end(batch, logs)
  File "/Users/lemonad/.local/share/virtualenvs/Deep_Learning_HT19-O0LExEKV/lib/python3.7/site-packages/wandb/keras/__init__.py", line 310, in on_batch_end
    wandb.run.summary['graph'] = wandb.Graph.from_keras(self.model)
  File "/Users/lemonad/.local/share/virtualenvs/Deep_Learning_HT19-O0LExEKV/lib/python3.7/site-packages/wandb/data_types.py", line 961, in from_keras
    inbound_keras_node = Node.from_keras(in_layer)
  File "/Users/lemonad/.local/share/virtualenvs/Deep_Learning_HT19-O0LExEKV/lib/python3.7/site-packages/wandb/data_types.py", line 1128, in from_keras
    node.id = layer.name
AttributeError: 'list' object has no attribute 'name'
```

**Comment by cvphelps** [comment]
Thanks for reporting this lemonad!

**Comment by lemonad** [comment]
I've previously run into other backend/computation graph problems using PlaidML, not related to wandb, so I would not be surprised if this is a problem based in the PlaidML backend differing from e.g. how the tensorflow backend works.

**Comment by ariG23498** [comment]
Hey @lemonad 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
