### ISSUE TITLE
wandb init throws error

### ISSUE THREAD

**Issue by lukas** [wandb/client#7]
* Weights and Biases version: 0.4.4
* Python version: 3.6.1
* Operating System: ubuntu

### Description

I did

```wandb init```

got

```
bottle-angle - This model finds the angle of a bottle.
lassen - Project to build neural net from scratch.
mnist-sample - Messing around with simple handwritten digits models
Traceback (most recent call last):
  File "/home/l2k/.pyenv/versions/3.6.1/bin/wandb", line 11, in <module>
    sys.exit(cli())
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/wandb/cli.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/home/l2k/.pyenv/versions/3.6.1/lib/python3.6/site-packages/wandb/cli.py", line 309, in init
    question = inquirer.List('project', message="Which project should we use?", choices=project_names + ["Create New"])
AttributeError: module 'inquirer' has no attribute 'List'
```

**Comment by vanpelt** [comment]
Weird, I can't reproduce this.  @lukas can you see what version of inquirer you have?  It should be 2.1.11 which the python spec enforces...
