### ISSUE TITLE
"wandb.Error: history.add expects dict" when adding OrderedDict

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#72]
Instead of isinstance check to see if dict-like by calling methods.

Traceback (most recent call last):
  File "./run_pg.py", line 79, in <module>
    run_policy_gradient_algorithm(env, agent, callback=callback, usercfg = cfg)
  File "/Users/shawn/code/modular_rl/modular_rl/core.py", line 117, in run_policy_gradient_algorithm
    if callback: callback(stats)
  File "./run_pg.py", line 74, in callback
    run.history.add(stats.items())
  File "/Users/shawn/.pyenv/versions/crowdai-run/lib/python2.7/site-packages/wandb/history.py", line 28, in add
    raise wandb.Error('history.add expects dict')
wandb.Error: history.add expects dict

**Comment by shawnlewis** [comment]
Fixed
