### ISSUE TITLE
TF 2 sync tensorboard fix summary_iterator import

### ISSUE THREAD

**Issue by YanickSchraner** [wandb/client#731]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.19
* Python version: 3.6.8
* Operating System: Linux (Ubuntu 18.04)

### Description

I tried to sync existing TB logs to wandb. It failed due to a TF 2 incompatible import of the summary_iterator.

### What I Did

```
wandb sync logs
wandb: Syncing logs to:
wandb: eager-bird-22 XXXXX
wandb: Found tfevents file, converting...
Traceback (most recent call last):
  File "/home/yanick/code/gfootball/venv/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/wandb/cli.py", line 152, in wrapper
    return func(*args, **kwargs)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/wandb/cli.py", line 445, in sync
    path, run_id=id, project=project, entity=entity, ignore_globs=globs)
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/wandb/wandb_run.py", line 316, in from_directory
    summary.update(wbtf.stream_tfevents(path, file_api, run, namespace=namespace))
  File "/home/yanick/code/gfootball/venv/lib/python3.6/site-packages/wandb/tensorflow/__init__.py", line 49, in stream_tfevents
    for summary in tf.train.summary_iterator(path):
```
### Fix
Change tensorflow/__init__.py file like this:
Add the summary_iterator import:
```
try:
    from tensorflow.train import summary_iterator
except ImportError:
    from tensorflow.compat.v1.train import summary_iterator
```
On line 49 change `for summary in tf.train.summary_iterator(path):` to `for summary in summary_iterator(path):`

Tested the change on my system and it worked.

**Comment by cvphelps** [comment]
Thanks for the PR
