### ISSUE TITLE
Error at the end of a run that was trying to sync a lot of data

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#83]
This was while I was sync'ing GB of data from other runs:

Exception in thread Thread-274:12690.000 of 245572398.000 bytes uploaded
Traceback (most recent call last):
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/site-packages/wandb/file_pusher.py", line 33, in run
    self._push_function(self.save_name, save_path)
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/site-packages/wandb/sync.py", line 288, in push_function
    progress=lambda _, total: self._stats.update_progress(path, total))
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/site-packages/wandb/api.py", line 86, in wrapper
    raise CommError(message)
CommError: The API call urlfetch.Fetch() took too long to respond and was cancelled.

**Comment by shawnlewis** [comment]
A second of those runs also failed. 

And a 3rd got this error:[2017-10-11 23:33:25,395] Request failed with exception 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql. Retrying for the 1 time...
Traceback (most recent call last):
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/site-packages/gql/client.py", line 64, in _get_result
    result = self.transport.execute(document, *args, **kwargs)
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/site-packages/gql/transport/requests.py", line 38, in execute
    request.raise_for_status()
  File "/home/shawn/anaconda2/envs/rllab/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql

**Comment by shawnlewis** [comment]
The second error was because pusher (in the server) got a 504, maybe because we're triggering it so rapidly. This run was uploading 918 files.

**Comment by shawnlewis** [comment]
One issue is the file store calls back to our server, which does a datastore write, for each file uploaded. This needs to be rate-limited (max one per second).  But error shouldn't be returned to the client, so something else happened.

This can probably be reproduced by creating a run that uploads lots of files in a row. Maybe run multiple of those runs in parallel.
