### ISSUE TITLE
W&B process failed to launch

### ISSUE THREAD

**Issue by raubitsj** [wandb/client#839]
* Weights and Biases version: 0.8.25
* Python version: Any
* Operating System: ?

### Description

When calling `wandb.init()`, a new process is spawned which performs the metric synchronization with the server.  When the synchronization process takes too long to start (30 seconds) you can see this message: 

```
wandb: Tracking run with wandb version 0.8.22
wandb: ERROR W&B process (PID 19750) did not respond
wandb: ERROR Failed to kill wandb process, PID 19750
wandb: ERROR W&B process failed to launch, see: wandb/wandb-debug.log
Traceback (most recent call last):
...
```

### Status

As of 0.8.25, there are workarounds in place for non jupyter / non windows environments.  We are still investigating some instances of the failure so please send the logs displayed on the terminal as well as the wandb/debug.log from the run that failed.

A workaround for most of the conditions is to set:
```
WANDB_DISABLE_CODE=True
```
or
```
os.environ["WANDB_DISABLE_CODE"] = "True"
```

**Comment by deepaks4077** [comment]
Hi @raubitsj :

An attempt to connect to compute note socket on compute canada, by the wandb process timed out:

wandb: Dry run mode, not syncing to the cloud.
wandb: Tracking run with wandb version **0.8.16**
Traceback (most recent call last):
  File "main.py", line 282, in <module>
    main()
  File "main.py", line 139, in main
    wandb.init(**wandb_args)
  File "/home/**/python3.7/site-packages/wandb/__init__.py", line 1056, in init
    _init_headless(run, False)
  File "/home/**/python3.7/site-packages/wandb/__init__.py", line 270, in _init_headless
    success, _ = server.listen(30)
  File "/home/**/python3.7/site-packages/wandb/wandb_socket.py", line 46, in listen
    self.connect()
  File "/home/**/python3.7/site-packages/wandb/wandb_socket.py", line 40, in connect
    self.connection, addr = self.socket.accept()
  File "/cvmfs/**/python/3.7.4/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
socket.timeout: timed out

I have also seen connection refused errors (similar stacktrace, except error was Errno 111).

**Comment by deepaks4077** [comment]
@raubitsj, Update on 0.8.25:

wandb: Dry run mode, not syncing to the cloud.
wandb: Tracking run with wandb version **0.8.25**

Traceback (most recent call last):
  File "main.py", line 282, in <module>
    main()
  File "main.py", line 139, in main
    wandb.init(**wandb_args)
  File "/home/**/python3.7/site-packages/wandb/__init__.py", line 1086, in init
    _init_headless(run, False)
  File "/home/**/python3.7/site-packages/wandb/__init__.py", line 281, in _init_headless
    success, _ = server.listen(30)
  File "/home/**/python3.7/site-packages/wandb/wandb_socket.py", line 46, in listen
    self.connect()
  File "/home/**/python3.7/site-packages/wandb/wandb_socket.py", line 40, in connect
    self.connection, addr = self.socket.accept()
  File "/cvmfs/**/python/3.7.4/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
socket.timeout: timed out

**Comment by raubitsj** [comment]
@deepaks4077 Thanks for the report, looks like our recent fixes didnt improve your environment, Can you send the debug.log from one of these failing runs? (attach here, paste in the app support window, or email jeff (at) wandb (dot) com)

**Comment by deepaks4077** [comment]
2020-02-09 20:36:32,779 DEBUG   MainThread:213683 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2020-02-09 20:36:32,799 DEBUG   MainThread:213683 [meta.py:setup():94] code probe starting
2020-02-09 20:36:32,803 DEBUG   MainThread:213683 [meta.py:_setup_code_git():49] probe for git information
2020-02-09 20:36:32,809 DEBUG   MainThread:213683 [cmd.py:execute():728] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/<pathtorepo>, universal_newlines=False, shell=None, istream=<valid stream>)
2020-02-09 20:36:32,851 DEBUG   MainThread:213683 [cmd.py:execute():728] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/<pathtorepo>, universal_newlines=False, shell=None, istream=None)
2020-02-09 20:36:32,864 DEBUG   MainThread:213683 [meta.py:_setup_code_program():58] scan for untracked program
2020-02-09 20:36:32,865 DEBUG   MainThread:213683 [cmd.py:execute():728] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/<pathtorepo>, universal_newlines=False, shell=None, istream=None)
2020-02-09 20:36:32,926 DEBUG   MainThread:213683 [meta.py:setup():116] code probe done
2020-02-09 20:36:32,936 DEBUG   MainThread:213683 [run_manager.py:__init__():537] Initialized sync for fairness-prj/5av61n0d
2020-02-09 20:36:32,944 INFO    MainThread:213683 [run_manager.py:wrap_existing_process():1135] wrapping existing process 212668
2020-02-09 20:36:32,950 DEBUG   MainThread:213683 [connectionpool.py:_new_conn():813] Starting new HTTPS connection (1): pypi.org:443
2020-02-09 20:36:33,798 INFO    Thread-3  :213683 [run_manager.py:_on_file_created():673] file/dir created: /home/<path_to_wandb_rundir>/dryrun-20200210_013543-5av61n0d/output.log
2020-02-09 20:36:40,967 INFO    MainThread:213683 [run_manager.py:init_run():920] system metrics and metadata threads started
2020-02-09 20:36:40,968 INFO    MainThread:213683 [run_manager.py:wrap_existing_process():1152] informing user process we are ready to proceed
2020-02-09 20:36:40,969 INFO    MainThread:213683 [run_manager.py:_sync_etc():1259] entering loop for messages from user process
2020-02-09 20:43:39,854 INFO    MainThread:213683 [run_manager.py:_sync_etc():1282] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1581298732.blg4507.int.ets1.calculquebec.ca", "policy": "live"}}
ser process
2020-02-09 20:43:39,854 INFO    MainThread:213683 [5av61n0d:run_manager.py:_sync_etc():1282] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1581298732.blg4507.int.ets1.calculquebec.ca", "policy": "live"}}

*This is my debug.log*, under my wandb run directory. All the runs have the same parent directory. 

1. I only see details for 1 run here even though I scheduled 576 runs. 
2. The 576 runs were split into 18 runs per slurm job. There were 32 jobs.
3. Only 178 runs completed :(
4. 1 run = 1 hyperparameter configuration = 1 experiment.

**Comment by raubitsj** [comment]
By default debug.log is only for the last run.  The debug.log attached appears to be for a successful run.
I will let you know later today how to get unique debug logs for your slurm usecase.

**Comment by raubitsj** [comment]
@deepaks4077 
Can you use different wandb sync directories for all your runs so we can track down what might be going on.  Here is a code snippet that will create a new directory for each process:

```python
path = "{}/wandb.{}".format(os.environ.get("PWD"), os.getpid())
os.mkdir(path)
wandb.init(dir=path)
```
