### ISSUE TITLE
KerasCallback crash when Keras tries to call isatty on OutStreamTee

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#87]
---------- Forwarded message ---------
From: Kaviarasu Vetriselvi <kaviarasu.vetriselvi@nielsen.com>
Date: Tue, Nov 7, 2017 at 3:08 PM
Subject: Error- perceptron.py
To: <lukeab@gmail.com>

kvetrisel-06405:keras-perceptron krangasamyvetriselvi$ wandb run perceptron.py 

Using TensorFlow backend.

/Users/krangasamyvetriselvi/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6

  return f(*args, **kwds)

2017-11-07 15:05:21.402135: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

wandb: Syncing https://app.wandb.ai/ml-class/perceptron-nov6/runs/68mn7eig

wandb: Run directory: wandb/run-20171107_150519-68mn7eig

Train on 60000 samples, validate on 10000 samples

Epoch 1/10

Traceback (most recent call last):

  File "perceptron.py", line 37, in <module>

    callbacks=[WandbKerasCallback()])

  File "/Users/krangasamyvetriselvi/anaconda/lib/python3.6/site-packages/keras/models.py", line 893, in fit

    initial_epoch=initial_epoch)

  File "/Users/krangasamyvetriselvi/anaconda/lib/python3.6/site-packages/keras/engine/training.py", line 1631, in fit

    validation_steps=validation_steps)

  File "/Users/krangasamyvetriselvi/anaconda/lib/python3.6/site-packages/keras/engine/training.py", line 1161, in _fit_loop

    callbacks.on_epoch_begin(epoch)

  File "/Users/krangasamyvetriselvi/anaconda/lib/python3.6/site-packages/keras/callbacks.py", line 59, in on_epoch_begin

    callback.on_epoch_begin(epoch, logs)

  File "/Users/krangasamyvetriselvi/anaconda/lib/python3.6/site-packages/keras/callbacks.py", line 276, in on_epoch_begin

    verbose=self.verbose)

  File "/Users/krangasamyvetriselvi/anaconda/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 270, in __init__

    self._dynamic_display = (sys.stdout.isatty() or

AttributeError: 'OutStreamTee' object has no attribute 'isatty'

wandb: Script ended because of Exception, press ctrl-c again to abort syncing.

wandb: Waiting for final file modifications.

wandb: Syncing files in wandb/run-20171107_150519-68mn7eig:

wandb:   description.md

wandb:   diff.patch

wandb:                                                                                

wandb: Verifying uploaded files... verified!

wandb: Synced https://app.wandb.ai/ml-class/perceptron-nov6/runs/68mn7eig

wandb: job (perceptron.py) Process exited with code: 1

kvetrisel-06405:keras-perceptron krangasamyvetriselvi$ python --version

Python 3.6.0 :: Anaconda 4.3.0 (x86_64)

**Comment by shawnlewis** [comment]
Fixed
