### ISSUE TITLE
Issue using agent with PyTorch+cuda

### ISSUE THREAD

**Issue by noncuro** [wandb/client#892]
* Weights and Biases version: 0.8.28
* Python version: Python 3.6.9
* Operating System: Linux (Colab)

### Description

I'm trying to run a sweep in Colab. My model is in PyTorch and requires a GPU. It seems that the use of multiprocessing isn't compatible with PyTorch. I've created the below toy example to reproduce the bug. Any advice?

### What I Did

```
import wandb
import torch

def train():
  model = torch.nn.Linear(100,100)
  model.cuda()

sweep_id = wandb.sweep({
    'method': 'grid',
    'parameters': {
        'blah': {
            'values': [1]
        }
    }
})
wandb.agent(sweep_id, function=train)
```

Stacktrace:
```
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/wandb_agent.py", line 64, in _start
    function()
  File "<ipython-input-23-3598f8bb2714>", line 6, in train
    model.cuda()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by raubitsj** [comment]
I tried your example on colab (enabling GPU fin the runtime) and I wasnt able to reproduce the failure you saw with your example posted.

I do understand the failure and we are working on better mechanisms to run sweeps in notebook environments that should address this issue.   I will leave this bug open until we have a beta of the new client code that should address this.

**Comment by noncuro** [comment]
Apologies! Try this code instead. The issue only occurs if you interact with cuda outside of the training loop, even if just to check if cuda is available

```
import wandb
import torch

cuda = torch.cuda.is_available()

def train():
  model = torch.nn.Linear(100,100)
  model.cuda()

sweep_id = wandb.sweep({
    'method': 'grid',
    'parameters': {
        'blah': {
            'values': [1]
        }
    }
})
wandb.agent(sweep_id, function=train)
```

**Comment by vanpelt** [comment]
Yeah, 

I believe this is the same as tensorflow.  Cuda isn't fork safe so once you connect to the GPU in a process you can't fork.  If you only connect to cuda in a forked process everything should work.  Is it possible for you to refactor your colab code to only access cuda in the train function?

**Comment by ariG23498** [comment]
Hey @noncuro
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by JayThibs** [comment]
I'm having this issue as well, but I'm not sure how to refactor my code to make the sweep work? Here's my PyTorch Lightning model and the sweep code I'm using:

```
class FloodModel(pl.LightningModule):
    def __init__(self, hparams):
        super(FloodModel, self).__init__()
        self.hparams.update(hparams)
        # self.save_hyperparameters()
        # print(self.hparams.get("architecture"))
        self.architecture = self.hparams.get("architecture", "Unet")
        self.backbone = self.hparams.get("backbone", "resnet34")
        self.weights = self.hparams.get("weights", "imagenet")
        self.lr = self.hparams.get("lr", 1e-3)
        self.max_epochs = self.hparams.get("max_epochs", 1000)
        self.min_epochs = self.hparams.get("min_epochs", 6)
        self.patience = self.hparams.get("patience", 6)
        self.num_workers = self.hparams.get("num_workers", 2)
        self.batch_size = self.hparams.get("batch_size", 32)
        self.x_train = train_x
        self.y_train = train_y
        self.x_val = val_x
        self.y_val = val_y
        self.output_path = self.hparams.get("output_path", "model-outputs")
        self.gpu = self.hparams.get("gpu", False)
        self.transform = training_transformations

        # Where final model will be saved
        self.output_path = Path.cwd() / self.output_path
        self.output_path.mkdir(exist_ok=True)

        # Track validation IOU globally (reset each epoch)
        self.intersection = 0
        self.union = 0

        # Instantiate datasets, model, and trainer params
        self.train_dataset = FloodDataset(
            self.x_train, self.y_train, transforms=self.transform
        )
        self.val_dataset = FloodDataset(self.x_val, self.y_val, transforms=None)
        self.model = self._prepare_model()
        self.trainer_params = self._get_trainer_params()

    # Required LightningModule methods

    def forward(self, image):
        # Forward pass through the network
        return self.model(image)

    def training_step(self, batch, batch_idx):
        # Swtich on training mode
        self.model.train()
        torch.set_grad_enabled(True)

        # Load images and labels
        x = batch["chip"]
        y = batch["label"].long()

        if self.gpu:
            x, y = x.cuda(non_blocking=True), y.cuda(non_blocking=True) ## CUDA

        # Forward pass
        preds = self.forward(x)

        # Calculate training loss
        criterion = XEDiceLoss()
        xe_dice_loss = criterion(preds, y)

        # Log batch xe_dice_loss
        self.log(
            "xe_dice_loss",
            xe_dice_loss,
            on_step=True,
            on_epoch=True,
            prog_bar=True,
            logger=True
        )
        return xe_dice_loss

    def validation_step(self, batch, batch_idx):
        # Switch on evaluation mode
        self.model.eval()
        torch.set_grad_enabled(False)

        # Load images and labels
        x = batch["chip"]
        y = batch["label"].long()
        if self.gpu:
            x, y = x.cuda(non_blocking=True), y.cuda(non_blocking=True) ## CUDA

        # Forward pass & softmax
        preds = self.forward(x)
        preds = torch.softmax(preds, dim=1)[:, 1]
        preds = (preds > 0.5) * 1

        # Calculate validation IOU (global)
        intersection, union = intersection_and_union(preds, y)
        self.intersection += intersection
        self.union += union

        # Log batch IOU
        batch_iou = intersection / union
        self.log(
            "iou", batch_iou, on_step=True, on_epoch=True, prog_bar=True, logger=True
        )

        return batch_iou

    def train_dataloader(self):
        # DataLoader class for training
        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            shuffle=True,
            pin_memory=True,
        )

    def val_dataloader(self):
        # DataLoader class for training
        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            num_workers=0,
            shuffle=False,
            pin_memory=True,
        )

    def configure_optimizers(self):
        # Define optimizer
        optimizer = torch.optim.Adam(self.model.parameters(), lr=self.lr)

        # Define Scheduler
        scheduler = lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='max', factor=0.5, patience=self.patience
        )

        scheduler = {
            "scheduler": scheduler,
            "interval": "epoch",
            "monitor": "val_iou",
        } # logged value to monitor

        return [optimizer], [scheduler]

    def validation_epoch_end(self, outputs):
        # Calculate IOU at the end of epoch
        epoch_iou = self.intersection / self.union

        # Reset metrics before next epoch
        self.intersection = 0
        self.union = 0

        # Saving the model in ONNX format
        # dummy_input = torch.zeros(64, 2, 7, 7, device=self.device)
        # model_filename = f"model_{str(self.global_step).zfill(5)}.onnx"
        # torch.onnx.export(self, dummy_input, model_filename, opset_version=11)
        # wandb.save(model_filename)

        # Log epoch validation IOU
        self.log("val_iou", epoch_iou, on_epoch=True, prog_bar=True, logger=True)
        return epoch_iou

    ## Convenience Methods ##

    def _prepare_model(self):
        cls = getattr(smp, self.architecture)
        model = cls(
           encoder_name=self.backbone,
           encoder_weights=self.weights,
           in_channels=2,
           classes=2,
        )
        if self.gpu:
            model.cuda() ## CUDA
        return model

    def _get_trainer_params(self):
        # Define callback behavior
        checkpoint_callback = ModelCheckpoint(
            dirpath=self.output_path,
            # save_top_k=1,
            monitor="val_iou",
            mode="max",
            verbose=True,
        )
        early_stop_callback = EarlyStopping(
            monitor="val_iou",
            patience=(self.patience * 4),
            mode="max",
            verbose=True,
        )

        # Specify where Tensorboard logs will be saved
        self.log_path = Path.cwd() / self.hparams.get("log_path", "tensorboard-logs")
        self.log_path.mkdir(exist_ok=True)
        logger = TensorBoardLogger(self.log_path, name="driven-data-comp")
        wandb_logger = WandbLogger(project="Driven-Data-Floodwater-Mapping", entity="effective-altruism-techs")

        trainer_params = {
            "callbacks": [checkpoint_callback, early_stop_callback],
            "max_epochs": self.max_epochs,
            "min_epochs": self.min_epochs,
            "default_root_dir": self.output_path,
            "logger": [logger, wandb_logger],
            "gpus": None if not self.gpu else 1,
            "fast_dev_run": self.hparams.get("fast_dev_run", False),
            "num_sanity_val_steps": self.hparams.get("val_sanity_checks", 0),
        }
        return trainer_params

    def fit(self):
        # Set up and fit Trainer object
        self.trainer = pl.Trainer(**self.trainer_params)
        self.trainer.fit(self)
```
Sweep code:

```
def sweep_iteration():
    # set up W&B logger
    wandb.init()    # required to have access to `wandb.config`
    wandb_logger = WandbLogger()

    # print(wandb.config)

    # instantiate model - note how we refer to sweep parameters with wandb.config
    flood_model = FloodModel(hparams=wandb.config)

    # train
    flood_model.fit()

    wandb.watch(flood_model)

    print(wandb.config)
    print(flood_model.trainer_params["callbacks"][0].best_model_score)
```
