### ISSUE TITLE
socket timeout

### ISSUE THREAD

**Issue by Yumin-Sun-00** [wandb/client#903]
* Weights and Biases version: 0.8.21
* Python version: 3.6.9
* Operating System: Ubuntu 1804

### What I did

I run my script and got time out error on socket. This happened once before, and it recovered itself. Today, I got the same problem.

### error log
```
wandb: Tracking run with wandb version 0.8.21
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    wandb.init(project="net")
  File "/usr/*/Documents/.py3torch/lib/python3.6/site-packages/wandb/__init__.py", line 1075, in init
    _init_headless(run)
  File "/usr/*/Documents/.py3torch/lib/python3.6/site-packages/wandb/__init__.py", line 277, in _init_headless
    success, _ = server.listen(30)
  File "/usr/*/Documents/.py3torch/lib/python3.6/site-packages/wandb/wandb_socket.py", line 46, in listen
    self.connect()
  File "/usr/*/Documents/.py3torch/lib/python3.6/site-packages/wandb/wandb_socket.py", line 40, in connect
    self.connection, addr = self.socket.accept()
  File "/usr/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out
```

**Comment by raubitsj** [comment]
Can you update to a more recent version, we have made some fixes that address some of the socket issues similar to what you described.

**Comment by Yumin-Sun-00** [comment]
I update the version `wandb-0.8.29`, but I think this is hard to have conclusions. Because the errors happen somehow like randomly.

**Comment by ariG23498** [comment]
Hey @Yumin-Sun-00 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
