### ISSUE TITLE
Writing to wandb-summary.json.

### ISSUE THREAD

**Issue by tryptofanik** [wandb/client#915]
* Weights and Biases version: 0.8.29
* Python version: 3.6.9
* Operating System: Linux

### Description

I am trying to run neural network training on computational cluster. Because of some limitation I can submit my job via srun, so it is not possible to pass in web token when wandb.init is executed. So wandb outputs me:

```
wandb: W&B is a tool that helps track and visualize machine learning experiments
wandb: No credentials found.  Run "wandb login" to visualize your metrics
wandb: Tracking run with wandb version 0.8.29
wandb: Run data is saved locally in wandb/run-20200315_130643-351p8022
```
But unfortunately after my model is created and starts training and error occurs:

```
Training...
Steps per epoch = 152
Total steps = 76000

Epoch 0
model.save_weights() at step 152

Epoch 1
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    'bn_momentum': bn_momentum.numpy()}, step=step)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/__init__.py", line 744, in log
    run.log(row, commit, step, sync, *args, **kwargs)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/wandb_run.py", line 648, in log
    self.history.add(row, *args, step=step, commit=commit, **kwargs)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/history.py", line 162, in add
    self._write()
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/history.py", line 248, in _write
    self._add_callback(self.row)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/wandb_run.py", line 626, in _history_added
    self.summary.update(row, overwrite=False)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/summary.py", line 172, in update
    self._root._write(commit=True)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/summary.py", line 363, in _write
    with open(self._fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/scidatasm/ar/pointnet_own/src/wandb/run-20200315_130643-351p8022/wandb-summary.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/history.py", line 248, in _write
    self._add_callback(self.row)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/wandb_run.py", line 626, in _history_added
    self.summary.update(row, overwrite=False)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/summary.py", line 172, in update
    self._root._write(commit=True)
  File "/scidatasm/ar/.tf2.1/lib/python3.6/site-packages/wandb/summary.py", line 363, in _write
    with open(self._fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/scidatasm/ar/pointnet_own/src/wandb/run-20200315_130643-351p8022/wandb-summary.json'
wandb: Program ended successfully.
``` 

### What I Did

I set `WANDB_DIR` to the directory I want and passed this environmental var. to srun. I have checked if python see it.

Any suggestion why this happen? 
Is there any way of passing web token inside the code or to env variable?

**Comment by vanpelt** [comment]
Hey @tryptofanik What is srun?  Can you send me a link to it?  You can pass the API key using the env variable WANDB_API_KEY.

**Comment by tryptofanik** [comment]
srun is a command for submitting commands to computational nodes:
https://slurm.schedmd.com/srun.html
Actually, now it is working. Maybe that was a problem with disc sync or something...

And thanks for answering second question it solves my problem anyway :)
