### ISSUE TITLE
Anaconda 400 error when running sweep with wandb agent

### ISSUE THREAD

**Issue by StephanHeijl** [wandb/client#917]
* Weights and Biases version: 0.8.29
* Python version: Python 3.6.9
* Operating System: Linux

### Description
I tried to initialize a new sweep, this created no problems in the previous days, so I used the previous sweep configuration as a template. When running the sweep with the wandb agent command, copied directly from the sweep page, the first run finishes and syncs. After syncing the anaconda 400 error appears and the sweep halts without exiting the script. Relauching the sweep immediately yields the 400 error included below.

```
method: bayes
metric:
  goal: maximize
  name: Mean ROC AUC
parameters:
  activation:
    distribution: categorical
    values:
    - selu
    - relu
    - prelu
    - elu
  batch_size:
    distribution: int_uniform
    max: 256
    min: 16
  dropout:
    distribution: uniform
    max: 0.5
    min: 0
  embedding_layer_1:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_2:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_3:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_4:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_5:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_6:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_7:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_8:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_9:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_10:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_11:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_12:
    distribution: categorical
    values:
    - 0
    - 1
  embedding_layer_13:
    distribution: categorical
    values:
    - 0
    - 1
  epochs:
    distribution: int_uniform
    max: 200
    min: 10
  hidden_size:
    distribution: int_uniform
    max: 2048
    min: 64
  learning_rate:
    distribution: categorical
    values:
    - 0.001
    - 0.005
    - 0.0001
    - 0.0005
    - 1e-05
    - 5e-05
  n_layers:
    distribution: int_uniform
    max: 8
    min: 1
  optimizer:
    distribution: categorical
    values:
    - adam
    - sgd
program: train_custom_summaries_nn.py
```

### What I Did

Attempt to update the wandb client, create a new sweep (same result), remove redundant configuration options.

```
wandb: Synced sweet-sweep-1: https://app.wandb.ai/stephanheijl/summaries-predictor/runs/fewqa8aj
2020-03-17 13:34:38,830 - wandb.wandb_agent - INFO - Cleaning up finished run: fewqa8aj
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop. See /home/stephan/summary_classifier/wandb/debug.log for full traceback.
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
```
Debug log:
```
2020-03-17 13:33:37,953 DEBUG   MainThread:13472 [wandb_config.py:_load_defaults():119] no defaults not found in config-defaults.yaml
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [meta.py:setup():97] code probe starting
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [git_repo.py:repo():30] git repository is invalid
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [meta.py:_setup_code_program():58] save program starting
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [meta.py:_setup_code_program():60] save program starting: /home/stephan/summary_classifier/venv/bin/wandb
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [meta.py:_setup_code_program():65] save program saved: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/code/venv/bin/wandb
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [meta.py:_setup_code_program():67] save program
2020-03-17 13:33:37,970 DEBUG   MainThread:13472 [meta.py:setup():119] code probe done
2020-03-17 13:33:37,984 DEBUG   MainThread:13472 [run_manager.py:__init__():541] Initialized sync for summaries-predictor/fewqa8aj
2020-03-17 13:33:37,987 INFO    MainThread:13472 [run_manager.py:wrap_existing_process():1144] wrapping existing process 13417
2020-03-17 13:33:37,987 WARNING MainThread:13472 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-03-17 13:33:37,990 DEBUG   MainThread:13472 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2020-03-17 13:33:38,220 DEBUG   MainThread:13472 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 41731
2020-03-17 13:33:38,274 INFO    MainThread:13472 [run_manager.py:init_run():924] system metrics and metadata threads started
2020-03-17 13:33:38,274 INFO    MainThread:13472 [run_manager.py:init_run():963] upserting run before process can begin, waiting at most 10 seconds
2020-03-17 13:33:38,288 DEBUG   Thread-14 :13472 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:33:38,516 DEBUG   Thread-14 :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:33:38,528 INFO    Thread-14 :13472 [run_manager.py:_upsert_run():1048] saving patches
2020-03-17 13:33:38,528 INFO    Thread-14 :13472 [r2020-03-17 13:33:40,646 INFO    MainThread:13397 [wandb_agent.py:run():194] Running runs: ['fewqa8aj']
2020-03-17 13:33:40,649 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:33:40,853 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:33:45,860 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:33:46,277 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:33:51,285 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:33:51,537 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:33:56,544 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:33:56,768 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:01,776 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:01,992 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:07,000 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:07,200 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:12,208 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:12,414 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:17,420 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:17,641 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:22,648 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:23,376 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:28,384 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:28,588 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:33,601 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:33,822 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:38,830 INFO    MainThread:13397 [wandb_agent.py:run():209] Cleaning up finished run: fewqa8aj
2020-03-17 13:34:38,833 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:39,063 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:34:39,067 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:34:39,068 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:34:40,160 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:40,375 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:34:40,376 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:34:40,377 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:34:42,720 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:43,413 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:34:43,417 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:34:43,418 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:34:43,418 ERROR   MainThread:13397 [retry.py:__call__():108] Retry attempt failed:
Traceback (most recent call last):
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/wandb/retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/wandb/apis/internal.py", line 116, in execute
    six.reraise(*sys.exc_info())
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/wandb/apis/internal.py", line 110, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/stephan/summary_classifier/venv/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2020-03-17 13:34:48,151 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:48,403 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:34:48,407 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:34:48,408 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:34:56,924 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:57,279 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:34:57,283 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:34:57,283 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:35:14,963 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:35:20,742 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:35:20,745 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:35:20,746 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:35:57,755 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:35:57,993 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:35:57,996 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:35:57,998 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2020-03-17 13:37:15,699 DEBUG   MainThread:13397 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:37:16,000 DEBUG   MainThread:13397 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 500 None
2020-03-17 13:37:16,003 ERROR   MainThread:13397 [internal.py:execute():113] 500 response executing GraphQL.
2020-03-17 13:37:16,004 ERROR   MainThread:13397 [internal.py:execute():114] {"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"TypeError: bad operand type for unary -: 'NoneType'\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
fied: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:14,978 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:16,830 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:16,979 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:18,980 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:20,461 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:20,980 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:22,981 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:23,951 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:23,982 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:25,982 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:26,983 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/wandb-metadata.json
2020-03-17 13:34:27,598 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:27,983 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:29,984 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:30,937 INFO    MainThread:13472 [run_manager.py:_sync_etc():1291] received message from user process: {"exitcode": 0}
2020-03-17 13:34:30,938 INFO    MainThread:13472 [run_manager.py:_sync_etc():1377] closing log streams and sending exitcode to W&B
2020-03-17 13:34:30,938 INFO    MainThread:13472 [run_manager.py:shutdown():1068] shutting down system stats and metadata service
2020-03-17 13:34:30,984 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/output.log
2020-03-17 13:34:30,984 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/wandb-history.jsonl
2020-03-17 13:34:30,985 INFO    Thread-3  :13472 [run_manager.py:_on_file_created():677] file/dir created: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/wandb-summary.json
2020-03-17 13:34:31,061 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:31,325 INFO    MainThread:13472 [run_manager.py:shutdown():1080] stopping streaming files and file change observer
2020-03-17 13:34:31,985 INFO    Thread-3  :13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/wandb-events.jsonl
2020-03-17 13:34:31,986 INFO    MainThread:13472 [run_manager.py:_on_file_modified():688] file/dir modified: /home/stephan/summary_classifier/wandb/run-20200317_123335-fewqa8aj/wandb-metadata.json
2020-03-17 13:34:32,017 DEBUG   MainThread:13472 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:32,276 DEBUG   MainThread:13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:34,009 DEBUG   Thread-18 :13472 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-03-17 13:34:34,144 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:34,227 DEBUG   Thread-18 :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-03-17 13:34:34,238 DEBUG   Thread-18 :13472 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-03-17 13:34:34,293 DEBUG   Thread-7  :13472 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/stephanheijl/summaries-predictor/fewqa8aj/file_stream HTTP/1.1" 200 None
2020-03-17 13:34:34,294 INFO    MainThread:13472 [run_manager.py:_sync_etc():1396] rendering summary
2020-03-17 13:34:34,294 INFO    MainThread:13472 [run_manager.py:_sync_etc():1429] syncing files to cloud storage
2020-03-17 13:34:34,675 DEBUG   Thread-18 :13472 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/stephanheijl/summaries-predictor/fewqa8aj/___batch_archive_2.tgz?Expires=1584448534&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=aCemPzgvnvqHg5xVGrPDBNH1Nns08WCKdSM8lbF%2B8MNoxWksbHx90qa2ra7c3f6XCwCkXZyk52Fl6i4sb9%2Byv1Ivz1secA3Ey3knzsGhv6BcMkwmI1D3prLxEH6H5wIWXm%2FTOyv03rPmRWguOyozgn6ks5W7MWR2sy%2FZzhSuYuwHDvTAwcXq111BBfGeS8xFHCN4j7yDfromuhdCDr3uY4CzGU3b1I1GWsqWxsHRzcN7BcjtcmK5ENg0RMBri1QsK9b1MZDLxO0%2Fxso022AHolPJ0HxLHWsa4LOlaXR8bPQN0uDnHOfN6ixA5RIJgOZmtHmlbljhGjQrVgTWh1iPLg%3D%3D HTTP/1.1" 200 0
2020-03-17 13:34:35,800 INFO    MainThread:13472 [run_manager.py:_sync_etc():1444] syncing complete: https://app.wandb.ai/stephanheijl/summaries-predictor/runs/fewqa8aj
2020-03-17 13:34:35,800 INFO    MainThread:13472 [fewqa8aj:run_manager.py:_sync_etc():1444] syncing complete: https://app.wandb.ai/stephanheijl/summaries-predictor/runs/fewqa8aj
```

**Comment by kennazilis** [comment]
Hi Stephan, 
One common reason for this is that the metric your are optimizing in your configuration YAML file is not a metric that you are logging. For example, you could be optimizing the metric f1, but logging validation_f1. Double check that you're logging the exact metric name that you're optimizing.

If that doesn't help, please let me know and we can look deeper into this.

**Comment by StephanHeijl** [comment]
Hi @kennazilis,

That was indeed the issue, I renamed my loss in the logging code but not in the YAML file. 
Making sure they conformed fixed my issue.

Thanks for your help!
