### ISSUE TITLE
wandb: ERROR W&B process (PID 18228) did not respond (in windows)

### ISSUE THREAD

**Issue by braindotai** [wandb/client#923]
`wandb --version && python --version && uname`

wandb, version 0.8.29
Python 3.7.5
MINGW64_NT-10.0-18363,

* Weights and Biases version: 3.7.5
* Python version: 0.8.29
* Operating System: Windows

### Description
I'm using wandb first time and I am initializing a project using `wandb.init()` in a python script.
### What I Did
I am running -
```python 
# other imports
import wandb

wandb.init()
# building model, training... etc
```
Its showing
```
wandb: Tracking run with wandb version 0.8.29
Traceback (most recent call last):
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\internal_cli.py", line 106, in <module>
    main()
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\internal_cli.py", line 98, in main
    headless(args)
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\internal_cli.py", line 54, in headless
    util.sentry_reraise(e)
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\util.py", line 94, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\internal_cli.py", line 52, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\run_manager.py", line 1137, in wrap_existing_process
    stderr_read_file = os.fdopen(stderr_read_fd, 'rb')
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\os.py", line 1027, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [WinError 6] The handle is invalid
wandb: ERROR W&B process (PID 8748) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "c:\Users\brain\Desktop\Projects\Dxeon\pytorch nn.py", line 6, in <module> 
    wandb.init(project = "my-project")
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\__init__.py", line 1088, in init
    _init_headless(run)
  File "C:\Users\brain\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\__init__.py", line 304, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
```

**Comment by cvphelps** [comment]
Hey there, thanks for reporting this— for anyone else who was encountering this issue, make sure you're doing `wandb login` on the command line where you're running your training script so that your machine is authenticated.

**Comment by tumbleintoyourheart** [comment]
> Hey there, thanks for reporting this— for anyone else who was encountering this issue, make sure you're doing `wandb login` on the command line where you're running your training script so that your machine is authenticated.

This doesn't help. The launch error has been like forever and it hasn't been fixed even though there are multiples issues reported on it.

**Comment by vanpelt** [comment]
@tumbleintoyourheart are you seeing this in issue in Windows?  We're working hard on a new CLI to put this issue to bed for good.  Shoot me an email at vanpelt@wandb.com with any specifics about your environment and we'll see if we can come up with a quick fix.

**Comment by raubitsj** [comment]
@tumbleintoyourheart 
There is an early access release of a new CLI which was refactored to focus on better windows support.  If you are willing to try it out, it is available at:
https://pypi.org/project/wandb-ng/
We will have a more functional release of this code next week but we are hoping it addresses the issues you have been seeing with startup.
If you find any issues with this release (there are still many) you can file them at:
https://github.com/wandb/client-ng

**Comment by tumbleintoyourheart** [comment]
Thanks for such quick responses.

I know it's always a whole different story for Windows users and actually I'm facing the issue on an Azure *Ubuntu* VM. Though it's not on Windows like the title, feel free to move these to anywhere more suitable.

Reproduce steps:
* `pip install wandb`
* In Python:
```
import wandb
wandb.init()
```

What I did:
* I did ensure to `wandb login`

What I tried but did not solve the problem:
* The workaround from [#839](https://github.com/wandb/client/issues/839#issue-560574511)
* Remove `wandb`
* Remove `.git`
* Ensure data folders are not included in where wandb is called.
* Reinstall wandb
* Restart the VM

The tracebacks are the same as @braindotai's.

**Comment by braindotai** [comment]
@tumbleintoyourheart just quick sanity check, make sure you are logging by pasting your api (wandb login <your api key>). I was logging in without my api key and that's when I got that error logs, after correctly logging everything is working as expected.
