### ISSUE TITLE
`wandb gc` → ValueError: time data 'in' does not match format '%Y%m%d_%H%M%S'

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#943]
wandb, version 0.8.30
Python 3.8.2
Linux

```
wandb gc
```

Traceback:

```
Traceback (most recent call last):
  File "/home/marcel/.local/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/marcel/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/marcel/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/marcel/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/marcel/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marcel/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/marcel/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marcel/.local/lib/python3.8/site-packages/wandb/cli.py", line 825, in gc
    dates = [datetime.datetime.strptime(p.split("-")[1],'%Y%m%d_%H%M%S') for p in paths]
  File "/home/marcel/.local/lib/python3.8/site-packages/wandb/cli.py", line 825, in <listcomp>
    dates = [datetime.datetime.strptime(p.split("-")[1],'%Y%m%d_%H%M%S') for p in paths]
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'in' does not match format '%Y%m%d_%H%M%S'
```

**Comment by cvphelps** [comment]
Hi Marcel, it sounds like this happens when there is something in the wandb directory that does not match what the garbage collector is expecting. We'd like to include this fix in our next generation of the CLI.

**Comment by kushalj001** [comment]
Is there a fix for this?

**Comment by raubitsj** [comment]
I am working on this now.  We are making it easier to set preferences on how much data to keep around so you don't have to remember to run `wandb gc`.

**Comment by vanpelt** [comment]
The fix for now would be to run `ls wandb` and manually removing any folders that don't match the pattern `run-%Y%m%d_%H%M%S` pattern.  Can you share any folders that stand out?

**Comment by adambielski** [comment]
@raubitsj For me the problem is cause by this line:
https://github.com/wandb/client/blob/63f3d7806669d2dd8d459134c2f88d6e341a797e/wandb/cli.py#L927
```
dates = [datetime.datetime.strptime(p.split("-")[1],'%Y%m%d_%H%M%S') for p in paths]
```
The date is searched for by spliting the path using '-' sign and taking the second element; however, my project path has '-' sign in it, e.g. ~/project/my-name-of-the-project/ , it searches for the data in "name"

Changing the line to:
```
dates = [datetime.datetime.strptime(p.split("-")[-2],'%Y%m%d_%H%M%S') for p in paths]
```
makes it grab the second last split and fixes the problem

**Comment by dreamflasher** [comment]
Push

**Comment by raubitsj** [comment]
@dreamflasher 
This has been completely rewritten in 0.10.x.
The replacement command is:wandb sync --clean

Is this still a problem for you?

**Comment by dreamflasher** [comment]
Thank you!
