### ISSUE TITLE
If I make a project with a space in the name, things get messed up

### ISSUE THREAD

**Issue by lukas** [wandb/client#95]
* Weights and Biases version: 0.4.40
* Python version: 3.6
* Operating System: OSX

### Description

I made a project called "fashion mnist" - it sort of seemed to change the name to fashion-mnist, but somehow not completely.

-L

```
ERROR:wandb.sync:Traceback (most recent call last):

  File "/Users/l2k/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wandb/api.py", line 70, in wrapper
    return func(*args, **kwargs)

  File "/Users/l2k/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wandb/api.py", line 511, in upsert_run
    'sweep': sweep_name})

  File "/Users/l2k/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gql/client.py", line 52, in execute
    raise Exception(str(result.errors[0]))

Exception: {'message': 'Model not found: l2k2/fashion mnist', 'code': 404, 'locations': [{'column': 3, 'line': 2}]}


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/l2k/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wandb/sync.py", line 321, in watch
    sweep_name=self._sweep_id)

  File "/Users/l2k/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wandb/api.py", line 93, in wrapper
    raise CommError(message)

wandb.api.CommError: Model not found: l2k2/fashion mnist
```

**Comment by vanpelt** [comment]
Yeah, it changed it on the server but the client doesn't perform the formatting before writing to `wandb/settings`.  Editing that file will work for now, we should format the slugs on the client the same as the server does.
