### ISSUE TITLE
RuntimeError: range of [nan, nan] is not finite

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#955]
`wandb --version && python --version && uname`

wandb, version 0.8.31
Python 3.8.2
Linux

### Description

When running sweeps, for several runs I get this error:

```
Traceback (most recent call last):
  File "model.py", line 494, in <module>
    train(**kwargs)
  File "model.py", line 395, in train
    pass  # This comment shows up if we ran into a callback error
  File "/home/marcel/git/model-in-the-loop/mitlmodels/ml_utils.py", line 61, in __exit__
    raise exc_type(exc_val).with_traceback(exc_tb) from None
  File "model.py", line 373, in train
    learn.fit_one_cycle(max_epochs, slice(lr_init, lr_init * 30), wd=wd,
  File "/home/marcel/.local/lib/python3.8/site-packages/fastai/train.py", line 23, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "/home/marcel/.local/lib/python3.8/site-packages/fastai/basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/home/marcel/.local/lib/python3.8/site-packages/fastai/basic_train.py", line 101, in fit
    loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
  File "/home/marcel/.local/lib/python3.8/site-packages/fastai/basic_train.py", line 34, in loss_batch
    if not skip_bwd:                     loss.backward()
  File "/home/marcel/.local/lib/python3.8/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/marcel/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
    Variable._execution_engine.run_backward(
  File "/home/marcel/.local/lib/python3.8/site-packages/wandb/wandb_torch.py", line 256, in <lambda>
    handle = var.register_hook(lambda grad: _callback(grad, log_track))
  File "/home/marcel/.local/lib/python3.8/site-packages/wandb/wandb_torch.py", line 254, in _callback
    self.log_tensor_stats(grad.data, name)
  File "/home/marcel/.local/lib/python3.8/site-packages/wandb/wandb_torch.py", line 207, in log_tensor_stats
    tensor = flat.histc(bins=self._num_bins, min=tmin, max=tmax)
RuntimeError: range of [nan, nan] is not finite 
```

There are plenty of runs in the same sweep where there's no error at all and everything runs smoothly. It also does not occur consistently for certain configurations.

**Comment by borisdayma** [comment]
As a quick fix, try to use `WandbCallback(log=None)`

**Comment by cvphelps** [comment]
Thanks Marcel. @adrnswanberg could you take a look?

**Comment by cvphelps** [comment]
@adrnswanberg thanks for fixing this!
