### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by chrisdonahue** [wandb/client#958]
`wandb --version && python --version && uname`

* Weights and Biases version: `0.8.31`
* Python version: `3.7.3
* Operating System: `Linux`

### Description

Running a bunch of jobs where some of them proceed as normal and some of them display `ValueError: 'timeout' must be a non-negative number` which appears to crash the entire job.

The relevant line of code is [here](https://github.com/wandb/client/blob/master/wandb/file_pusher.py#L319). Looks like for some reason the current time is greater than `batch_end_at`, causing `wait_secs` to be negative.

### What I Did

```
Traceback (most recent call last):
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-ilm-cdonahue/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-ilm-cdonahue/lib/python3.7/threading.py", line 865, in run 
    self._target(*self._args, **self._kwargs)
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-ilm-cdonahue/lib/python3.7/site-packages/wandb/file_pusher.py", line 319, in _batch_body
    event = self._batch_queue.get(timeout=wait_secs)
  File "/u/nlp/anaconda/main/anaconda3/envs/py37-ilm-cdonahue/lib/python3.7/queue.py", line 172, in get
    raise ValueError("'timeout' must be a non-negative number")
ValueError: 'timeout' must be a non-negative number

wandb: Network error resolved after 0:03:06.729788, resuming normal operation.
```

**Comment by raubitsj** [comment]
Thanks, we have some fixes for this problem that we are working on deploying in an upcoming release.   We will update this issue when we can give a more precise schedule and close it when it is released

**Comment by ariG23498** [comment]
Hey @chrisdonahue 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
