### ISSUE TITLE
wandb: ERROR W&B process (PID 4388) did not respond on Windows.

### ISSUE THREAD

**Issue by Juanvulcano** [wandb/client#993]
* Weights and Biases version: 0.8.32
* Python version: 3.6.10
* Operating System: Windows 10

### Description

I'm training a model using Tensorflow's Object detection API and I'm using wandb.init() to log the process of the job on the wandb console. All was working well but now I'm getting a Windows fatal exception error. `Windows fatal exception: code 0x80320012`. When running the script where I initiate wandb.

Wandb is also showing this on the console:
```wandb: ERROR W&B process (PID 4388) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
```

### What I Did

I'm running Tensorflow's Object detection "model_main.py" with some modification to log in wandb.

To initiate wandb I first ran `wandb login` on the console and pasted my user key. 

Then on the script I added:
```
import wandb
wandb.init(
	name="optimizer", #Name of the run 
	entity="<My-username>", 
	project="obj-detector",  #The name of the project I created.
	sync_tensorboard=True
)
```

I ran the script on an Anaconda Prompt with admin privileges  

It was all working well at first, and I could even see the training runs on my wandb console.

But now when I run the script I get the error mentioned above.

**Traceback:**
```
Windows fatal exception: code 0x80320012

Current thread 0x000038b8 (most recent call first):
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\wandb\wandb_socket.py", line 30 in __init__
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\wandb\__init__.py", line 232 in _init_headless
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\wandb\__init__.py", line 1090 in init
  File "model_main.py", line 96 in main
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\absl\app.py", line 250 in _run_main
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\absl\app.py", line 299 in run
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "model_main.py", line 176 in <module>
wandb: Tracking run with wandb version 0.8.32
wandb: ERROR W&B process (PID 6948) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "model_main.py", line 176, in <module>
    tf.app.run()
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_main.py", line 96, in main
    sync_tensorboard=True
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\wandb\__init__.py", line 1090, in init
    _init_headless(run)
  File "C:\Users\user\ProgramFiles\miniconda3\envs\ml_train_env\lib\site-packages\wandb\__init__.py", line 306, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
```
**wandb\debug.log:**
```
2020-04-23 16:12:20,459 DEBUG   MainThread:6424 [wandb_config.py:_load_defaults():122] no defaults not found in config-defaults.yaml
2020-04-23 16:12:30,467 DEBUG   MainThread:6424 [meta.py:setup():97] code probe starting
2020-04-23 16:12:30,467 DEBUG   MainThread:6424 [meta.py:setup():101] non time limited probe of code
2020-04-23 16:12:30,473 DEBUG   MainThread:6424 [meta.py:_setup_code_git():49] probe for git information
2020-04-23 16:12:30,528 DEBUG   MainThread:6424 [meta.py:_setup_code_program():58] save program starting
2020-04-23 16:12:30,529 DEBUG   MainThread:6424 [meta.py:_setup_code_program():60] save program starting: C:\Users\user\obj_detector\workspace\model_main.py
2020-04-23 16:12:30,530 DEBUG   MainThread:6424 [meta.py:_setup_code_program():65] save program saved: C:\Users\user\obj_detector\workspace\wandb\run-20200423_141209-21hjiwlj\code\obj_detector\workspace\model_main.py
2020-04-23 16:12:30,530 DEBUG   MainThread:6424 [meta.py:_setup_code_program():67] save program
2020-04-23 16:12:30,530 DEBUG   MainThread:6424 [meta.py:setup():119] code probe done
2020-04-23 16:12:30,532 DEBUG   MainThread:6424 [run_manager.py:__init__():545] Initialized sync for move13-obj-detector/21hjiwlj
2020-04-23 16:12:30,534 INFO    MainThread:6424 [run_manager.py:wrap_existing_process():1148] wrapping existing process 14748
2020-04-23 16:12:31,466 INFO    Thread-7  :6424 [run_manager.py:_on_file_modified():692] file/dir modified: C:\Users\user\obj_detector\workspace\wandb\run-20200423_141209-21hjiwlj\config.yaml
2020-04-23 16:12:31,466 INFO    Thread-7  :6424 [21hjiwlj:run_manager.py:_on_file_modified():692] file/dir modified: C:\Users\user\obj_detector\workspace\wandb\run-20200423_141209-21hjiwlj\config.yaml
```

**Comment by Juanvulcano** [comment]
Changed formatting

**Comment by cvphelps** [comment]
Hi there, thanks for reporting this issue— may I ask what version of TensorFlow you're using?

**Comment by cvphelps** [comment]
It looks like this is an issue with how we work with Windows. My colleague @raubitsj is working on a new version of our CLI that will address these issues

**Comment by cvphelps** [comment]
Hi @Juanvulcano , could you please try this with the latest version of our Python library and let me know if you see these issues.
